---
permalink: online-help/concept-guidelines-for-adding-alerts.html 
sidebar: sidebar 
keywords:  
summary: アラートは、クラスタ、ノード、アグリゲート、ボリュームなどのリソース、および特定の重大度タイプのイベントに基づいて追加できます。ベストプラクティスとして、重要なオブジェクトが属するクラスタを追加したあと、それらのすべてのオブジェクトについてのアラートを追加することを推奨します。 
---
= アラートの追加に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートは、クラスタ、ノード、アグリゲート、ボリュームなどのリソース、および特定の重大度タイプのイベントに基づいて追加できます。ベストプラクティスとして、重要なオブジェクトが属するクラスタを追加したあと、それらのすべてのオブジェクトについてのアラートを追加することを推奨します。

アラートを作成する際は、システムを効率的に管理できるように次のガイドラインと考慮事項を参考にしてください。

* Alert 概要の略
+
アラートを効果的に追跡できるように、概要をアラートに設定する必要があります。

* リソース
+
アラートが必要な物理リソースまたは論理リソースを決める必要があります。必要に応じて、リソースを追加したり除外したりできます。たとえば、アラートを設定してアグリゲートを詳細に監視する場合は、リソースのリストから必要なアグリゲートを選択する必要があります。

* イベントの重大度
+
イベントの重大度（重大、エラー、警告）ごとにアラートをトリガーするかどうかを決め、アラートをトリガーする重大度を指定する必要があります。

* イベント名
+
生成されるイベントのタイプに基づいてアラートを追加する場合は、アラートが必要なイベントを決める必要があります

* アクション
+
通知を受信するユーザのユーザ名と E メールアドレスを指定する必要があります。通知のモードとして SNMP トラップを指定することもできます。アラートが生成されたときに実行されるように、アラートにスクリプトを関連付けることができます。

* 通知の頻度
+
指定した期間、受信者に繰り返し通知を送信するようにアラートを設定できます。アラートに対してイベント通知をアクティブにする時間を決める必要があります。イベントが確認されるまでイベント通知を再送する場合は、通知を再送する頻度を決める必要があります。

* スクリプトを実行します
+
アラートにスクリプトを関連付けることができます。スクリプトはアラートが生成されると実行されます。


