---
permalink: online-help/concept-add-disks-and-reallocate-data.html 
sidebar: sidebar 
keywords:  
summary: アグリゲートにディスクを追加することで、ストレージ容量を増やし、そのアグリゲートのパフォーマンスを高めることができます。ディスクを追加したあと、追加したディスクにデータを再配置するまでは読み取りパフォーマンスは向上しません。 
---
= ディスクを追加してデータを再配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートにディスクを追加することで、ストレージ容量を増やし、そのアグリゲートのパフォーマンスを高めることができます。ディスクを追加したあと、追加したディスクにデータを再配置するまでは読み取りパフォーマンスは向上しません。

この手順は、 Unified Manager で動的しきい値またはシステム定義のパフォーマンスしきい値に基づいてトリガーされたアグリゲートイベントを受信したときに使用できます。

* 動的しきい値のイベントを受信した場合、イベントの詳細ページで、競合状態にあるアグリゲートを表すクラスタコンポーネントのアイコンが赤で強調表示されます。
+
このアイコンの下には、ディスクを追加できるアグリゲートの名前がかっこ内に表示されます。

* システム定義のしきい値のイベントを受信した場合、イベントの詳細ページのイベント概要に、問題があるアグリゲートの名前が表示されます。
+
このアグリゲートにディスクを追加してデータを再配置できます。



アグリゲートに追加できるのは、クラスタにすでに存在しているディスクだけです。クラスタに使用可能なディスクが残っていない場合は、必要に応じて管理者に問い合わせるか追加のディスクを購入してください。OnCommand System ManagerまたはONTAP コマンドを使用して、アグリゲートにディスクを追加できます。

[NOTE]
====
データの再配置を行うのは、 HDD アグリゲートおよび Flash Pool アグリゲートを使用している場合だけです。SSD アグリゲートまたは FabricPool アグリゲートにはデータを再割り当てしないでください。

====