---
permalink: online-help/concept-verify-whether-other-volumes-in-the-qos-policy-group-have-unusually-high-activity.html 
sidebar: sidebar 
keywords:  
summary: アクティビティの変化が最も大きい QoS ポリシーグループ内のワークロードを確認すると、複数のワークロードがイベントの原因となったかどうかを判断できます。また、他のワークロードがスループット制限を超えているかどうか、またはアクティビティの想定範囲内に戻ったかどうかを確認することもできます。 
---
= QoS ポリシーグループ内の他のボリュームのアクティビティが非常に高くなっていないかを確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクティビティの変化が最も大きい QoS ポリシーグループ内のワークロードを確認すると、複数のワークロードがイベントの原因となったかどうかを判断できます。また、他のワークロードがスループット制限を超えているかどうか、またはアクティビティの想定範囲内に戻ったかどうかを確認することもできます。

イベントの詳細ページのシステム診断セクションで、ワークロードをアクティビティのピーク偏差でソートして、アクティビティの変化が最も大きいワークロードをテーブルの先頭に表示できます。これらのワークロードは、アクティビティが設定された制限を超え、イベントの原因となった「いじめ」である可能性があります。

グラフ内の各ボリュームワークロードのパフォーマンス/ボリュームの詳細ページに移動して、そのIOPSアクティビティを確認できます。処理のアクティビティが非常に高い期間が存在するワークロードは、イベントの原因となった可能性があります。ワークロードのポリシーグループの設定を変更したり、ワークロードを別のポリシーグループに移動したりできます。

OnCommand System ManagerまたはONTAP CLIコマンドを使用して、ポリシーグループを次のように管理できます。

* ポリシーグループを作成する。
* ポリシーグループ内のワークロードを追加または削除します。
* ポリシーグループ間でワークロードを移動します。
* ポリシーグループのスループット制限を変更します。

