---
permalink: online-help/concept-what-report-importing-is.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerのレポートのインポートオプションを使用してレポートをインポートし、インポートしたレポートに名前と簡単な概要 を付けて保存できます。レポートをインポートすると、Unified Managerに付属の標準のレポートに加え、カスタムのレポートを環境に追加することができます。 
---
= レポートのインポートとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerの* Import Report *オプションを使用してレポートをインポートし、インポートしたレポートに名前と簡単な概要 を付けて保存できます。レポートをインポートすると、Unified Managerに付属の標準のレポートに加え、カスタムのレポートを環境に追加することができます。

をインポートできます `.rptdesign` すでに作成されているファイル。インポートしたレポートは、実行、共有、スケジュール、および削除することができます。

Unified Managerは、レポートのインポートのログファイルをjboss.log、ocum-report.log、ocumserver-debug.logの各ファイルに保存します。

[NOTE]
====
カスタマーサポートがレポートの設計を支援することはありませんが、レポートのインポート処理で発生した問題についてのサポートは提供されます。

====
レポートのインポートでは、次の機能がサポートされます。

* 列のスパンが1に設定されている複数のヘッダーがあるレポート (`colspan=1`)
* グラフのみのレポート
* リストとグリッドのみのレポート
* レポートで使用するパスワードは、「base64」形式でエンコードする必要があります。"JCE`"形式など、他のエンコーディングを使用するレポートでは、インポート処理中に原因 にエラーが発生します。
* データ集約を含むレポートでは、レポートのテーブルデータに集計列要素を含める必要があります。


テキスト、CSV、Excel形式のレポートは、次のシナリオでサポートされます。

* 内のテーブル要素のみ `.rptdesign` ファイル。
* ヘッダー行が1つしかないテーブル


[NOTE]
====
列のスパンが1より大きい値に設定されているレポートをインポートすることはできません。テキスト、CSV、Excel形式のレポートに複数のヘッダー行がある場合、最初のヘッダー行のみが考慮され、残りは無視されます。

====