---
permalink: online-help/concept-how-group-rules-work-for-groups.html 
sidebar: sidebar 
keywords:  
summary: グループルールとは、ストレージオブジェクト（ボリューム、クラスタ、またはSVM）を特定のグループに追加する基準を定義したものです。グループのグループルールは、条件グループまたは条件を使用して定義できます。 
---
= グループでのグループルールの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グループルールとは、ストレージオブジェクト（ボリューム、クラスタ、または SVM ）を特定のグループに追加する基準を定義したものです。グループのグループルールは、条件グループまたは条件を使用して定義できます。

* グループにはグループルールを関連付ける必要があります。
* グループルールにはオブジェクトタイプを関連付ける必要があります。関連付けることができるオブジェクトタイプは 1 つだけです。
* グループに対してストレージオブジェクトが追加または削除されるのは、各監視サイクルの完了後、またはルールの作成、編集、削除時です。
* グループルールには 1 つ以上の条件グループを、各条件グループには 1 つ以上の条件を含めることができます。
* ストレージオブジェクトは、作成したグループルールに基づいて複数のグループに属することができます。




== 条件：

複数の条件グループを作成し、各条件グループに 1 つ以上の条件を含めることができます。グループのグループルールに定義されたすべての条件グループを適用して、グループに含めるストレージオブジェクトを指定することができます。

条件グループ内の条件は論理 AND を使用して実行されます。条件グループのすべての条件が満たされている必要があります。条件はグループルールを作成または変更すると作成され、条件グループのすべての条件を満たすストレージオブジェクトのみが適用、選択、およびグループの対象となります。グループに含めるストレージオブジェクトの範囲を限定するには、条件グループで複数の条件を使用します。

次のオペランドと演算子を使用して必要な値を指定することで、ストレージオブジェクトの条件を作成できます。

|===
| ストレージオブジェクトのタイプ | 適用可能なオペランド 


 a| 
ボリューム
 a| 
* オブジェクト名
* 所有クラスタ名
* 所有 SVM 名
* 注釈




 a| 
SVM
 a| 
* オブジェクト名
* 所有クラスタ名
* 注釈




 a| 
クラスタ
 a| 
* オブジェクト名
* 注釈


|===
ストレージ・オブジェクトのオペランドとしてアノテーションを選択すると 'is' 演算子を使用できますそれ以外のオペランドについては ' 演算子として Is または Contains を選択できます

* オペランド
+
Unified Manager では、選択したオブジェクトタイプによってリストに表示されるオペランドが変わります。リストには、オブジェクト名、所有クラスタ名、所有 SVM 名、および Unified Manager で定義したアノテーションが含まれます。

* 演算子
+
演算子のリストは、条件に対して選択したオペランドによって変わります。Unified Manager でサポートされる演算子は「 Is 」で、「 contains 」です。

+
「 Is 」演算子を選択すると、選択したオペランドの値が指定した値と完全に一致する場合に条件が評価されます。

+
"`contains" 演算子を選択すると、条件は次のいずれかの条件を満たすように評価されます。

+
** 選択したオペランドの値が指定した値と完全に一致する
** 選択したオペランドの値に指定した値が含まれる


* 価値
+
値のフィールドは、選択したオペランドによって変わります。





== 条件を使用したグループルールの例

ボリュームに対する条件グループで、次の 2 つの条件が定義されているとします。

* 名前に「 vol 」を含む
* SVM 名は「 `d ata_svm 」です。


この条件グループでは、名前に「 vol 」を含み、「 `d ata_svm 」という名前の SVM でホストされているすべてのボリュームが選択されます。



== 条件グループ

条件グループは論理 OR を使用して実行され、ストレージオブジェクトに適用されます。ストレージオブジェクトがグループに追加されるためには、いずれかの条件グループを満たす必要があります。すべての条件グループのストレージオブジェクトがまとめられます。条件グループを使用して、グループに含めるストレージオブジェクトの範囲を広げることができます。



== 条件グループを使用したグループルールの例

ボリュームに対する 2 つの条件グループで、各グループにそれぞれ次の 2 つの条件が定義されているとします。

* 条件グループ 1
+
** 名前に「 vol 」を含む
** SVM 名が「 `d ata_svm 」の場合、条件グループ 1 では、名前に「 vol 」を含み、名前が「 `d ata_svm 」の SVM でホストされているすべてのボリュームが選択されます。


* 条件グループ 2.
+
** 名前に「 vol 」を含む
** data-priority のアノテーション値は「 critical 」条件グループ 2 では、名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」とアノテートされているすべてのボリュームが選択されます。




これらの 2 つの条件グループを含むグループルールをストレージオブジェクトに適用した場合、選択したグループに次のストレージオブジェクトが追加されます。

* 名前に「 vol 」を含み、「 'data_svm 」という名前の SVM でホストされているすべてのボリューム
* 名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリューム

