---
permalink: online-help/concept-how-group-actions-work-on-storage-objects.html 
sidebar: sidebar 
keywords:  
summary: グループアクションは、グループ内のすべてのストレージオブジェクトに対して実行される処理です。たとえば、ボリュームしきい値のグループアクションを設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。 
---
= ストレージオブジェクトでのグループ操作の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グループアクションは、グループ内のすべてのストレージオブジェクトに対して実行される処理です。たとえば、ボリュームしきい値のグループアクションを設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。

グループは、一意のグループアクションタイプをサポートします。ボリューム健常性しきい値タイプのグループアクションは 1 つのグループに 1 つしか設定できません。ただし、同じグループに別のタイプのグループアクションがある場合は、それを設定できます。グループアクションがストレージオブジェクトに適用される順序はアクションのランクで決まります。ストレージオブジェクトに適用されるグループアクションの情報は、ストレージオブジェクトの詳細ページで確認できます。



== 一意なグループアクションの例

ボリューム A がグループ G1 と G2 に属しており、これらのグループに次のボリューム健常性しきい値グループアクションが設定されているとします。

* `Change_capacity_threshold` ボリュームの容量を設定するためのランク1のグループ操作
* `Change_snapshot_copies` グループ操作のランク2。ボリュームのSnapshotコピーを設定します


。 `Change_capacity_threshold` グループ操作は、よりも常に優先されます `Change_snapshot_copies` グループ操作でボリュームAに適用されますUnified Managerによる監視サイクルが1回完了すると、ボリュームAの健常性しきい値関連イベントがごとに再評価されます `Change_capacity_threshold` グループ操作G1 または G2 のどちらのグループにも、ボリュームしきい値タイプの別のグループアクションを設定することはできません。
