---
permalink: online-help/concept-understanding-the-um-recommendations-to-tier-data-to-the-cloud.html 
sidebar: sidebar 
keywords:  
summary: Performance/Volumesインヘントリヘエシには、ボリュームに保存されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関連する情報が表示されます。Unified Managerが、特定のボリュームについて、アクセス頻度の低いデータをFabricPool対応アグリゲートのクラウド階層（クラウドプロバイダまたはStorageGRID ）に階層化することを推奨することがあります。 
---
= Unified Manager によるクラウドへのデータの階層化の推奨について理解していること
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance/Volumesインヘントリヘエシには、ボリュームに保存されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関連する情報が表示されます。Unified Manager が、特定のボリュームについて、アクセス頻度の低いデータを FabricPool 対応アグリゲートのクラウド階層（クラウドプロバイダまたは StorageGRID ）に階層化することを推奨することがあります。

[NOTE]
====
FabricPool は ONTAP 9.2 で導入されたため、 9.2 より前のバージョンの ONTAP ソフトウェアを使用している場合、 Unified Manager によるデータの階層化の推奨を有効にするには、 ONTAP ソフトウェアのアップグレードが必要になります。また、も参照してください `auto` 階層化ポリシーはONTAP 9.4で導入されたため、の使用を推奨します `auto` 階層化ポリシーを使用する場合は、ONTAP 9.4以降にアップグレードする必要があります。

====
Performance/Volumesインヘントリヘエシノ次の3つのフィールドには、アクセス頻度の低いデータをクラウド階層に移動することでストレージシステムのディスク使用率の改善やパフォーマンス階層のスペースの削減が可能かどうかに関する情報が表示されます。

* * 階層化ポリシー *
+
階層化ポリシーによって、ボリュームのデータを高パフォーマンス階層に残すか、あるいは一部のデータをパフォーマンス階層からクラウド階層に移動するかが決まります。

+
このフィールドには、ボリュームに対して設定されている階層化ポリシーが、ボリュームが現在 FabricPool アグリゲートにない場合も含めて表示されます。階層化ポリシーが適用されるのは、ボリュームが FabricPool アグリゲートにある場合のみです。

* * コールドデータ *
+
ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズが表示されます。

+
この値は、ONTAP 9.4以降のソフトウェアを使用している場合にのみ表示されます。ボリュームを導入するアグリゲートにが含まれている必要があるためです `inactive data reporting` パラメータをに設定します `enabled`を使用しているボリュームで、クーリング日数のしきい値の最小値に達していること `snapshot-only` または `auto` 階層化ポリシー）。それ以外の場合、値は「 N/A 」と表示されます。

* * クラウドの推奨事項 *
+
ボリュームのデータアクティビティに関して十分な情報が収集されると、 Unified Manager は、対処が不要か、またはアクセス頻度の低いデータをクラウド階層に移動することでパフォーマンス階層のスペースを削減できるかを判断することができます。



[NOTE]
====
コールドデータフィールドは 15 分ごとに更新されますが、ボリュームでコールドデータ分析が実行されると、クラウドの推奨事項フィールドが 7 日ごとに更新されます。したがって、コールドデータの正確な量はフィールド間で異なる場合があります。Cloud Recommendation フィールドには、分析が実行された日付が表示されます。

====
Inactive Data Reporting が有効になっている場合は、コールドデータフィールドにはアクセス頻度の低いデータの正確な量が表示されます。Inactive Data Reporting 機能を使用できない場合、 Unified Manager はパフォーマンス統計に基づいてアクセス頻度の低いデータがボリュームにあるかどうかを判断します。アクセス頻度の低いデータの量はこの場合のコールドデータフィールドには表示されませんが、クラウドに関する推奨事項を表示するために「 * ティア * 」という単語にカーソルを合わせると表示されます。

クラウドに関する推奨事項は次のとおりです。

* * 学習中 * 。推奨事項を利用できるだけの十分なデータが収集されていません。
* * 階層 * 。分析の結果、アクセス頻度の低いコールドデータがボリュームにあり、そのデータをクラウド階層に移動するようにボリュームを設定することが推奨されます。一部のケースでは、ボリュームをまず FabricPool 対応アグリゲートに移動する必要があります。ボリュームがすでに FabricPool アグリゲートにあれば、階層化ポリシーの変更だけで済みます。
* * アクションなし * 。ボリュームにアクセス頻度の低いデータがほとんどないか、ボリュームが FabricPool アグリゲートですでに「 auto 」階層化ポリシーに設定されているか、ボリュームがデータ保護ボリュームです。この値は、ボリュームがオフラインの場合や MetroCluster 構成で使用されている場合にも表示されます。


ボリュームを移動したり、ボリュームの階層化ポリシーやアグリゲートのInactive Data Reportingの設定を変更するには、OnCommand System Manager、ONTAP のCLIコマンド、またはこの2つを組み合わせて使用します。

OnCommand 管理者ロールまたはストレージ管理者ロールでUnified Managerにログインしている場合は、「*階層*」にカーソルを合わせるとクラウドに関する推奨事項の「ボリュームの設定*」リンクが使用可能になります。このボタンをクリックすると、 System Manager の Volumes （ボリューム）ページが開き、推奨される変更が行われます。
