---
permalink: online-help/concept-understanding-events-from-adaptive-qos-policies-that-have-a-defined-block-size.html 
sidebar: sidebar 
keywords:  
summary: アダプティブ QoS ポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、 TB または GB あたりの IOPS が一定に維持されます。ONTAP 9.5以降では、QoSポリシーにブロックサイズを指定することでMBpsのしきい値も同時に適用できます。 
---
= ブロックサイズの定義を含むアダプティブ QoS ポリシーによるイベントの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アダプティブ QoS ポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、 TB または GB あたりの IOPS が一定に維持されます。ONTAP 9.5以降では、QoSポリシーにブロックサイズを指定することでMBpsのしきい値も同時に適用できます。

アダプティブ QoS ポリシーに IOPS のしきい値を割り当てると、各ワークロードで発生する処理数にのみ制限のみが適用されます。ワークロードを生成するクライアントに設定されているブロックサイズによっては、一部の IOPS にはるかに多くのデータが含まれ、処理を実行するノードの負荷がはるかに大きくなることがあります。

ワークロードのMBpsは次の式を使用して算出されます。

[listing]
----
MBps = (IOPS * Block Size) / 1000
----
平均IOPSが3、000のワークロードについて、クライアントのブロックサイズが32KBに設定されている場合、このワークロードの実効MBpsは96です。平均IOPSが3、000の同じワークロードについて、クライアントのブロックサイズが48KBに設定されている場合は、このワークロードの実効MBpsは144になります。この場合、ブロックサイズが大きい方がノードでの処理データが 50% 多くなることがわかります。

次に、アダプティブ QoS ポリシーにブロックサイズが定義されている場合について、クライアントで設定されているブロックサイズに基づいてどのようにイベントがトリガーされるかを見てみましょう。

ポリシーを作成し、ピークスループットを 2 、 500IOPS/TB 、ブロックサイズを 32KB に設定します。この場合、使用容量が1TBのボリュームに対するMBpsのしきい値は80MBps（（2500 IOPS * 32KB）/ 1000）に設定されます。Unified Manager では、スループットの値が定義されたしきい値を 10% 下回ると警告イベントが生成されます。イベントは次の状況で生成されます。

|===
| 使用済み容量 | イベントが生成されるスループットのしきい値 


| IOPS | MBps 


 a| 
1 TB
 a| 
2 、 250 IOPS



 a| 
72 Mbps
 a| 
2TB



 a| 
4 、 500 IOPS
 a| 
144 Mbps



 a| 
5 TB
 a| 
11 、 250 IOPS

|===
ボリュームの使用可能なスペースが2TB、IOPSが4、000、クライアントで設定されているQoSブロックサイズが32KBである場合、スループットは128MBps（（4、000 IOPS * 32 KB）/ 1000）になります。この場合、4、000 IOPSと128MBpsのどちらについても、ボリュームで2TBのスペースを使用する場合のしきい値を超えていないため、イベントは生成されません。

ボリュームの使用可能なスペースが2TB、IOPSが4、000、クライアントで設定されているQoSブロックサイズが64KBである場合、スループットは256MBps（（4、000 IOPS * 64KB）/ 1000）になります。この場合、4、000 IOPSについてはイベントは生成されませんが、MBpsの値については256MBpsでしきい値の144MBpsを超えているためイベントが生成されます。

そのため、アダプティブQoSポリシーにブロックサイズを含むMBpsの違反が原因でイベントがトリガーされると、イベントの詳細ページのシステム診断セクションにMBpsのグラフが表示されます。アダプティブ QoS ポリシーに対する IOPS の違反に基づいてイベントがトリガーされると、システム診断セクションに IOPS チャートが表示されます。IOPSとMBpsの両方に違反がある場合は、2つのイベントが表示されます。

QoS 設定の調整の詳細については、 ONTAP 9 パフォーマンス管理パワーガイドを参照してください。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html["ONTAP 9 パフォーマンス管理パワーガイド"]
