---
permalink: online-help/concept-cluster-components-and-why-they-can-be-in-contention.html 
sidebar: sidebar 
keywords:  
summary: クラスタコンポーネントの競合の原因となるクラスタのパフォーマンスの問題を特定することができます。コンポーネントを使用するボリュームのワークロードのパフォーマンスが低下し、クライアント要求に対する応答時間（レイテンシ）が長くなると、Unified Managerでイベントがトリガーされます。 
---
= クラスタコンポーネントとその競合要因
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタコンポーネントの競合の原因となるクラスタのパフォーマンスの問題を特定することができます。コンポーネントを使用するボリュームのワークロードのパフォーマンスが低下し、クライアント要求に対する応答時間（レイテンシ）が長くなると、Unified Managerでイベントがトリガーされます。

競合状態のコンポーネントは、最適なレベルのパフォーマンスを提供できません。パフォーマンスが低下し、 _Victim _ と呼ばれる他のクラスタコンポーネントやワークロードのパフォーマンスによってレイテンシが増大する可能性があります。コンポーネントの競合状態を解消するには、ワークロードを減らすか処理能力を高めることでパフォーマンスを通常レベルに戻す必要があります。Unified Manager では、ワークロードのパフォーマンスの収集と分析が 5 分間隔で行われるため、クラスタコンポーネントの利用率が高い状態が長時間続いたときにのみ検出されます。利用率が高い状態が 5 分インターバルの間に短時間しか続かないような一時的な利用率の急増は検出されません。

ストレージアグリゲートが競合状態になる原因としては、たとえば、 1 つ以上のワークロードがそれぞれの I/O 要求に対応するために競合する場合などがあります。アグリゲートの他のワークロードに影響し、それらのワークロードのパフォーマンスが低下する可能性があります。アグリゲートのアクティビティを減らす方法はいくつかありますが、たとえば、1つ以上のワークロードを負荷の低いアグリゲートに移動し、現在のアグリゲートに対する全体的なワークロードの負荷を低くするなどの方法が効果的です。QoS ポリシーグループの場合は、スループット制限を調整したりワークロードを別のポリシーグループに移動したりすることで、ワークロードが抑制されないようにすることができます。

Unified Manager では、次のクラスタコンポーネントを監視して、これらのコンポーネントが競合状態になるとアラートを生成します。

* * ネットワーク *
+
クラスタ上でのiSCSIプロトコルまたはファイバチャネル（FC）プロトコルによるI/O要求の待機時間を表します。待機時間とは、クラスタがI/O要求に応答できるようになるまでに、iSCSI Ready to Transfer（R2T）またはFCP Transfer Ready（XFER_RDY）トランザクションが待つ時間です。ネットワークコンポーネントが競合状態にある場合、ブロックプロトコルレイヤでの長い待機時間は、1つ以上のワークロードのレイテンシに影響していることを意味します。

* * ネットワーク処理 *
+
プロトコルレイヤとクラスタ間の I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。ネットワーク処理を実行するノードがイベント検出後に変更された可能性があります。ネットワーク処理コンポーネントが競合状態にある場合、ネットワーク処理ノードでの高利用率は、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

* * QoS ポリシー *
+
ワークロードがメンバーになっているストレージQoSポリシーグループを表します。ポリシーグループコンポーネントが競合状態にある場合、ポリシーグループ内のすべてのワークロードに、スループットの制限によってスロットルが適用され、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

* * クラスタインターコネクト *
+
クラスタノードを物理的に接続するケーブルとアダプタを表します。クラスタインターコネクトコンポーネントが競合状態にある場合は、クラスタインターコネクトでの I/O 要求の長い待機時間がワークロードのレイテンシに影響していることを意味します。

* * データ処理 *
+
クラスタとストレージアグリゲート間でワークロードを含む I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。データ処理を実行するノードがイベント検出後に変更された可能性があります。データ処理コンポーネントが競合状態にある場合、データ処理ノードでの高利用率は、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

* * MetroCluster リソース *
+
NVRAM とインタースイッチリンク（ ISL ）を含む MetroCluster リソースを表します。 MetroCluster 構成のクラスタ間でデータをミラーリングするのに使用します。MetroCluster コンポーネントが競合状態問題にある場合は、ローカルクラスタのワークロードによる大量の書き込みスループットまたはリンクの不具合が、ローカルクラスタの 1 つ以上のワークロードのレイテンシに影響していることを意味します。クラスタが MetroCluster 構成に含まれていない場合は、このアイコンは表示されません。

* * アグリゲートまたは SSD アグリゲートの処理 *
+
ワークロードが実行されているストレージアグリゲートを表します。アグリゲートコンポーネントが競合状態にある場合、アグリゲートの高利用率が 1 つ以上のワークロードのレイテンシに影響していることを意味します。アグリゲートには、HDDのみで構成されるものと、HDDとSSDが混在するもの（Flash Poolアグリゲート）があります。「 SD アグリゲート」は、すべての SSD （オールフラッシュアグリゲート）、または SSD とクラウド階層（ FabricPool アグリゲート）が混在しています。

* * クラウドレイテンシ *
+
クラスタとユーザデータ格納先のクラウド階層の間の I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。クラウドレイテンシコンポーネントが競合状態にある場合、クラウド階層でホストされたボリュームからの大量の読み取りが 1 つ以上のワークロードのレイテンシに影響していることを意味します。

* * 同期 SnapMirror *
+
SnapMirror 同期関係でのプライマリボリュームからセカンダリボリュームへのユーザデータのレプリケーションに関係する、クラスタ内のソフトウェアコンポーネントを表します。同期 SnapMirror コンポーネントが競合状態にある場合、 SnapMirror Synchronous 処理のアクティビティが 1 つ以上のワークロードのレイテンシに影響していることを意味します。


