---
permalink: online-help/concept-what-a-data-continuity-collection-cycle-is.html 
sidebar: sidebar 
keywords:  
summary: データの継続性収集サイクルは、リアルタイムのクラスタパフォーマンス収集サイクルの外部で、デフォルトでは 5 分ごとにパフォーマンスデータを取得します。データの継続性収集により、 Unified Manager がリアルタイムのデータを収集できなかった期間の統計データを補完することができます。 
---
= データの継続性収集サイクルとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データの継続性収集サイクルは、リアルタイムのクラスタパフォーマンス収集サイクルの外部で、デフォルトでは 5 分ごとにパフォーマンスデータを取得します。データの継続性収集により、 Unified Manager がリアルタイムのデータを収集できなかった期間の統計データを補完することができます。

データの継続性収集は、ONTAP バージョン8.3.1以降のソフトウェアがインストールされたクラスタでのみサポートされます。

Unified Manager は、次のイベントが発生したときにデータの継続性収集による履歴パフォーマンスデータのポーリングを実行します。

* クラスタが最初に Unified Manager に追加されたとき。
+
Unified Manager は、過去 15 日間の履歴パフォーマンスデータを収集します。これにより、クラスタが追加されてから数時間で 2 週間分の履歴パフォーマンス情報を表示できます。

+
また、該当する期間にシステム定義のしきい値のイベントが発生していた場合はそれらのイベントも報告されます。

+
[NOTE]
====
ボリュームについては、現在は過去15日間の統計は収集されません。

====
* 現在のパフォーマンスデータ収集サイクルが所定の時間に完了しない。
+
リアルタイムのパフォーマンスのポーリングが 5 分間隔の収集期間を超えると、データの継続性収集サイクルが開始され、収集されなかった期間の情報が収集されます。データの継続性収集が実行されなかった場合、次の収集期間がスキップされます。

* 次の状況により、 Unified Manager に一時的にアクセスできなくなり、そのあとオンラインに戻ったとき。
+
** 再起動された。
** ソフトウェアのアップグレードやバックアップファイルの作成のために Unified Manager がシャットダウンされた。
** ネットワーク停止から復旧した。


* 次の状況により、クラスタに一時的にアクセスできなくなり、そのあとオンラインに戻ったとき。
+
** ネットワーク停止から復旧した。
** 低速なワイドエリアネットワーク接続が原因で、通常のパフォーマンスデータの収集に遅延が生じた。




データの継続性収集サイクルは、最大 24 時間の履歴データを収集できます。Unified Manager が停止した状態が 24 時間以上続くと、 UI のページにパフォーマンスデータが表示されない期間が発生します。

データの継続性収集サイクルとリアルタイムのデータ収集サイクルを同時に実行することはできません。データの継続性収集サイクルが完了してからでないと、リアルタイムのパフォーマンスデータ収集は開始されません。1時間以上の履歴データを収集するためにデータの継続性収集が必要な場合は、パフォーマンスダッシュボードの上部にそのクラスタ用のバナーメッセージが表示されます。
