---
permalink: online-help/concept-understanding-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: Storage Virtual Machine（SVM）の関連付けは、ソースSVMからデスティネーションSVMへのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。 
---
= SVMの関連付けの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）の関連付けは、ソースSVMからデスティネーションSVMへのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。

デスティネーションSVMがセカンダリデスティネーションと3次デスティネーションのどちらであるかに関係なく、関連付けは常にソースSVMとデスティネーションSVMの間で作成されます。セカンダリデスティネーションSVMをソースとして使用して、3次デスティネーションSVMとの関連付けを作成することはできません。

SVMを関連付ける方法は3つあります。

* 任意のSVMを関連付ける
+
任意のプライマリソースSVMと1つ以上のデスティネーションSVMの間で関連付けを作成できます。つまり、現時点で保護を必要とする既存のすべてのSVMおよび今後作成されるすべてのSVMが指定したデスティネーションSVMに関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを1箇所にある1つ以上のデスティネーションSVMにバックアップできます。

* 特定のSVMを関連付ける
+
特定のソースSVMと1つ以上の特定のデスティネーションSVMの間で関連付けを作成できます。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定のソースSVMを、対象のクライアントにのみ割り当てられる特定のデスティネーションSVMに関連付けることができます。

* 外部のSVMに関連付ける
+
ソースSVMとデスティネーションSVMの外部のフレキシブルボリュームの間で関連付けを作成できます。


