---
permalink: online-help/concept-use-qos-policy-settings-to-prioritize-the-work-on-this-node.html 
sidebar: sidebar 
keywords:  
summary: QoSポリシーグループに上限を設定して、ポリシーグループに含まれるワークロードの1秒あたりのI/O処理数（IOPS）やスループット（MBps）の上限を制御できます。デフォルトポリシーグループなどの制限が設定されていないポリシーグループにワークロードが含まれている場合や、設定された制限値が設定されていない場合は、設定された制限値を増やすか、必要な制限値が設定された新規または既存のポリシーグループにワークロードを移動できます。 
---
= QoS ポリシーの設定を使用して、このノードでの作業に優先順位を付けます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoS ポリシーグループに上限を設定して、ポリシーグループに含まれるワークロードの 1 秒あたりの I/O 処理数（ IOPS ）やスループット（ MBps ）の上限を制御できます。デフォルトポリシーグループなどの制限が設定されていないポリシーグループにワークロードが含まれている場合や、設定された制限値が設定されていない場合は、設定された制限値を増やすか、必要な制限値が設定された新規または既存のポリシーグループにワークロードを移動できます。

ノードのパフォーマンスイベントの原因がノードリソースを過剰に消費しているワークロードにある場合、イベントの詳細ページのイベント概要に関連するボリュームのリストへのリンクが表示されます。パフォーマンス / ボリュームページで、影響を受けたボリュームを IOPS と MBps でソートすると、イベントの原因となった可能性がある使用率が最も高いワークロードを確認できます。

ノードリソースを過剰に消費しているボリュームは、より制限の厳しいポリシーグループに割り当てます。これにより、ポリシーグループによる調整でワークロードのアクティビティが制限されて、そのノードでのリソースの使用が削減されます。

OnCommand System ManagerまたはONTAP コマンドを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ポリシーグループを作成する
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でワークロードを移動する
* ポリシーグループのスループット制限を変更する

