---
permalink: online-help/concept-metrocluster-configuration-verification.html 
sidebar: sidebar 
keywords:  
summary: MetroCluster 構成でミラーされたワークロードにパフォーマンスの問題が発生しないようにするには、 MetroCluster 構成が正しくセットアップされていることを確認します。また、構成を変更するか、ソフトウェアまたはハードウェアコンポーネントをアップグレードすることで、ワークロードのパフォーマンスを向上させることもできます。 
---
= MetroCluster 構成の検証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成でミラーされたワークロードにパフォーマンスの問題が発生しないようにするには、 MetroCluster 構成が正しくセットアップされていることを確認します。また、構成を変更するか、ソフトウェアまたはハードウェアコンポーネントをアップグレードすることで、ワークロードのパフォーマンスを向上させることもできます。

『 MetroCluster インストレーションおよび構成ガイド』では、ファイバチャネル（ FC ）スイッチ、ケーブル、スイッチ間リンク（ ISL ）など、 MetroCluster 構成でクラスタをセットアップする手順を説明しています。また、ローカルクラスタとリモートクラスタがミラーボリュームデータと通信できるように MetroCluster ソフトウェアを設定する際にも役立ちます。

使用する MetroCluster 構成を MetroCluster インストレーションおよび構成ガイドの要件と比較して、ワークロードのパフォーマンスを改善するために MetroCluster 構成のコンポーネントの変更またはアップグレードが必要かどうかを判断できます。この比較は、次の点について回答を行う場合に役立ちます。

* コントローラはワークロードに適していますか？
* スループットの処理能力を高めるために、 ISL バンドルをより大きな帯域幅にアップグレードする必要があるか。
* 帯域幅を増やすためにスイッチ上でバッファ間クレジット（ BBC ）を調整できるか。
* ワークロードに SSD ストレージへの大量の書き込みスループットがある場合、そのスループットに対応するために FC-to-SAS ブリッジをアップグレードする必要があるか。


MetroCluster コンポーネントの交換またはアップグレードについては、 MetroCluster サービスガイドを参照してください。
