---
permalink: online-help/concept-cluster-configuration-and-performance-data-collection-activity.html 
sidebar: sidebar 
keywords:  
summary: クラスタの構成データの収集間隔は 15 分です。たとえば、クラスタを追加したあと、そのクラスタの詳細が Unified Manager の UI に表示されるまでに 15 分かかります。クラスタに対する変更を行った場合にも同じ間隔が適用されます。 
---
= クラスタの構成とパフォーマンスのデータの収集アクティビティ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ構成 data_is の収集間隔は 15 分です。たとえば、クラスタを追加したあと、そのクラスタの詳細が Unified Manager の UI に表示されるまでに 15 分かかります。クラスタに対する変更を行った場合にも同じ間隔が適用されます。

たとえば、クラスタ内の SVM に 2 つの新しいボリュームを追加した場合、それらの新しいオブジェクトが UI に表示されるのは次回のポーリング間隔のあとであるため、最大で 15 分後になります。

Unified Manager は、監視対象のすべてのクラスタから 5 分間隔で current_performance statistics _ を収集します。そのデータを分析することでパフォーマンスイベントや潜在的な問題を特定します。5分ごとのパフォーマンスデータについては30日分、1時間ごとのパフォーマンスデータについては390日分のデータが保持されます。これにより、過去 1 カ月間の非常にきめ細かなパフォーマンスの詳細と最大 1 年間のパフォーマンスの傾向を確認できます。

収集のポーリングは、各クラスタからのデータが同時に送信されてパフォーマンスに影響することがないように数分ずつオフセットされます。

次の表に、 Unified Manager で実行される収集アクティビティを示します。

|===
| アクティビティ | 時間間隔 | 説明 


 a| 
パフォーマンス統計のポーリング
 a| 
5 分ごと
 a| 
各クラスタからリアルタイムのパフォーマンスデータを収集します。



 a| 
統計分析
 a| 
5 分ごと
 a| 
Unified Manager では、統計のポーリングが完了するたびに、収集したデータをユーザ定義のしきい値、システム定義のしきい値、および動的なしきい値と比較します。

パフォーマンスしきい値の違反が見つかると、 Unified Manager はイベントを生成し、設定されている場合は該当のユーザに E メールを送信します。



 a| 
構成のポーリング
 a| 
15 分ごと
 a| 
各クラスタから詳細なインベントリ情報を収集して、すべてのストレージオブジェクト（ノード、 SVM 、ボリュームなど）を特定します。



 a| 
要約
 a| 
1 時間ごと
 a| 
5 分ごとに収集した最新の 12 回分のパフォーマンスデータを集計して 1 時間の平均を求めます。

1時間あたりの平均値は一部のUIページで使用され、390日間保持されます。



 a| 
予測分析とデータの削除
 a| 
毎日午前 0 時から
 a| 
クラスタのデータを分析し、次の 24 時間のボリュームのレイテンシと IOPS の動的なしきい値を設定します。

30 日を経過した 5 分ごとのパフォーマンスデータをデータベースから削除します。



 a| 
データの削除
 a| 
毎日午前 2 時から
 a| 
390日を経過したイベントと動的なしきい値をデータベースから削除します。



 a| 
データの削除
 a| 
毎日午前 3 時 30 分から
 a| 
390日を経過した1時間のパフォーマンスデータをデータベースから削除します。

|===