---
permalink: online-help/concept-what-the-expected-range-of-performance-is.html 
sidebar: sidebar 
keywords:  
summary: 想定される値の範囲とは、特定の時間において見込まれる上限と下限のパフォーマンス値の予測、または予測です。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値です。実測値がパフォーマンスしきい値を超えると、Unified Managerによってパフォーマンスイベントのアラートがトリガーされます。 
---
= パフォーマンスの想定範囲
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
想定される値の範囲とは、特定の時間において見込まれる上限と下限のパフォーマンス値の予測、または予測です。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値です。実測値がパフォーマンスしきい値を超えると、Unified Managerによってパフォーマンスイベントのアラートがトリガーされます。

たとえば、午前 9 時から午後 5 時までの通常の営業時間の間などですほとんどの従業員は、午前 9 時から午後 5 時まで E メールをチェックすることができますチェックするとしますこの期間、 E メールサーバの負荷が増加すると、バックエンドストレージのワークロードアクティビティが増加します。従業員の E メールクライアントからの応答時間が長くなる可能性があります。

昼食の時間は午後 12 時からとなっている午後 1 時までオープン午後 5 時以降の勤務日の終わりには、ほとんどの従業員がコンピュータから離れている可能性があります。一般に、 E メールサーバの負荷は軽減され、バックエンドストレージの負荷も軽減されます。または、ストレージのバックアップやウィルススキャンなどのワークロード処理を午後 5 時以降に実行するようにスケジュールしている場合もありますバックエンドストレージのアクティビティが増加します。

ワークロードアクティビティの増加と減少を数日間にわたって監視した結果から、アクティビティの想定範囲が特定され、ワークロードの上限と下限が決まります。オブジェクトに対する実際のワークロードアクティビティが上限と下限の範囲から外れ、その状態が一定の期間にわたって続く場合は、オブジェクトの使用率が高すぎるか低すぎる可能性があります。



== 想定範囲が決定される仕組み

Unified Managerでは、少なくとも3日分のワークロードアクティビティを収集して分析してから、GUIに表示するI/O応答時間と処理の想定範囲を決定します。この期間で収集されるデータには、ワークロードアクティビティにおける変化がすべて反映されるわけではありません。最初の3日間のアクティビティを収集したあと、Unified Managerでは想定範囲を24時間ごとに午前12時に調整し、ワークロードアクティビティの変化が反映された、より正確なパフォーマンスしきい値を設定します。

[NOTE]
====
システム時間が夏時間（DST）に切り替わると、監視しているワークロードのパフォーマンスの統計で使用する想定範囲が変わります。Unified Managerは、想定範囲の修正を即座に開始しますが、完了までに15日間ほどかかります。その間もUnified Managerの使用は継続できますが、Unified Managerは想定範囲を使用してイベントを検出するため、一部のイベントは正確でなくなる可能性があります。時間の変更前に検出されたイベントは影響を受けません。クラスタまたはUnified Managerサーバの時間を以前の時間に手動で変更した場合も、イベントの分析結果に影響します。

====