---
permalink: online-help/concept-what-reports-do.html 
sidebar: sidebar 
keywords:  
summary: レポートには、ストレージオブジェクトに関する詳細情報が表示されます。これにより、潜在的な問題を確認して特定できます。 
---
= レポートの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
レポートには、ストレージオブジェクトに関する詳細情報が表示されます。これにより、潜在的な問題を確認して特定できます。

レポートを保存、削除、共有、スケジュール、およびインポートできます。特定のレポートを検索することもできます。特定のユースケースに対応するようにレポートをカスタマイズして、あとで使用できるように保存できます。フィルタ、ソート、グループ化、書式設定などの追加の処理を実行できます。

デフォルトでは、各レポートグループはレポートタイプおよび概要 別に表示されます。レポートを実行して、特定のレポートグループを表示できます。

実行したレポートは、さらにカスタマイズして保存できます。[レポート]ページに保存されたカスタムレポートを、特定のレポートカテゴリに基づいてグループ化して表示できます。

PDF、XHTML、CSV、XLS、テキストのいずれかの形式で送信するようにレポートをスケジュールしたり、レポートを共有したりできます。

さまざまな形式でレポートをエクスポートして、デスクトップに保存できます。生成されたレポートから個 々 の列データをエクスポートできます。

レポート設計ファイルをインポートできます (`.rptdesign` ファイル）をクリックし、インポートしたレポートをReportsページに保存します。カスタムレポートとインポートしたレポートを削除できます。

インポートできるレポートは次のとおりです。

* 列のスパンが1に設定されている複数のヘッダーがあるレポート
* グラフのみのレポート
* リストとグリッドのみのレポート


テキスト、CSV、Excel形式のレポートは、次のシナリオでサポートされます。

* 内のテーブル要素のみ `.rptdesign` ファイル。
* 行としてヘッダーが1つだけのテーブル


列のスパンが1より大きい値に設定されているレポートをインポートすることはできません。テキスト、CSV、Excel形式のレポートに複数のヘッダー行がある場合、最初のヘッダー行だけが考慮され、残りの行は無視されます。
