---
permalink: online-help/concept-constituent-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 選択したFlexGroup コンスティチュエントの詳細なパフォーマンス情報は、パフォーマンス/コンスティチュエントボリュームエクスプローラページに表示されます。 
---
= Performance/ConstituentVolumeExplorerヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
選択したFlexGroup コンスティチュエントの詳細なパフォーマンス情報は、パフォーマンス/コンスティチュエントボリュームエクスプローラページに表示されます。

Performance/ConstituentVolumeExplorerヘエシを使用すると、一定期間のコンスティチュエントのパフォーマンスを追跡して比較できます。これは、FlexGroup ボリュームとそのコンスティチュエントボリュームのパフォーマンスのトラブルシューティングや微調整に役立ちます。

表示と比較機能を使用して、このコンスティチュエントボリュームのパフォーマンスを次の対象と比較できます。

* このコンスティチュエントボリュームが配置されているアグリゲート
* このコンスティチュエントボリュームが配置されているSVM
* コンスティチュエントボリュームが属するFlexGroup
* 同じアグリゲート上の他のボリューム


Performance/ConstituentVolumeExplorerヘエシを使用すると、次の操作を実行できます。

* しきい値に関連する問題とその詳細を表示します
* コンスティチュエントのパフォーマンスデータを追跡して比較する
* しきい値に関連する問題の調査とトラブルシューティング
* パフォーマンスの問題の調査とトラブルシューティング


[NOTE]
====
データ保護（DP）ボリュームについては、ユーザが生成したトラフィックのカウンタ値のみが表示されます。バージョン8.3より前のONTAP ソフトウェアがインストールされたクラスタでは、カウンタ値は表示されません。

====