---
permalink: online-help/concept-options-for-improving-workload-performance-from-the-client-side.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスイベントに関連したボリュームに I/O を送信しているアプリケーションやデータベースなどのクライアントワークロードを確認して、クライアント側の変更によってイベントが修正される可能性があるかどうかを判断できます。 
---
= クライアント側からワークロードパフォーマンスを改善するためのオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントに関連したボリュームに I/O を送信しているアプリケーションやデータベースなどのクライアントワークロードを確認して、クライアント側の変更によってイベントが修正される可能性があるかどうかを判断できます。

クラスタ上のボリュームに接続されたクライアントの I/O 要求が増加すると、その要求に対応するためにクラスタの負荷が増大します。クラスタの特定のボリュームに大量の I/O 要求を送信しているクライアントがわかれば、そのボリュームにアクセスするクライアントの数を調整するか、またはボリュームに送信される I/O の量を減らすことで、クラスタのパフォーマンスを向上させることができます。また、ボリュームがメンバーになっている QoS ポリシーグループに制限を適用または拡張することもできます。

クライアントとそのアプリケーションを調査して、クライアントが通常よりも多くの I/O を送信していることがクラスタコンポーネントでの競合の原因となっていないかを確認できます。イベントの詳細ページのシステム診断セクションに、競合状態にあるコンポーネントを使用する上位のボリュームワークロードが表示されます。特定のボリュームにアクセスしているクライアントがわかった場合は、そのクライアントに移動して、クライアントのハードウェアまたはアプリケーションが正常に動作しているか、あるいは通常より負荷が増えていないかを確認できます。

MetroCluster 構成では、ローカルクラスタ上のボリュームへの書き込み要求が、リモートクラスタ上のボリュームにミラーされます。ローカルクラスタ上のソースボリュームとリモートクラスタ上のデスティネーションボリュームの同期を維持することで、 MetroCluster 構成での両クラスタの要求が増加する可能性もあります。このようなミラーボリュームへの書き込み要求を減らすことで、クラスタが実行する同期処理が減り、他のワークロードのパフォーマンスに与える影響を軽減できます。
