---
permalink: online-help/concept-storage-virtual-machine-and-resource-pool-requirements-to-support-storage-services.html 
sidebar: sidebar 
keywords:  
summary: ストレージサービスに固有の SVM の関連付けやリソースプールの要件を確認する場合は、パートナーアプリケーションへの準拠を適切に確保することができます。 たとえば、 SVM を関連付けて Unified Manager でリソースプールを作成すると、パートナーアプリケーションから提供されるストレージサービスの保護トポロジがサポートされます。 
---
= ストレージサービスをサポートするための SVM とリソースプールの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージサービスに固有の SVM の関連付けやリソースプールの要件を確認する場合は、パートナーアプリケーションへの準拠を適切に確保することができます。 たとえば、 SVM を関連付けて Unified Manager でリソースプールを作成すると、パートナーアプリケーションから提供されるストレージサービスの保護トポロジがサポートされます。

一部のアプリケーションは、 Unified Manager サーバと連携し、ソースボリュームとセカンダリストレージまたは 3 番目のストレージにある保護ボリュームとの間で SnapMirror または SnapVault によるバックアップ保護を自動的に設定して実行するサービスを提供します。このような保護ストレージサービスをサポートするには、 Unified Manager を使用して、必要な SVM の関連付けとリソースプールを設定する必要があります。

ストレージサービスのシングルホップ保護またはカスケード保護をサポートするため、 SnapMirror ソースまたは SnapVault プライマリボリュームから、セカンダリまたは 3 番目の場所にあるデスティネーション SnapMirror または SnapVault バックアップボリュームへのレプリケーションを含むには、次の要件を確認してください。

* SnapMirror ソースまたは SnapVault プライマリボリュームを含む SVM と、セカンダリボリュームまたは 3 番目のボリュームが配置されている SVM の間で SVM の関連付けが設定されている必要があります。
+
** たとえば、ソースボリューム Vol_A が SVM_1 に配置されている保護トポロジで SnapMirror セカンダリデスティネーションボリューム Vol_B が SVM_2 に配置されている場合は、 3 番目の SnapVault バックアップボリューム Vol_C は SVM_3 に配置されています。 SVM _1 と SVM _2 の間の SnapMirror の関連付けと、 SVM _1 と SVM _3 の間の SnapVault バックアップの関連付けを設定するには、 Unified Manager Web UI を使用する必要があります。
+
この例では、 SVM _2 と SVM _3 の間の SnapMirror の関連付けまたは SnapVault バックアップの関連付けは不要なため、使用されません。

** ソースボリューム Vol_A と SnapMirror デスティネーションボリューム Vol_B の両方が SVM _1 に配置されている保護トポロジをサポートするには、 SVM _1 と SVM _1 の間に SnapMirror の関連付けを設定する必要があります。


* リソースプールには、関連付けられた SVM で使用可能なクラスタのアグリゲートリソースが含まれている必要があります。
+
Unified Manager Web UI でリソースプールを設定し、パートナーアプリケーションを使用してストレージサービスのセカンダリターゲットノードと 3 番目のターゲットノードを割り当てます。


