---
permalink: online-help/concept-types-of-workloads-monitored-by-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。 
---
= Unified Manager で監視されるワークロードのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。

* * _ ユーザ定義のワークロード _ *
+
アプリケーションからクラスタへの I/O スループット。読み取り要求と書き込み要求に関連するプロセスです。FlexVol ボリュームまたはFlexGroup ボリュームはユーザ定義のワークロードです。

+
[NOTE]
====
Unified Manager は、クラスタ内のワークロードだけを監視します。アプリケーション、クライアント、またはアプリケーションとクラスタ間のパスは監視しません。

====
+
次の条件が 1 つ以上該当するワークロードは、 Unified Manager で監視できません。

+
** 読み取り専用モードのデータ保護（ DP ）コピーである。（ONTAP 8.3以降を使用している場合は、ユーザ生成のトラフィックについてDPボリュームが監視されます）。
** ボリュームがInfinite Volumeである。
** ボリュームがオフラインデータクローンである。
** ボリュームが MetroCluster 構成のミラーボリュームである。


* * _ システム定義のワークロード _ *
+
次のストレージ効率化、データレプリケーション、およびシステム健全性に関連する内部プロセスです。

+
** 重複排除などのストレージ効率
** ディスクの健常性。 RAID の再構築、ディスクスクラビングなどが含まれます
** SnapMirror コピーなどのデータレプリケーション
** 管理アクティビティ
** ファイルシステムの健全性。さまざまな WAFL アクティビティが含まれます
** WAFL スキャンなどのファイルシステムスキャナ
** VMware ホストからのオフロードされたストレージ効率化処理などのコピーオフロード
** ボリューム移動やデータ圧縮などのシステムヘルス
** 監視対象外のボリューム




システム定義のワークロードのパフォーマンスデータは、これらのワークロードで使用されるクラスタコンポーネントが競合状態の場合にのみ表示されます。たとえば、システム定義のワークロードの名前を検索して、そのパフォーマンスデータを表示することはできません。同じ種類のシステム定義ワークロードが複数表示される場合は、ワークロード名にアルファベットが付け加えられます。この文字は、サポート担当者が使用することを目的としています。
