---
permalink: online-help/reference-dynamic-performance-event-chart-details.html 
sidebar: sidebar 
keywords:  
summary: 動的なパフォーマンスイベントの場合、イベントの詳細ページのシステム診断セクションに、競合状態のクラスタコンポーネントのレイテンシまたは使用量が最も高い上位のワークロードが表示されます。パフォーマンス統計は、パフォーマンスイベントが検出されてからイベントが最後に分析されるまでの時間に基づいています。このグラフには、競合状態のクラスタコンポーネントの過去のパフォーマンス統計も表示されます。 
---
= 動的なパフォーマンスイベントチャートの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
動的なパフォーマンスイベントの場合、イベントの詳細ページのシステム診断セクションに、競合状態のクラスタコンポーネントのレイテンシまたは使用量が最も高い上位のワークロードが表示されます。パフォーマンス統計は、パフォーマンスイベントが検出されてからイベントが最後に分析されるまでの時間に基づいています。このグラフには、競合状態のクラスタコンポーネントの過去のパフォーマンス統計も表示されます。

たとえば、コンポーネントの利用率が高いワークロードを特定して、利用率が低いコンポーネントに移動するワークロードを特定できます。ワークロードを移動すると、現在のコンポーネントでの作業量が減り、コンポーネントの競合状態が解消する可能性があります。このセクションには、イベントが検出されて最後に分析された時刻と日付の範囲が表示されます。アクティブなイベント（新規または確認済みのイベント）の場合は、最後に分析された時刻が継続的に更新されます。

レイテンシとアクティビティのグラフにカーソルを合わせると、上位のワークロードの名前が表示されます。グラフの右側にあるワークロードのタイプメニューをクリックすると、イベントでのワークロードのロールに基づいてワークロードをソートできます。これには、 _Shark 、 _Bully 、 _Victim の各ワークロードのレイテンシと競合しているクラスタコンポーネントでの使用状況の詳細が表示されます。実際の値と想定値を比較して、ワークロードがレイテンシまたは使用量の想定範囲を外れたタイミングを確認できます。を参照してください xref:concept-types-of-workloads-monitored-by-unified-manager.adoc[Unified Managerで監視されるワークロードの数]。

[NOTE]
====
レイテンシのピーク偏差でソートする場合は、システム定義のワークロードがテーブルに表示されません。これは、レイテンシがユーザ定義のワークロードにのみ適用されるためです。レイテンシの値が小さいワークロードはこのテーブルに表示されません。

====
動的なパフォーマンスしきい値の詳細については、を参照してください xref:reference-performance-event-analysis-and-notification.adoc[イベントとは]。Unified Managerでワークロードをランク付けしてソート順序を決定する方法については、を参照してください xref:concept-how-unified-manager-determines-the-performance-impact-for-an-incident.adoc[Unified Manager がイベントによるパフォーマンスへの影響を判定する仕組み]。

グラフ内のデータには、イベントが最後に分析されるまでの 24 時間のパフォーマンス統計が示されます。各ワークロードの実際の値と想定値は、ワークロードがイベントに関連した時刻に基づいています。たとえば、イベントの検出後にワークロードがイベントに関連した可能性があるため、そのパフォーマンス統計がイベント検出時の値と一致しないことがあります。デフォルトでは、レイテンシのピーク（最大）偏差でワークロードがソートされます。

[NOTE]
====
Unified Manager では 5 分ごとのパフォーマンスとイベントの履歴データが最大 30 日分保持されるため、 30 日前より古いイベントの場合、パフォーマンスデータは表示されません。

====
* * ワークロードソート列 *
+
** * レイテンシグラフ *
+
前回の分析中の、ワークロードのレイテンシに対するイベントの影響が表示されます。

** * コンポーネント使用状況列 *
+
競合状態のクラスタコンポーネントのワークロードの使用量に関する詳細が表示されます。グラフでは、実際の使用量は青い線で表示されます。検出時刻から最後に分析された時刻までのイベント期間が赤いバーで強調表示されます。詳細については、を参照してください xref:reference-workload-performance-measurement-values.adoc[ワークロードのパフォーマンスの測定値]。

+
[NOTE]
====
ネットワークコンポーネントの場合は、クラスタ以外のアクティビティに基づいてネットワークパフォーマンス統計が作成されるため、この列は表示されません。

====
** * コンポーネント使用率 *
+
QoS ポリシーグループコンポーネントのネットワーク処理、データ処理、および集約コンポーネントの使用率の履歴、またはアクティビティの履歴をパーセント単位で表示します。ネットワークコンポーネントまたはインターコネクトコンポーネントについては、このグラフは表示されません。統計にカーソルを合わせると、特定の時点における使用状況を表示できます。

** *書き込みMBps履歴の合計*
+
MetroCluster のリソースコンポーネントの場合にのみ、 MetroCluster 構成のパートナークラスタにミラーリングされるすべてのボリュームワークロードについて、書き込みスループットの合計が 1 秒あたりのメガバイト数（ MBps ）で表示されます。

** * イベント履歴 *
+
競合状態のコンポーネントの過去のイベントを示す赤い影付きの線が表示されます。廃止イベントの場合は、選択したイベントが検出される前に発生したイベントと解決後のイベントがグラフに表示されます。




