---
permalink: online-help/reference-management-annotations-page.html 
sidebar: sidebar 
keywords:  
summary: 管理/アノテーションページでは、Unified Managerでストレージオブジェクトのアノテーションを作成したり、アノテーションを編集または削除したりできます。アノテーション/値ペアを使用してストレージオブジェクトを手動でアノテートするか、またはアノテーションルールを設定することができます。ストレージオブジェクトは、適用したアノテーションに基づいて動的にアノテートされます。 
---
= 管理/アノテーションページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理/アノテーションページでは、Unified Managerでストレージオブジェクトのアノテーションを作成したり、アノテーションを編集または削除したりできます。アノテーション/値ペアを使用してストレージオブジェクトを手動でアノテートするか、またはアノテーションルールを設定することができます。ストレージオブジェクトは、適用したアノテーションに基づいて動的にアノテートされます。

オペレータとしてログインすると、ページへの読み取りアクセスのみが許可されます。ストレージ管理者またはUnified Manager管理者としてログインした場合は、各タブで追加、編集、削除の各ボタンを使用できます。



== [注釈]タブ

アノテーションタブでは、Unified Managerでアノテーションを表示、作成、編集、削除できます。

* *注釈リスト*
+
事前定義されたアノテーションとカスタムアノテーションの名前が表示されます。各アノテーションに関連付けられているアノテーション値の数も表示されます。アノテーション名をクリックすると、アノテーションの詳細が表示されます。





== サマリ領域

選択したアノテーションについて、次の詳細が表示されます。

* * 概要 *
+
アノテーションに設定されている概要 が表示されます。

* *作成者*
+
アノテーションを作成したユーザの名前が表示されます。

* *作成日*
+
アノテーションが作成された日付が表示されます。





== アノテーション=値ペア

選択したアノテーションに設定されているアノテーション/値ペアおよび関連するストレージオブジェクトのリストが表示されます。

* * 値 *
+
アノテーション/値ペアの名前が表示されます。

* *該当するクラスタ*
+
特定のアノテーション/値ペアでアノテートされているクラスタの数が表示されます。数をクリックすると、クラスタページが開いて、特定の値に関連するクラスタのみを含むリストが表示されます。

* *該当するStorage Virtual Machine（SVM）*
+
特定のアノテーション/値ペアでアノテートされているStorage Virtual Machine（SVM）の数が表示されます。数をクリックすると、Storage Virtual Machine（SVM）ページが開いて、特定の値に関連するStorage Virtual Machine（SVM）のみを含むリストが表示されます。

* *該当するボリューム*
+
特定のアノテーション/値ペアでアノテートされているボリュームの数が表示されます。数をクリックすると、ボリュームページが開いて、特定の値に関連するボリュームのみを含むリストが表示されます。





== ルールによるオブジェクトの関連付け

選択したアノテーションのアノテーションルールおよび関連するストレージオブジェクトのリストが表示されます。

* *ランク*
+
ストレージオブジェクトに適用されるアノテーションルールの順序が表示されます。

* *ルール*
+
アノテーションルールの名前が表示されます。

* *ターゲットオブジェクトタイプ*
+
アノテーションルールが適用されるストレージオブジェクトのタイプが表示されます。

* *関連付けられているアノテーション値*
+
ストレージオブジェクトに適用されるアノテーション/値ペアが表示されます。

* *該当するオブジェクト*
+
アノテーションルールに基づいてアノテートされているストレージオブジェクトの数が表示されます。





== 手動でのオブジェクトの関連付け

手動で設定してストレージオブジェクトに関連付けたアノテーションのリストが表示されます。

* *アノテーション=値ペア*
+
手動で設定したアノテーションの名前と値が表示されます。

* *該当するクラスタ*
+
手動で設定した特定のアノテーション値でアノテートされているクラスタの数が表示されます。数をクリックすると、クラスタページが開いて、特定の値に関連するクラスタのみを含むリストが表示されます。

* *該当するStorage Virtual Machine（SVM）*
+
手動で設定した特定のアノテーション値でアノテートされているStorage Virtual Machine（SVM）の数が表示されます。数をクリックすると、Storage Virtual Machine（SVM）ページが開いて、特定の値に関連するStorage Virtual Machine（SVM）のみを含むリストが表示されます。

* *該当するボリューム*
+
手動で設定した特定のアノテーション値でアノテートされているボリュームの数が表示されます。数をクリックすると、ボリュームページが開いて、特定の値に関連するボリュームのみを含むリストが表示されます。





== コマンドボタン

OnCommand 管理者またはストレージ管理者のロールが必要です。事前定義されたアノテーションに対して、値を追加または削除することはできません。

* *注釈を追加*
+
アノテーションの追加（Add Annotation）ダイアログボックスを開きます。このダイアログボックスで、新しいカスタムアノテーションを作成し、アノテーションに値を割り当てることができます。

* * アクション *
+
選択したアノテーション概要 を編集または削除できます。

* * 編集 * 。
+
アノテーションの編集ダイアログボックスが開き、アノテーション名と概要 を変更できます。

* * 削除 *
+
アノテーション値を削除できます。値を削除できるのは、どのアノテーションルールやグループルールにも関連付けられていない値のみです。





== アノテーションルールタブ

アノテーションルールタブには、ストレージオブジェクトにアノテーションを適用するために作成したアノテーションルールが表示されます。アノテーションルールの追加、編集、削除、順序変更などのタスクを実行できます。アノテーションルールを満たしているストレージオブジェクトの数を表示することもできます。



== コマンドボタン

OnCommand 管理者またはストレージ管理者のロールが必要です。

* * 追加 * 。
+
アノテーションルールの追加ダイアログボックスが表示されます。このダイアログボックスで、ストレージオブジェクトのアノテーションルールを作成できます。

* * 編集 * 。
+
アノテーションルールの編集ダイアログボックスが表示されます。このダイアログボックスで、以前に設定したアノテーションルールを再設定できます。

* * 削除 *
+
選択したアノテーションルールを削除します。

* *リオーダ*
+
ReorderAnnotationRuleタイアロクホツクスを表示します。このダイアログボックスでは、アノテーションルールの順序を変更できます。





== リストビュー

リストビューには、Unified Managerサーバで作成したアノテーションルールが表形式で表示されます。列のフィルタを使用して、表示するデータをカスタマイズできます。アノテーションルール(Annotation Rules)タブのリストビューとアノテーション(Annotation)タブの関連ルール(Associated Rules)セクションのリストビューには'次のカラムがあります

* ランク
* 名前
* ターゲットオブジェクトタイプ
* 関連付けられているアノテーション値
* 該当するオブジェクト


アノテーションルール（Associated Annotation）タブの追加の列が表示され、ストレージオブジェクトに適用されるアノテーションの名前が表示されます。
