---
permalink: online-help/reference-qtree-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Qtree Capacity and Utilizationレポートでは、システムのqtreeの容量と使用率を分析して、クラスタ容量の減少によって発生する可能性のあるリスクを把握できます。 
---
= qtreeの容量と使用状況レポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
qtreeの容量と使用状況レポートでは、システムのqtreeの容量と使用状況を分析して、クラスタ容量の減少が原因で発生する可能性があるリスクを把握することができます。



== qtreeの容量と使用状況レポートの表形式ビュー

* * クラスタ *
+
qtree を含むクラスタの名前が表示されます。

* * Storage Virtual Machine *
+
qtree を含む Storage Virtual Machine （ SVM ）の名前が表示されます。

* * 音量 *
+
qtreeを含むボリュームの名前が表示されます。

* * qtree *
+
qtree の名前が表示されます。

* *クォータタイプ*
+
ユーザ、ユーザグループ、またはqtreeのいずれのクォータであるかを示します。

* * ユーザーまたはグループ *
+
ユーザまたはユーザグループの名前が表示されます。ユーザおよびユーザグループごとに複数の行が表示されます。クォータのタイプがqtreeの場合は、_not applicable _が表示されます。クォータが設定されていない場合は、列が空になります。

* * 使用ディスク %*
+
ディスクスペースの使用率が表示されます。ディスクのハードリミットが設定されている場合は、そのハードリミットに基づく値です。ディスクのハードリミットなしでクォータが設定されている場合は、ボリュームのデータスペースに基づきます。クォータが設定されていない場合やqtreeが属するボリュームでクォータがオフになっている場合は、_not applicable _が表示されます。

* * ディスクハードリミット *
+
qtreeに割り当てられる最大ディスクスペースが表示されます。この上限に達すると、 Unified Manager で重大なイベントが生成され、ディスクへの書き込みがそれ以上許可されなくなります。ディスクのハードリミットなしでクォータが設定されている場合、クォータが設定されていない場合、またはqtreeが属するボリュームでクォータがオフになっている場合は、「_Unlimited」と表示されます。

* * ディスクソフトリミット *
+
qtreeに割り当てられるディスクスペースについて、警告イベントを生成する容量が表示されます。ディスクのソフトリミットなしでクォータが設定されている場合、クォータが設定されていない場合、またはqtreeが属するボリュームでクォータがオフになっている場合は、「_Unlimited」と表示されます。

* * 使用されているファイル数 %*
+
qtree で使用されているファイルの割合が表示されます。ファイルのハードリミットが設定されている場合は、そのハードリミットに基づく値です。クォータが設定されていない場合、ファイルのハードリミットなしでクォータが設定されている場合、またはqtreeが属するボリュームでクォータがオフになっている場合は、この値は_not applicable _と表示されます。

* * ファイルハードリミット *
+
qtree に許可されるファイル数のハードリミットが表示されます。ファイルのハードリミットなしでクォータが設定されている場合、クォータが設定されていない場合、またはqtreeが属するボリュームでクォータがオフになっている場合は、「_Unlimited」と表示されます。

* * ファイルソフトリミット *
+
qtree に許可されるファイル数のソフトリミットが表示されます。ファイルのソフトリミットなしでクォータが設定されている場合、クォータが設定されていない場合、またはqtreeが属するボリュームでクォータがオフになっている場合は、「_Unlimited」と表示されます。


