---
permalink: online-help/reference-group-action-volume-thresholds-section.html 
sidebar: sidebar 
keywords:  
summary: グループ操作ボリュームしきい値セクションでは、ボリュームについてのグループレベルの健常性しきい値を設定できます。これらのしきい値はグループ内のすべてのボリュームに適用されます。グループレベルでボリュームの健常性しきい値が設定されている場合、グローバルな健常性しきい値の値は適用されません。 
---
= グループ操作ボリュームしきい値セクション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グループ操作ボリュームしきい値セクションでは、ボリュームについてのグループレベルの健常性しきい値を設定できます。これらのしきい値はグループ内のすべてのボリュームに適用されます。グループレベルでボリュームの健常性しきい値が設定されている場合、グローバルな健常性しきい値の値は適用されません。

グループ操作の設定では、次の項目についてボリューム健常性しきい値を設定できます。

* 容量
* 容量増加
* qtreeクォータ
* Snapshot コピー
* inode


これらのうちボリューム健常性しきい値が設定されていないカテゴリについて、グローバルなデフォルト値が使用されます。次の項目について健常性しきい値を設定できます。

* 容量
* 容量増加
* qtreeクォータ
* Snapshot コピー
* inode




== 容量セクション

ボリュームの容量について、次の健常性しきい値条件を設定できます。

* *スペースがほぼフル*
+
ボリュームがほぼフルであるとみなす割合を示します。

+
** デフォルト値：80%
+
管理サーバでイベントが生成されるように、このしきい値の値は「ボリュームがフル」のしきい値の値よりも小さくする必要があります。

** 生成されるイベント：ボリュームがほぼフルです
** イベントの重大度：警告


* *スペースがフル*
+
ボリュームがフルであるとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：ボリュームがフルです
** イベントの重大度：エラー


* *オーバーコミット*
+
ボリュームがオーバーコミットされているとみなす割合を示します。

+
** デフォルト値は100%です
** 生成されるイベント：Volume Overcommitted
** イベントの重大度：エラー






== 成長セクション

ボリュームの増加率について、次の健常性しきい値条件を設定できます。

* *増加率*
+
ボリュームの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「ボリュームの増加率-異常」イベントが生成されます。

+
** デフォルト値：1%
** 生成されるイベント：ボリュームの増加率-異常
** イベントの重大度：警告


* *増加率係数*
+
ボリュームの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

+
アグリゲートが増加率の変化による影響を受けやすい場合は、増加率係数の値を小さくします。増加率係数の範囲は1~5です。

+
** デフォルト値：2






== qtreeクォータセクション

ボリュームのクォータについて、次の健常性しきい値条件を設定できます。

* *ほぼオーバーコミット*
+
ボリュームのqtreeクォータがほぼオーバーコミットされているとみなす割合を示します。

+
** デフォルト値：95%
** 生成されるイベント：ボリュームのqtreeクォータがほぼオーバーコミットされています
** イベントの重大度：警告


* *オーバーコミット*
+
ボリュームのqtreeクォータがオーバーコミットされているとみなす割合を示します。

+
** デフォルト値は100%です
** 生成されるイベント：ボリュームのqtreeクォータがオーバーコミット
** イベントの重大度：エラー






== Snapshotコピーセクション

ボリューム内のSnapshotコピーについて、次の健常性しきい値条件を設定できます。

* * Snapshotリザーブがフル*
+
Snapshotコピー用にリザーブされたスペースがフルであるとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：ボリュームのSnapshotリザーブがフルです
** イベントの重大度：エラー


* *フルまでの日数*
+
Snapshotコピー用にリザーブされたスペースがフルに達するまでの残り日数を示します。

+
** デフォルト値：7
** 生成されるイベント：ボリュームのSnapshotリザーブのフルまでの日数
** イベントの重大度：エラー


* *カウント*
+
ボリュームのSnapshotコピーが多すぎるとみなす数を示します。

+
** デフォルト値：250
** 生成されるイベント：Snapshotコピー数の上限を超えています
** イベントの重大度：エラー






== inodeセクション

inodeについて、次の健常性しきい値条件を設定できます。

* *ほぼフル*
+
ボリュームのinodeがほぼ使用されているとみなす割合を示します。

+
** デフォルト値：80%
** 生成されるイベント：inodeがほぼフルです
** イベントの重大度：警告


* *フル*
+
ボリュームのinodeがすべて使用されているとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：inodeがフルです
** イベントの重大度：エラー



