---
permalink: online-help/reference-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: このページでは、ボリュームの物理的な属性と論理的な属性のリストを確認できます。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。このページのタイトルは、FlexVol ボリュームとFlexGroup ボリュームのどちらを表示しているかによって異なります。 
---
= ハフオオマンス/ホリユウムマタハハハフオオマンス/FlexGroupシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このページでは、ボリュームの物理的な属性と論理的な属性のリストを確認できます。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。このページのタイトルは、FlexVol ボリュームとFlexGroup ボリュームのどちらを表示しているかによって異なります。



== ボリュームの属性

* * タイプ *
+
ボリュームのタイプ（読み書き可能（rw）またはデータ保護（DP））。

* * スタイル *
+
ボリュームの形式。FlexVol またはFlexGroup のいずれかです。

+
[NOTE]
====
Unified Managerのパフォーマンスページでは、Infinite Volumeがサポートされません。

====
* * クラスタ *
+
このFlexVol またはFlexGroup ボリュームが属するクラスタの名前。名前をクリックすると、Performance/ClusterExplorerヘエシにクラスタの詳細を表示できます。

* * アグリゲート *
+
このFlexVol ボリュームが配置されているアグリゲートの名前、またはこのFlexGroup ボリュームが配置されているアグリゲートの数。

+
FlexVol ボリュームの場合は、名前をクリックすると、パフォーマンス/アグリゲートエクスプローラのページにアグリゲートの詳細を表示できます。FlexGroup ボリュームの場合は、数値をクリックすると、このFlexGroup ボリュームで使用されているアグリゲートをPerformance/AggregateInventoryページに表示できます。

* * Storage Virtual Machine *
+
このFlexVol またはFlexGroup ボリュームが属するSVMの名前。名前をクリックすると、Performance/SVMExplorerヘエシにSVMの詳細を表示できます。

* * 階層化ポリシー *
+
ボリュームに対して設定されている階層化ポリシー。このポリシーは、ボリュームがFabricPool アグリゲートに導入されている場合にのみ適用されます。使用可能なポリシーは次のとおりです。

+
** なしこのボリュームのデータは常に高パフォーマンス階層に残ります。
** Snapshotのみ：Snapshotデータのみがクラウド階層に自動的に移動されます。それ以外のデータはすべて高パフォーマンス階層に残ります。
** バックアップ：データ保護ボリュームで、転送されたユーザデータは最初はすべてクラウド階層に配置されますが、その後、クライアントによるホットデータの読み取りが多い原因 を高パフォーマンス階層に移動できます。
** 自動：このボリューム上のデータは、ONTAP がデータが「ホット」または「コールド」と判断した場合に、パフォーマンス階層とクラウド階層の間で自動的に移動されます。


* * RAID タイプ *
+
このボリュームが配置されているアグリゲートのパフォーマンス階層で使用されている冗長性のタイプ。有効なタイプは次のとおり

+
** RAID 0
** RAID 4
** RAID-DP
** RAID-TEC


+
[NOTE]
====
FlexGroup ボリュームの場合は、コンスティチュエントボリュームが異なるRAIDタイプのアグリゲートに配置されている可能性があるため、値「該当なし」が表示されます。

====
* *容量（空き/合計）*
+
ボリューム上で使用可能な合計ストレージ容量（GB）、および現在使用可能なストレージ容量。


