---
permalink: online-help/reference-definitions-of-user-types.html 
sidebar: sidebar 
keywords:  
summary: ユーザは、アカウントの種類に基づいて、リモートユーザ、リモートグループ、ローカルユーザ、データベースユーザ、およびメンテナンスユーザの各タイプに分類されます。それぞれのタイプには、OnCommand 管理者ロールを持つユーザによって独自のロールが割り当てられます。 
---
= ユーザタイプの定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザは、アカウントの種類に基づいて、リモートユーザ、リモートグループ、ローカルユーザ、データベースユーザ、およびメンテナンスユーザの各タイプに分類されます。それぞれのタイプには、OnCommand 管理者ロールを持つユーザによって独自のロールが割り当てられます。

Unified Manager には次のユーザタイプがあります。

* * メンテナンスユーザー *
+
Unified Manager の初期設定時に作成されます。メンテナンスユーザは、別のユーザを作成してロールを割り当てます。メンテナンスコンソールにアクセスできる唯一のユーザでもあります。Unified Manager を Red Hat Enterprise Linux または CentOS システムにインストールしている場合、メンテナンスユーザのユーザ名は「 umadmin 」です。

* * ローカルユーザー *
+
Unified Manager UIにアクセスし、メンテナンスユーザまたはOnCommand 管理者ロールを持つユーザから割り当てられたロールに基づいて操作を実行します。

* * リモートグループ *
+
認証サーバに保存されているクレデンシャルを使用して Unified Manager UI にアクセスするユーザのグループです。このアカウントの名前は、認証サーバに保存されているグループの名前と一致している必要があります。リモートグループのユーザは、各自のユーザクレデンシャルを使用して Unified Manager UI にアクセスできます。リモートグループに割り当てられたロールに基づいて操作を実行できます。

* * リモートユーザー *
+
認証サーバに保存されているクレデンシャルを使用して Unified Manager UI にアクセスします。リモートユーザは、メンテナンスユーザまたはOnCommand 管理者ロールを持つユーザから割り当てられたロールに基づいて操作を実行します。

* * データベースユーザー *
+
Unified Manager データベースのデータへの読み取り専用アクセスが許可されます。 Unified Manager の Web インターフェイスやメンテナンスコンソールにはアクセスできず、 API 呼び出しも実行できません。


