---
permalink: online-help/reference-events-report.html 
sidebar: sidebar 
keywords:  
summary: Eventsレポートでは、特定の期間のイベントの傾向に関する情報を確認できます。この情報を使用して、設定の変更やアップグレードなど、最新のアクティビティと過去のアクティビティを比較することができます。この情報は、未解決のイベントを特定するのにも役立ちます。 
---
= イベントレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eventsレポートでは、特定の期間のイベントの傾向に関する情報を確認できます。この情報を使用して、設定の変更やアップグレードなど、最新のアクティビティと過去のアクティビティを比較することができます。この情報は、未解決のイベントを特定するのにも役立ちます。



== イベントレポートチャートビュー

Eventsレポートは、次の2つの形式で表示されます。

* イベントレポートチャートビュー
* イベントレポートの表形式ビュー


イベントチャートは、次の2つの形式で表示されます。

* イベント重大度トレンド（すべてのオープンイベント）
* イベントステータストレンド


このチャートには、一定期間のすべてのオープンなイベントの重大度の傾向が表示されます。縦軸（y軸）にイベントの数が表示され、横軸（x軸）に日付が表示されます。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。詳細には、イベントの重大度、特定の重大度のイベントの数、およびイベントの日付が表示されます。

イベントの重大度は、「重大」、「エラー」、「警告」のいずれかになります。これらの重大度別にイベントが色分けされて表示されます。状態が異なるイベントが同じ日に同じ数存在する場合があります。

* *カウント*
+
イベントの数が表示されます。

* * 日付 *
+
日付が表示されます。x軸には、イベントが発生した時点から現在の日付までのデータが表示されます。グラフをクリックしてズームすると、詳細を確認できます。



このグラフには、一定期間の1日あたりのイベントのステータスの傾向が表示されます。縦軸（y軸）にイベントの数が表示され、横軸（x軸）に日付が表示されます。詳細には、イベントの状態、特定の状態のイベントの数、およびイベントの日付が表示されます。

イベントのステータスは、「新規」、「確認済み」、「解決済み」のいずれかです。これらのステータス別にイベントが色分けされて表示されます。

このグラフには、1日に生成された新規のイベントの累積数が棒グラフに緑色で表示されます。イベントが確認および解決されると、それらのイベントの数が日単位で集計されて表示されます。

グラフにはズーム機能が用意されています。この機能を使用すると、グラフ内の特定のポイントをズームして見やすくすることができます。

* * 出典 *
+
イベントのソースを表示します。

* * ステータス *
+
イベントの重大度が表示されます。この列でフィルタすると、特定の重大度のイベントを表示できます。イベントの重大度タイプは、「重大」、「エラー」、または「警告」です。

* * 状態 *
+
イベントの状態が表示されます。新規、確認済み、解決済み、廃止のいずれかになります。この列でフィルタすると、特定の状態のイベントを表示できます。

* * イベント *
+
イベント名が表示されます。

* * トリガー日時 *
+
イベントが生成された時刻が表示されます。時刻と日付の両方が表示されます。

* * 未処理日数 *
+
イベントが発生してから解決されるか廃止されるまでの日数が表示されます。

* * ソースタイプ *
+
イベントが関連付けられているオブジェクトのタイプ（Storage Virtual Machine（SVM）、ボリューム、qtreeなど）が表示されます。

* *データ優先度*
+
ストレージオブジェクトのデータの優先度に基づいて、アノテーションのタイプが表示されます。

* * 影響レベル *
+
イベントがインシデント、リスク、または情報のいずれに分類されているかが表示されます。

* * 影響領域 *
+
容量、可用性、パフォーマンス、保護、または構成のいずれに関連するイベントであるかが表示されます。

* * 割り当て先 *
+
イベントが割り当てられているユーザの名前が表示されます。

* * 割り当て時間 *
+
イベントがユーザに割り当てられた時刻が表示されます。

* * メモ *
+
イベントに追加されているメモの数が表示されます。

* * 承認者 *
+
イベントを確認したユーザの名前が表示されます。イベントが確認されていない場合は空白になります。

* * 承認時間 *
+
イベントが確認されてからの経過時間が表示されます。1週間を過ぎたイベントには、確認時のタイムスタンプが表示されます。

* * 解決者 *
+
イベントを解決したユーザの名前が表示されます。イベントが解決されていない場合は空白になります。

* * 解決時間 *
+
イベントが解決されてからの経過時間が表示されます。1週間を過ぎたイベントには、解決時のタイムスタンプが表示されます。

* * 廃止時刻 *
+
イベントの状態が「廃止」になった時刻が表示されます。


