---
permalink: online-help/reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Rules to Generate User and Group Quota Email Address ページでは、クラスタ、 SVM 、ボリューム、 qtree 、ユーザに関連付けられたユーザクォータに基づいて E メールアドレスを指定するルールを作成できます。 またはユーザグループを指定します。クォータに違反が発生すると、指定した E メールアドレスに通知が送信されます。 
---
= RulestoGenerateUserandGroupQuotaEmailAddress ヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Rules to Generate User and Group Quota Email Address ページでは、クラスタ、 SVM 、ボリューム、 qtree 、ユーザに関連付けられたユーザクォータに基づいて E メールアドレスを指定するルールを作成できます。 またはユーザグループを指定します。クォータに違反が発生すると、指定した E メールアドレスに通知が送信されます。



== ルール領域

クォータの E メールアドレスに関するルールを定義する必要があります。ルールを説明するコメントを追加することもできます。



== ルールを定義する方法

ルールは実行する順序で入力する必要があります。最初のルールの条件が満たされると、このルールに基づいて E メールアドレスが生成されます。条件が満たされていない場合は、次のルールの条件が考慮されます。行ごとに個別のルールがリストされます。デフォルトのルールはリストの最後のルールです。ルールの優先順位は変更できます。ただし、デフォルトルールの順序は変更できません。

たとえば、 qtree1 でのクォータ違反に関する通知を E メールアドレス「 qtree1@xyz.com 」で受信し、それ以外の qtree については E メールアドレス「 admin@xyz.com 」を使用する場合は、次の順序でルールを指定する必要があります。

* if （ $qtree='qtree1' ） then qtree1@xyz.com
* if （ $qtree== * ） then admin@xyz.com


指定したルールの条件がどれも満たされていない場合は、デフォルトのルールが使用されます。

if （ $user_or_group=* ） then $user_or_group@$domain

複数のユーザが同じクォータを使用する場合は、ユーザの名前がカンマで区切って表示され、そのクォータにはルールが適用されません。



== コメントを追加する方法

ルールを説明するコメントを追加できます。各コメントの先頭に # を付け、 1 行に 1 つずつコメントがリストされるようにしてください。



== ルールの構文

ルールの構文には、次のいずれかを使用する必要があります。

* if（_有効な変数** OPERATOR _*）then _email ID_@_ domain name_
+
`if` はキーワードで、小文字で記述します。演算子は = です。E メール ID には、任意の文字、有効な変数 $user_or_group 、 $user 、または $group 、あるいは任意の文字と有効な変数 $user_or_group 、 $user 、または $group の組み合わせを含めることができます。ドメイン名には、任意の文字、有効な変数 $DOMAIN 、または任意の文字と有効な変数 $DOMAIN の組み合わせを使用できます。有効な変数は大文字と小文字のどちらでもかまいませんが、両方を組み合わせることはできません。たとえば、 $domain と $domain は有効ですが、 $Domain は有効な変数ではありません。

* if（_有効な変数** OPERATOR _'_STRING_'）then _email ID_@_ DOMAIN NAME_
+
`if` はキーワードで、小文字です。演算子はです `contains` または=。E メール ID には、任意の文字、有効な変数 $user_or_group 、 $user 、または $group 、あるいは任意の文字と有効な変数 $user_or_group 、 $user 、または $group の組み合わせを含めることができます。ドメイン名には、任意の文字、有効な変数 $DOMAIN 、または任意の文字と有効な変数 $DOMAIN の組み合わせを使用できます。有効な変数は大文字と小文字のどちらでもかまいませんが、両方を組み合わせることはできません。たとえば、 $domain と $domain は有効ですが、 $Domain は有効な変数ではありません。





== コマンドボタン

コマンドボタンを使用して、作成したルールを保存、検証、またはキャンセルできます。

* * 検証 *
+
作成したルールの構文を検証します。検証でエラーが発生した場合は、エラーを生成するルールがエラーメッセージとともに表示されます。

* * 工場出荷時のデフォルトに戻します *
+
アドレスルールを工場出荷時のデフォルト値に戻すことができます。

* * 保存 *
+
ルールの構文を検証し、エラーがない場合はルールを保存します。検証でエラーが発生した場合は、エラーを生成するルールがエラーメッセージとともに表示されます。


