---
permalink: online-help/reference-lag-thresholds-for-unmanaged-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: 管理対象外の関係の遅延しきい値ページでは、管理対象外の保護関係にグローバルな遅延警告しきい値と遅延エラーしきい値を設定できます。これにより、遅延エラーやしきい値エラーが発生した場合に、通知を受けて対処することができます。これらの設定に対する変更は、次にスケジュールされている更新で適用されます。 
---
= 管理対象外の関係の遅延しきい値ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理対象外の関係の遅延しきい値ページでは、管理対象外の保護関係にグローバルな遅延警告しきい値と遅延エラーしきい値を設定できます。これにより、遅延エラーやしきい値エラーが発生した場合に、通知を受けて対処することができます。これらの設定に対する変更は、次にスケジュールされている更新で適用されます。

OnCommand 管理者またはストレージ管理者のロールが必要です。

しきい値を超えるとイベントが生成されます。そのようなイベントに対して対処方法を実行できます。管理対象外の関係に対する遅延しきい値の設定は、デフォルトで有効になっています。

遅延しきい値では、遅延時間が超えてはならない割合を指定します。たとえば、1時間の例で遅延しきい値が150%と定義されている場合、遅延時間が1.5時間を超えるとイベントが生成されます。



== 管理対象外の関係の遅延しきい値領域

遅延領域では、次の条件について、管理対象外の関係の遅延しきい値を設定できます。

* * 警告 *
+
遅延時間が遅延警告しきい値に達した、あるいは超えたとみなす割合を指定します。

+
** デフォルト値は150%です
** 生成されるイベント：SnapMirror関係の遅延警告またはSnapVault 関係の遅延警告
** イベントの重大度：警告


* * エラー *
+
遅延時間が遅延エラーしきい値に達した、あるいは超えたとみなす割合を指定します。

+
** デフォルト値：250%
** 生成されるイベント：SnapMirror関係の遅延エラーまたはSnapVault 関係の遅延エラー
** イベントの重大度：エラー






== コマンドボタン

* * 工場出荷時のデフォルトに戻します *
+
構成設定を工場出荷時のデフォルト値に戻すことができます。

* * 保存 *
+
選択したオプションの設定を保存します。


