---
permalink: online-help/reference-schedule-report-dialog-box-um-6-2.html 
sidebar: sidebar 
keywords:  
summary: Schedule Report dialog boxでは、レポートが指定した頻度で定期的に生成されるようにスケジュールを設定できます。レポートは、Schedule Report dialog boxで指定した1人以上のユーザにEメールで送信されます。 
---
= Schedule Report dialog box
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Schedule Report dialog boxでは、レポートが指定した頻度で定期的に生成されるようにスケジュールを設定できます。レポートは、Schedule Report dialog boxで指定した1人以上のユーザにEメールで送信されます。



== プロパティ

ユーザのEメールアドレス、レポートの形式、レポートの生成頻度などのプロパティを指定してレポートをスケジュールできます。

* *既存のスケジュールを使用*
+
** * スケジュール名 *
+
既存のスケジュールの名前がすべて表示されます。ここからレポートの既存のスケジュールを選択できます。



* *新しいスケジュールの作成*
+
** * スケジュール名 *
+
新しいスケジュールを作成する際にスケジュール名を入力できます。

** *受信者の電子メールアドレス*
+
レポートの送信先であるユーザのEメールアドレスを指定します。カンマで区切って1つ以上のエントリを指定できます。これは必須フィールドです。

** *レポート形式*
+
レポートをスケジュールする形式を指定します。デフォルトでは、_PDF_Optionが選択されています。

** * 周波数 *
+
レポートをスケジュールする頻度を指定します。デフォルトでは、_Hourly_optionが選択されます。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * スケジュール *
+
保存または更新されたテンプレートでレポートをスケジュールし、Schedule Report dialog boxを閉じます。

* * キャンセル *
+
レポートスケジュールテンプレートの保存を指示するメッセージが表示されている状態で、Schedule Report dialog boxを閉じます。


