---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: アグリゲートのConfiguration / Health Thresholdsページでは、監視対象のアグリゲートのグローバル健全性しきい値を設定できます。オプションをグローバルに設定すると、すべてのオブジェクトのデフォルト値が変更されます。ただし、オブジェクトレベルでデフォルト値が変更されている場合、グローバルな値は変更されません。 
---
= アグリゲートの構成/健常性しきい値のページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートのConfiguration / Health Thresholdsページでは、監視対象のアグリゲートのグローバル健全性しきい値を設定できます。オプションをグローバルに設定すると、すべてのオブジェクトのデフォルト値が変更されます。ただし、オブジェクトレベルでデフォルト値が変更されている場合、グローバルな値は変更されません。

OnCommand 管理者またはストレージ管理者のロールが必要です。

しきい値を超えるとイベントが生成されます。そのようなイベントに対して対処方法を実行できます。

ノードのルートアグリゲートにはしきい値の値は適用されません。

容量、アグリゲートの増加率、およびアグリゲートのSnapshotコピーについてアグリゲートの健全性しきい値を設定できます。



== 容量領域

容量領域では、アグリゲートの容量について、次のしきい値条件を設定できます。アグリゲートに配置されているボリュームで自動拡張が有効になっている場合は、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて、アグリゲートの容量のしきい値を超えているかどうかが判定されることに注意してください。

* *スペースがほぼフル*
+
アグリゲートがほぼフルであるとみなす割合を示します。

+
** デフォルト値：80%
+
管理サーバでイベントが生成されるように、このしきい値の値は「アグリゲートがフル」のしきい値の値よりも小さくする必要があります。

** 生成されるイベント：アグリゲートがほぼフルです
** イベントの重大度：警告


* *スペースがフル*
+
アグリゲートがフルであるとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：アグリゲートがフルです
** イベントの重大度：エラー


* *ほぼオーバーコミット*
+
アグリゲートがほぼオーバーコミットされているとみなす割合を示します。

+
** デフォルト値：95%
+
管理サーバでイベントが生成されるように、このしきい値の値は「アグリゲートがオーバーコミット」のしきい値の値よりも小さくする必要があります。

** 生成されるイベント：アグリゲートがほぼオーバーコミット
** イベントの重大度：警告


* *オーバーコミット*
+
アグリゲートがオーバーコミットされているとみなす割合を示します。

+
** デフォルト値は100%です
** 生成されるイベント：アグリゲートがオーバーコミット
** イベントの重大度：エラー


* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの残り日数を示します。

+
** デフォルト値：7
** 生成されるイベント：アグリゲートのフルまでの日数
** イベントの重大度：エラー






== 成長領域

Growth領域では、アグリゲートの増加率について、次のしきい値条件を設定できます。

* *増加率*
+
アグリゲートの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「Aggregate Growth Rate Abnormal」イベントが生成されます。

+
** デフォルト値：1%
** 生成されるイベント：アグリゲートの増加率-異常
** イベントの重大度：警告


* *増加率係数*
+
アグリゲートの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「アグリゲートの増加率が異常」イベントが生成されます。

+
アグリゲートが増加率の変化による影響を受けやすい場合は、増加率係数の値を小さくします。増加率係数の範囲は1~5です。

+
** デフォルト値：2


+
[NOTE]
====
グローバルしきい値レベルでアグリゲートの増加率係数を変更した場合、グローバルしきい値レベルのボリュームの増加率係数にも変更が適用されます。

====




== Snapshotコピー領域

Snapshotコピー領域では、Snapshotリザーブについて、次のしきい値条件を設定できます。

* * Snapshotリザーブがフル*
+
アグリゲートのSnapshotコピー用にリザーブされたスペースがすべて使用されているとみなす割合を示します。

+
** デフォルト値：90%
** 生成されるイベント：アグリゲートのSnapshotリザーブがフルです
** イベントの重大度：警告






== コマンドボタン

* * 工場出荷時のデフォルトに戻します *
+
構成設定を工場出荷時のデフォルト値に戻すことができます。

* * 保存 *
+
選択したオプションの設定を保存します。


