---
permalink: online-help/reference-volume-data-protection-configuration-report.html 
sidebar: sidebar 
keywords:  
summary: ボリュームデータ保護設定レポートを使用すると、ノードまたはクラスタで使用される、保護されていないボリュームとStorage Virtual Machine（SVM）を表示できます。この情報を使用すると、システムのデータ保護のリスクを把握したり、システムで保護されているボリュームと保護されていないボリュームの詳細を確認したりできます。 
---
= Volume Data Protection Configurationレポートの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume Data Protection Configurationレポートを使用すると、ノードまたはクラスタで使用される、保護されていないボリュームとStorage Virtual Machine（SVM）を表示できます。この情報を使用すると、システムのデータ保護のリスクを把握したり、システムで保護されているボリュームと保護されていないボリュームの詳細を確認したりできます。

Volume Data Protection Configurationレポートは、次の2つの形式で表示されます。

* 保護されている/いないボリュームの円グラフ
* 保護されていないボリュームデータの表形式ビュー




== 保護されている/いないボリュームの円グラフ

システムで保護されているボリュームと保護されていないボリュームの相対割合が表示されます。



== 保護されていないボリュームデータの表形式ビュー

* * クラスタ *
+
クラスタ名が表示されます。

* * Storage Virtual Machine *
+
ボリュームが含まれているStorage Virtual Machine（SVM）の名前が表示されます。

* * 音量 *
+
ボリューム名が表示されます。

* *合計データ容量（GB）*
+
合計データ容量（GB、使用容量と使用可能容量を足したもの）が表示されます。

* *使用済みデータ容量（GB）*
+
使用済みデータ容量（GB）が表示されます。

* *使用済みデータ%*
+
使用済みデータ容量の割合が表示されます。

* *使用可能なデータ容量（GB）*
+
使用可能なデータ容量（GB）が表示されます。

* *使用可能なデータ%*
+
使用可能なデータ容量の割合が表示されます。

* * Snapshotリザーブの使用容量（GB）*
+
Snapshotコピーで使用されるSnapshotリザーブのスペースの量（GB）が表示されます。

* * Snapshotリザーブの使用率
+
Snapshotコピーで使用されるSnapshotリザーブのスペースの量の割合が表示されます。

* * Snapshotリザーブの使用可能容量（GB）*
+
Snapshotコピーに使用可能なスペースの量（GB）が表示されます。

* * Snapshotリザーブの使用可能率
+
Snapshotコピーに使用できるスペースの量の割合が表示されます。

* * Snapshotリザーブの合計容量（GB）*
+
アグリゲートのSnapshotリザーブの合計容量（GB）が表示されます。

* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの推定日数が表示されます。

* *スペースがフルのしきい値%*
+
アグリゲートがフルであるとみなす割合が表示されます。

* *スペースがほぼフルのしきい値%*
+
アグリゲートがほぼフルであるとみなす割合が表示されます。

* *日次増加率
+
ボリュームでの24時間ごとの増加率が表示されます。

* * inodeの総数*
+
ボリューム内のinodeの総数が表示されます。

* * inode使用率*
+
ボリュームで使用されているinodeスペースを示します。

* *クォータコミット容量*
+
ボリュームでリザーブされているスペースが表示されます。

* *クォータオーバーコミット容量（GB）*
+
「ボリュームクォータがオーバーコミット」イベントが生成される基準となるスペースの使用量（GB）が表示されます。

* * Snapshotの自動削除*
+
Snapshotコピーの自動削除が有効か無効かが表示されます。

* * 重複排除 *
+
ボリュームで重複排除処理が有効か無効かが表示されます。

* *重複排除によるスペース削減（GB）*
+
重複排除を使用して削減されたボリュームのスペース（GB）が表示されます。

* * 圧縮 *
+
ボリュームで圧縮が有効か無効かが表示されます。

* *圧縮によるスペース削減（GB）*
+
圧縮を使用して削減されたボリュームのスペース（GB）が表示されます。

* * シンプロビジョニング *
+
選択したボリュームにスペースギャランティが設定されているかどうかが表示されます。有効な値は「はい」と「いいえ」です

* * 自動拡張 *
+
スペースが不足したときにFlexVol ボリュームのサイズが自動で拡張されるかどうかが表示されます。

* * スペース保証 *
+
FlexVol ボリュームがアグリゲートから空きブロックを削除するタイミングを制御する設定が表示されます。

* * 状態 *
+
エクスポートされるボリュームの状態が表示されます。

* * SnapLock タイプ *
+
ボリュームがSnapLock ボリュームかSnapLockなしのボリュームかを示します。

* *有効期限*

