---
permalink: online-help/reference-create-snapmirror-policy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: SnapMirror ポリシーの作成ダイアログボックスでは、 SnapMirror 転送の優先度を設定するポリシーを作成できます。ポリシーを使用することで、ソースからデスティネーションへの転送効率を最大化できます。 
---
= SnapMirror ポリシーの作成ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror ポリシーの作成ダイアログボックスでは、 SnapMirror 転送の優先度を設定するポリシーを作成できます。ポリシーを使用することで、ソースからデスティネーションへの転送効率を最大化できます。

* * デスティネーションクラスタ *
+
Configure Protection （保護の設定）ダイアログボックスの SnapMirror （ SnapMirror ）タブで選択したクラスタの名前。

* * デスティネーション SVM *
+
保護の設定ダイアログボックスの SnapMirror タブで選択した SVM の名前。

* * ポリシー名 *
+
新しいポリシーに指定する名前。ポリシー名には、 A~Z 、 a~z 、 0~9 、ピリオド（ . ）、ハイフン（ - ）、 とアンダースコア (_)

* * 転送優先順位 *
+
非同期操作の転送を実行する優先順位。標準または低を選択できます。転送の優先順位として「標準」を指定したポリシーを使用する関係の転送は、「低」を指定したポリシーを使用する関係の転送の前に実行されます。

* * コメント *
+
オプションのフィールド。ポリシーに関するコメントを追加できます。

* * 転送再開 *
+
中止処理によって転送が中断された場合や、ネットワーク停止などの何らかの障害によって転送が中断された場合に実行する再開処理を指定します。次のいずれかを選択できます。

+
** 常に
+
転送を再開する前に新しいSnapshotコピーを作成し、既存のSnapshotコピーが存在する場合は、チェックポイントから転送を再開して、そのあとに新しく作成したSnapshotコピーに基づく差分転送を実行するように指定します。

** なし
+
中断された転送を再開しないように指定します。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して、 Configure Protection ダイアログボックスを閉じます。

* * 適用 *
+
選択項目を適用して保護プロセスを開始します。


