---
permalink: online-help/reference-event-retention-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 指定した期間を経過したイベント（情報、解決済み、または廃止状態のイベント）を指定した頻度で自動的に削除するようにイベントを設定することができます。これらのイベントは手動で削除することもできます。 
---
= [イベント保持設定]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
指定した時間を経過したイベント（情報、解決済み、または廃止状態のイベント）を指定した頻度で自動的に削除するようにイベントを設定することができます。これらのイベントは手動で削除することもできます。

OnCommand 管理者またはストレージ管理者のロールが必要です。



== イベント設定

次のオプションを設定できます。

* *以下より古い情報、解決済み、廃止イベントを削除します
+
「Information」、「Resolved」、または「Obsolete」とマークされたイベントの保持期間を指定できます。これらのイベントのうち、この期間を経過したイベントが管理サーバから削除されます。

+
デフォルト値は180日です。イベントの保持期間を180日以上に設定するとパフォーマンスに影響するため推奨されません。イベントの保持期間の下限は7日ですが、上限はありません。

* *スケジュールの削除*
+
「Information」、「Resolved」、または「Obsolete」とマークされたイベントを削除する頻度を指定できます。これらのイベントのうち、保持期間を経過したすべてのイベントがこの頻度で管理サーバから自動的に削除されます。指定できる値は、「Daily」、「Weekly」、または「Monthly」です。

+
デフォルト値は「Daily」です。

* *今すぐ削除*
+
指定した保持期間を超えている情報、解決済み、および廃止状態のすべてのイベントを手動で削除できます。





== コマンドボタン

各コマンドボタンを使用して、セットアップオプションを保存またはキャンセルできます。

* *保存して閉じる*
+
選択したオプションの設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
最新の変更内容をキャンセルしてダイアログボックスを閉じます。


