---
permalink: online-help/reference-aggregate-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: アグリゲートの容量と使用状況レポートでは、クラスタ内のアグリゲートの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。 
---
= アグリゲートの容量と使用状況レポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートの容量と使用状況レポートでは、クラスタ内のアグリゲートの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。



== アグリゲートの容量と使用状況レポートの表形式ビュー

* * クラスタ *
+
クラスタ名が表示されます。

* * HAペア*
+
2つのノードを構成して得られるHAペア値が表示されます。

* * 集計 *
+
アグリゲート名が表示されます。

* *合計データ容量（GB）*
+
合計データ容量（使用容量と使用可能容量を足したもの）が表示されます。

* *使用済みデータ容量（GB）*
+
使用済みデータ容量が表示されます。

* *使用済みデータ%*
+
使用済みデータ容量の割合が表示されます。

* *使用可能なデータ容量（GB）*
+
使用可能なデータ容量が表示されます。

* *使用可能なデータ%*
+
使用可能なデータ容量の割合が表示されます。

* *日次増加率
+
ボリュームでの24時間ごとの増加率が表示されます。

* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの推定日数が表示されます。

* *スペースがフルのしきい値*
+
アグリゲートがフルであるとみなす割合が表示されます。

* *スペースがほぼフルのしきい値*
+
アグリゲートがほぼフルであるとみなす割合が表示されます。

* *増加率しきい値*
+
アグリゲートの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「アグリゲートの増加率-異常」イベントが生成されます。

* *増加率係数しきい値*
+
ボリュームの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

* *フルまでの日数しきい値*
+
アグリゲートの容量がフルに達するまでの残り日数を示します。

* * Snapshotリザーブの合計容量（GB）*
+
アグリゲートのSnapshotリザーブの合計容量が表示されます。

* * Snapshotリザーブの使用容量（GB）*
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量が表示されます。

* * Snapshotリザーブの使用率
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量の割合が表示されます。

* * Snapshotリザーブの使用可能容量（GB）*
+
Snapshotコピーに使用できるスペースの量が表示されます。

* * Snapshotリザーブの使用可能率
+
Snapshotコピーに使用できるスペースの量の割合が表示されます。

* *「Snapshotコピーリザーブがフル」しきい値*
+
アグリゲートのSnapshotコピー用にリザーブされたスペースがすべて使用されているとみなす割合を示します。

* *オーバーコミット容量%*
+
アグリゲートオーバーコミットの割合が表示されます。

* *オーバーコミットのしきい値%*
+
アグリゲートがオーバーコミットされたとみなす割合が表示されます。

* *「ほぼオーバーコミット」しきい値
+
アグリゲートがほぼオーバーコミットされているとみなす割合が表示されます。

* * タイプ *
+
アグリゲートのタイプが表示されます。

+
** HDD
** ハイブリッド
+
HDDとSSDの組み合わせですが、Flash Poolは有効になっていません。

** ハイブリッド（Flash Pool）
+
HDDとSSDの組み合わせで、Flash Poolが有効になっています。

** SSD の場合
** SSD （ FabricPool ）
+
SSDとクラウド階層の組み合わせです

** VMDisk（SDS）
+
仮想マシン内の仮想ディスク

** VMディスク（FabricPool ）
+
仮想ディスクとクラウド階層の組み合わせです

** 標準ディスクおよびSSDディスクのLUN（FlexArray ）の場合、監視対象のストレージシステムが8.3より前のバージョンのONTAP を実行しているときは、この列が空白になります。


* * RAID タイプ *
+
RAID構成タイプが表示されます。

* *アグリゲートの状態*
+
アグリゲートの現在の状態が表示されます。

* * SnapLock タイプ *
+
アグリゲートがSnapLock アグリゲートか非SnapLockアグリゲートかを示します。

* *クラウド階層の使用済みスペース（GB）*
+
クラウド階層で現在使用されているデータ容量が表示されます。

* * クラウド階層 *
+
ONTAP での作成時に指定されたクラウド階層の名前が表示されます。


