---
permalink: online-help/reference-create-rule-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Create Ruleダイアログボックスを使用すると、データポリシーの新しいルールを作成できます。たとえば、特定のファイルタイプのコンテンツの配置を指定する場合、ルールの作成ダイアログボックスを使用してデータポリシーのルールを作成できます。 
---
= Create Ruleダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create Ruleダイアログボックスを使用すると、データポリシーの新しいルールを作成できます。たとえば、特定のファイルタイプのコンテンツの配置を指定する場合、ルールの作成ダイアログボックスを使用してデータポリシーのルールを作成できます。



== ルール名

新しいルールの名前を指定します。



== [Templates]領域

ルールテンプレートのリストが表示されます。リストから適切なルールテンプレートを選択して、データポリシーのルールを作成できます。



== 一致条件

選択したルールテンプレートに関連する条件のリストが表示されます。条件のリストは、選択したルールテンプレートに基づいて変更されます。たとえば'指定された所有者名を持つすべてのファイルを適切なストレージクラスに配置するを選択した場合'*List of Owner that…*がMatching Criteriaに表示されます

* * 追加 * 。
+
選択したルールテンプレートに基づいて新しいルールのプロパティを追加できます。たとえば'ルール・テンプレートを選択した場合'指定した所有者名を持つすべてのファイルを適切なストレージ・クラスに配置するには'*Add*ボタンを使用して所有者の名前を追加します

* * 削除 *
+
選択したルールのプロパティを削除できます。





== コンテンツ配置

ルールに適したストレージクラスをリストから選択できます。



== コマンドボタン

* * 作成 * 。
+
データポリシーの新しいルールを作成して、Create Ruleダイアログボックスを閉じます。

* * キャンセル *
+
ルールに対する最近の変更をキャンセルして、[ルールの作成]ダイアログボックスを閉じます。


