---
permalink: online-help/reference-add-user-dialog-box-um.html 
sidebar: sidebar 
keywords:  
summary: ローカルユーザまたはデータベースユーザを作成するか、リモートユーザまたはリモートグループを追加し、それらのユーザがストレージオブジェクトやデータをUnified Managerで管理できるようにロールを割り当てることができます。 
---
= Add Userダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルユーザまたはデータベースユーザを作成するか、リモートユーザまたはリモートグループを追加し、それらのユーザがストレージオブジェクトやデータをUnified Managerで管理できるようにロールを割り当てることができます。

ユーザを追加するには、次のフィールドを設定します。

* * タイプ *
+
作成するユーザのタイプを指定できます。

* * 名前 *
+
ユーザがUnified Managerへのログインに使用するユーザ名を指定できます。

* * パスワード *
+
指定したユーザ名のパスワードを指定できます。このフィールドは、ローカルユーザまたはデータベースユーザを追加する場合にのみ表示されます。

* *パスワードの確認*
+
パスワードフィールドに入力した内容が正確になるように、パスワードを再入力できます。このフィールドは、ローカルユーザまたはデータベースユーザを追加する場合にのみ表示されます。

* * 電子メール *
+
ユーザのEメールアドレスを指定できます。ユーザ名ごとに一意のEメールアドレスを指定する必要があります。このフィールドは、リモートユーザまたはローカルユーザを追加する場合にのみ表示されます。

* * 役割 *
+
ユーザにロールを割り当て、ユーザが実行できるアクティビティの範囲を定義できます。ロールは、OnCommand 管理者、ストレージ管理者、オペレータ、統合スキーマ、レポートスキーマのいずれかになります。





== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * 追加 * 。
+
ユーザを追加して、[Add User]ダイアログボックスを閉じます。

* * キャンセル *
+
変更内容をキャンセルして、[Add User]ダイアログボックスを閉じます。


