---
permalink: online-help/reference-create-schedule-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: スケジュールの作成ダイアログボックスでは、 SnapMirror 関係と SnapVault 関係の転送の基本または詳細な保護スケジュールを作成できます。データ更新を頻繁に行うために、データ転送の頻度を増やすための新しいスケジュールを作成できます。データがあまり変更されない場合は、少ない頻度のスケジュールを作成することもできます。 
---
= スケジュールの作成ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スケジュールの作成ダイアログボックスでは、 SnapMirror 関係と SnapVault 関係の転送の基本または詳細な保護スケジュールを作成できます。データ更新を頻繁に行うために、データ転送の頻度を増やすための新しいスケジュールを作成できます。データがあまり変更されない場合は、少ない頻度のスケジュールを作成することもできます。

SnapMirror 同期関係にスケジュールを設定することはできません。

* * デスティネーションクラスタ *
+
保護の設定ダイアログボックスの SnapVault タブまたは SnapMirror タブで選択したクラスタの名前。

* * スケジュール名 *
+
スケジュールに指定する名前。スケジュール名には、 A~Z 、 a~z 、 0~9 、および次の特殊文字を使用できます。！@ # $ % ｛ キャレット ｝ & * （） _ - 。スケジュール名には、以下の文字は使用できません。

* * Basic または Advanced *
+
使用するスケジュールモード。

+
基本モードには、次の要素が含まれます。

+
** 繰り返します
+
スケジュールされた転送が発生する頻度。時間単位、日単位、週単位のいずれかを選択できます。

** 日
+
「 Weekly 」の繰り返しを選択した場合に転送が発生する曜日。

** 時間
+
「毎日」または「毎週」を選択した場合に転送が発生する時刻。



+
詳細モードには、次の要素が含まれます。

+
** 月
+
カンマで区切った数値のリスト。月を表します。有効な値は 0~11 です。 0 は 1 月を表し、以降も同様です。この要素はオプションです。このフィールドを空にすると、毎月転送が発生します。

** 日
+
カンマで区切った数値のリスト。日にちを表します。有効な値は 1~31 です。この要素はオプションです。このフィールドを空にすると、指定した月に毎日転送が発生します。

** 平日
+
カンマで区切った数値のリスト。曜日を表します。有効な値は 0~6 です。 0 は日曜を表し、以降も同様です。この要素はオプションです。このフィールドを空にすると、指定した週に毎日転送が発生します。曜日を指定し、日にちを指定していない場合は、毎日ではなく指定した曜日にのみ転送が実行されます。

** 時間
+
カンマで区切った数値のリスト。 1 日のうちの時間数を表します。有効な値は 0~23 です。 0 は午前 0 時を表します。この要素はオプションです。

** 分
+
カンマで区切った数値のリスト。 1 時間のうちの分数を表します。有効な値は 0~59 です。この要素は必須です。




