---
permalink: online-help/reference-nfs-shares-health-fields.html 
sidebar: sidebar 
keywords:  
summary: NFS Exportsレポートを使用すると、ストレージシステム内のボリュームに対するNFSエクスポートポリシーとその関連ルールに関する情報を監査できます。 
---
= NFS Exportsレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS Exportsレポートを使用すると、ストレージシステム内のボリュームに対するNFSエクスポートポリシーとその関連ルールに関する情報を監査できます。



== NFSエクスポートレポートの表形式ビュー

* * クラスタ *
+
クラスタの名前が表示されます。

* * Storage Virtual Machine *
+
NFSエクスポートポリシーが適用されるSVMの名前が表示されます。

* * 音量 *
+
NFSエクスポートポリシーが適用されるボリュームの名前が表示されます。

* * qtree *
+
NFSエクスポートポリシーが適用されるボリューム上のqtreeの名前が表示されます。

* * ボリュームの状態 *
+
ボリュームの現在の状態が表示されます。「オフライン」、「オンライン」、「制限」のいずれかです。

+
** オフラインです
+
ボリュームへの読み取り / 書き込みアクセスが許可されていません。

** オンライン
+
ボリュームへの読み取り / 書き込みアクセスが許可されています。

** 制限
+
パリティの再構築などの一部の処理は許可されますが、データアクセスは許可されません。



* * ジャンクションパス *
+
ボリュームがマウントされているパスが表示されます。

* * ジャンクションパスがアクティブ *
+
マウントされたボリュームにアクセスするパスがアクティブであるか非アクティブであるかが表示されます。

* *エクスポートポリシー*
+
エクスポートされているボリュームのアクセス権限を定義するルールが表示されます。

* *ルールインデックス*
+
エクスポートポリシーに関連付けられているルールが表示されます。これには、認証プロトコルやアクセス権限などが含まれます。

* *アクセスプロトコル*
+
エクスポートポリシールールに対して有効になっているプロトコルが表示されます。

* *クライアント一致*
+
ボリューム上のデータにアクセスする権限があるクライアントが表示されます。

* *読み取り専用アクセス*
+
ボリューム上のデータの読み取りに使用される認証プロトコルが表示されます。

* *読み取り/書き込みアクセス*
+
ボリューム上のデータの読み取りまたは書き込みに使用される認証プロトコルが表示されます。

* * セキュリティ形式 *
+
エクスポートされているボリュームのアクセス権限が表示されます。セキュリティ形式には、 UNIX 、 Unified 、 NTFS 、 Mixed があります。

+
** UNIX （ NFS クライアント）
+
ボリューム内のファイルおよびディレクトリに UNIX 権限が設定されています。

** 統合：
+
ボリューム内のファイルおよびディレクトリに unified セキュリティ形式が設定されています。

** NTFS （ CIFS クライアント）
+
ボリューム内のファイルおよびディレクトリに Windows NTFS 権限が設定されています。

** 混在
+
ボリューム内のファイルおよびディレクトリに UNIX 権限または Windows NTFS 権限のどちらかを設定できます。



* * Unixの許可*
+
エクスポートされるボリュームに設定されている 8 進数の文字列形式の UNIX 権限ビットが表示されます。UNIX 形式の権限ビットと同様の形式です。


