---
permalink: online-help/reference-node-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Performance/NodeInformationページを使用して、ノードの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= Performance/NodeInformationヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance/NodeInformationページを使用して、ノードの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== ノード属性

* * IP アドレス *
+
ノード管理LIFのIPv4アドレスまたはIPv6アドレス。

* * FQDN *
+
ノード管理LIFの完全修飾ドメイン名（FQDN）。

* * OSバージョン*
+
ノードにインストールされているONTAP ソフトウェアのバージョン。

* *モデル/ファミリー*
+
ノードのプラットフォームモデル番号。

* *容量（空き/合計）*
+
ノードで使用可能な合計ストレージ容量（GB）、および現在使用可能なストレージ容量。

* * クラスタ *
+
このノードが属するクラスタの名前。名前をクリックすると、Performance/ClusterExplorerヘエシにクラスタの詳細を表示できます。

* * HAパートナー*
+
HAパートナーノードの名前（該当する場合）。名前をクリックすると、Performance/NodeExplorerヘエシにパートナーノードの詳細を表示できます。

* * アグリゲート *
+
このノード上のアグリゲートの数。数をクリックすると、ハフオオマンス/アクリケエトインヘントリヘエシにアグリゲートを表示できます。

+
[NOTE]
====
インベントリページにルートアグリゲートが含まれていないため、ここに記載する数値がパフォーマンス/アグリゲートインベントリページの数値と一致しない可能性があります。

====
* * ポート * ：
+
このノード上のポートの数。番号をクリックすると、[Performance/Ports Inventory]ページにポートが表示されます。

+
[NOTE]
====
インベントリページにはノード管理ポートがないため、ここに記載されている番号はパフォーマンス/ポートインベントリページの番号と一致しない場合があります。

====
* *連絡先/場所*
+
該当する場合は、このノードに関する連絡先の管理者の名前とノードの場所。

* *コア数/速度*
+
使用可能な場合は、コントローラのCPUコアの数とCPUコアの速度。

* *ラム*
+
使用可能な場合は、コントローラで使用可能な合計メモリ。





== フラッシュデバイス

[NOTE]
====
Flash Cache のデータは、ノードに Flash Cache モジュールがインストールされている場合にのみ表示されます。

====
* *スロット番号*
+
Flash Cacheモジュールが取り付けられているスロットの番号。

* * ステータス *
+
モジュールの動作ステータス。有効な値：

+
** オンライン
** offline_failed
** offline_threshold


* *モデル/ファミリー*
+
モジュールのモデル番号。

* *ファームウェアリビジョン*
+
モジュールにインストールされているファームウェアのバージョン。

* * 容量 *
+
設置されているFlash Cacheモジュールのサイズ。


