---
permalink: online-help/reference-edit-qtree-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: qtreeの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「qtreeがフル」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。 
---
= qtreeシキイチノヘンシユウタイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
qtreeの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「qtreeがフル」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。

OnCommand 管理者またはストレージ管理者のロールが必要です。

qtreeしきい値の編集ダイアログボックスでは、選択したqtreeに適用されるqtreeレベルのしきい値を設定できます。qtreeレベルでしきい値を設定すると、それらの値がグループレベルのしきい値やグローバルレベルのしきい値よりも優先されます。

qtreeレベルでは、容量についてのしきい値を設定できます。qtreeしきい値タイプのグループ操作が設定されている場合、qtreeレベルで設定されていない項目にはグループ操作のしきい値の値が使用されます。qtreeしきい値タイプのグループ操作が設定されていない場合は、qtreeしきい値の編集ダイアログボックスの設定されていない領域にグローバルしきい値の値が使用されます。



== 容量領域

容量領域では、qtreeの容量について、次のしきい値条件を設定できます。

* *スペースがほぼフル*
+
qtreeがほぼフルであるとみなす割合を示します。指定したしきい値の値に対応するqtreeのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *スペースがフル*
+
qtreeがフルであるとみなす割合を示します。指定したしきい値の値に対応するqtreeのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。





== コマンドボタン

選択したqtreeについて、各コマンドボタンを使用して次のタスクを実行できます。

* *デフォルトに戻します*
+
しきい値を次のいずれかの値に戻すことができます。

+
** グループの値：qtreeがグループに属しており、そのグループでqtreeしきい値タイプのアクションが設定されている場合。
** グローバルな値：qtreeがいずれのグループにも属していないか、属しているグループでqtreeしきい値タイプのアクションが設定されていない場合。


* * 保存 *
+
すべてのしきい値設定を保存します。

* *保存して閉じる*
+
すべてのしきい値の設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
しきい値の設定に対する変更内容を破棄してダイアログボックスを閉じます。


