---
permalink: online-help/reference-dashboards-performance-page.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerのパフォーマンスダッシュボードを使用して、監視しているすべてのクラスタのパフォーマンスステータスの概要を表示できます。Unified Managerが監視しているクラスタと通信できない場合、ダッシュボード/パフォーマンスページにバナーメッセージも表示されます。 
---
= Dashboards/Performanceページに移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerのパフォーマンスダッシュボードを使用して、監視しているすべてのクラスタのパフォーマンスステータスの概要を表示できます。Unified Managerが監視しているクラスタと通信できない場合、ダッシュボード/パフォーマンスページにバナーメッセージも表示されます。



== 概要

クラスタは、次の基準に基づいて重大度の順に並べられます。

. クラスタに到達できない場合。
. クラスタにアクティブな重大パフォーマンスイベントが1つ以上ある場合（赤のオブジェクトアイコン）。
. クラスタにアクティブな警告パフォーマンスイベントが1つ以上ある場合（黄色のオブジェクトアイコン）。
. クラスタにアクティブなパフォーマンスイベントがない場合（緑のオブジェクトアイコン）：IOPSが高い順にソートされます。


重大イベントは、ユーザ定義のパフォーマンスしきい値ポリシーの重大しきい値を超えたときに生成されます。警告イベントは、ユーザ定義のパフォーマンスしきい値ポリシーの警告しきい値を超えた場合、またはシステム定義のしきい値ポリシーまたは動的しきい値を超えた場合に送信されます。

[NOTE]
====
ソート順序は、イベントがあるオブジェクトの数ではなく、アクティブなイベント（新規または確認済みのイベント）の総数で決まります。たとえば、クラスタAに重大なボリュームレイテンシイベントが7つある場合、また、クラスタBには、ボリュームレイテンシイベントが2つ、重大なノードIOPSイベントが2つ（合計4つ）あります。クラスタBには赤のオブジェクトアイコンが2つありますが、クラスタAはリストの上位に表示されます。

====
各クラスタについて表示される共通の監視対象イベントタイプは次のとおりです。

* Storage Virtual Machine（SVM）、ボリューム、およびLUNのレイテンシイベント
* ノードおよびSVMのIOPSイベント
* ノードおよびSVMのMBpsイベント
* ノードおよびアグリゲートの使用済みパフォーマンス容量イベント
* ノードおよびアグリゲートの利用率イベント


Unified Managerでは、アグリゲートのMBpsイベントやボリュームのIOPSイベントなど、他のストレージオブジェクトとカウンタに対するパフォーマンスイベントも受信できます。これらのタイプのイベントがある場合、クラスタ名の横のアイコンで警告イベント（黄色）か重大イベント（赤）かが示されます。これらのイベントタイプはカウンタパネルの既存のカテゴリには当てはまらないため、カウンタパネルの5つのアイコンに黄色または赤のアイコンがなくても、このアイコンはイベントが存在していることを示す場合があります。

オブジェクトアイコンをクリックすると、そのオブジェクトのパフォーマンスインベントリページが表示され、このクラスタ内でそのタイプのすべてのオブジェクトを確認できます。たとえば、ボリュームアイコンをクリックすると、パフォーマンス/ボリュームインベントリページが表示され、選択したクラスタ内のすべてのボリュームのリストが、最大パフォーマンスに対してソートされて表示されます。



== パフォーマンスカウンタ

すべてのクラスタについて、5つのパフォーマンスカウンタがそれぞれ独立したパネルに表示されます。この情報は、5分間隔で収集された収集期間後に自動的に更新されます。

|===
| カウンタ | 説明 


 a| 
レイテンシ
 a| 
クライアントアプリケーションの要求に対するクラスタの応答速度が処理あたりのミリ秒（ミリ秒/処理）で表示されます。アイコンの領域には、レイテンシの値がしきい値の設定を超えてアクティブなイベントが発生したSVM、ボリューム、またはLUNがないかが示されます。



 a| 
IOPS
 a| 
ストレージシステムの処理速度が1秒あたりの入出力処理数（IOPS）で表示されます。

* アイコンの領域に、IOPSの数がしきい値の設定を超えてアクティブなイベントが発生したノードまたはSVMがないかが示されます。
* 下部の領域に、最後の5分間の収集期間におけるクラスタの合計IOPSが表示されます。




 a| 
MBps
 a| 
クラスタとの間のデータの転送量が1秒あたりのメガバイト数（MBps）で表示されます。

* アイコンの領域に、MBpsの値がしきい値の設定を超えてアクティブなイベントが発生したノードまたはSVMがないかが示されます。
* 下部の領域に、最後の5分間の収集期間におけるクラスタの合計スループットが表示されます。




 a| 
使用済みパフォーマンス容量
 a| 
使用可能なパフォーマンス容量を過剰に消費しているノードまたはアグリゲートがないかが表示されます。

* アイコンの領域に、使用済みパフォーマンス容量の値がしきい値の設定を超えてアクティブなイベントが発生したノードまたはアグリゲートがないかが示されます。
* 下部の領域に、最もビジーなノードと最もビジーなアグリゲートの使用済みパフォーマンス容量の最大値が表示されます。


[NOTE]
====
パフォーマンス容量のデータは、クラスタ内のノードにONTAP 9.0以降のソフトウェアがインストールされている場合にのみ表示されます。

====


 a| 
利用率
 a| 
リソースの利用率が高いノードまたはアグリゲートがないかが表示されます。

* アイコンの領域に、利用率の値がしきい値の設定を超えてアクティブなイベントが発生したノードまたはアグリゲートがないかが示されます。
* 下部の領域に、最もビジーなノードと最もビジーなアグリゲートの利用率の最大値が表示されます。


|===
省略記号(...)ヘッダー領域に、パフォーマンスデータが現在収集されていることを示します。

パフォーマンスイベントが発生しているクラスタの「クラスタの詳細を表示」をクリックすると、パフォーマンスクラスタランディングページが表示され、クラスタやその他のストレージオブジェクトに関する詳細なパフォーマンス情報を確認できます。



== クラスタステータスメッセージ

Unified Managerで管理しているクラスタが使用できない状態になると、パフォーマンスカウンタの上にステータスメッセージバナーが表示されます。クラスタに到達できない場合、ステータスメッセージバナーの右側に「* Details *」ボタンが表示されます。ステータスメッセージの* Details *ボタンをクリックすると、Cluster Data Sourcesページに移動できます。このページには、問題 に関するすべての情報が表示されます。[Cluster Data Sources]ページで、クラスタが使用不能になった問題 のトラブルシューティングに必要なデータを確認できます。
