---
permalink: online-help/reference-advanced-destination-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: デスティネーションボリュームのスペースギャランティの設定を有効にするには、詳細設定ダイアログボックスを使用します。詳細設定は、ソースではスペースギャランティが無効になっている状況において、デスティネーションでスペースギャランティを有効にする場合に使用します。SnapMirror 関係の重複排除、圧縮、および自動拡張の設定はソースボリュームから継承され、変更することはできません。 
---
= Advanced Destination Settings ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デスティネーションボリュームのスペースギャランティの設定を有効にするには、詳細設定ダイアログボックスを使用します。詳細設定は、ソースではスペースギャランティが無効になっている状況において、デスティネーションでスペースギャランティを有効にする場合に使用します。SnapMirror 関係の重複排除、圧縮、および自動拡張の設定はソースボリュームから継承され、変更することはできません。



== スペースギャランティ

データ転送が常に成功するようにデスティネーションボリュームに十分なスペースを割り当てます。スペースギャランティの設定は次のいずれかです。

* ファイル。
+
ファイルのスペースギャランティはONTAP 8.3では使用できません。

* ボリューム
* なし


たとえば、 200GB のボリュームに合計 50GB のファイルが格納されており、それらのファイルに実際に格納されているデータは 10GB だけであるとします。ボリュームギャランティでは、ソースの内容に関係なく、デスティネーションボリュームに 200GB が割り当てられます。ファイルギャランティでは、デスティネーションのソースファイル用に十分なスペースが確保されるように 50GB が割り当てられます。このシナリオで「なし」を選択すると、ソースのファイルデータで使用される実際のスペース用に、デスティネーションには 10GB しか割り当てられません。

スペースギャランティはデフォルトでボリュームに設定されています。
