---
permalink: online-help/reference-edit-storage-class-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: '[Edit Storage Class Thresholds]ダイアログボックスを使用すると、組織の要件に基づいて、Infinite Volumeを備えた各SVMのさまざまなストレージクラスのデフォルトのしきい値を変更できます。デフォルトのしきい値は、ストレージクラスに対するアクティビティのレベルがその値に達するとイベントがトリガーされるレベルを示します。' 
---
= EditStorageClassThresholdsタイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージクラスしきい値の編集ダイアログボックスを使用して、Infinite Volumeを備えた各SVMのさまざまなストレージクラスのデフォルトのしきい値を組織の要件に基づいて変更できます。デフォルトのしきい値は、ストレージクラスに対するアクティビティのレベルがその値に達するとイベントがトリガーされるレベルを示します。

OnCommand 管理者またはストレージ管理者のロールが必要です。



== 容量

容量領域では、選択したストレージクラスの容量しきい値条件を設定できます。

* *スペースがほぼフル*
+
Infinite Volumeを備えたSVMのストレージクラスがほぼフルであるとみなす割合を示します。ストレージクラスの対応するスペース（GB、MB、またはTB）も表示されます。たとえば、ストレージクラスのサイズが10GBで「Space Nearly Full」しきい値が80%の場合、「（8 GB of 10 GB）」のように表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *スペースがフル*
+
Infinite Volumeを備えたSVMのストレージクラスがフルであるとみなす割合を示します。ストレージクラスの対応するスペース（GB、MB、またはTB）も表示されます。たとえば、ストレージクラスのサイズが10GBで「Space Full」しきい値が90%の場合、「（9 GB of 10 GB）」のように表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* * Snapshotの使用制限*
+
ストレージクラス内でSnapshotコピー用にリザーブされるスペースの上限を示します。





== コマンドボタン

選択したボリュームについて、各コマンドボタンを使用してタスクを実行できます。

* *グローバル・デフォルトに戻します*
+
しきい値の設定をグローバルレベルで設定されている現在の値に戻すことができます。

* * 保存 *
+
すべてのしきい値設定を保存します。

* *保存して閉じる*
+
すべてのしきい値の設定を保存して、[Edit Storage Class Thresholds]ダイアログボックスを閉じます。

* * キャンセル *
+
しきい値の設定に対する変更内容をキャンセルして、Edit Storage Class Thresholdsダイアログボックスを閉じます。


