---
permalink: online-help/reference-performance-statistics-displayed-in-the-data-breakdown-charts.html 
sidebar: sidebar 
keywords:  
summary: グラフを使用してボリュームのパフォーマンスの傾向を表示できます。また、読み取りと書き込みの統計、ネットワークプロトコルのアクティビティ、QoSポリシーグループの調整によるレイテンシへの影響、キャッシュストレージへの読み取りと書き込みの比率、ワークロードで使用されているクラスタの合計CPU時間、および特定のクラスタコンポーネントも表示できます。 
---
= データ内訳グラフに表示されるパフォーマンス統計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グラフを使用してボリュームのパフォーマンスの傾向を表示できます。また、読み取りと書き込みの統計、ネットワークプロトコルのアクティビティ、QoSポリシーグループの調整によるレイテンシへの影響、キャッシュストレージへの読み取りと書き込みの比率、ワークロードで使用されているクラスタの合計CPU時間、および特定のクラスタコンポーネントも表示できます。

これらのビューには、現在の日付から最大30日間の統計が表示されます。履歴データチャートで2日以上の期間を選択すると、画面の解像度によっては、その期間におけるレイテンシとIOPSの最大値が表示されます。

[NOTE]
====
[すべて選択*]チェックボックスを使用して、リストされているすべてのグラフオプションを選択または選択解除できます。

====
* * 遅延 *
+
以下のチャートに、選択したワークロードのレイテンシ、つまり応答時間の情報が詳細に表示されます。

+
** *クラスタ・コンポーネント*
+
選択したボリュームで使用されている各クラスタコンポーネントで費やされた時間がグラフに表示されます。

+
このチャートは、合計レイテンシのうちの各コンポーネントによるレイテンシへの影響を判断するのに役立ちます。各コンポーネントの横にあるチェックボックスを使用して、グラフの表示と非表示を切り替えることができます。

+
QoSポリシーグループについては、ユーザ定義のポリシーグループのデータのみが表示されます。デフォルトポリシーグループなどのシステム定義のポリシーグループについてはゼロと表示されます。

** *読み取り/書き込みレイテンシ*
+
選択した期間における、選択したボリュームワークロードからの成功した読み取り要求と書き込み要求のレイテンシがグラフに表示されます。

+
書き込み要求はオレンジ、読み取り要求は青の線で表されます。クラスタのすべてのワークロードではなく、選択したボリュームワークロードのレイテンシに関連した要求についてのデータです。

+
[NOTE]
====
読み取りと書き込みの合計が、レイテンシグラフに表示される合計レイテンシと異なる場合があります。これは想定された動作で、Unified Managerによるワークロードの読み取りと書き込みの統計を収集および分析する方法によるものです。

====
** *ポリシーグループの影響*
+
選択したボリュームワークロードのレイテンシのうち、QoSポリシーグループのスループット制限による影響の割合がグラフに表示されます。

+
ワークロードが調整されている場合、ある時点において調整がレイテンシに影響した割合を示します。それぞれ次の調整量に該当します。

+
*** 0%=調整なし
*** 0%超=調整あり
*** 20%超=重大スロットルクラスタの処理量が増えると、ポリシーグループの上限を引き上げることで調整を減らすことができます。あるいは、負荷の低いアグリゲートにワークロードを移動します。




+
[NOTE]
====
このグラフは、スループット制限が設定されているユーザ定義のQoSポリシーグループ内のワークロードについてのみ表示されます。デフォルトポリシーグループやQoS制限のないポリシーグループなど、システム定義のポリシーグループにワークロードが含まれている場合は表示されません。QoSポリシーグループについては、カーソルをポリシーグループの名前に当てると、そのスループット制限と最終変更時刻が表示されます。関連するクラスタがUnified Managerに追加される前にポリシーグループが変更された場合、最終変更時刻は、Unified Managerが最初にクラスタを検出した日付と時刻です。

====
* * IOPS *
+
以下のチャートに、選択したワークロードのIOPSデータの詳細が表示されます。

+
** *読み取り/書き込み/その他*
+
選択した期間における、1秒あたりの読み取り/書き込みIOPS、およびその他のIOPSがグラフに表示されます。

+
その他のIOPSは、クライアントによって開始された読み取りまたは書き込み以外のプロトコルアクティビティです。たとえばNFS環境の場合、getattr、setattr、fsstatなどのメタデータ処理がこれに該当します。CIFS環境の場合は、属性のルックアップ、ディレクトリの表示、またはウィルススキャンなどです。書き込みIOPSはオレンジ、読み取りIOPSは青の線で表されます。クラスタのすべての処理ではなく、選択したボリュームワークロードのすべての処理のIOPSについてのデータです。



* * Mbps *
+
以下のチャートに、選択したワークロードのスループットデータの詳細が表示されます。

+
** *キャッシュヒット率*
+
選択した期間における、クライアントアプリケーションからの読み取り要求のうち、キャッシュで処理された割合がグラフに表示されます。

+
キャッシュにはFlash CacheカードまたはFlash Poolアグリゲートのソリッドステートドライブ（SSD）を使用できます。青はキャッシュヒットでキャッシュから読み取られた要求、オレンジはキャッシュミスでアグリゲート内のディスクから読み取られた要求を表します。クラスタのすべてのワークロードではなく、選択したボリュームワークロードに関連した要求についてのデータです。

+
ボリュームキャッシュの使用量に関する詳細情報は、Unified Managerの健全性ページとOnCommand のSystem Managerで確認できます。



* *コンポーネント*
+
以下のチャートに、選択したワークロードで使用されているクラスタコンポーネント別のデータの詳細が表示されます。

+
** *クラスタCPU時間*
+
選択したワークロードが使用しているクラスタ内のすべてのノードのCPU使用率のグラフが表示されます（ミリ秒）。

+
このグラフには、ネットワーク処理とデータ処理に使用されたCPU時間の合計が表示されます。選択したワークロードに関連していて、データ処理に同じノードを使用しているシステム定義のワークロードのCPU時間も含まれます。このチャートを使用して、ワークロードがクラスタ上のCPUリソースを大量に消費しているかどうかを判断できます。また、このチャートをレイテンシチャートの読み取り/書き込みレイテンシチャートまたはIOPSチャートの下の読み取り/書き込み/その他チャートと組み合わせて使用すると、ワークロードのアクティビティの変化がクラスタのCPU利用率に与える影響を判断できます。

** *ディスク利用率*
+
選択した期間における、ストレージアグリゲート内のデータディスクの利用率がグラフに表示されます。

+
この利用率には、選択したボリュームワークロードからのディスクの読み取り/書き込み要求だけが含まれ、キャッシュからの読み取りは含まれません。ディスク上のすべてのワークロードではなく、選択したボリュームワークロードに関連した利用率についてのデータです。監視対象のボリュームがボリューム移動の対象である場合、このチャートの利用率の値は移動先のアグリゲートの値になります。




