---
permalink: online-help/reference-create-or-clone-performance-threshold-policy-page-opm.html 
sidebar: sidebar 
keywords:  
summary: Create Threshold PolicyページまたはClone Threshold Policyページを使用すると、新しいパフォーマンスしきい値ポリシーを作成できます。 
---
= パフォーマンスしきい値ポリシーの作成ページまたはクローンポリシーのページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create Threshold PolicyページまたはClone Threshold Policyページを使用すると、新しいパフォーマンスしきい値ポリシーを作成できます。

このページのフィールドに値を入力し、* Save *をクリックしてパフォーマンスしきい値ポリシーを追加できます。

* *オブジェクトタイプ*
+
しきい値ポリシーを作成するストレージオブジェクトのタイプを選択します。

* * ポリシー名 *
+
しきい値ポリシーの名前を入力します。この名前は、Unified Managerの他のページに表示されます。ポリシーの簡単な概要 を入力してください。

* * 概要 *
+
（オプション）しきい値ポリシーの詳細な概要 を入力します。

* *しきい値*
+
プライマリおよびオプションでセカンダリのしきい値カウンタの条件を定義します。セカンダリカウンタを使用する場合、しきい値を超えたとみなされるには、両方のカウンタが制限値を超える必要があります。

+
** *カウンタを選択*
+
パフォーマンスしきい値を設定するカウンタを選択します。

** * 警告 *
+
警告とみなすカウンタの制限値を入力します。

** * 重要 *
+
重大とみなすカウンタの制限値を入力します。



+
しきい値の有効な値は、数値については 0.001~10 、 000 、 000 、割合については 0.001~100 、使用済みパフォーマンス容量の割合については 0.001~200 です。

* * 期間 *
+
カウンタの値が警告または重大の制限値よりも大きい時間を分単位で選択してください。Unified Managerは新しいパフォーマンスカウンタの値を5分ごとに収集するため、メニューには5の倍数がオプションとして表示されます。


