---
permalink: online-help/reference-event-details-page.html 
sidebar: sidebar 
keywords:  
summary: イベントの詳細ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。問題を解決するための考えられる対処方法について、追加情報を確認することもできます。 
---
= イベントの詳細ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントの詳細ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。問題を解決するための考えられる対処方法について、追加情報を確認することもできます。

* * イベント名 *
+
イベントの名前と最終確認時刻。

+
パフォーマンスイベント以外のイベントの場合は、状態が「新規」または「確認済み」のときは最終確認時刻が不明なため、この情報は表示されません。

* * イベント概要 *
+
イベントの簡単な概要。

+
イベント概要には、イベントがトリガーされた理由が含まれる場合があります。

* * 競合状態のコンポーネント *
+
動的なパフォーマンスイベントについて、クラスタの論理コンポーネントと物理コンポーネントを表すアイコンが表示されます。コンポーネントが競合状態にある場合は、アイコンが赤い丸で強調表示されます。

+
次のコンポーネントが表示される場合があります。

+
** * ネットワーク *
+
クラスタ上でのiSCSIプロトコルまたはファイバチャネル（FC）プロトコルによるI/O要求の待機時間を表します。待機時間とは、クラスタがI/O要求に応答できるようになるまでに、iSCSI Ready to Transfer（R2T）またはFCP Transfer Ready（XFER_RDY）トランザクションが待つ時間です。ネットワークコンポーネントが競合状態にある場合、ブロックプロトコルレイヤでの長い待機時間は、1つ以上のワークロードのレイテンシに影響していることを意味します。

** * ネットワーク処理 *
+
プロトコルレイヤとクラスタ間の I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。ネットワーク処理を実行するノードがイベント検出後に変更された可能性があります。ネットワーク処理コンポーネントが競合状態にある場合、ネットワーク処理ノードでの高利用率は、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

** * QoS ポリシー *
+
ワークロードがメンバーになっているストレージQoSポリシーグループを表します。ポリシーグループコンポーネントが競合状態にある場合、ポリシーグループ内のすべてのワークロードに、スループットの制限によってスロットルが適用され、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

** * クラスタインターコネクト *
+
クラスタノードを物理的に接続するケーブルとアダプタを表します。クラスタインターコネクトコンポーネントが競合状態にある場合は、クラスタインターコネクトでの I/O 要求の長い待機時間がワークロードのレイテンシに影響していることを意味します。

** * データ処理 *
+
クラスタとストレージアグリゲート間でワークロードを含む I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。データ処理を実行するノードがイベント検出後に変更された可能性があります。データ処理コンポーネントが競合状態にある場合、データ処理ノードでの高利用率は、 1 つ以上のワークロードのレイテンシに影響していることを意味します。

** * MetroCluster リソース *
+
NVRAM とインタースイッチリンク（ ISL ）を含む MetroCluster リソースを表します。 MetroCluster 構成のクラスタ間でデータをミラーリングするのに使用します。MetroCluster コンポーネントが競合状態問題にある場合は、ローカルクラスタのワークロードによる大量の書き込みスループットまたはリンクの不具合が、ローカルクラスタの 1 つ以上のワークロードのレイテンシに影響していることを意味します。クラスタが MetroCluster 構成に含まれていない場合は、このアイコンは表示されません。

** * アグリゲートまたは SSD アグリゲートの処理 *
+
ワークロードが実行されているストレージアグリゲートを表します。アグリゲートコンポーネントが競合状態にある場合、アグリゲートの高利用率が 1 つ以上のワークロードのレイテンシに影響していることを意味します。アグリゲートには、HDDのみで構成されるものと、HDDとSSDが混在するもの（Flash Poolアグリゲート）があります。「 SD アグリゲート」は、すべての SSD （オールフラッシュアグリゲート）、または SSD とクラウド階層（ FabricPool アグリゲート）が混在しています。

** * クラウドレイテンシ *
+
クラスタとユーザデータ格納先のクラウド階層の間の I/O 処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。クラウドレイテンシコンポーネントが競合状態にある場合、クラウド階層でホストされたボリュームからの大量の読み取りが 1 つ以上のワークロードのレイテンシに影響していることを意味します。

** * 同期 SnapMirror *
+
SnapMirror 同期関係でのプライマリボリュームからセカンダリボリュームへのユーザデータのレプリケーションに関係する、クラスタ内のソフトウェアコンポーネントを表します。同期 SnapMirror コンポーネントが競合状態にある場合、 SnapMirror Synchronous 処理のアクティビティが 1 つ以上のワークロードのレイテンシに影響していることを意味します。





「イベント情報」、「システム診断」、および「推奨処置」の各セクションについては、他のトピックで説明しています。



== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * メモアイコン *
+
イベントに関するメモを追加または更新したり、他のユーザが残したすべてのメモを確認したりできます。



* アクションメニュー *

* * 自分に割り当て *
+
イベントを自分に割り当てます。

* * 他のユーザーに割り当て *
+
[ 所有者の割り当て ] ダイアログボックスが開きますこのダイアログボックスで ' イベントを他のユーザーに割り当てたり ' 再割り当てしたりできます

+
イベントをユーザに割り当てると、イベントリストの選択したイベントの該当するフィールドに、ユーザの名前とイベントが割り当てられた時刻が追加されます。

+
所有権のフィールドを空白にすると、イベントの割り当てを解除できます。

* * 確認 *
+
選択したイベントに確認応答し、アラート通知が繰り返し送信されないようにします。

+
イベントを確認すると、ユーザ名とそのイベントを確認した時刻が、選択したイベントのイベントリスト（確認済みのイベントのリスト）に追加されます。確認したイベントについては、自分で対処する必要があります。

* * 解決済みとしてマーク *
+
イベントの状態を解決済みに変更できます。

+
イベントを解決すると、イベントリスト（で解決）に選択したイベントのユーザ名と解決時刻が追加されます。イベントに対処したら、そのイベントを解決済みとしてマークする必要があります。

* * アラートの追加 *
+
アラートの追加ダイアログボックスが表示され、選択したイベントにアラートを追加できます。


