---
permalink: online-help/reference-add-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: アラートを作成すると、特定のイベントが生成されたときに通知されるため、問題にすばやく対処し、環境への影響を最小限に抑えることができます。アラートは、単一のリソース、一連のリソース、および特定の重大度タイプのイベントについて作成することができます。アラートの通知方式と通知頻度を指定することもできます。 
---
= Add Alert ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートを作成すると、特定のイベントが生成されたときに通知されるため、問題にすばやく対処し、環境への影響を最小限に抑えることができます。アラートは、単一のリソース、一連のリソース、および特定の重大度タイプのイベントについて作成することができます。アラートの通知方式と通知頻度を指定することもできます。

OnCommand 管理者またはストレージ管理者のロールが必要です。



== 名前

この領域では、アラートの名前と概要を指定できます。

* * アラート名 *
+
アラート名を指定できます。

* * Alert 概要 *
+
アラートの概要を指定できます。





== リソース

この領域では、アラートをトリガーする対象のリソースを個別に選択したり、動的ルールに基づいてリソースをグループ化したりできます。a_dynamic rule_ は、指定したテキスト文字列に基づいてフィルタリングされるリソースのセットです。ドロップダウンリストからリソースタイプを選択してリソースを検索するか、正確なリソース名を指定して特定のリソースを表示できます。

いずれかのストレージオブジェクトの詳細ページからアラートを作成する場合は、ストレージオブジェクトが自動的にアラートに含まれます。

* * インクルード *
+
アラートをトリガーする対象に含めるリソースを指定できます。テキスト文字列を指定すると、その文字列に一致するリソースをグループ化し、そのグループをアラートの対象として選択できます。たとえば、「abc」という文字列が名前に含まれるすべてのボリュームをグループ化できます。

* * 除外 *
+
アラートをトリガーする対象から除外するリソースを指定できます。たとえば、「 xyz 」という文字列が名前に含まれるすべてのボリュームを除外することができます。

+
[除外]タブは'特定のリソースタイプのすべてのリソースを選択した場合にのみ表示されますたとえば' <<All Volumes>> または <<All Volumes whose name contains '_xyz_'>>。

+
あるリソースが対象に含めるルールと除外するルールの両方に該当する場合は、除外するルールが優先され、イベントについてはアラートが生成されません。





== イベント

この領域では、アラートを作成するイベントを選択できます。アラートは特定の重大度のイベントに対して作成するか、一連のイベントについて作成することができます。

複数のイベントを選択するには、 Ctrl キーを押しながら選択します。

* * イベントの重大度 *
+
重大度タイプに基づいてイベントを選択できます。タイプは、「重大」、「エラー」、「警告」のいずれかになります。

* * イベント名に * が含まれています
+
名前に指定した文字を含むイベントを選択できます。





== アクション

この領域では、アラートがトリガーされたときに通知するユーザを指定できます。通知方式と通知頻度を指定することもできます。

* * これらのユーザーに警告 *
+
通知を受信するユーザの E メールアドレスまたはユーザ名を指定できます。

+
ユーザに対して指定されている E メールアドレスを変更し、アラートを再び開いて編集しようとすると、変更した E メールアドレスが以前に選択したユーザにマッピングされていないため、名前フィールドは空白になります。また、[Management/Users]ページで選択したユーザのEメールアドレスを変更しても、変更後のEメールアドレスは更新されません。

* * 通知頻度 *
+
イベントが確認または解決されるか、廃止状態に設定されるまでの間、管理サーバが通知を送信する頻度を指定できます。

+
次のいずれかの通知方式を選択できます。

+
** 1 回だけ通知します
** 指定した頻度で通知します
** 指定した期間内の指定した頻度で通知します


* * 問題 SNMP トラップ *
+
このチェックボックスをオンにすると、グローバルに設定された SNMP ホストに SNMP トラップを送信するかどうかを指定できます。

* * スクリプトの実行 *
+
アラートにカスタムスクリプトを追加できます。このスクリプトはアラートが生成されたときに実行されます。





== コマンドボタン

* * 保存 *
+
アラートを作成してダイアログボックスを閉じます。

* * キャンセル *
+
変更内容を破棄してダイアログボックスを閉じます。


