---
permalink: online-help/reference-volume-transfer-status-historical-report.html 
sidebar: sidebar 
keywords:  
summary: ボリューム転送ステータス（履歴）レポートを使用して、一定期間のボリューム転送の傾向を分析できます。特定の期間のボリューム転送ステータスを表示するようにレポートを設定できます。また、このレポートにはボリューム転送が成功したか失敗したかが表示されます。 
---
= ボリューム転送ステータス（履歴）レポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム転送ステータス（履歴）レポートを使用して、一定期間のボリューム転送の傾向を分析できます。特定の期間のボリューム転送ステータスを表示するようにレポートを設定できます。また、このレポートにはボリューム転送が成功したか失敗したかが表示されます。

ボリューム転送ステータス（履歴）レポートは、次の2つの形式で表示されます。

* ボリューム転送ステータスの折れ線グラフ
* ボリューム転送ステータス（履歴）レポートの表形式ビュー




== ボリューム転送ステータスの折れ線グラフ

この折れ線グラフでは、日付に対する転送数を示すことにより、ボリューム転送の詳細が表示されます。また、特定のボリューム転送が成功したか失敗したかを表示することもできます。



== ボリューム転送ステータスの表形式ビュー

* *ソースクラスタ名*
+
ソースクラスタ名が表示されます。

* * ソース SVM *
+
Storage Virtual Machine （ SVM ）名が表示されます。

* *ソースボリューム名*
+
ソースボリューム名が表示されます。

* *デスティネーションクラスタ名*
+
デスティネーションクラスタ名が表示されます。

* * デスティネーション SVM *
+
デスティネーション SVM 名が表示されます。

* *デスティネーションボリューム名*
+
デスティネーションボリューム名が表示されます。

* * 操作結果 *
+
ボリューム転送が成功したかどうかが表示されます。

* *開始時間*
+
ボリューム転送の開始時間が表示されます。

* *終了時間*
+
ボリューム転送の終了時間が表示されます。

* *転送時間（hh：mm：ss）*
+
ボリューム転送が完了するまでの所要時間（時間）が表示されます。

* *転送サイズ（MB）*
+
転送されたボリュームのサイズ（ MB ）が表示されます。

* * 操作タイプ *
+
ボリューム転送のタイプが表示されます。


