---
permalink: online-help/reference-svm-health-fields.html 
sidebar: sidebar 
keywords:  
summary: SVMインベントリレポートを使用すると、SVMボリューム構成の制限と全体的な健全性を分析して、将来的なストレージの可用性に対するリスクを把握できます。 
---
= SVMインベントリレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVMインベントリレポートを使用すると、SVMボリューム構成の制限と全体的な健全性を分析して、将来的なストレージの可用性に対するリスクを把握できます。



== SVMインベントリレポートの表形式ビュー

* * クラスタ *
+
SVMを含むクラスタの名前が表示されます。

* * Storage Virtual Machine *
+
SVM の名前が表示されます。

* * 状態 *
+
SVMの現在の管理状態が表示されます。「Running」、「Stopped」、「Starting」、「Stopping」、「Not mapped」、初期化、または削除中です。

* *ボリューム数*
+
SVMに含まれているボリュームの数が表示されます。

* *許容される最大ボリューム数*
+
SVMで設定できる、許容される最大ボリューム数が表示されます。

* *ルートボリューム*
+
SVMのルートボリュームの名前が表示されます。

* *許可されたプロトコル*
+
SVMで設定できるプロトコルのタイプが表示されます。

* * DNSドメイン*
+
DNSドメイン名が表示されます。

* * NISドメイン*
+
Network Information Service（NIS；ネットワーク情報サービス）ドメイン名が表示されます。Network Information Service（NIS；ネットワーク情報サービス）サーバが無効になっているか設定されていない場合、この列は空白になります。

* * LDAP有効*
+
LDAPプロトコルが有効になっているかどうかが表示されます。

* *ネームサービススイッチ*
+
ホストから収集された情報のタイプが表示されます。指定可能な値は、file、ldap、またはnisです。


