---
permalink: online-help/reference-configure-protection-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 保護の設定ダイアログボックスを使用して、クラスタ上のすべての読み取り、書き込み、データ保護のボリュームに対して SnapMirror 関係と SnapVault 関係を作成し、ソースボリュームまたはプライマリボリューム上のデータをレプリケートできます。 
---
= Configure Protection （保護の設定）ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護の設定ダイアログボックスを使用して、クラスタ上のすべての読み取り、書き込み、データ保護のボリュームに対して SnapMirror 関係と SnapVault 関係を作成し、ソースボリュームまたはプライマリボリューム上のデータをレプリケートできます。



== [ ソース ] タブ

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内のソースが強調表示されます。

* * ソース情報 *
+
選択したソースボリュームに関する詳細が表示されます。次の情報が含まれます。

+
** ソースクラスタ名
** ソース SVM 名
** ボリュームの累積合計サイズ
+
選択したすべてのソースボリュームの合計サイズが表示されます。

** ボリュームの累積使用サイズ
+
選択したすべてのソースボリュームの累積使用サイズが表示されます。

** ソースボリューム
+
次の情報を表形式で表示します。

+
*** ソースボリューム
+
選択したソースボリュームの名前が表示されます。

*** を入力します
+
ボリュームタイプが表示されます。

*** SnapLock タイプ
+
ボリュームの SnapLock タイプが表示されます。「 Compliance 」、「 Enterprise 」、「 Non-SnapLock 」のいずれかです。

*** Snapshot コピー
+
ベースライン転送に使用される Snapshot コピーが表示されます。ソースボリュームが読み取り / 書き込みの場合、 Snapshot コピーの列の default の値は、新しい Snapshot コピーがデフォルトで作成され、ベースライン転送に使用されることを示します。ソースボリュームがデータ保護ボリュームの場合、 Snapshot コピー列の default の値は新しい Snapshot コピーが作成されないことを示し、既存のすべての Snapshot コピーがデスティネーションに転送されます。Snapshot コピーの値をクリックすると Snapshot コピーのリストが表示され、ベースライン転送に使用する既存の Snapshot コピーを選択できます。ソースタイプがデータ保護の場合、別のデフォルトの Snapshot コピーを選択することはできません。









== SnapMirror タブ

保護関係のデスティネーションクラスタ、 Storage Virtual Machine （ SVM ）、アグリゲート、および SnapMirror 関係を作成する際のデスティネーションの命名規則を指定できます。SnapMirror ポリシーとスケジュールを指定することもできます。

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内の SnapMirror のデスティネーションリソースが強調表示されます。

* * 目的地情報 *
+
保護関係のデスティネーションリソースを選択できます。

+
** 詳細リンク
+
SnapMirror 関係の作成時に、詳細なデスティネーション設定ダイアログボックスを表示します。

** クラスタ
+
保護デスティネーションホストとして使用できるクラスタが表示されます。このフィールドは必須です。

** Storage Virtual Machine （ SVM ）
+
選択したクラスタで使用可能な SVM が表示されます。このリストに SVM を表示するには、クラスタを選択する必要があります。このフィールドは必須です。

** アグリゲート
+
選択した SVM で使用できるアグリゲートが表示されます。このリストにアグリゲートを表示するには、クラスタを選択する必要があります。このフィールドは必須です。アグリゲートリストには、次の情報が表示されます。

+
*** ランク
+
複数のアグリゲートがデスティネーションの要件をすべて満たす場合、この順位は、次の条件に従ってアグリゲートを表示する優先順位を示します。

+
.... ソースボリュームのノードとは異なるノードに配置されているアグリゲートが優先され、障害ドメインの分離が可能になります。
.... ボリューム数が少ないノード上のアグリゲートが優先され、クラスタ内のノード間での負荷分散が可能になります。
.... 他のアグリゲートよりも空きスペースの多いアグリゲートが優先され、容量の分散が可能になります。順位 1 は、この 3 つの条件に従っているアグリゲートが最も優先されることを示します。


*** アグリゲート名
+
アグリゲートの名前

*** 使用可能容量
*** アグリゲートでデータに使用できるスペースの量
*** リソースプール
+
アグリゲートが属するリソースプールの名前



** 命名規則
+
デスティネーションボリュームに適用されるデフォルトの命名規則を指定します。用意されている命名規則をそのまま使用することも、カスタムの命名規則を作成することもできます。命名規則には、 %C 、 %M 、 %V 、 %N という属性を指定できます。 %C はクラスタ名、 %M は SVM 名、 %V はソースボリューム、 %N はトポロジのデスティネーションノード名です。

+
入力が無効な場合、命名規則のフィールドが赤で強調表示されます。「名前のプレビュー」リンクをクリックすると、入力した命名規則のプレビューが表示され、テキストフィールドに命名規則を入力するとプレビューテキストが動的に更新されます。関係の作成時に、001 ~ 999のサフィックスがデスティネーション名に付加されます。これがで置き換えられます `nnn` これはプレビューテキストに表示され、001が最初に割り当てられ、002が2番目に割り当てられたというようになります。



* * 関係設定 *
+
保護関係で使用する最大転送速度、 SnapMirror ポリシー、およびスケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。ただし、ONTAP 8.2を実行し、かつプライマリクラスタとセカンダリクラスタが同じである場合は、この設定が無視されます。

** SnapMirror ポリシー
+
関係の ONTAP SnapMirror ポリシーを指定します。デフォルトは DPDefault です。

** ポリシーの作成
+
SnapMirror ポリシーの作成ダイアログボックスが開きます。このダイアログボックスで、新しい SnapMirror ポリシーを作成して使用できます。

** SnapMirror スケジュール
+
関係の ONTAP SnapMirror ポリシーを指定します。スケジュールは、「 None 」、「 5min 」、「 8hour 」、「 daily 」、「 hourly 」、 毎週、デフォルトは「 None 」で、関係にスケジュールが関連付けられません。スケジュールが設定されていない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールを作成します
+
スケジュールの作成ダイアログボックスが開きます。このダイアログボックスで、新しい SnapMirror スケジュールを作成できます。







== SnapVault タブ

保護関係のセカンダリクラスタ、 SVM 、アグリゲート、および SnapVault 関係を作成する際のセカンダリボリュームの命名規則を指定できます。SnapVault ポリシーとスケジュールを指定することもできます。

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内の SnapVault セカンダリリソースが強調表示されます。

* * 二次情報 *
+
保護関係のセカンダリリソースを選択できます。

+
** 詳細リンク
+
Advanced Secondary Settings ダイアログボックスを起動します。

** クラスタ
+
セカンダリ保護ホストとして使用できるクラスタが表示されます。このフィールドは必須です。

** Storage Virtual Machine （ SVM ）
+
選択したクラスタで使用可能な SVM が表示されます。このリストに SVM を表示するには、クラスタを選択する必要があります。このフィールドは必須です。

** アグリゲート
+
選択した SVM で使用できるアグリゲートが表示されます。このリストにアグリゲートを表示するには、クラスタを選択する必要があります。このフィールドは必須です。アグリゲートリストには、次の情報が表示されます。

+
*** ランク
+
複数のアグリゲートがデスティネーションの要件をすべて満たす場合、この順位は、次の条件に従ってアグリゲートを表示する優先順位を示します。

+
.... プライマリボリュームのノードとは異なるノードに配置されているアグリゲートが優先され、障害ドメインの分離が可能になります。
.... ボリューム数が少ないノード上のアグリゲートが優先され、クラスタ内のノード間での負荷分散が可能になります。
.... 他のアグリゲートよりも空きスペースの多いアグリゲートが優先され、容量の分散が可能になります。順位 1 は、この 3 つの条件に従っているアグリゲートが最も優先されることを示します。


*** アグリゲート名
+
アグリゲートの名前

*** 使用可能容量
*** アグリゲートでデータに使用できるスペースの量
*** リソースプール
+
アグリゲートが属するリソースプールの名前



** 命名規則
+
セカンダリボリュームに適用されるデフォルトの命名規則を指定します。用意されている命名規則をそのまま使用することも、カスタムの命名規則を作成することもできます。命名規則には、 %C 、 %M 、 %V 、 %N という属性を指定できます。 %C はクラスタ名、 %M は SVM 名、 %V はソースボリューム、 %N はトポロジのセカンダリノード名です。

+
入力が無効な場合、命名規則のフィールドが赤で強調表示されます。「名前のプレビュー」リンクをクリックすると、入力した命名規則のプレビューが表示され、テキストフィールドに命名規則を入力するとプレビューテキストが動的に更新されます。無効な値を入力すると、プレビュー領域に無効な情報が赤の疑問符として表示されます。関係の作成時に、001 ~ 999のサフィックスがセカンダリ名に付加されます。これは、の代わりに使用されます `nnn` これはプレビューテキストに表示され、001が最初に割り当てられ、002が2番目に割り当てられたというようになります。



* * 関係設定 *
+
保護関係で使用する最大転送速度、 SnapVault ポリシー、および SnapVault スケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。ただし、ONTAP 8.2を実行し、かつプライマリクラスタとセカンダリクラスタが同じである場合は、この設定が無視されます。

** SnapVault ポリシー
+
関係の ONTAP SnapVault ポリシーを指定します。デフォルトは XDPDefault です。

** ポリシーの作成
+
Create SnapVault Policy ダイアログボックスが開きます。このダイアログボックスで、新しい SnapVault ポリシーを作成して使用できます。

** SnapVault スケジュール
+
関係の ONTAP SnapVault スケジュールを指定します。スケジュールは、「 None 」、「 5min 」、「 8hour 」、「 daily 」、「 hourly 」、 毎週、デフォルトは「 None 」で、関係にスケジュールが関連付けられません。スケジュールが設定されていない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールを作成します
+
スケジュールの作成ダイアログボックスが開きます。このダイアログボックスで、 SnapVault スケジュールを作成できます。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して、 Configure Protection ダイアログボックスを閉じます。

* * 適用 *
+
選択項目を適用して保護プロセスを開始します。


