---
permalink: online-help/reference-initialize-update-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Initialize/Update ダイアログボックスでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行する場合は、関係を更新できます。 
---
= Initialize/Update ダイアログボックスが表示されます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Initialize/Update ダイアログボックスでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行する場合は、関係を更新できます。



== [ 転送オプション ] タブ

[ 転送オプション ] タブでは、転送の初期設定の優先順位を変更したり、転送中に使用される帯域幅を変更したりできます。

* * 転送優先順位 *
+
転送を実行する優先順位。標準または低を選択できます。関係のポリシーで転送の優先順位「 Normal 」が指定されている場合、その関係は転送の優先順位「 Low 」が指定された関係より先に実行デフォルトでは「 Normal 」が選択されます。

* * 最大転送速度 *
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。ただし、ONTAP 8.2を実行し、かつプライマリクラスタとセカンダリクラスタが同じである場合は、この設定が無視されます。最大転送速度が異なる複数の関係を選択する場合は、次の最大転送速度設定のいずれかを指定できます。

+
** 個々の関係のセットアップまたは編集で指定した値を使用します
+
このオプションを選択すると、各関係の作成時または編集時に指定された最大転送速度が初期化処理と更新処理で使用されます。このフィールドは、転送速度が異なる複数の関係を初期化または更新する場合にのみ使用できます。

** 無制限
+
関係間の転送に帯域幅の制限がないことを示します。このフィールドは、転送速度が異なる複数の関係を初期化または更新する場合にのみ使用できます。

** 帯域幅をに制限します
+
選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力してから、 KBps （ 1 秒あたりのキロバイト数）、 MBps （ 1 秒あたりのメガバイト数）、 GBps （ 1 秒あたりのギガバイト数）、 TBps （ 1 秒あたりのテラバイト数）のいずれかの単位を選択できます。最大転送速度は 1KBps~4TBps の範囲で指定する必要があります。







== ソース Snapshot コピータブ

ソース Snapshot コピータブには、ベースライン転送に使用されるソース Snapshot コピーに関する次の情報が表示されます。

* * ソースボリューム *
+
対応するソースボリュームの名前が表示されます。

* * デスティネーションボリューム *
+
選択したデスティネーションボリュームの名前が表示されます。

* * ソースタイプ *
+
ボリュームタイプが表示されます。「読み取り / 書き込み」または「データ保護」のいずれかです。

* * Snapshot コピー *
+
データ転送に使用される Snapshot コピーが表示されます。Snapshot コピーの値をクリックすると、 Select Source Snapshot Copy ダイアログボックスが表示されます。このダイアログボックスでは、使用している保護関係のタイプおよび実行している処理に応じて、転送する特定の Snapshot コピーを選択できます。データ保護タイプのソースについては、別の Snapshot コピーを指定できません。





== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して [Initialize] / [Update] ダイアログボックスを閉じます。

* * 送信 *
+
選択内容を保存し、初期化ジョブまたは更新ジョブを開始します。


