---
permalink: online-help/reference-types-of-performance-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 標準のパフォーマンスグラフには、選択したストレージオブジェクトのカウンタの値が表示されます。内訳カウンタグラフには、合計値が読み取り、書き込み、およびその他のカテゴリに分けて表示されます。さらに、一部の内訳カウンタグラフでは、ズームビューでグラフを表示すると詳細が表示されます。 
---
= パフォーマンスカウンタグラフのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
標準のパフォーマンスグラフには、選択したストレージオブジェクトのカウンタの値が表示されます。内訳カウンタグラフには、合計値が読み取り、書き込み、およびその他のカテゴリに分けて表示されます。さらに、一部の内訳カウンタグラフでは、ズームビューでグラフを表示すると詳細が表示されます。

次の表は、使用可能なパフォーマンスカウンタグラフを示しています。

|===
| 使用可能なチャート | Chart 概要（チャート） 


 a| 
イベント
 a| 
ルートオブジェクトの統計グラフに関連し、重大、エラー、警告、情報のイベントが表示されます。パフォーマンスイベントに加えて健全性イベントも表示されるため、パフォーマンスに影響する可能性がある原因を総合的に確認できます。



 a| 
レイテンシ - 合計
 a| 
アプリケーションの要求に応答するまでのミリ秒数。平均レイテンシの値はI/Oの重み付きであることに注意してください。



 a| 
レイテンシ - 内訳
 a| 
レイテンシの合計に表示される情報と同じ情報が、パフォーマンスデータが読み取り、書き込み、その他のレイテンシに分けて表示されます。このグラフは、選択したオブジェクトがSVM、ノード、アグリゲート、ボリューム、LUNの場合にのみ表示されます。またはネームスペースです。



 a| 
Latency - クラスタコンポーネント
 a| 
レイテンシの合計に表示される情報と同じ情報が、パフォーマンスデータがクラスタコンポーネントごとにレイテンシに分けて表示されます。このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。



 a| 
IOPS - 合計
 a| 
1 秒あたりの入出力処理数。



 a| 
IOPS - 内訳
 a| 
IOPS の合計に表示される情報は同じですが、パフォーマンスデータが読み取り、書き込み、その他の IOPS に分けて表示されます。ズームビューで表示した場合、ONTAP で設定されている場合、ボリュームのグラフにQoSの最小スループットと最大スループットの値が表示されます。

このグラフは、選択したオブジェクトが SVM 、ノード、アグリゲート、ボリューム、 LUN である場合にのみ表示されます。 またはネームスペースです。



 a| 
IOPS - プロトコル
 a| 
IOPS の合計に表示される情報は同じですが、パフォーマンスデータは、 CIFS 、 NFS 、 FCP 、 NVMe 、 iSCSI のプロトコルトラフィックの個々のグラフに分けて表示されます。このグラフは、選択したオブジェクトが SVM の場合にのみ表示されます。



 a| 
IOPS/TB - 合計
 a| 
ワークロードで消費されている合計スペースに基づいて 1 秒あたりの入出力処理数（テラバイト単位）。I/O密度とも呼ばれます。このカウンタは、特定のストレージ容量で提供可能なパフォーマンスを測定します。ズームビューで表示すると、ONTAP で設定されている場合、ボリュームのグラフにはQoSの想定値と最大スループット値が表示されます。

このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。



 a| 
MBps -合計
 a| 
1 秒あたりにオブジェクトとの間で転送されたデータのメガバイト数。



 a| 
MBps -内訳
 a| 
MBpsグラフと同じ情報が表示されますが、MBpsデータがディスク読み取り、Flash Cache読み取り、書き込み、その他に分けて表示されます。Zoom Viewで表示すると、QoS最大スループット値がONTAP で設定されている場合はボリュームのグラフに表示されます。

このグラフは、選択したオブジェクトが SVM 、ノード、アグリゲート、ボリューム、 LUN である場合にのみ表示されます。 またはネームスペースです。

[NOTE]
====
Flash Cache のデータは、ノードに Flash Cache モジュールがインストールされている場合にのみ表示されます。

====


 a| 
使用済みパフォーマンス容量 - 合計
 a| 
ノードまたはアグリゲートによるパフォーマンス容量の消費率。

[NOTE]
====
パフォーマンス容量のデータは、クラスタ内のノードにONTAP 9.0以降のソフトウェアがインストールされている場合にのみ表示されます。

====


 a| 
使用済みパフォーマンス容量 - 内訳
 a| 
使用済みパフォーマンス容量。ユーザプロトコルおよびシステムのバックグラウンドプロセスに分けて表示されます。また、空きパフォーマンス容量が表示されます。



 a| 
使用可能な IOPS - 合計
 a| 
このオブジェクトで現在使用可能な（空き） 1 秒あたりの入出力処理数。この数値は、 Unified Manager がオブジェクトで実行可能と計算する合計 IOPS から現在使用されている IOPS を引いた結果です。このグラフは、選択したオブジェクトがノードまたはアグリゲートの場合にのみ表示されます。

[NOTE]
====
使用可能なIOPSのデータは、クラスタ内のノードにONTAP 9.0以降のソフトウェアがインストールされている場合にのみ表示されます。

====


 a| 
Utilization - 合計
 a| 
オブジェクトの使用可能なリソースの使用率。利用率は、ノードのノード利用率、アグリゲートのディスク利用率、およびポートの帯域幅利用率を示します。このグラフは、選択したオブジェクトがノード、アグリゲート、またはポートである場合にのみ表示されます。



 a| 
キャッシュミス率 - 合計
 a| 
クライアントアプリケーションからの読み取り要求に対してキャッシュからではなくディスクからデータが返される割合。このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。

|===