---
permalink: online-help/reference-volume-relationships-inventory-report.html 
sidebar: sidebar 
keywords:  
summary: ボリューム関係インベントリレポートでは、クラスタ内のストレージインベントリの詳細を分析できるほか、ボリュームに必要な保護レベルを把握したり、障害の原因、パターン、スケジュールに基づいてボリュームの詳細をフィルタリングしたりできます。 
---
= ボリューム関係インベントリレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム関係インベントリレポートでは、クラスタ内のストレージインベントリの詳細を分析できるほか、ボリュームに必要な保護レベルを把握したり、障害の原因、パターン、スケジュールに基づいてボリュームの詳細をフィルタリングしたりできます。

ボリューム関係インベントリレポートは、次の2つの形式で表示されます。

* SnapMirror関係の円グラフとSnapVault 関係の円グラフ
* ボリューム関係インベントリレポートの表形式ビュー




== SnapMirrorとSnapVault の円グラフ

ストレージシステムに存在するボリューム関係の設定の詳細が表示されます。



== ボリューム関係インベントリの表形式ビュー

* * 関係の健全性 *
+
クラスタの関係の健全性が表示されます。

* * 関係の状態 *
+
SnapMirror関係のミラー状態が表示されます。

* * 転送ステータス *
+
SnapMirror関係のステータスが表示されます。

* * 遅延ステータス *
+
ボリュームの遅延ステータスが表示されます。

* * ソースクラスタ *
+
SnapMirror 関係のソースクラスタの名前が表示されます。

* * ソース SVM *
+
SnapMirror関係のソースStorage Virtual Machine（SVM）の名前が表示されます。

* * ソースボリューム *
+
SnapMirror関係のソースボリュームの名前が表示されます。

* * デスティネーションクラスタ *
+
SnapMirror 関係のデスティネーションクラスタの名前が表示されます。

* * デスティネーション SVM *
+
SnapMirror関係のデスティネーションStorage Virtual Machine（SVM）の名前が表示されます。

* * デスティネーションボリューム *
+
SnapMirror関係のデスティネーションボリュームの名前が表示されます。

* * 関係タイプ *
+
SnapMirrorまたはSnapVault を含む、関係のタイプを表示します。

* *前回成功した更新時間*
+
SnapMirror または SnapVault の処理に最後に成功した時刻が表示されます。

* *前回の転送時間（時間）*
+
前回のデータ転送が完了するまでの時間が表示されます。

* *最後の転送サイズ（MB）*
+
前回のデータ転送のサイズがバイト単位で表示されます。

* *前回の転送終了時間*
+
SnapMirror処理またはSnapVault 処理が最後に正常に完了した時刻が表示されます。

* * 正常でない理由 *
+
関係が正常な状態でない理由が表示されます。

* *遅延時間（時間）*
+
ミラーのデータがソースより遅延している時間が表示されます。

* * バージョンに依存しないレプリケーション *
+
[ はい ] 、 [ バックアップオプションあり ] 、または [ なし ] のいずれかを表示します。


