---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: ケンセンセイ/クラスタストレエシサマリヘエシヲシヨウシテ、スヘテノクラスタノストレエシヨウリヨウトシヨウリヨウニカンスルカイヨウホウヲヒヨウシできますこの情報は、容量のリスクの可能性を把握して、ワークロードをリバランシングするための適切な処置を行う場合に役立ちます。 
---
= ケンシヨウセイ/クラスタストレエシサマリヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ケンセンセイ/クラスタストレエシサマリヘエシヲシヨウシテ、スヘテノクラスタノストレエシヨウリヨウトシヨウリヨウニカンスルカイヨウホウヲヒヨウシできますこの情報は、容量のリスクの可能性を把握して、ワークロードをリバランシングするための適切な処置を行う場合に役立ちます。

すべての監視対象クラスタの詳細をカンマ区切り値でエクスポートするには、* Export *ボタンを使用します (`.csv`)ファイル。

* * クラスタ *
+
クラスタ名。

* * HAペア*
+
2つのノードを構成して得られるHAペア値。

* *モデル/ファミリー*
+
クラスタのモデルまたはファミリーの名前。

* * OSバージョン*
+
システムにインストールされているONTAP のバージョン。

* *合計物理容量*
+
アレイ内のすべてのディスクの合計物理容量が表示されます。

* *未設定の物理容量*
+
コンテナタイプが「アグリゲート」、「破損」、「スペア」、「共有」以外のディスクの未設定の容量。この容量は、ONTAP のディスクの物理容量よりも常に多くなります。たとえば、2TBのディスクがあるとします。ディスクの物理容量はONTAP では1.6TBですが、Unified Managerでの未設定の物理容量は1.8TBになります。

* *アグリゲート合計容量*
+
ユーザが使用可能なアグリゲートの合計サイズ。これにはSnapshotコピーリザーブが含まれます。

* *アグリゲートの使用容量*
+
アグリゲートですでに使用されている容量。これには、ボリューム、LUN、その他のStorage Efficiencyテクノロジのオーバーヘッドによって消費される容量も含まれます。

* *アグリゲート-未使用容量*
+
アグリゲートに追加データを格納するために使用できる容量。これにはSnapshotコピーリザーブが含まれます。

* *割り当て済みLUN容量*
+
マッピングされているLUNの容量。

* *未割り当てのLUN容量*
+
ホストにマッピングされていないすべてのLUNの容量。

* *ボリューム合計容量*
+
ボリュームの合計容量（使用容量と未使用容量を足したもの）。

* *ボリュームの使用容量*
+
ボリュームの使用済み容量。

* *ボリューム-未使用容量*
+
ボリュームの未使用容量。

* *ボリュームの保護容量*
+
SnapMirrorとSnapVault が有効になっているボリュームの容量。

* *クラスタ-ライセンス設定済みのクラウドの合計容量*
+
クラウド階層でライセンスが付与されている合計容量。このフィールドは、FabricPool ライセンスが必要なストレージプロバイダに対して表示されます。たとえば、Amazon S3、Microsoft Azureクラウド、IBM Cloud Object Storage、Alibaba Cloud Object Storageなどです。

* *クラスタ-クラウド階層のライセンス設定済み容量*
+
FabricPool ライセンスが必要なストレージプロバイダについて、クラウド階層でデータに使用されているスペース。

* *使用済みクラスタStorageGRID 容量*
+
StorageGRID など、FabricPool ライセンスが不要なストレージプロバイダについて、クラウド階層でデータに使用されているスペース。


