---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Storage Summaryレポートを使用すると、HAペアのストレージ容量についてまとめた情報を確認できます。この情報は、容量のリスクの可能性を把握して、ワークロードをリバランシングするための適切な処置を行う場合に役立ちます。シングルノードクラスタの情報はレポートに表示されません。 
---
= Storage Summaryレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Summaryレポートを使用すると、HAペアのストレージ容量についてまとめた情報を確認できます。この情報は、容量のリスクの可能性を把握して、ワークロードをリバランシングするための適切な処置を行う場合に役立ちます。シングルノードクラスタの情報はレポートに表示されません。



== Storage Summaryレポートチャートビュー

Storage Summaryレポートは、次の2つの形式で表示されます。

* Storage Summaryレポートチャートビュー
* ストレージサマリレポートの表形式ビュー


一定の期間にわたるアグリゲートの使用済みのデータ容量と未使用のデータ容量のトレンドがグラフに表示されます。縦（y）軸には合計データ容量、横（x）軸にはクラスタ名が表示されます。したがって、グラフ内の各バーは1つのクラスタを表します。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。

* *クラスタ名*
+
クラスタ名が表示されます。

* * HAペア*
+
2つのノードを構成して得られるHAペア値が表示されます。

* * モデル *
+
モデルの名前を表示します。

* * OSバージョン*
+
使用されているONTAP のバージョンが表示されます。

* *合計物理容量*
+
アレイ内のすべてのディスクの合計物理容量が表示されます。

* *未設定の物理容量*
+
コンテナタイプが「アグリゲート」、「破損」、「スペア」、「共有」以外のディスクの未設定の容量が表示されます。この容量は、ONTAP のディスクの物理容量よりも常に多くなります。たとえば、2TBのディスクがあるとします。ディスクの物理容量はONTAP では1.6TBですが、Unified Managerでの未設定の物理容量は1.8TBになります。

* *アグリゲート合計容量*
+
ユーザが使用可能なアグリゲートの合計サイズが表示されます。これにはSnapshotコピーリザーブが含まれます。

* *アグリゲートの使用容量*
+
アグリゲートですでに使用されている容量が表示されます。これには、ボリューム、LUN、その他のStorage Efficiencyテクノロジのオーバーヘッドによって消費される容量も含まれます。

* *アグリゲート-未使用容量*
+
アグリゲートに追加データを格納するために使用できる容量が表示されます。これにはSnapshotコピーリザーブが含まれます。

* *割り当て済みLUN容量*
+
マッピングされているLUNの容量が表示されます。

* *未割り当てのLUN容量*
+
ホストにマッピングされていないすべてのLUNの容量が表示されます。

* *ボリューム合計容量*
+
ボリュームの合計容量（使用容量と未使用容量を足したもの）が表示されます。

* *ボリュームの使用容量*
+
ボリュームの使用済み容量が表示されます。

* *ボリューム-未使用容量*
+
ボリュームの未使用容量が表示されます。

* *ボリュームの保護容量*
+
SnapMirrorとSnapVault が有効になっているボリュームの容量が表示されます。

* *クラスタ-ライセンス設定済みのクラウドの合計容量*
+
クラウド階層でライセンスが付与されている合計容量が表示されます。このフィールドは、FabricPool ライセンスが必要なストレージプロバイダに対して表示されます。たとえば、Amazon S3、IBM Cloud Object Storage、Microsoft Azureクラウド、Alibaba Cloud Object Storageなどです。

* *クラスタ-クラウド階層のライセンス設定済み容量*
+
FabricPool ライセンスが必要なストレージプロバイダについて、クラウド階層でデータに使用されているスペースが表示されます。

* *使用済みクラスタStorageGRID 容量*
+
StorageGRID など、FabricPool ライセンスが不要なストレージプロバイダについて、クラウド階層でデータに使用されているスペースが表示されます。


