---
permalink: online-help/reference-notifications-page.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager サーバでは、イベントが生成されたときやユーザに割り当てられたときに通知を送信するように設定することができます。通知メカニズムを設定することもできます。たとえば、通知を E メールや SNMP トラップとして送信できます。 
---
= Setup/Notificationsページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager サーバでは、イベントが生成されたときやユーザに割り当てられたときに通知を送信するように設定することができます。通知メカニズムを設定することもできます。たとえば、通知を E メールや SNMP トラップとして送信できます。

OnCommand 管理者またはストレージ管理者のロールが必要です。



== E メール

この領域では、アラート通知に関する次の E メール設定を行うことができます。

* * 送信元アドレス *
+
アラート通知の送信元 E メールアドレスを指定します。この値は、共有時にレポートの送信元アドレスとしても使用されます。送信元アドレスに「OnCommand@localhost.com」というアドレスが事前に入力されている場合は、すべての電子メール通知が正常に配信されるように、実際の作業用電子メールアドレスに変更する必要があります。





== SMTP サーバ

この領域では、次の SMTP サーバ設定を行うことができます。

* * ホスト名または IP アドレス *
+
SMTP ホストサーバのホスト名を指定します。このホスト名は、指定した受信者へのアラート通知の送信に使用されます。

* * ユーザー名 *
+
SMTP ユーザ名を指定します。SMTP ユーザ名は、 SMTP サーバで SMTPAUTH が有効になっている場合にのみ必要です。

* * パスワード *
+
SMTP パスワードを指定します。SMTP ユーザ名は、 SMTP サーバで SMTPAUTH が有効になっている場合にのみ必要です。

* * ポート *
+
アラート通知を送信する SMTP ホストサーバで使用されるポートを指定します。

+
デフォルト値は 25. です。

* * STARTTLSを使用*
+
このチェックボックスをオンにすると、 TLS/SSL プロトコル（ start_tls および StartTLS とも表記）を使用して SMTP サーバと管理サーバの間のセキュアな通信が確立されます。

* * SSL * を使用します
+
このチェックボックスをオンにすると、 SSL プロトコルを使用して SMTP サーバと管理サーバの間のセキュアな通信が確立されます。





== SNMP

この領域では、次の SNMP トラップ設定を行うことができます。

* * バージョン *
+
必要なセキュリティのタイプに応じて、使用する SNMP のバージョンを指定します。オプションには、バージョン 1 、バージョン 3 、認証を使用するバージョン 3 、認証と暗号化を使用するバージョン 3 があります。デフォルト値はバージョン 1 です。

* * トラップ送信先ホスト *
+
管理サーバによって送信される SNMP トラップを受信するホスト名または IP アドレス（ IPv4 または IPv6 ）を指定します。

* * アウトバウンドトラップポート *
+
管理サーバによって送信されるトラップを SNMP サーバが受信する際に使用するポートを指定します。

+
デフォルト値は 162. です。

* * コミュニティ *
+
ホストにアクセスするためのコミュニティストリングです。

* * エンジン ID *
+
SNMP エージェントの一意の識別子を指定します。この識別子は、管理サーバによって自動的に生成されます。エンジン ID は、 SNMP バージョン 3 、認証付き SNMP バージョン 3 、認証および暗号化付き SNMP バージョン 3 で使用できます。

* * ユーザー名 *
+
SNMP ユーザ名を指定します。ユーザ名は、 SNMP バージョン 3 、認証を使用する SNMP バージョン 3 、および認証と暗号化を使用する SNMP バージョン 3 で使用できます。

* * 認証プロトコル *
+
ユーザの認証に使用するプロトコルを指定します。プロトコルオプションには MD5 と SHA があります。MD5 がデフォルト値です。認証プロトコルは、認証および暗号化を使用する SNMP バージョン 3 で使用できます。

* * 認証パスワード *
+
ユーザの認証時に使用するパスワードを指定します。認証パスワードは、 SNMP バージョン 3 （認証あり）および SNMP バージョン 3 （認証および暗号化あり）で使用できます。

* * プライバシープロトコル *
+
SNMP メッセージの暗号化に使用するプライバシープロトコルを指定します。プロトコルのオプションには、 AES 128 と DES があります。デフォルト値は AES 128 です。プライバシープロトコルは、認証および暗号化を使用する SNMP バージョン 3 で使用できます。

* * プライバシーパスワード *
+
プライバシープロトコルを使用する場合のパスワードを指定します。プライバシーパスワードは、認証と暗号化を使用する SNMP バージョン 3 で使用できます。


