---
permalink: online-help/reference-capacity-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: Health/Aggregates Capacity and Utilizationページでは、すべてのクラスタのアグリゲートの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。 
---
= 健常性/アグリゲートの容量と使用状況ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health/Aggregates Capacity and Utilizationページでは、すべてのクラスタのアグリゲートの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。

監視しているすべてのアグリゲートの詳細をカンマ区切り値でエクスポートするには、* Export *ボタンを使用します (`.csv`)ファイル。

* * クラスタ *
+
クラスタ名。

* * HAペア*
+
2つのノードを構成して得られるHAペア値。

* * 集計 *
+
アグリゲート名。

* *合計データ容量*
+
合計データ容量（使用容量と使用可能容量を足したもの）。

* *使用済みデータ容量*
+
使用済みデータ容量。

* *使用済みデータ%*
+
使用済みデータ容量の割合。

* *使用可能なデータ容量*
+
使用可能なデータ容量。

* *使用可能なデータ%*
+
使用可能なデータ容量の割合。

* *日次増加率
+
アグリゲートでの24時間ごとの増加率。

* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの推定日数。

* *スペースがフルのしきい値%*
+
アグリゲートがフルであるとみなす割合。

* *スペースがほぼフルのしきい値%*
+
アグリゲートがほぼフルであるとみなす割合。

* *増加率しきい値*
+
アグリゲートの増加率が正常であるとみなす割合。このしきい値を超えると、「アグリゲートの増加率-異常」イベントが生成されます。

* *増加率係数しきい値*
+
アグリゲートの増加率の標準偏差に適用される係数。増加率が係数適用後の標準偏差を超えると、「アグリゲートの増加率が異常」イベントが生成されます。

* *フルまでの日数しきい値*
+
アグリゲートの容量がフルに達するまでの残り日数。

* * Snapshotリザーブの合計容量*
+
アグリゲートのSnapshotリザーブの合計容量。

* * Snapshotリザーブの使用容量*
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量。

* * Snapshotリザーブの使用率
+
SnapshotコピーがSnapshotリザーブで使用しているスペースの量の割合。

* * Snapshotリザーブの使用可能容量*
+
Snapshotコピーに使用できるスペースの量。

* * Snapshotリザーブの使用可能率
+
Snapshotコピーに使用できるスペースの量の割合。

* *「Snapshotコピーリザーブがフル」しきい値を超えています
+
アグリゲートのSnapshotコピー用にリザーブされたスペースがすべて使用されているとみなす割合。

* *オーバーコミット容量%*
+
アグリゲートオーバーコミットの割合。

* *オーバーコミットのしきい値%*
+
アグリゲートがオーバーコミットされているとみなす割合。

* *「ほぼオーバーコミット」しきい値
+
アグリゲートがほぼオーバーコミットされているとみなす割合。

* *アグリゲートタイプ*
+
アグリゲートのタイプ：

+
** HDD
** ハイブリッド
+
HDDとSSDの組み合わせですが、Flash Poolは有効になっていません。

** ハイブリッド（Flash Pool）
+
HDDとSSDの組み合わせで、Flash Poolが有効になっています。

** SSD の場合
** SSD （ FabricPool ）
+
SSDとクラウド階層の組み合わせです

** VMDisk（SDS）
+
仮想マシン内の仮想ディスク

** VMディスク（FabricPool ）
+
仮想ディスクとクラウド階層の組み合わせです

** 標準ディスクおよびSSDディスクのLUN（FlexArray ）の場合、監視対象のストレージシステムが8.3より前のバージョンのONTAP を実行しているときは、この列が空白になります。


* * RAID タイプ *
+
RAID構成タイプ。

* *アグリゲートの状態*
+
アグリゲートの現在の状態。

* * SnapLock タイプ *
+
アグリゲートがSnapLock アグリゲートか非SnapLockアグリゲートか。

* *クラウド階層の使用済みスペース*
+
クラウド階層で現在使用されているデータ容量。

* * クラウド階層 *
+
ONTAP での作成時に指定されたクラウド階層のオブジェクトストアの名前。


