---
permalink: online-help/reference-setup-autosupport-page.html 
sidebar: sidebar 
keywords:  
summary: セットアップ/ AutoSupportページでは、AutoSupport 概要 の表示、定期的なAutoSupport の有効化、またはオンデマンドのAutoSupport メッセージの送信を行うことができます。 
---
= Setup/AutoSupportヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セットアップ/ AutoSupportページでは、AutoSupport 概要 の表示、定期的なAutoSupport の有効化、またはオンデマンドのAutoSupport メッセージの送信を行うことができます。



== 情報エリア

* * システム ID *
+
このUnified ManagerサーバのシステムIDが表示されます。





== 定期的なAutoSupport エリア

問題 の診断と解決のためにテクニカルサポートに送信する、特定の事前定義されたメッセージを定期的に生成できます。

* *定期的なAutoSupport を有効にします*
+
定期的なAutoSupport 機能を有効にするように指定します。





== On-Demand AutoSupport エリアの略

テクニカルサポート、指定したEメール受信者、またはその両方に宛てたオンデマンドメッセージを生成して送信できます。

* *テクニカルサポートに送信*
+
発生した問題に関するオンデマンドメッセージをテクニカルサポートに送信するように指定します。

* * Eメール受信者に送信*
+
発生した問題に関するオンデマンドメッセージを指定した受信者に送信するように指定します。

* * AutoSupport の生成と送信*
+
発生した問題に関するオンデマンドメッセージを生成し、テクニカルサポート、指定した受信者、またはその両方に送信します。





== HTTPプロキシ領域

Unified Manager サーバからの直接アクセスが環境によって提供されない場合に、 AutoSupport のコンテンツをサポートに送信するためのインターネットアクセスを提供するプロキシを指定できます。

* * HTTP プロキシ * を使用します
+
HTTP プロキシとして使用するサーバを識別するには、このチェックボックスをオンにします。

+
プロキシサーバのホスト名または IP アドレス、およびサーバへの接続に使用するポート番号を入力します。

* * 認証を使用 *
+
HTTP プロキシとして使用するサーバにアクセスするための認証情報を指定する必要がある場合は、このチェックボックスをオンにします。

+
HTTP プロキシでの認証に必要なユーザ名とパスワードを入力します。



[NOTE]
====
ベーシック認証のみを提供する HTTP プロキシはサポートされていません。

====