---
permalink: online-help/reference-advanced-secondary-setting-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Advanced Secondary Settings ダイアログボックスを使用して、セカンダリボリュームのバージョンに依存しないレプリケーション、複数コピーバックアップ、およびスペース関連設定を有効にすることができます。Advanced Secondary Settings ダイアログボックスを使用して、現在の設定を有効または無効にすることができます。 
---
= Advanced Secondary Settings ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Advanced Secondary Settings ダイアログボックスを使用して、セカンダリボリュームのバージョンに依存しないレプリケーション、複数コピーバックアップ、およびスペース関連設定を有効にすることができます。Advanced Secondary Settings ダイアログボックスを使用して、現在の設定を有効または無効にすることができます。

スペース関連設定には、重複排除、データ圧縮、自動拡張、スペースギャランティなど、格納できるデータの量を最大限に増やすための設定が含まれます。

このダイアログボックスには次のフィールドがあります。

* * バージョンに依存しないレプリケーション * を有効にします
+
バージョンに依存しないレプリケーションで SnapMirror を有効にします。バージョンに依存しないレプリケーションでは、ソースとデスティネーションの両方でONTAP 8.3以降が実行されていれば、デスティネーションボリュームでソースボリュームよりも古いバージョンのONTAP が実行されていても、ソースボリュームのSnapMirror保護が可能です。

+
** バックアップを有効にします
+
バージョンに依存しないレプリケーションを有効にすると、 SnapMirror ソースデータの複数の Snapshot コピーを SnapMirror デスティネーションに転送して保持することができます。



* * 重複排除を有効にする *
+
SnapVault 関係のセカンダリボリュームで重複排除を有効にして、重複するデータブロックを排除してスペースを削減できるようにします。重複排除は、スペース削減率が 10% 以上で、データが頻繁には上書きされない場合に効果を期待できます。重複排除は、仮想環境、ファイル共有、バックアップのデータによく使用されます。この設定は、デフォルトでは無効になっています。有効にすると、転送が完了するたびにこの処理が開始されます。

+
** 圧縮を有効にします
+
透過的なデータ圧縮を有効にします。圧縮は、スペース削減率が 10% 以上で、潜在的なオーバーヘッドを許容でき、ピーク時以外の時間帯に圧縮を完了できるだけの十分なシステムリソースがある場合に効果を期待できます。SnapVault 関係では、この設定はデフォルトで無効になっています。圧縮は、重複排除を選択した場合にのみ使用できます。

** インラインで圧縮します
+
ディスクに書き込む前にデータを圧縮することで、スペース削減効果を即座に実現できます。インライン圧縮は、システムのピーク時の利用率が 50% 以下で、ピーク時に書き込みや CPU が多少増えても許容できる場合に効果を期待できます。この設定は、「圧縮を有効にする」が選択されている場合にのみ使用できます。



* * 自動拡張を有効にします。 *
+
空きスペースの割合が指定したしきい値を下回ったときに、関連付けられているアグリゲートに使用可能なスペースが残っていれば、デスティネーションボリュームを自動的に拡張できます。

* * 最大サイズ *
+
ボリュームを最大で何パーセントまで拡張できるかを設定します。デフォルトでは、ソースボリュームのサイズよりも 20% まで大きくできます。現在のボリュームサイズがこの値以上の場合、そのボリュームは自動的に拡張されません。このフィールドは、自動拡張の設定を有効にした場合にのみ有効になります。

* * 増分サイズ *
+
ボリュームの自動拡張で何パーセントずつ拡張するかを指定します。ソースボリュームの割合で示した最大サイズに達するまで、この割合で自動的に拡張されます。

* * スペース保証 *
+
データ転送が常に成功するようにセカンダリボリュームに十分なスペースを割り当てます。スペースギャランティの設定は次のいずれかです。

+
** ファイル。
** ボリューム
** noneたとえば、200GBのボリュームに合計50GBのファイルが格納されており、それらのファイルに実際に格納されているデータは10GBだけであるとします。ボリュームギャランティでは、ソースの内容に関係なく、デスティネーションボリュームに 200GB が割り当てられます。ファイルギャランティでは、ソース上のファイルに十分なスペースが確保されるように 50GB が割り当てられます。このシナリオで None を選択した場合、ソース上のファイルデータで使用される実際のスペースに対して、デスティネーションには 10GB だけが割り当てられます。


+
スペースギャランティはデフォルトでボリュームに設定されています。





== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * 適用 *
+
選択した効率化設定を保存し、 [ 保護の設定 ] ダイアログボックスで [ 適用 ] をクリックしたときに適用します。

* * キャンセル *
+
選択内容を破棄して、 [Advanced Destination Settings] ダイアログボックスを閉じます。



* 関連情報 *

http://www.netapp.com/us/media/tr-3966.pdf["ネットアップテクニカルレポート3966：『ネットアップのデータ圧縮機能と重複排除機能導入および実装ガイド：clustered Data ONTAP 』"]
