---
permalink: online-help/reference-user-defined-threshold-policies-page-opm.html 
sidebar: sidebar 
keywords:  
summary: Configuration / Performance Thresholdsページを使用すると、現在定義されているすべてのパフォーマンスしきい値ポリシーを表示できます。このページには、しきい値ポリシーを作成、クローニング、編集、および削除する機能も用意されています。 
---
= Configuration / Performance Thresholdsページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configuration / Performance Thresholdsページを使用すると、現在定義されているすべてのパフォーマンスしきい値ポリシーを表示できます。このページには、しきい値ポリシーを作成、クローニング、編集、および削除する機能も用意されています。

パフォーマンスしきい値ポリシーのリストは、ポリシー名のアルファベット順にソートされます。列ヘッダーをクリックすると、その列でポリシーをソートできます。特定のポリシーを検索する場合は、フィルタと検索を使用して、インベントリリストに表示するしきい値ポリシーを絞り込むことができます。



== フィルタと検索バー

[*Filtering*]ボタンを使用すると、特定の条件に一致するポリシーのみを表示して、しきい値ポリシーのリストを絞り込むことができます。

* Search *ボタンを使用すると、ポリシー名の全体または一部を入力して特定のポリシーを検索し、インベントリリストに表示するしきい値ポリシーのリストを絞り込むことができます。



== コマンドボタン

* * 作成 * 。
+
新しいパフォーマンスしきい値ポリシーを作成します。

* * クローン *
+
選択したポリシーのコピーに基づいて、新しいパフォーマンスしきい値ポリシーを作成します。

* * 編集 * 。
+
選択したパフォーマンスしきい値ポリシーを変更します。ポリシーを使用しているすべてのストレージオブジェクトが、改訂したポリシーを使用するように更新されます。

* * 削除 *
+
選択したパフォーマンスしきい値ポリシーを削除します。ポリシーを使用しているすべてのストレージオブジェクトからポリシーが削除されます。[関連オブジェクト]列の項目をクリックすると、このポリシーを現在使用しているオブジェクトを表示できます。





== しきい値ポリシーのリスト

* * ポリシー名 *
+
しきい値ポリシーの名前が表示されます。ポリシー名にカーソルを合わせると、ポリシーの詳細を確認できます。

* * 概要 *
+
しきい値ポリシーの簡単な概要 が表示されます。

* *最初の条件*
+
しきい値ポリシーの第1条件が表示されます。定義済みのパフォーマンスカウンタおよび警告トリガーの値と重大トリガーの値が含まれます。条件名にカーソルを合わせると、条件の詳細を確認できます。

* * 2番目の条件*
+
セカンダリしきい値ポリシーの条件が定義されている場合は表示されます。条件名にカーソルを合わせると、条件の詳細を確認できます。2番目の条件が定義されていない場合、この列は空白になります。

+
[NOTE]
====
第2条件が定義されている場合は、両方の条件に違反している場合にのみイベントが生成されます。

====
* *関連オブジェクト*
+
しきい値ポリシーを適用可能なストレージオブジェクトのタイプ、およびポリシーを使用しているオブジェクトの数が表示されます。少なくとも1つのオブジェクトにポリシーを割り当てるまで、このフィールドは空白になります。

+
列見出しをクリックすると、ボリューム、LUN、アグリゲートなど、オブジェクトタイプ別にポリシーをソートできます。ポリシー名をクリックすると、現在しきい値ポリシーを使用しているオブジェクトを含むインベントリページを表示できます。


