---
permalink: online-help/reference-edit-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 関連付けられているリソース、イベント、スクリプト、通知オプションなど、アラートのプロパティを編集することができます。 
---
= EditAlert タイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関連付けられているリソース、イベント、スクリプト、通知オプションなど、アラートのプロパティを編集することができます。



== 名前

この領域では、アラートの名前と概要を編集できます。

* * アラート名 *
+
アラート名を編集できます。

* * Alert 概要 *
+
アラートの概要を指定できます。

* * アラートの状態 *
+
アラートを有効または無効にできます。





== リソース

この領域では、アラートをトリガーする対象のリソースを個別に選択したり、動的ルールに基づいてリソースをグループ化したりできます。ドロップダウンリストからリソースタイプを選択してリソースを検索するか、正確なリソース名を指定して特定のリソースを表示できます。

* * インクルード *
+
アラートをトリガーする対象に含めるリソースを指定できます。テキスト文字列を指定すると、その文字列に一致するリソースをグループ化し、そのグループをアラートの対象として選択できます。たとえば、「 vol0 」という文字列が名前に含まれるすべてのボリュームをグループ化することができます。

* * 除外 *
+
アラートをトリガーする対象から除外するリソースを指定できます。たとえば、「 xyz 」という文字列が名前に含まれるすべてのボリュームを除外することができます。

+
[NOTE]
====
[除外]タブは'特定のリソースタイプのすべてのリソースを選択した場合にのみ表示されますたとえば'次のように表示されます <<All Volumes>> または <<All Volumes whose name contains '_xyz_'>>。

====




== イベント

この領域では、アラートをトリガーするイベントを選択できます。アラートは特定の重大度のイベントに対してトリガーするか、一連のイベントを指定してトリガーできます。

* * イベントの重大度 *
+
重大度タイプに基づいてイベントを選択できます。タイプは、「重大」、「エラー」、「警告」のいずれかになります。

* * イベント名に * が含まれています
+
名前に指定した文字を含むイベントを選択できます。





== アクション

この領域では、通知方式と通知頻度を指定できます。

* * これらのユーザーに警告 *
+
通知を受け取る E メールアドレスまたはユーザ名を編集できます。新しい E メールアドレスまたはユーザ名を指定することもできます。

* * 通知頻度 *
+
イベントが確認または解決されるか、廃止状態に設定されるまでの間、管理サーバが通知を送信する頻度を編集できます。

+
次のいずれかの通知方式を選択できます。

+
** 1 回だけ通知します
** 指定した頻度で通知します
** 指定した期間内の指定した頻度で通知します


* * 問題 SNMP トラップ *
+
グローバルに設定された SNMP ホストに SNMP トラップを送信するかどうかを指定できます。

* * スクリプトの実行 *
+
アラートにスクリプトを関連付けることができます。このスクリプトはアラートが生成されたときに実行されます。





== コマンドボタン

* * 保存 *
+
変更内容を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更内容を破棄してダイアログボックスを閉じます。


