---
permalink: online-help/reference-management-groups-page.html 
sidebar: sidebar 
keywords:  
summary: 管理/グループページでは、Unified Managerでグループを作成してストレージオブジェクトを簡単に管理できます。グループとはストレージオブジェクト（クラスタ、ボリューム、SVM）の動的な集まりです。この集まりは、グループに対して作成するグループルールで定義されます。 
---
= ［管理/グループ］ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理/グループページでは、Unified Managerでグループを作成してストレージオブジェクトを簡単に管理できます。グループとはストレージオブジェクト（クラスタ、ボリューム、およびSVM）の動的な集まりです。この集まりは、グループに対して作成するグループルールで定義されます。

[Management/Groups]ページには、グループ、グループルール、およびグループアクションを追加、削除、または編集できるタブがあります。オペレータとしてログインすると、ページへの読み取りアクセスのみが許可されます。ストレージ管理者またはUnified Manager管理者としてログインした場合は、各タブで追加、編集、削除の各ボタンを使用できます。



== [ グループ ] タブ

[グループ]タブには、作成したグループの名前と概要 が表示されます。グループの追加、編集、削除などのタスクを実行できます。このタブには、グループに関連付けられているグループルールとグループアクションの数、グループ内のクラスタ、SVM、ボリュームの数も表示されます。



== コマンドボタン

* * 追加 * 。
+
グループの追加ダイアログボックスが表示されます。このダイアログボックスで、グループを追加し、グループの名前と概要 を指定できます。

+
グループルールは、ストレージオブジェクトを含めるためにあとでグループに適用することもできます。

* * 編集 * 。
+
グループの編集ダイアログボックスが表示され、選択したグループの名前と概要 を編集できます。

* * 削除 *
+
選択したグループを削除します。





== リストビュー

リストビューには、Unified Managerで作成したグループが表形式で表示されます。列のフィルタを使用して、表示するデータをカスタマイズできます。デフォルトでは、リストはグループ名でソートされます。

* * 名前 *
+
グループの名前が表示されます。

* * 概要 *
+
グループの概要 が表示されます。

* *関連付けられたルール*
+
グループに追加されているルールの数が表示されます。

* *関連付けられているアクション*
+
グループに追加されているグループ操作の数が表示されます。

* *該当するクラスタ*
+
グループに含まれているクラスタの数が表示されます。

* *該当するSVM *
+
グループに含まれているSVMの数が表示されます。

* *該当するボリューム*
+
グループに含まれているボリュームの数が表示されます。





== ［グループルール］タブ

グループルールタブには、ストレージオブジェクトを格納するグループに対して作成したグループルールが表示されます。グループルールの追加、編集、削除などのタスクを実行できます。このタブには、グループルールの作成対象であるグループの名前と、ルールが適用されるストレージオブジェクトも表示されます。グループルールを満たしているストレージオブジェクトの数も確認できます。



== コマンドボタン

* * 追加 * 。
+
Add Group Ruleダイアログボックスが表示されます。このダイアログボックスでは、ストレージオブジェクトのグループルールを作成できます。

* * 編集 * 。
+
[Edit Group Rule]ダイアログボックスが表示されます。このダイアログボックスでは、以前に設定したグループルールを再設定できます。

* * 削除 *
+
選択したグループルールを削除します。





== リストビュー

リストビューには、特定のストレージオブジェクト（クラスタ、ボリューム、またはSVM）に対して作成したグループルール、および定義したグループルールを満たしているストレージオブジェクトの数が表形式で表示されます。

* * 名前 *
+
ルールの名前が表示されます。

* *関連付けられたグループ*
+
グループルールが定義されているグループの名前が表示されます。

* *ターゲットオブジェクトタイプ*
+
グループルールが適用されるストレージオブジェクトのタイプが表示されます。

* *該当するオブジェクト*
+
グループルールに基づいてグループに含まれているストレージオブジェクトの数が表示されます。





== [グループアクション]タブ

[グループアクション]タブには、グループに対して定義したグループアクションの名前とタイプが表示されます。グループ操作の追加、編集、削除、順序変更などのタスクを実行できます。このタブには、グループアクションが適用されるグループの名前も表示されます。



== コマンドボタン

* * 追加 * 。
+
アクションの追加（Add Action）ダイアログボックスが表示されます。このダイアログボックスでは、ストレージオブジェクトのグループに対してグループアクションを作成できます。たとえば、グループ内のストレージオブジェクトのしきい値レベルを設定できます。

* * 編集 * 。
+
アクションの編集ダイアログボックスが表示されます。このダイアログボックスでは、以前に設定したグループアクションを再設定できます。

* * 削除 *
+
選択したグループ操作を削除します。

* *リオーダ*
+
ReorderGroupActionsタイアロクホツクスを表示して、グループアクションの順序を変更します。





== リストビュー

リストビューには、Unified Managerサーバでグループに対して作成したグループ操作が表形式で表示されます。列のフィルタを使用して、表示するデータをカスタマイズできます。

* *ランク*
+
グループ内のストレージオブジェクトに適用されるグループアクションの順序が表示されます。

* * 名前 *
+
グループ操作の名前が表示されます。

* *関連付けられたグループ*
+
グループ操作が定義されているグループの名前が表示されます。

* *アクションタイプ*
+
グループ内のストレージオブジェクトで実行できるグループ操作のタイプが表示されます。

+
グループに対して同じ操作タイプのグループ操作を複数作成することはできません。たとえば、あるグループに対してボリュームしきい値を設定するグループ操作を作成した場合、ただし、同じグループに対してボリュームしきい値を変更する別のグループ操作を作成することはできません。

* * 概要 *
+
グループ操作の概要 が表示されます。


