---
permalink: online-help/reference-edit-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 既存の保護関係を編集して、最大転送速度、保護ポリシー、保護スケジュールを変更することができます。 
---
= 関係の編集ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の保護関係を編集して、最大転送速度、保護ポリシー、保護スケジュールを変更することができます。



== 宛先情報

* * デスティネーションクラスタ *
+
選択したデスティネーションクラスタの名前です。

* * デスティネーション SVM *
+
選択した SVM の名前

* * 関係設定 *
+
保護関係で使用する最大転送速度、 SnapMirror ポリシー、およびスケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でベースラインデータを転送する最大速度を指定します。選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力してから、 KBps （ 1 秒あたりのキロバイト数）、 MBps （ 1 秒あたりのメガバイト数）、 GBps （ 1 秒あたりのギガバイト数）、 TBps （ 1 秒あたりのテラバイト数）のいずれかの単位を選択できます。最大転送速度は 1KBps~4TBps の範囲で指定する必要があります。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。この設定は、プライマリクラスタとセカンダリクラスタが同じ場合は無効になります。

** SnapMirror ポリシー
+
関係の ONTAP SnapMirror ポリシーを指定します。デフォルトは DPDefault です。

** ポリシーの作成
+
SnapMirror ポリシーの作成ダイアログボックスが開きます。このダイアログボックスで、新しい SnapMirror ポリシーを作成して使用できます。

** SnapMirror スケジュール
+
関係の ONTAP SnapMirror ポリシーを指定します。スケジュールは、「 None 」、「 5min 」、「 8hour 」、「 daily 」、「 hourly 」、 毎週、デフォルトは「 None 」で、関係にスケジュールが関連付けられません。スケジュールが設定されていない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールを作成します
+
スケジュールの作成ダイアログボックスが開きます。このダイアログボックスで、新しい SnapMirror スケジュールを作成できます。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して、 Configure Protection ダイアログボックスを閉じます。

* * 送信 *
+
選択内容を適用して、 [ 関係の編集 ] ダイアログボックスを閉じます。


