---
permalink: online-help/reference-remote-authentication-page.html 
sidebar: sidebar 
keywords:  
summary: Remote Authentication ページでは、 Unified Manager Web UI にログインするリモートユーザを認証できるように、 Unified Manager と認証サーバの通信を設定することができます。 
---
= Remote Authentication ページの略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Remote Authentication ページでは、 Unified Manager Web UI にログインするリモートユーザを認証できるように、 Unified Manager と認証サーバの通信を設定することができます。

OnCommand 管理者またはストレージ管理者のロールが必要です。

[ リモート認証を有効にする ] チェックボックスをオンにすると、認証サーバーを使用してリモート認証を有効にできます。

* * 認証サービス *
+
Active Directory や OpenLDAP などのディレクトリサービスプロバイダでユーザを認証するように管理サーバを設定するか、または独自の認証メカニズムを指定できます。認証サービスは、リモート認証を有効にした場合にのみ指定できます。

+
** * Active Directory *
+
*** 管理者の名前
+
認証サーバの管理者名を指定します。

*** パスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバでのリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名がou@domain.comの場合、ベース識別名はになります `cn=ou,dc=domain,dc=com`。

*** ネストされたグループの検索を無効化
+
ネストされたグループの検索を有効にするか無効にするかを指定します。デフォルトでは、このオプションは無効になっています。Active Directory を使用する場合は、ネストされたグループのサポートを無効にすることで認証を高速化できます。

*** セキュアな接続を使用します
+
認証サーバとの通信に使用する認証サービスを指定します。



** * OpenLDAP *
+
*** バインド識別名
+
認証サーバでリモートユーザを検出する際にベース識別名とともに使用されるバインド識別名を指定します。

*** バインドパスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバでのリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名がou@domain.comの場合、ベース識別名はになります `cn=ou,dc=domain,dc=com`。

*** セキュアな接続を使用します
+
LDAPS 認証サーバとの通信に使用されるセキュアな LDAP を指定します。



** * その他 *
+
*** バインド識別名
+
設定した認証サーバでリモートユーザを検出する際にベース識別名とともに使用されるバインド識別名を指定します。

*** バインドパスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバでのリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名がou@domain.comの場合、ベース識別名はになります `cn=ou,dc=domain,dc=com`。

*** プロトコルバージョン
+
認証サーバでサポートされる Lightweight Directory Access Protocol （ LDAP ）のバージョンを指定します。プロトコルのバージョンを自動的に検出するか、バージョン 2 または 3 に設定するかを指定できます。

*** ユーザー名属性
+
管理サーバによって認証されるユーザログイン名を含む認証サーバ内の属性の名前を指定します。

*** グループメンバーシップ属性
+
ユーザの認証サーバで指定されている属性と値に基づいて管理サーバのグループメンバーシップをリモートユーザに割り当てる値を指定します。

*** UGID
+
リモートユーザが GroupOfUniqueNames オブジェクトのメンバーとして認証サーバに含まれている場合は、このオプションを使用して、 GroupOfUniqueNames オブジェクトで指定されている属性を基に管理サーバのグループメンバーシップをリモートユーザに割り当てることができます。

*** ネストされたグループの検索を無効化
+
ネストされたグループの検索を有効にするか無効にするかを指定します。デフォルトでは、このオプションは無効になっています。Active Directory を使用する場合は、ネストされたグループのサポートを無効にすることで認証を高速化できます。

*** メンバー
+
認証サーバがグループの個々のメンバーに関する情報を格納するために使用する属性の名前を指定します。

*** ユーザオブジェクトクラス
+
リモート認証サーバ内のユーザのオブジェクトクラスを指定します。

*** グループオブジェクトクラス
+
リモート認証サーバ内のすべてのグループのオブジェクトクラスを指定します。

*** セキュアな接続を使用します
+
認証サーバとの通信に使用する認証サービスを指定します。





+
[NOTE]
====
認証サービスを変更する場合は、既存の認証サーバをすべて削除してから新しい認証サーバを追加してください。

====




== Authentication Servers 領域

Authentication Servers 領域には、管理サーバがリモートユーザの検索および認証のために通信する認証サーバが表示されます。リモートのユーザまたはグループのクレデンシャルは、認証サーバで管理されます。

* * コマンドボタン *
+
認証サーバを追加、編集、または削除できます。

+
** 追加（ Add ）
+
認証サーバを追加できます。

+
追加する認証サーバがハイアベイラビリティペアを構成している（同じデータベースを使用している）場合は、パートナーの認証サーバも追加できます。これにより、いずれかの認証サーバにアクセスできない場合でも管理サーバはパートナーと通信できます。

** 編集
+
選択した認証サーバの設定を編集できます。

** 削除
+
選択した認証サーバを削除します。



* * 名前または IP アドレス *
+
管理サーバでユーザの認証に使用される認証サーバのホスト名または IP アドレスが表示されます。

* * ポート *
+
認証サーバのポート番号が表示されます。

* * 認証のテスト *
+
このボタンでは、リモートのユーザまたはグループを認証することで認証サーバの設定を検証します。

+
テストの際にユーザ名のみを指定すると、管理サーバは認証サーバでリモートユーザを検索しますが、ユーザの認証は行いません。ユーザ名とパスワードを指定すると、管理サーバはリモートユーザの検索と認証を行います。

+
リモート認証が無効になっている場合は、認証をテストできません。


