---
permalink: online-help/reference-create-snapvault-policy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Create SnapVault Policy ダイアログボックスでは、 SnapVault 転送の優先度を設定するポリシーを作成できます。ポリシーを使用することで、プライマリからセカンダリボリュームへの転送効率を最大化できます。 
---
= Create SnapVault Policy ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create SnapVault Policy ダイアログボックスでは、 SnapVault 転送の優先度を設定するポリシーを作成できます。ポリシーを使用することで、プライマリからセカンダリボリュームへの転送効率を最大化できます。

* * デスティネーションクラスタ *
+
[ 保護の構成 ] ダイアログ・ボックスの [ 保護の構成 ] タブで選択 SnapVault したクラスタの名前

* * デスティネーション SVM *
+
保護の設定ダイアログボックスの SnapVault タブで選択した SVM の名前。

* * ポリシー名 *
+
新しいポリシーに指定する名前。ポリシー名には、 A~Z 、 a~z 、 0~9 、ピリオド（ . ）、ハイフン（ - ）、 とアンダースコア (_)

* * 転送優先順位 *
+
転送を実行する優先順位。標準または低を選択できます。転送の優先順位として「標準」を指定したポリシーを使用する関係の転送は、「低」を指定したポリシーを使用する関係の転送の前に実行されます。デフォルト設定は Normal です。

* * コメント *
+
オプションのフィールド。 SnapVault ポリシーに関するコメントを 255 文字以内で追加できます。

* * アクセス時間を無視 *
+
アクセス時間だけが変更されたファイルを差分転送で無視するかどうかを指定します。

* * レプリケーションラベル *
+
ONTAP で選択された Snapshot コピーに関連付けられているルールを表形式で示します。この Snapshot コピーのポリシーには特定のレプリケーションラベルが指定されています。次の情報とアクションも利用できます。

+
** コマンドボタン
+
各コマンドボタンを使用して次の操作を実行できます。

+
*** 追加（ Add ）
+
Snapshot コピーラベルと保持数を作成できます。

*** 保持数を編集
+
既存の Snapshot コピーラベルの保持数を変更できます。保持数は 1~251 の数値にする必要があります。すべてのルールのすべての保持数の合計は 251 個以下でなければなりません。

*** 削除
+
既存の Snapshot コピーラベルを削除できます。



** Snapshot コピーラベル
+
Snapshot コピーラベルが表示されます。同じローカル Snapshot コピーポリシーを使用する 1 つ以上のボリュームを選択すると、ポリシー内の各ラベルのエントリが表示されます。2 つ以上のローカル Snapshot コピーポリシーを使用する複数のボリュームを選択すると、すべてのポリシーのすべてのラベルがテーブルに表示されます

** スケジュール
+
各 Snapshot コピーラベルに関連付けられているスケジュールが表示されます。ラベルに複数のスケジュールが関連付けられている場合は、そのラベルのスケジュールがカンマで区切ったリストに表示されます。同じラベルでスケジュールが異なる複数のボリュームを選択すると、スケジュールには「 Various 」と表示され、選択したボリュームに複数のスケジュールが関連付けられていることが示されます。

** デスティネーションの保持数
+
SnapVault セカンダリに保持されている、指定したラベルを持つ Snapshot コピーの数が表示されます。複数のスケジュールを使用するラベルの保持数として、各ラベルとスケジュールのペアの保持数の合計が表示されます。2 つ以上のローカル Snapshot コピーポリシーを使用する複数のボリュームを選択した場合、保持数は空になります。




