---
permalink: online-help/reference-capacity-all-volumes-view.html 
sidebar: sidebar 
keywords:  
summary: ケンシヨウセイ/ホリユウムノヨウリヨウトシヨウシヨウキヨウヘエシヲシヨウシテクラスタナイノホリユウムノヨウリヨウトシヨウキヨウニカンスルシヨウホウヲヒヨウシこの情報を使用すると、容量のリスクの可能性を把握したり、ボリュームの設定済みの容量、使用容量、未使用容量を確認したりできます。また、この情報から、重複排除やシンプロビジョニングなどのスペース削減機能を有効にするかどうかを判断できます。 
---
= ケンセンセイ/ホリユウムノヨウリヨウトシヨウシヨウキヨウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ケンシヨウセイ/ホリユウムノヨウリヨウトシヨウシヨウキヨウヘエシヲシヨウシテクラスタナイノホリユウムノヨウリヨウトシヨウキヨウニカンスルシヨウホウヲヒヨウシこの情報を使用すると、容量のリスクの可能性を把握したり、ボリュームの設定済みの容量、使用容量、未使用容量を確認したりできます。また、この情報から、重複排除やシンプロビジョニングなどのスペース削減機能を有効にするかどうかを判断できます。

監視しているすべてのボリュームの詳細をカンマ区切り値でエクスポートするには、* Export *ボタンを使用します (`.csv`)ファイル。

* * クラスタ *
+
クラスタ名。

* * SVM *
+
ボリュームが含まれているStorage Virtual Machine（SVM）の名前。

* * 音量 *
+
ボリューム名。

* *合計データ容量*
+
ボリューム内の合計データ容量（使用容量と使用可能容量を足したもの）。

* *使用済みデータ容量*
+
ボリューム内の使用済みデータ容量。

* *使用済みデータ%*
+
ボリューム内の使用済みデータの割合。

* *使用可能なデータ容量*
+
ボリューム内の使用可能なデータ容量。

* *使用可能なデータ%*
+
ボリューム内の使用可能なデータ容量の割合。

* *日次増加率
+
ボリュームでの24時間ごとの増加率。

* *フルまでの日数*
+
ボリュームの容量がフルに達するまでの推定日数。

* *スペースがフルのしきい値%*
+
ボリュームがフルであるとみなす使用済みスペースの割合。

* *スペースがほぼフルのしきい値%*
+
ボリュームがほぼフルであるとみなす使用済みスペースの割合。

* *増加率しきい値
+
ボリュームの増加率が正常であるとみなす割合。このしきい値を超えると、「ボリュームの増加率-異常」イベントが生成されます。

* *増加率係数しきい値*
+
ボリュームの増加率の標準偏差に適用される係数。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

* *フルまでの日数しきい値*
+
容量がフルに達するまでの残り日数。

* * Snapshotオーバーフロー%*
+
Snapshotコピーで使用されているデータスペースの割合。

* * Snapshotリザーブの使用容量*
+
ボリュームでSnapshotコピーに使用されているスペースの量。

* * Snapshotリザーブの使用率
+
ボリュームでSnapshotコピーに使用されているスペースの量の割合。

* * Snapshotリザーブの使用可能容量*
+
ボリュームでSnapshotコピーに使用可能なスペースの量。

* * Snapshotリザーブの使用可能率
+
ボリュームでSnapshotコピーに使用可能なスペースの量の割合。

* * Snapshotリザーブの合計容量*
+
ボリューム内のSnapshotコピーの合計容量が表示されます。

* *「Snapshotコピーリザーブがフル」しきい値を超えています
+
Snapshotコピー用にリザーブされたスペースがフルであるとみなす割合。

* * Snapshotコピー数のしきい値*
+
ボリュームのSnapshotコピーが多すぎるとみなす数。

* *「Snapshotコピーのフルまでの日数」しきい値*
+
Snapshotコピー用にリザーブされたスペースがフルに達するまでの残り日数。

* * inodeの数*
+
ボリューム内のinodeの数。

* * inode使用率
+
ボリュームで使用されているinodeスペースの割合。

* * inodeがフルのしきい値%*
+
ボリュームのinodeがすべて使用されているとみなす割合。

* * inodeがほぼフルのしきい値%*
+
ボリュームのinodeがほぼ使用されているとみなす割合。

* *クォータコミット容量*
+
ボリューム内のクォータ用にリザーブされているスペース。

* *クォータオーバーコミット容量*
+
「ボリュームクォータがオーバーコミット」イベントが生成される基準となるクォータ用のスペースの使用量。

* *クォータがオーバーコミットのしきい値%*
+
ボリュームのクォータ用のスペースがオーバーコミットされているとみなす割合。

* *クォータがほぼオーバーコミットのしきい値%*
+
ボリュームのクォータ用のスペースがほぼオーバーコミットされているとみなす割合。

* * Snapshotの自動削除*
+
Snapshotコピーの自動削除が有効か無効か。

* * 重複排除 *
+
ボリュームで重複排除が有効か無効か。

* *重複排除によるスペース削減*
+
重複排除を使用して削減されたボリュームのスペース。

* * 圧縮 *
+
ボリュームで圧縮が有効か無効か。

* *圧縮スペースの節約*
+
圧縮を使用して削減されたボリュームのスペース。

* *キャッシングポリシー*
+
選択したボリュームに関連付けられているキャッシングポリシー。

+
このポリシーは、Flash Poolのキャッシングがボリュームに対して実行される方法に関する情報を提供します。キャッシングポリシーの詳細については、健全性/ボリュームインベントリページを参照してください。

* *キャッシュの保持優先度*
+
キャッシュされたプールの保持に使用される優先度。

* * シンプロビジョニング *
+
選択したボリュームにスペースギャランティが設定されているかどうか。有効な値は「はい」と「いいえ」です

* * 自動拡張 *
+
スペースが不足したときにボリュームのサイズが自動的に拡張されるかどうか。

* * スペース保証 *
+
ボリュームに関連付けられているストレージギャランティオプション。

* *保護の役割*
+
ボリュームに設定されている保護の役割。

* * 状態 *
+
エクスポートされるボリュームの状態。

* * SnapLock タイプ *
+
ボリュームがSnapLock ボリュームかSnapLockなしのボリュームか。

* * SnapLock 有効期限*
+
SnapLock の有効期限。

* * 階層化ポリシー *
+
ボリュームに対して設定されている階層化ポリシー。FabricPool対応アグリゲートに導入した場合のみ有効です。


