---
permalink: online-help/reference-edit-aggregate-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: アグリゲートの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「Aggregate Full」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。 
---
= EditAggregateThresholdsタイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「Aggregate Full」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。

OnCommand 管理者またはストレージ管理者のロールが必要です。

Edit Aggregate Thresholdsダイアログボックスでは、選択したアグリゲートに適用されるアグリゲートレベルのしきい値を設定できます。アグリゲートレベルのしきい値を設定すると、それらの値がグローバルレベルのしきい値よりも優先されます。アグリゲートレベルでは、容量、増加率、およびSnapshotコピーについてのしきい値を設定できます。これらの設定が行われていない場合は、グローバルしきい値の値が適用されます。

[NOTE]
====
ノードのルートアグリゲートにはしきい値の値は適用されません。

====


== 容量領域

容量領域では、アグリゲートの容量について、次のしきい値条件を設定できます。

* *スペースがほぼフル*
+
アグリゲートがほぼフルであるとみなす割合を示します。指定したしきい値の値に対応するアグリゲートのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *スペースがフル*
+
アグリゲートがフルであるとみなす割合を示します。指定したしきい値の値に対応するアグリゲートのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *ほぼオーバーコミット*
+
アグリゲートがほぼオーバーコミットされているとみなす割合を示します。

* *オーバーコミット*
+
アグリゲートがオーバーコミットされているとみなす割合を示します。

* *フルまでの日数*
+
アグリゲートの容量がフルに達するまでの残り日数を示します。





== 成長領域

Growth領域では、アグリゲートの増加率について、次のしきい値条件を設定できます。

* *増加率*
+
アグリゲートの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「アグリゲートの増加率-異常」イベントが生成されます。

* *増加率係数*
+
アグリゲートの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「アグリゲートの増加率が異常」イベントが生成されます。

+
アグリゲートが増加率の変化による影響を受けやすい場合は、増加率係数の値を小さくします。

+
[NOTE]
====
グローバルしきい値レベルでアグリゲートの増加率係数を変更した場合、グローバルしきい値レベルのボリュームの増加率係数にも変更が適用されます。

====




== Snapshotコピー領域

Snapshotコピー領域では、Snapshotリザーブについて、次のしきい値条件を設定できます。

* * Snapshotリザーブがフル*
+
アグリゲートのSnapshotコピー用にリザーブされたスペースがすべて使用されているとみなす割合を示します。

+
このしきい値の値はスライダを使用して設定することもできます。





== コマンドボタン

選択したアグリゲートについて、各コマンドボタンを使用して次のタスクを実行できます。

* *デフォルトに戻します*
+
アグリゲートレベルのしきい値の値をグローバルな値に戻すことができます。

* * 保存 *
+
すべてのしきい値設定を保存します。

* *保存して閉じる*
+
すべてのしきい値の設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
しきい値の設定に対する変更内容を破棄してダイアログボックスを閉じます。


