---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: ダッシュボード/概要ページには、クラスタ、アグリゲート、Storage Virtual Machine（SVM）などのストレージオブジェクトの健全性がグラフで表示されます。ストレージオブジェクトは、生成されたイベントに基づいて、可用性、容量、パフォーマンスに関するイベントについては「健全性」、「リスクあり」、または「インシデントあり」、保護に関するイベントについては「健全性」、「警告」、または「エラー」に分類されます。 
---
= [ダッシュボード/概要]ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボード/概要ページには、クラスタ、アグリゲート、Storage Virtual Machine（SVM）などのストレージオブジェクトの健全性がグラフで表示されます。ストレージオブジェクトは、生成されたイベントに基づいて、可用性、容量、パフォーマンスに関するイベントについては「健全性」、「リスクあり」、または「インシデントあり」、保護に関するイベントについては「健全性」、「警告」、または「エラー」に分類されます。



== 「Cluster Not Reachable」バーが表示さ

クラスタに到達できない場合、Unified Managerの各ページの上部のバーに詳細が表示されます。このペインは、すべてのクラスタに到達できる場合は表示されません。

このペインに表示される情報は、F5キーを押すとリフレッシュできます。これにより、現在到達できないクラスタに関する最新の情報が表示されます。たとえば、「クラスタに到達できません」イベントが削除された場合やイベントの状態が「廃止」になった場合は、ペインをリフレッシュするとイベントに関する情報が削除されます。

到達不能なクラスタに関する詳細情報を表示するには、 * Details * ボタンをクリックします。この操作により、Eventsインベントリページが開きます。このバーを閉じた場合は、Unified Managerに再度ログインしたときにのみ表示されます。



== 概要エリア

* *可用性ペイン*
+
Unified Managerで監視されるクラスタ、アグリゲート、およびSVMの可用性に関する情報が表示されます。ストレージオブジェクトは、「健全性」、「リスクあり」、または「インシデントあり」のいずれかに分類されます。たとえば、スペアディスクが不足しているクラスタのステータスは「リスクあり」と表示されます。

+
このペインには、カテゴリごとのストレージオブジェクトの数も表示されます。いずれかのオブジェクトの総数をクリックすると、そのオブジェクトのページが表示されます。たとえば、クラスタの総数をクリックすると、健全性/クラスタのインベントリページが表示されます。列の上部にある数値をクリックすると、Eventsインベントリページが表示されます。

* *容量ペイン*
+
Unified Managerで監視されるアグリゲートとSVMの容量に関する情報が表示されます。ストレージオブジェクトは、「健全性」、「リスクあり」、または「インシデントあり」のいずれかに分類されます。たとえば、使用済み容量がフルのしきい値に達しているアグリゲートのステータスは「リスクあり」と表示されます。

+
このペインには、カテゴリごとのストレージオブジェクトの数も表示されます。

* *パフォーマンス・ペイン*
+
Unified Managerで監視されるクラスタ、SVM、ボリュームのパフォーマンスに関する情報が表示されます。ストレージオブジェクトは、生成されたパフォーマンス関連のインシデントに基づいて、「健常性」、「リスクあり」、「インシデントあり」のいずれかに分類されます。たとえば、ワークロードに対するI/O応答時間が最大しきい値に達しているボリュームのステータスは「インシデントあり」と表示されます。

+
このペインには、Unified Managerで監視されるクラスタ、SVM、およびボリュームの総数も表示されます。いずれかのオブジェクトの総数をクリックすると、そのオブジェクトのページが表示されます。たとえば、クラスタの総数をクリックすると、Performance/ClusterInventoryページが表示されます。

* *保護ペイン*
+
Unified Managerで監視される保護関係に関する情報が表示されます。保護関係は、「健全性」、「警告」、または「エラー」のいずれかに分類されます。たとえば、遅延時間が遅延警告のしきい値を超えている関係は「警告」と表示されます。

+
このペインには、保護カテゴリごとのストレージオブジェクトの総数も表示されます。LAGステータス、非同期バックアップ、非同期ミラー、または同期のカテゴリのリンクをクリックすると、保護/ボリューム関係ページにフィルタリングされたオブジェクトのリストが表示されます。


