---
permalink: online-help/reference-cluster-health-fields.html 
sidebar: sidebar 
keywords:  
summary: Cluster Inventoryレポートには、クラスタコンポーネントで使用可能なリソースに関する情報が表示されます。これは、リソースの不足が原因で発生する可能性のあるリスクを把握するためです。 
---
= クラスタインベントリレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cluster Inventoryレポートには、クラスタコンポーネントで使用可能なリソースに関する情報が表示されます。これは、リソースの不足が原因で発生する可能性のあるリスクを把握するためです。



== クラスタインベントリレポートの表形式ビュー

* * クラスタ *
+
クラスタの名前が表示されます。

* * HAペア*
+
2つのノードを構成して得られるHAペア値が表示されます。

* * ノード *
+
ノードの名前が表示されます。

* * モデル *
+
モデルの名前を表示します。

* * OS バージョン *
+
使用されているONTAP のバージョンが表示されます。

* *オールフラッシュによる最適化*
+
ソリッドステートドライブ（SSD）だけをサポートするようにノードが設定されているかどうかが表示されます。

* * シリアル番号 *
+
ノードのシリアル番号が表示されます。

* * ファームウェアバージョン *
+
ノードのファームウェアバージョンが表示されます。

* * SVM数*
+
クラスタに含まれているSVMの数が表示されます。

* * FCポート数*
+
ノードに含まれているFCポートの数が表示されます。

* * FCoEポート数*
+
ノードに含まれているFCoEポートの数が表示されます。

* *イーサネットポート数*
+
ノードに含まれているイーサネットポートの数が表示されます。

* *フラッシュカード数*
+
データセンター内のノードに取り付けられているフラッシュカードの数が表示されます。これにより、潜在的な問題を監視できます。

* *フラッシュカードサイズ（GB）*
+
ノードに取り付けられているフラッシュカードのサイズが表示されます。

* *ディスクシェルフ数*
+
ノードに含まれているディスクシェルフの数が表示されます。

* * ディスク数 *
+
ノード内のディスクの数が表示されます。


