---
permalink: online-help/reference-constituent-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Performance / constituentVolume Informationページを使用して、FlexGroup 構成要素ボリュームの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= パフォーマンス/コンスティチュエントボリューム情報ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance / constituentVolume Informationページを使用して、FlexGroup 構成要素ボリュームの物理属性と論理属性のリストを表示します。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== コンスティチュエントボリュームの属性

* * タイプ *
+
コンスティチュエントのタイプ。読み取り/書き込み（RW）とデータ保護（DP）のいずれかです。

* * スタイル *
+
ボリュームの形式。FlexGroup ボリュームのコンスティチュエントボリュームです。

* * クラスタ *
+
このFlexGroup コンスティチュエントボリュームが属するクラスタの名前。名前をクリックすると、Performance/ClusterExplorerヘエシにクラスタの詳細を表示できます。

* * 集計 *
+
このFlexGroup コンスティチュエントボリュームが配置されているアグリゲートの名前。名前をクリックすると、Performance/AggregateExplorerヘエシにアグリゲートの詳細を表示できます。

* * FlexGroup *
+
このコンスティチュエントが属するFlexGroup ボリュームの名前。名前をクリックすると、パフォーマンス/ FlexGroupエクスプローラのページにFlexGroup ボリュームの詳細を表示できます。

* * Storage Virtual Machine *
+
このFlexGroup コンスティチュエントボリュームが属するSVMの名前。名前をクリックすると、Performance/SVMExplorerヘエシにSVMの詳細を表示できます。

* * 階層化ポリシー *
+
ボリュームに対して設定されている階層化ポリシー。このポリシーは、ボリュームがFabricPool アグリゲートに導入されている場合にのみ適用されます。使用可能なポリシーは次のとおりです。

+
** なしこのボリュームのデータは常に高パフォーマンス階層に残ります。
** Snapshotのみ：Snapshotデータのみがクラウド階層に自動的に移動されます。それ以外のデータはすべて高パフォーマンス階層に残ります。
** バックアップ：データ保護ボリュームで、転送されたユーザデータは最初はすべてクラウド階層に配置されますが、その後、クライアントによるホットデータの読み取りが多い原因 を高パフォーマンス階層に移動できます。
** 自動：このボリューム上のデータは、ONTAP がデータが「ホット」または「コールド」と判断した場合に、パフォーマンス階層とクラウド階層の間で自動的に移動されます。


* * RAID タイプ *
+
このコンスティチュエントが配置されているアグリゲートで使用されている冗長性タイプ。有効なタイプは次のとおり

+
** RAID 0
** RAID 4
** RAID-DP
** RAID-TEC


* *容量（空き/合計）*
+
コンスティチュエントで使用可能な合計ストレージ容量（GB）、および現在使用可能なストレージ容量。


