---
permalink: online-help/reference-manage-report-schedules-dialog-box-um-6-2.html 
sidebar: sidebar 
keywords:  
summary: ［レポートスケジュールの管理］ダイアログボックスでは、既存のレポートスケジュールを表示、変更、または削除したり、レポートの新しいスケジュールを追加したりできます。 
---
= ManageReportSchedulesタイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
［レポートスケジュールの管理］ダイアログボックスでは、既存のレポートスケジュールを表示、変更、または削除したり、レポートの新しいスケジュールを追加したりできます。



== プロパティ

レポートの既存のスケジュールを選択するか、新しいスケジュールを作成できます。レポートスケジュールは、表示、変更、または削除することができます。

* *左ペイン*
+
** * スケジュール名 *
+
既存のスケジュールが表示されます。任意のスケジュールをクリックすると、右側のペインにスケジュールの詳細が表示されます。初回ログイン時は、既存のスケジュールがありません。

** *スケジュールの追加*
+
右側のペインに新しいスケジュールフォームが表示されます。新しいスケジュールを追加できます。



* *右ペイン*
+
** * スケジュール名 *
+
スケジュール名が表示されます。

** *受信者の電子メールアドレス*
+
レポートの送信先であるユーザのEメールアドレスが表示されます。複数のEメールアドレスをカンマで区切って入力できます。

** *レポート形式*
+
レポートを表示する形式が表示されます。PDFオプションがデフォルトのレポート形式として選択されます。XHTML形式が選択されている場合は、Eメールで送信されたレポートをサポート対象のWebブラウザで開きます。

** * 周波数 *
+
レポートがスケジュールされる頻度が表示されます。

** *レポートカテゴリ*
+
レポートカテゴリグループを表示します。リストからレポートカテゴリを選択すると、そのレポートカテゴリに属するレポートが[Available Reports]カラムに表示されます。

** *使用可能なレポート*
+
選択したレポートカテゴリに属するレポートのみを表示します。

** *選択されたレポート*
+
スケジュールの適用対象として選択したレポートが表示されます。必要なレポートは、Available Reports列から選択できます。少なくとも1つのレポートを選択する必要があります







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* *スケジュールの追加*
+
新しいスケジュールを追加できます。

* *スケジュールの削除*
+
現在表示されているスケジュールを削除できます。新しいスケジュールを作成する場合は、このボタンを使用できません。

* * 保存 *
+
表示中、変更中、または追加中のスケジュールを保存します。

* *保存して閉じる*
+
表示中、変更中、または追加中のスケジュールを保存し、Manage Report Schedules（レポートスケジュールの管理）ダイアログボックスを閉じます。

* * キャンセル *
+
スケジュールを保存するためのメッセージが表示されている状態で、[レポートスケジュールの管理]ダイアログボックスを閉じます。


