---
permalink: online-help/reference-cluster-events.html 
sidebar: sidebar 
keywords:  
summary: クラスタイベントは、クラスタのステータスに関する情報を提供します。これにより、クラスタの潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= クラスタイベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタイベントは、クラスタのステータスに関する情報を提供します。これにより、クラスタの潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：可用性

アスタリスク（ * ）は、 Unified Manager イベントに変換された EMS イベントを示します。

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタにスペアディスクなし（ Document EvtDisksNoSpares ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタに到達できません（ Document EvtClusterUnreachable ）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー



 a| 
クラスタの監視に失敗しました（ Document EvtClusterMonitoringFailed ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタの FabricPool ライセンス容量制限を超過（ Document EvtExternalCapacityTierSpaceFull ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - 開始 * （ nvmetfGracePeriodStart ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - アクティブ * （ nvmetfGracePeriodActive ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - 終了 * （ nvmetfGracePeriodExpired ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
オブジェクトのメンテナンス時間が開始されました (objectMaintenanceWindowStarted)
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
オブジェクトのメンテナンス時間が終了しました（ objectMaintenanceWindowEnded ）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
MetroCluster のスペアディスクが残されている（ ocument EvtSpareDiskLeftBehind ）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー



 a| 
MetroCluster の自動計画外スイッチオーバーが無効（ Document EvtMccAutomaticUnplannedSwitchOverDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告

|===


== 影響範囲：容量

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタのクラウド階層の計画（ clusterCloudTierPlaningWarning ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
FabricPool スペースがほぼフル*
 a| 
リスク
 a| 
クラスタ
 a| 
エラー

|===


== 影響範囲：構成

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ノードが追加されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
ノードが削除されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
クラスタが削除されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
クラスタの追加に失敗（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
エラー



 a| 
クラスタ名が変更されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
緊急の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
重大な EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
アラートの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
エラー



 a| 
エラーの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
警告の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
デバッグの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
通知の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
情報の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告

|===
ONTAP EMS イベントは、 Unified Manager イベントの 3 つの重大度レベルに分類されます。

|===
| Unified Manager イベントの重大度レベル | ONTAP EMS イベントの重大度レベル 


 a| 
重要
 a| 
緊急

重要



 a| 
エラー
 a| 
アラート



 a| 
警告
 a| 
エラー

警告

デバッグ

注意

情報

|===


== 影響範囲：パフォーマンス

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタ IOPS の重大しきい値を超過（ドキュメント ClusterIopsIncident ）
 a| 
インシデント
 a| 
クラスタ
 a| 
重要



 a| 
クラスタ IOPS の警告しきい値を超過（ドキュメントクラスタ警告）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタMBpsの重大しきい値を超過（ドキュメントクラスタMbpsIncident）
 a| 
インシデント
 a| 
クラスタ
 a| 
重要



 a| 
クラスタMBpsの警告しきい値を超過（ドキュメントクラスタのMbpsWarning）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ動的しきい値を超過（ DocumentClusterDynamicEventWarning ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告

|===