---
permalink: online-help/reference-edit-volume-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: ボリュームの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「ボリュームがフル」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。 
---
= ボリュームしきい値の編集ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームの容量に関するイベントが生成されたときに通知を送信するようにアラートを設定し、イベントに対処することができます。たとえば、「ボリュームがフル」しきい値を指定して、指定した期間が経過しても状態が続く場合に通知を送信するようにアラートを設定できます。

OnCommand 管理者またはストレージ管理者のロールが必要です。

ボリュームしきい値の編集ダイアログボックスでは、選択したボリュームに適用されるボリュームレベルのしきい値を設定できます。ボリュームレベルでしきい値を設定すると、それらの値がグループレベルのしきい値やグローバルレベルのしきい値よりも優先されます。

ボリュームレベルでは、容量、Snapshotコピー、qtreeクォータ、増加率、およびinodeについてのしきい値を設定できます。ボリュームしきい値タイプのグループ操作が設定されている場合、ボリュームレベルで設定されていない項目にはグループ操作のしきい値の値が使用されます。ボリュームしきい値タイプのグループ操作が設定されていない場合は、ボリュームしきい値の編集ダイアログボックスの設定されていない領域にグローバルしきい値の値が使用されます。



== 容量領域

容量領域では、ボリュームの容量について、次のしきい値条件を設定できます。

* *スペースがほぼフル*
+
ボリュームがほぼフルであるとみなす割合を示します。指定したしきい値の値に対応するボリュームのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *スペースがフル*
+
ボリュームがフルであるとみなす割合を示します。指定したしきい値の値に対応するボリュームのサイズも表示されます。

+
このしきい値の値はスライダを使用して設定することもできます。

* *フルまでの日数*
+
ボリュームの容量がフルに達するまでの残り日数を示します。





== Snapshot コピー

Snapshotコピー領域では、ボリューム内のSnapshotコピーについて、次のしきい値条件を設定できます。

* * Snapshotリザーブがフル*
+
Snapshotコピー用にリザーブされたスペースがフルであるとみなす割合を示します。

* *フルまでの日数*
+
Snapshotコピー用にリザーブされたスペースがフルに達するまでの残り日数を示します。

* *カウント*
+
ボリュームのSnapshotコピーが多すぎるとみなす数を示します。





== qtreeクォータ領域

qtreeクォータ領域では、選択したボリュームについて、qtreeクォータについて、次のしきい値条件を設定できます。

* *ほぼオーバーコミット*
+
ボリュームのqtreeクォータがほぼオーバーコミットされているとみなす割合を示します。

* *オーバーコミット*
+
ボリュームのqtreeクォータがオーバーコミットされているとみなす割合を示します。





== 成長領域

[Growth（増加率）]領域では、ボリュームの増加率について、次のしきい値条件を設定できます。

* *増加率*
+
ボリュームの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「ボリュームの増加率-異常」イベントが生成されます。

* *増加率係数*
+
ボリュームの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

+
ボリュームが増加率の変化による影響を受けやすい場合は、増加率係数の値を小さくします。

+
[NOTE]
====
グローバルしきい値レベルでボリュームの増加率係数を変更した場合、グローバルしきい値レベルのアグリゲートの増加率係数にも変更が適用されます。

====




== inode領域

inode領域では、inodeについて、次のしきい値条件を設定できます。

* *ほぼフル*
+
ボリュームのinodeがほぼ使用されているとみなす割合を示します。

+
このしきい値の値はスライダを使用して設定することもできます。

* *フル*
+
ボリュームのinodeがすべて使用されているとみなす割合を示します。

+
このしきい値の値はスライダを使用して設定することもできます。





== コマンドボタン

選択したボリュームについて、各コマンドボタンを使用して次のタスクを実行できます。

* *デフォルトに戻します*
+
しきい値を次のいずれかの値に戻すことができます。

+
** グループの値：ボリュームがグループに属しており、そのグループでボリュームしきい値タイプのアクションが設定されている場合。
** グローバルな値：ボリュームがいずれのグループにも属していないか、属しているグループでボリュームしきい値タイプのアクションが設定されていない場合。


* * 保存 *
+
すべてのしきい値設定を保存します。

* *保存して閉じる*
+
すべてのしきい値の設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
しきい値の設定に対する変更内容を破棄してダイアログボックスを閉じます。


