---
permalink: online-help/reference-resynchronize-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 再同期ダイアログボックスを使用すると、以前に解除した SnapMirror 関係や SnapVault 関係のデータを、デスティネーションが読み書き可能ボリュームになったあとに再同期できます。再同期は、必要な共通の Snapshot コピーがソースボリュームで削除されたために SnapMirror や SnapVault の更新が失敗する場合にも実行することがあります。 
---
= Resynchronize タイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
再同期ダイアログボックスを使用すると、以前に解除した SnapMirror 関係や SnapVault 関係のデータを、デスティネーションが読み書き可能ボリュームになったあとに再同期できます。再同期は、必要な共通の Snapshot コピーがソースボリュームで削除されたために SnapMirror や SnapVault の更新が失敗する場合にも実行することがあります。



== 再同期オプションタブ

再同期オプションタブでは、再同期する保護関係の転送の優先順位と最大転送速度を設定できます。

* * 転送優先順位 *
+
転送を実行する優先順位。標準または低を選択できます。関係のポリシーで転送の優先順位「 Normal 」が指定されている場合、その関係は転送の優先順位「 Low 」が指定された関係より先に実行されます。

* * 最大転送速度 *
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力してから、 KBps （ 1 秒あたりのキロバイト数）、 MBps （ 1 秒あたりのメガバイト数）、 GBps （ 1 秒あたりのギガバイト数）、 TBps （ 1 秒あたりのテラバイト数）のいずれかの単位を選択できます。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。ただし、ONTAP 8.2を実行し、かつプライマリクラスタとセカンダリクラスタが同じである場合、この設定は無効になります。





== ソース Snapshot コピータブ

ソース Snapshot コピータブには、ベースライン転送に使用されるソース Snapshot コピーに関する次の情報が表示されます。

* * ソースボリューム *
+
対応するソースボリュームの名前が表示されます。

* * デスティネーションボリューム *
+
選択したデスティネーションボリュームの名前が表示されます。

* * ソースタイプ *
+
ボリュームタイプが表示されます。読み取り / 書き込みまたはデータ保護のいずれかです。

* * Snapshot コピー *
+
データ転送に使用される Snapshot コピーが表示されます。Snapshot コピーの値をクリックすると、 Select Source Snapshot Copy ダイアログボックスが表示されます。このダイアログボックスでは、保護関係のタイプおよび実行中の処理に応じて、転送する特定の Snapshot コピーを選択できます。





== コマンドボタン

* * 送信 *
+
再同期プロセスを開始して、再同期ダイアログボックスを閉じます。

* * キャンセル *
+
選択内容をキャンセルして再同期ダイアログボックスを閉じます。


