---
permalink: online-help/reference-reverse-resync-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: ソースボリュームが機能しなくなったために保護関係を解除して、デスティネーションを読み書き可能なボリュームにした場合は、逆再同期によって関係の方向を反転させて、デスティネーションを新しいソースにし、ソースを新しいデスティネーションにすることができます。 
---
= ReverseResync タイアロクホツクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースボリュームが機能しなくなったために保護関係を解除して、デスティネーションを読み書き可能なボリュームにした場合は、逆再同期によって関係の方向を反転させて、デスティネーションを新しいソースにし、ソースを新しいデスティネーションにすることができます。

災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換、ソースの更新、および関係の再確立を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続することができます。逆再同期処理を実行すると、共通の Snapshot コピーのデータよりも新しいソース上のデータは削除されます。



== 逆再同期前

逆再同期処理を実行する前の関係のソースとデスティネーションが表示されます。

* * ソースボリューム *
+
逆再同期処理を実行する前のソースボリュームの名前と場所。

* * デスティネーションボリューム *
+
逆再同期処理を実行する前のデスティネーションボリュームの名前と場所。





== 逆再同期後

リザーブ再同期処理を実行したあとの関係のソースとデスティネーションが表示されます。

* * ソースボリューム *
+
逆再同期処理を実行したあとのソースボリュームの名前と場所。

* * デスティネーションボリューム *
+
逆再同期処理を実行したあとのデスティネーションボリュームの名前と場所。





== コマンドボタン

各コマンドボタンを使用して次の操作を実行できます。

* * 送信 *
+
逆再同期プロセスを開始します。

* * キャンセル *
+
逆再同期処理を開始せずに逆再同期ダイアログボックスを閉じます。


