---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: ボリュームの容量と使用状況レポートでは、クラスタ内のボリュームの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。また、このレポートを使用して、重複排除やシンプロビジョニングなどのスペース削減機能を有効にするかどうかを判断できます。 
---
= ボリュームの容量と使用状況レポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームの容量と使用状況レポートでは、クラスタ内のボリュームの容量と使用状況に関する情報を確認できます。この情報を使用すると、容量のリスクの可能性を把握したり、アグリゲートの設定済みの容量、使用容量、未使用容量を確認したりできます。また、このレポートを使用して、重複排除やシンプロビジョニングなどのスペース削減機能を有効にするかどうかを判断できます。



== ボリュームの容量と使用状況レポートの表形式ビュー

* * クラスタ *
+
クラスタ名が表示されます。

* * Storage Virtual Machine *
+
ボリュームが含まれているStorage Virtual Machine（SVM）の名前が表示されます。

* * 音量 *
+
ボリューム名が表示されます。

* *合計データ容量*
+
ボリューム内の合計データ容量（使用容量と使用可能容量を足したもの）が表示されます。

* *使用済みデータ容量*
+
ボリューム内の使用済みデータ容量が表示されます。

* *使用済みデータ%*
+
ボリューム内の使用済みデータの割合が表示されます。

* *使用可能なデータ容量*
+
ボリューム内の使用可能なデータ容量が表示されます。

* *使用可能なデータ%*
+
ボリューム内の使用可能なデータ容量の割合が表示されます。

* *日次増加率
+
ボリュームでの24時間ごとの増加率が表示されます。

* *フルまでの日数*
+
ボリュームの容量がフルに達するまでの推定日数が表示されます。

* *スペースがフルのしきい値%*
+
フルであるとみなすボリュームに対する制限を示します。

* *スペースがほぼフルのしきい値%*
+
ほぼフルであるとみなすボリュームに対する制限を示します。

* *増加率しきい値
+
アグリゲートの増加率が正常であるとみなす割合を示します。このしきい値を超えると、「アグリゲートの増加率-異常」イベントが生成されます。

* *増加率係数しきい値*
+
ボリュームの増加率の標準偏差に適用される係数を示します。増加率が係数適用後の標準偏差を超えると、「ボリュームの増加率が異常」イベントが生成されます。

* *フルまでの日数しきい値*
+
容量がフルに達するまでの残り日数を示します。

* * Snapshotオーバーフロー%*
+
Snapshotコピーで使用されているデータスペースの割合が表示されます。

* * Snapshotリザーブの使用容量*
+
ボリュームでSnapshotコピーに使用されているスペースの量が表示されます。

* * Snapshotリザーブの使用率
+
ボリュームでSnapshotコピーに使用されているスペースの量の割合が表示されます。

* * Snapshotリザーブの使用可能容量*
+
ボリュームでSnapshotコピーに使用可能なスペースの量が表示されます。

* * Snapshotリザーブの使用可能率
+
ボリュームでSnapshotコピーに使用可能なスペースの量の割合が表示されます。

* * Snapshotリザーブの合計容量*
+
ボリューム内のSnapshotコピーの合計容量が表示されます。

* *「Snapshotコピーリザーブがフル」しきい値を超えています
+
Snapshotコピー用にリザーブされたスペースがフルであるとみなす割合を示します。

* * Snapshotコピー数のしきい値*
+
ボリュームのSnapshotコピーが多すぎるとみなす数を示します。

* *「Snapshotコピーのフルまでの日数」しきい値*
+
Snapshotコピー用にリザーブされたスペースがフルに達するまでの残り日数を示します。

* * inodeの数*
+
ボリューム内のinodeの数が表示されます。

* * inode使用率
+
ボリュームで使用されているinodeスペースの割合を示します。

* *「inodeがフル」しきい値*
+
ボリュームのinodeがすべて使用されているとみなす割合を示します。

* *「inodeがほぼフル」しきい値*
+
ボリュームのinodeがほぼ使用されているとみなす割合を示します。

* *クォータコミット容量*
+
ボリュームでリザーブされているスペースが表示されます。

* *クォータオーバーコミット容量*
+
「ボリュームクォータがオーバーコミット」イベントが生成される基準となるスペースの使用量が表示されます。

* *クォータがオーバーコミットのしきい値%*
+
ボリュームがほぼオーバーコミットされているとみなす割合を示します。

* *クォータがほぼオーバーコミットのしきい値%*
+
ボリュームスペースがほぼオーバーコミットされているとみなす割合を示します。

* * Snapshotの自動削除*
+
Snapshotコピーの自動削除が有効か無効かが表示されます。

* * 重複排除 *
+
ボリュームで重複排除処理が有効か無効かが表示されます。

* *重複排除によるスペース削減*
+
重複排除を使用して削減されたボリュームのスペースが表示されます。

* * 圧縮 *
+
ボリュームで圧縮が有効か無効かが表示されます。

* *圧縮スペースの節約*
+
圧縮を使用して削減されたボリュームのスペースが表示されます。

* *キャッシングポリシー*
+
選択したボリュームに関連付けられているキャッシングポリシーが表示されます。このポリシーは、Flash Poolのキャッシングがボリュームに対して実行される方法に関する情報を提供します。キャッシングポリシーの詳細については、健全性/ボリュームインベントリページを参照してください。

* *キャッシュの保持優先度*
+
キャッシュされたプールの保持に使用される優先度が表示されます。

* * シンプロビジョニング *
+
選択したボリュームにスペースギャランティが設定されているかどうかが表示されます。有効な値は「はい」と「いいえ」です

* * 自動拡張 *
+
スペースが不足したときにFlexVol ボリュームのサイズが自動で拡張されるかどうかが表示されます。

* * スペース保証 *
+
FlexVol ボリュームがアグリゲートから空きブロックを削除するタイミングを制御する設定が表示されます。

* * 状態 *
+
エクスポートされるボリュームの状態が表示されます。

* * SnapLock タイプ *
+
ボリュームがSnapLock ボリュームかSnapLockなしのボリュームかを示します。

* *有効期限*
+
SnapLock の有効期限。

* * 階層化ポリシー *
+
このボリュームがFabricPool対応アグリゲートに導入されている場合は、ボリュームに対して設定されている階層化ポリシーが表示されます。


