---
permalink: online-help/reference-email-notification-format-page.html 
sidebar: sidebar 
keywords:  
summary: '[電子メール通知形式]ページには、クォータ関連の問題 がある場合にユーザーまたはユーザーグループに送信される電子メールのルールが表示されます\（ソフトリミットを超過しているか、ハードリミットに達しています\）。' 
---
= Email Notification Format ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 電子メール通知形式 ] ページには、クォータ関連の問題が存在するときにユーザーまたはユーザーグループに送信される電子メールのルールが表示されます ( ソフトリミットを超過しているか、ハードリミットに達しています ) 。

E メール通知は、次のユーザまたはユーザグループのクォータイベントが生成された場合にのみ送信されます。 ユーザクォータまたはグループクォータのディスクスペースがソフトリミットを超過、ユーザクォータまたはグループクォータのファイル数がソフトリミットを超過、ユーザクォータまたはグループクォータのディスクスペースがハードリミットに達した、またはユーザクォータまたはグループクォータのファイル数がハードリミットを超過しました。

* * から *
+
E メールの送信元の E メールアドレスが表示されます。このアドレスは変更が可能です。デフォルトでは、これはセットアップ/通知ページで指定された電子メールアドレスです。

* * 件名 *
+
通知メールの件名が表示されます。

* * 電子メールの詳細 *
+
通知 E メールのテキストが表示されます。テキストは要件に基づいて変更できます。たとえば、クォータ属性に関する情報を指定して、キーワードの数を減らすことができます。ただし、キーワードは変更しないでください。

+
有効なキーワードは次のとおりです。

+
** $event_name
+
E メール通知の原因となったイベントの名前を示します。

** $QUOTA_TARGET
+
クォータが適用される qtree またはボリュームを示します。

** $QUOTA_OF_Used% です
+
ディスクのハードリミット、ディスクのソフトリミット、ファイルのハードリミット、またはファイルのソフトリミットについて、ユーザまたはユーザグループが使用している割合を示します。

** $ QUOTA_limit です
+
ユーザまたはユーザグループがリミットに達して次のいずれかのイベントが生成されたディスクのハードリミットまたはファイルのハードリミットを示します。

+
*** ユーザクォータまたはグループクォータのディスクスペースがハードリミットに達しました
*** ユーザクォータまたはグループクォータのディスクスペースがソフトリミットに達しました
*** ユーザクォータまたはグループクォータのファイル数がハードリミットに達しました
*** ユーザクォータまたはグループクォータのファイル数がソフトリミットに達しました


** $QUOTA_Used の値
+
ユーザまたはユーザグループが使用しているディスクスペースと作成したファイルの数を示します。

** $QUOTA_USER を選択してください
+
ユーザまたはユーザグループの名前を示します。







== コマンドボタン

各コマンドボタンを使用して、 E メール通知の形式に対する変更内容をプレビュー、保存、キャンセルできます。

* * プレビュー *
+
通知メールのプレビューが表示されます。

* * 工場出荷時のデフォルトに戻します *
+
通知の形式を工場出荷時のデフォルトに戻すことができます。

* * 保存 *
+
通知の形式に対する変更内容を保存します。


