---
permalink: online-help/reference-storage-vm-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Performance/SVMInformationヘエシを使用すると、SVMの設定済み属性のリストを表示できます。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。 
---
= Performance/SVMInformationヘエシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance/SVMInformationヘエシを使用すると、SVMの設定済み属性のリストを表示できます。この情報は、パフォーマンス関連の疑問を解決するのに役立ちます。



== SVM属性

* * IP アドレス *
+
定義されている場合、SVM管理LIFのIPv4またはIPv6アドレスです。

* * IPspace *
+
このSVMが配置されているIPspace。

* *ドメイン名*
+
SVM管理LIFの完全修飾ドメイン名（FQDN）。

* *サービスタイプ*
+
SVMのタイプ。

+
指定できる値は、クラスタ全体の管理SVMには「Admin」、IPspaceにはクラスタレベルの通信には「System」、データ提供用SVMには「Data」、ノード管理SVMには「Node」です。

* *容量（空き/合計）*
+
SVMで使用可能な合計ストレージ容量、GB、および現在使用可能なストレージ容量。

* * クラスタ *
+
SVMが属するクラスタの名前。名前をクリックすると、Performance/ClusterExplorerヘエシにクラスタの詳細を表示できます。

* * ボリューム *
+
SVM内のボリュームの数。数をクリックすると、パフォーマンス/ボリュームインベントリページにボリュームを表示できます。

* * LIF *
+
SVMが使用できるLIFの数。数をクリックすると、ハフオオマンス/LIFインヘントリヘエシにLIFを表示できます。

* *データLIF *
+
SVMが使用できるデータLIFの数とタイプ。

* *使用できるボリュームタイプ*
+
SVMで作成できるボリュームのタイプ。

+
SVMには、1つ以上のFlexVol またはFlexGroup ボリュームを含めることができます。FlexGroup タイプはONTAP 9.1以降を使用している場合に使用できます。

+
[NOTE]
====
Unified Managerのパフォーマンスページでは、Infinite Volumeがサポートされません。

====
* * 許可されたプロトコル *
+
このSVMで処理できるすべてのプロトコルのリスト。使用可能なプロトコルは、FC / FCoE、iSCSI、HTTP、NDMP、NVMeです。NFS、CIFSです。

* * ポートセット *
+
FCPまたはiSCSIプロトコル用に定義されている場合、このSVMに割り当てられているポートセット。


