---
permalink: online-help/task-reversing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。 
---
= ケンセンセイ/ホリユウムノシヨウサイヘエシテノホコカンケイノハンテン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。
* SnapVault 関係は使用できません。
* 保護関係がすでに存在している必要があります。
* 保護関係が解除されている必要があります。
* ソースとデスティネーションの両方がオンラインになっている必要があります。
* ソースが別のデータ保護ボリュームのデスティネーションになっていることはできません。




== このタスクについて

* このタスクを実行すると、共通の Snapshot コピーのデータよりも新しいソースのデータは削除されます。
* 逆再同期した関係に対して作成されるポリシーとスケジュールは、元の保護関係と同じになります。
+
ポリシーとスケジュールが存在しない場合は作成されます。





== 手順

. 健常性/ボリューム*の詳細ページの*保護*タブで、ソースとデスティネーションを反転するSnapMirror関係をトポロジから探して右クリックします。
. メニューから * 逆再同期 * を選択します。
+
逆再同期（ Reverse Resync ）ダイアログボックスが表示されます。

. 逆再同期を実行する関係が * 逆再同期 * （ Reverse Resync * ）ダイアログボックスに表示されていることを確認し、 * 送信 * （ Submit * ）をクリックします。
+
逆再同期（Reverse Resync）ダイアログボックスが閉じ、健常性/ボリュームの詳細ページの上部にジョブのリンクが表示されます。

. 各逆再同期ジョブのステータスを追跡するには、*健常性/ボリューム*の詳細ページで*ジョブの表示*をクリックします。
+
フィルタリングされたジョブのリストが表示されます。

. ブラウザの戻る矢印をクリックして、*正常性/ボリューム*の詳細ページに戻ります。
+
すべてのタスクが正常に完了すれば逆再同期処理は終了です。


