---
permalink: online-help/task-disabling-unwanted-events.html 
sidebar: sidebar 
keywords:  
summary: デフォルトでは、すべてのイベントが有効になっています。環境で重要でないイベントについては、グローバルに無効にして通知が生成されないようにすることができます。無効にしたイベントの通知を再開するときは、該当するイベントを有効にすることができます。 
---
= イベントの無効化または有効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、すべてのイベントが有効になっています。環境で重要でないイベントについては、グローバルに無効にして通知が生成されないようにすることができます。無効にしたイベントの通知を再開するときは、該当するイベントを有効にすることができます。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== このタスクについて

イベントを無効にすると、システムで以前に生成されたイベントは「廃止」とマークされ、それらのイベントに設定されたアラートはトリガーされなくなります。無効にしたイベントを有効にすると、それらのイベントの通知の生成が次の監視サイクルから開始されます。

オブジェクトのイベント（など）を無効にした場合 `vol offline` イベント）をクリックし、あとでイベントを有効にした場合、イベントが無効な状態のときにオフラインになったオブジェクトに対しては新しいイベントは生成されません。Unified Managerでは、イベントを再度有効にしたあとにオブジェクトの状態に変更があった場合にのみ新規のイベントが生成されます。



== 手順

. 左側のナビゲーションペインで、* Configuration *>* Manage Events *をクリックします。
. [*Configuration/Manage Events*]ページで、次のいずれかのオプションを選択してイベントを無効または有効にします。
+
|===
| 状況 | 操作 


 a| 
イベントを無効にします
 a| 
.. [*Disable*] をクリックします。
.. [ イベントの無効化 ] ダイアログボックスで、イベントの重大度を選択します。
.. [Matching Events] カラムで、イベントの重大度に基づいてディセーブルにするイベントを選択し、右矢印をクリックして [Disable Events] カラムに移動します。
.. [ 保存して閉じる ] をクリックします。
.. 無効にしたイベントが[構成/イベントの管理]ページのリストビューに表示されることを確認します。




 a| 
イベントを有効にします
 a| 
.. 有効にするイベントのチェックボックスを選択します。
.. [*Enable*] をクリックします。


|===

