---
permalink: online-help/task-analyzing-a-performance-incident-on-a-remote-cluster-in-a-metrocluster-configuration.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager を使用して、 MetroCluster 構成のリモートクラスタの動的なパフォーマンスイベントを分析できます。この分析によって、リモートクラスタのイベントがそのパートナークラスタのイベントの原因となったかどうかを判断できます。 
---
= MetroCluster 構成のリモートクラスタの動的なパフォーマンスイベントを分析する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を使用して、 MetroCluster 構成のリモートクラスタの動的なパフォーマンスイベントを分析できます。この分析によって、リモートクラスタのイベントがそのパートナークラスタのイベントの原因となったかどうかを判断できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* MetroCluster 構成内のローカルクラスタのパフォーマンスイベントを分析し、イベント検出時刻を確認しておく必要があります。
* パフォーマンスイベントに関連したローカルクラスタとそのパートナークラスタの健常性を確認し、パートナークラスタの名前を確認しておく必要があります。




== 手順

. パートナークラスタを監視している Unified Manager インスタンスにログインします。
. 左側のナビゲーションペインで、 * Events * をクリックしてイベントリストを表示します。
. * 時間範囲 * セレクタから * 過去 1 時間 * を選択し、 * 範囲の適用 * をクリックします。
. [*Filtering*selector] で、左ドロップダウンメニューから [*Cluster*] を選択し、テキストフィールドにパートナークラスタの名前を入力して、 [*Apply Filter*] をクリックします。
+
選択したクラスタのイベントが過去 1 時間ない場合は、パートナーでイベントが検出されたときにこのクラスタではパフォーマンスの問題は発生していません。

. 選択したクラスタで過去 1 時間にイベントが検出された場合は、イベントの検出時刻をローカルクラスタのイベントの検出時刻と比較します。
+
これらのイベントにデータ処理コンポーネントの競合を引き起こしている Bully ワークロードが関係している場合は、これらの Bully ワークロードが原因でローカルクラスタのイベントが発生した可能性があります。イベントをクリックして分析し、推奨される解決方法をイベントの詳細ページで確認できます。

+
これらのイベントに Bully ワークロードが関係していない場合、ローカルクラスタのパフォーマンスイベントの原因を作成していません。


