---
permalink: online-help/task-excluding-disaster-recovery-destination-volumes-from-generating-alerts.html 
sidebar: sidebar 
keywords:  
summary: ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。 
---
= ディザスタリカバリのデスティネーションボリュームをアラート生成対象から除外します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== このタスクについて

ディザスタリカバリのデスティネーションボリュームに対するアラートを無効にするには、デスティネーション SVM の名前を含むボリュームを除外します。これは、ボリュームイベントの識別子にSVM名とボリューム名の両方が「<svm_name> ：<volume_name> 」の形式で含まれているためです。

次の例は、プライマリSVM「vs1」上のボリューム「vol1」に対するアラートを作成し、SVM「vs1-dr」上の同じ名前のボリュームにはアラートが生成されないようにする方法を示しています。

[Add Alert] ダイアログボックスで、次の手順を実行します。



== 手順

. [* 名前 *] をクリックして、アラートの名前と概要を入力します。
. [* リソース（ * Resources ） ] をクリックし、 [* 含める * （ * Include * ） ] タブを選択します。
+
.. ドロップダウンリストから「* Volume *」を選択し、と入力します `vol1` 名前に「*」が含まれているボリュームを表示するには、「*」フィールドを使用します。
.. *を選択します<<All Volumes whose name contains 'vol1'>>*使用可能なリソース*領域から、*選択したリソース*領域に移動します。


. [*除外*]タブを選択し、[*ボリューム*]を選択して、と入力します `vs1-dr` [名前に*が含まれています]フィールドで、[*追加]をクリックします。
+
これにより、SVM「vs1-dr」上のボリューム「vol1」に対してアラートが生成されることはなくなります。

. 「 * Events 」をクリックして、ボリュームに適用するイベントを選択します。
. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMP トラップを発行してスクリプトを実行するために、このページの他のオプションを設定し、 * Save * をクリックします。

