---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: データをカンマ区切り値（.csv）ファイルとしてエクスポートして、レポートの作成に使用することができます。たとえば、未解決の重大イベントが10件ある場合、イベントインベントリページからデータをエクスポートしてレポートを作成し、それらのイベントに対処することができます。 
---
= レポートを作成するためのCSVファイルへのデータのエクスポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データをカンマ区切り値でエクスポートできます (`.csv`）を作成し、エクスポートしたデータを使用してレポートを作成します。たとえば、未解決の重大イベントが10件ある場合、イベントインベントリページからデータをエクスポートしてレポートを作成し、それらのイベントに対処することができます。



== 作業を開始する前に

オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。



== このタスクについて

にデータをエクスポートできます `.csv` ファイルを生成します。

エクスポート機能は、Infinite Volumeのコンスティチュエントについてはサポートされていません。-コンスティチュエントの詳細をにエクスポートすることはできません `.csv` ファイル。



== 手順

. 次のいずれかを実行します。
+
|===
| エクスポートする項目 | 手順 


 a| 
イベントの詳細
 a| 
[*イベント*]をクリックします。



 a| 
ストレージオブジェクトのインベントリの詳細
 a| 
左側のナビゲーションメニューから* Health *または* Performance *をクリックし、ストレージオブジェクトを選択します。



 a| 
ストレージ容量と保護の履歴の詳細
 a| 
* Health *>* Aggregates * or * Health *>* Volumes *をクリックし、1つのアグリゲートまたはボリュームを選択します。



 a| 
SVMのqtreeまたはNFSエクスポートの情報
 a| 
* Health *>* SVM*をクリックし、1つのSVMを選択して、* Qtrees *または* nfs exports *タブを選択します。



 a| 
上位 10 個のストレージオブジェクトのパフォーマンスの詳細
 a| 
[*パフォーマンス*>]、[*クラスタ*]の順にクリックし、クラスタを選択して、[*パフォーマンス上位*]タブを選択します。次に、ストレージオブジェクトとパフォーマンスカウンタを選択します。

|===
. [* Export*（エクスポート）]ボタンをクリックします。
. [* Export to CSV*（CSVにエクスポート）]をクリックして、エクスポート要求を確認します。
+
パフォーマンス上位タブおよびSVMの詳細ページから、表示している単一のクラスタの統計のレポートをダウンロードするか、データセンター内のすべてのクラスタの統計のレポートをダウンロードするかを選択できます。

+
ファイルがダウンロードされます。

. を開きます `.csv` ファイルを適切なアプリケーションに保存します。

