---
permalink: online-help/task-editing-user-and-group-quota-email-addresses.html 
sidebar: sidebar 
keywords:  
summary: 'クラスタ、Storage Virtual Machine（SVM）、ボリューム、qtree、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、Eメールアドレスを変更することができます。[ ユーザクォータおよびグループクォータの E メールアドレスを生成するルール ] ダイアログボックスで指定したルールによって生成された E メールアドレスを上書きする場合は、 E メールアドレスを変更できます。' 
---
= ユーザクォータおよびグループクォータの E メールアドレスの編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、 qtree 、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、 E メールアドレスを変更することができます。[ ユーザクォータおよびグループクォータの E メールアドレスを生成するルール ] ダイアログボックスで指定したルールによって生成された E メールアドレスを上書きする場合は、 E メールアドレスを変更できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* を確認しておく必要があります xref:reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.adoc[ルールの作成に関するガイドライン]。




== このタスクについて

E メールアドレスを編集すると、ユーザクォータおよびグループクォータの E メールアドレスを生成するルールがクォータに適用されなくなります。指定したルールに従って生成された E メールアドレスに通知を送信するには、 E メールアドレスを削除して変更を保存する必要があります。



== 手順

. 左側のナビゲーションペインで、* Health *>* SVM*をクリックします。
. *健常性/ Storage Virtual Machine *インベントリページでSVMを選択し、*ユーザクォータとグループクォータ*タブをクリックします。
. タブの行の下にある * 電子メールアドレスの編集 * をクリックします。
. [ 電子メールアドレスの編集 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 状況 | 作業 


 a| 
指定したルールに従って生成された E メールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドの電子メールアドレスを削除します。
.. [ 保存（ Save ） ] をクリックします。
.. F5 キーを押して E メールアドレスの編集ダイアログボックスをリロードし、ブラウザをリフレッシュします。指定したルールによって生成された E メールアドレスが ［ * E メールアドレス * ］ フィールドに表示されます。




 a| 
指定した E メールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドで電子メールアドレスを変更します。
.. [ 保存（ Save ） ] をクリックします。ユーザクォータおよびグループクォータの E メールアドレスを生成するルールがクォータに適用されなくなります。


|===

