---
permalink: online-help/task-initializing-or-updating-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 保護/ボリューム関係ページでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化された関係でスケジュールされていない増分更新を手動で実行してすぐに転送する場合は、関係を更新できます。 
---
= Protection / Volume Relationshipsページから保護関係を初期化または更新しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護/ボリューム関係ページでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化された関係でスケジュールされていない増分更新を手動で実行してすぐに転送する場合は、関係を更新できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* OnCommand Workflow Automation のセットアップが完了している必要があります。




== 手順

. [保護/ボリューム関係*]ページで、ボリュームを右クリックし、更新または初期化する関係を持つボリュームを1つ以上選択して、ツールバーの[*初期化/更新*]をクリックします。
+
Initialing/Update ダイアログボックスが表示されます。

. 転送オプション * タブで、転送の優先順位と最大転送速度を選択します。
. [ * ソース Snapshot コピー * ] をクリックし、 [ * Snapshot コピー * ] 列で [ * デフォルト * ] をクリックします。
+
Select Source Snapshot Copy （ソース Snapshot コピーの選択）ダイアログボックスが表示されます。

. デフォルトの Snapshot コピーを転送するのではなく、既存の Snapshot コピーを指定する場合は、 * 既存の Snapshot コピー * をクリックし、リストから Snapshot コピーを選択します。
. [Submit （送信） ] をクリックします。
+
Initialing/Update ダイアログボックスに戻ります。

. 初期化または更新するソースを複数選択した場合は、既存の Snapshot コピーを指定する次のソースに対して「 * Default * 」をクリックします。
. [Submit] をクリックして、初期化ジョブまたは更新ジョブを開始します。
+
初期化ジョブまたは更新ジョブが開始されると、保護/ボリューム関係ページに戻り、ページの上部にジョブのリンクが表示されます。

. *正常性/ボリューム*インベントリページで*ジョブの表示*をクリックして、各初期化ジョブまたは更新ジョブのステータスを追跡します。
+
フィルタリングされたジョブのリストが表示されます。

. 各ジョブをクリックすると詳細が表示されます。
. ブラウザの戻る*矢印をクリックして、「*保護/ボリュームの関係*」ページに戻ります。
+
すべてのタスクが正常に終了すれば初期化処理または更新処理は終了です。


