---
permalink: online-help/task-investigating-perceived-slow-response-time-for-a-workload.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerを使用して、クラスタでの処理がボリュームワークロードの応答時間低下（レイテンシ）の一因となったかどうかを判断できます。 
---
= ワークロードの応答時間低下の調査
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用すると、クラスタでの処理がボリュームワークロードの応答時間（レイテンシ）低下の一因となったかどうかを判断できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 分析するボリュームまたは関連するLUNの名前を特定しておく必要があります。
* Unified Managerで最低5日間のパフォーマンス統計がクラスタから収集されて分析されている必要があります。




== このタスクについて

イベントの詳細ページを表示している場合は、ボリュームの名前をクリックして、パフォーマンス/ボリュームの詳細ページに直接移動できます。



== 手順

. *検索*バーにボリュームの名前を入力します。
+
ボリュームの名前が検索結果に表示されます。

. ボリュームの名前をクリックします。
+
ボリュームがPerformance / Volume Detailsページに表示されます。

. 履歴データチャートで*5d*をクリックして、過去5日間の履歴データを表示します。
. IOPS *チャートを確認して、次の点を回答 に報告してください。
+
** アクティビティの急増はあるか。
** アクティビティの急減はあるか。
** 処理パターンの異常な変化はあるか。アクティビティの急増や急減がなく、この期間にクラスタ構成への変更がない場合、他のワークロードによるボリュームパフォーマンスへの影響はないと判断できます。


. [*Break down data by *]メニューの[*IOPS]で、[*** Reads/Writes/other]を選択します。
. [Submit （送信） ] をクリックします。
+
読み取り/書き込み/その他のチャートがIOPSチャートの下に表示されます。

. 読み取り/書き込み/その他*のグラフを確認して、ボリュームの読み取り/書き込み量の急増や急減がないか確認します。
+
読み取りや書き込みの急増または急減がない場合、クラスタのI/Oは正常に動作していると判断できます。パフォーマンスの問題は、ネットワークまたは接続されているクライアントで発生している可能性があります。


