---
permalink: online-help/task-responding-to-a-system-defined-node-resources-overutilized-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 1 つのノードが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、 Unified Manager でノードリソース過剰使用警告イベントが生成されます。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。 
---
= ノードリソース過剰使用パフォーマンスイベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つのノードが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、 Unified Manager でノードリソース過剰使用警告イベントが生成されます。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントがある必要があります。




== このタスクについて

Unified Manager では、パフォーマンス容量の使用率が 30 分以上にわたって 100% を超えているノードが見つかると、ノードリソース過剰使用ポリシーの違反とみなして警告イベントを生成します。

System Manager または ONTAP コマンドを使用して、このタイプのパフォーマンス問題を修正できます。これには次の作業が含まれます。

* QoS ポリシーを作成してシステムリソースを過剰に消費しているボリュームや LUN に適用する
* ワークロードが適用されているポリシーグループの QoS の最大スループット制限を小さくします
* 別のアグリゲートまたはノードにワークロードを移動する
* ノードにディスクを追加するか、高速 CPU とより多くの RAM を搭載したノードにアップグレードして、容量を増やす




== 手順

. イベントの詳細ページを表示して、イベントに関する情報を確認します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「 Perf 」というメッセージが表示されます。simplicity-02 の使用済み容量が 139% のため、警告イベントがトリガーされました。データ処理装置に潜在的なパフォーマンスの問題があります。」は、ノード simplicity-02 のパフォーマンス容量の使用率が高く、ノードのパフォーマンスに影響を及ぼしていることを示しています。

. システム診断 * セクションで、 3 つのグラフを確認します。 1 つはノードで使用されているパフォーマンス容量、 1 つは上位のワークロードで使用されている平均ストレージ IOPS 、もう 1 つは上位のワークロードで使用されているレイテンシです。これらのグラフを参考に、ノード上のレイテンシの原因であるワークロードを確認できます。
+
QoS ポリシーが適用されているワークロードと適用されていないワークロードを表示するには、 IOPS グラフにカーソルを合わせます。

. 「推奨される対処方法」セクションで、推奨される対処方法を確認し、ワークロードのレイテンシ増加を回避するために実行する必要がある対処方法を決定します。
+
必要に応じて、ヘルプ * ボタンをクリックして、パフォーマンスイベントの解決方法に関する推奨される操作の詳細を確認します。


