---
permalink: online-help/task-displaying-information-about-a-performance-event.html 
sidebar: sidebar 
keywords:  
summary: イベントインベントリページでは、Unified Managerで監視されているクラスタの新規および廃止状態のすべてのパフォーマンスイベントのリストを表示できます。この情報を表示することで、最も重大なイベントを特定し、詳細情報にドリルダウンしてイベントの原因を確認できます。 
---
= パフォーマンスイベントに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントインベントリページでは、Unified Managerで監視されているクラスタの新規および廃止状態のすべてのパフォーマンスイベントのリストを表示できます。この情報を表示することで、最も重大なイベントを特定し、詳細情報にドリルダウンしてイベントの原因を確認できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントがある必要があります。




== このタスクについて

イベントのリストは検出時刻でソートされ、最新のイベントが最初に表示されます。列ヘッダーをクリックすると、その列でイベントをソートできます。たとえば、 Status 列でソートして、重大度別にイベントを表示できます。特定のイベントまたは特定のタイプのイベントを検索する場合は、フィルタと検索を使用して、リストに表示するイベントを絞り込むことができます。

このページにはすべてのソースのイベントが表示されます。

* ユーザ定義のパフォーマンスしきい値ポリシー
* システム定義のパフォーマンスしきい値ポリシー
* 動的なパフォーマンスしきい値


[ イベントタイプ ] 列には、イベントのソースが一覧表示されます。イベントを選択すると、そのイベントに関する詳細をイベントの詳細ページで確認できます。



== 手順

. 左側のナビゲーションペインで、 * Events * （イベント * ）をクリックします。
. 分析するイベントを特定し、イベント名をクリックします。
+
イベントの詳細ページが表示されます。

+
[NOTE]
====
また、パフォーマンスエクスプローラのページでイベント名のリンクをクリックし、アラート E メールでイベントの詳細ページを表示することもできます。

====

