---
permalink: online-help/task-editing-template-based-rules.html 
sidebar: sidebar 
keywords:  
summary: ルールテンプレートを使用して作成されたルールは、［ルールの編集］ダイアログボックスで編集できます。ルールのディレクトリパス、ファイルタイプ、所有者などのプロパティを追加、変更、または削除できます。ルールの名前やルールに関連付けられているストレージクラスを変更することもできます。 
---
= テンプレートベースのルールを編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ルールテンプレートを使用して作成されたルールは、［ルールの編集］ダイアログボックスで編集できます。ルールのディレクトリパス、ファイルタイプ、所有者などのプロパティを追加、変更、または削除できます。ルールの名前やルールに関連付けられているストレージクラスを変更することもできます。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== 手順

. 左側のナビゲーションペインで、* Health *>* SVM*をクリックします。
. *ケンセンセイ/ Storage Virtual Machines *インヘントリヘエシで、適切なSVMを選択します。
. [*データポリシー*]をクリックします。
+
選択したInfinite Volumeを備えたSVMのデータポリシーに含まれるルールのリストが表示されます。

. 新しい条件または条件セットを含めるルールを選択します。
. [ 編集（ Edit ） ] をクリックします。
. ［*ルールの編集*］ダイアログボックスで、必要に応じてルールを編集します。
+
|===
| 状況 | 手順 


 a| 
新しいルールのプロパティを追加します
 a| 
[ 追加（ Add ） ] をクリックします。



 a| 
ルールのプロパティを削除します
 a| 
適切なルールのプロパティを選択して、*削除*をクリックします。



 a| 
ルールのプロパティを変更します
 a| 
該当するルールのプロパティをダブルクリックし、必要に応じて変更します。

|===
. [ 更新（ Update ） ] をクリックします。
. [*データポリシー*]タブでルールを展開して、変更がルールに適用されていることを確認します。
. データポリシーに対して行ったその他の変更をプレビューします。
. Activate *をクリックして、SVMのルールのプロパティへの変更をアクティブ化します。

