---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: ボリュームでデータバックアップを有効にして保護するために、健常性/ボリュームの詳細ページを使用してSnapVault 関係を作成することができます。 
---
= ケンセンセイ/ホリユウムノシヨウサイヘエシテノSnapVault ホコカンケイノサクセイ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームでデータバックアップを有効にして保護するために、健常性/ボリュームの詳細ページを使用してSnapVault 関係を作成することができます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* このタスクを実行するには、 Workflow Automation をセットアップしておく必要があります。




== このタスクについて

次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など




== 手順

. *正常性/ボリューム*の詳細ページの*保護*タブで、保護するボリュームをトポロジビューで右クリックします。
. メニューから * Protect * > * SnapVault * を選択します。
+
Configure Protection （保護の設定）ダイアログボックスが開きます。

. SnapVault * をクリックして、 * SnapVault * タブを表示し、セカンダリ・リソース情報を設定します。
. [ * 詳細設定 * ] をクリックして、必要に応じて重複排除、圧縮、自動拡張、およびスペースギャランティを設定し、 [ * 適用 * ] をクリックします。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
健常性とボリュームの詳細ページに戻ります。

. 「* Health / Volume * details」ページの上部にある保護設定ジョブのリンクをクリックします。
+
保護/ジョブの詳細ページが表示されます。

. 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
+
ジョブのタスクが完了すると、新しい関係が正常性/ボリュームの詳細ページのトポロジビューに表示されます。


