---
permalink: online-help/task-resynchronizing-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: Protection / Volume Relationshipsページで、ソースボリュームを機能しない状態にしたイベントからリカバリする場合や、現在のソースを別のボリュームに変更する場合に、関係を再同期できます。 
---
= Protection / Volume Relationshipsページから保護関係を再同期しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Protection / Volume Relationshipsページで、ソースボリュームを機能しない状態にしたイベントからリカバリする場合や、現在のソースを別のボリュームに変更する場合に、関係を再同期できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== 手順

. [保護/ボリューム関係*]ページで、休止した関係を持つ1つ以上のボリュームを選択し、ツールバーの[*再同期*]をクリックします。
+
再同期化ダイアログボックスが表示されます。

. [* Resynchronization Options] * タブで、転送の優先順位と最大転送速度を選択します。
. [ * ソース Snapshot コピー * ] をクリックし、 [ * Snapshot コピー * ] 列で [ * デフォルト * ] をクリックします。
+
Select Source Snapshot Copy （ソース Snapshot コピーの選択）ダイアログボックスが表示されます。

. デフォルトの Snapshot コピーを転送するのではなく、既存の Snapshot コピーを指定する場合は、 * 既存の Snapshot コピー * をクリックし、リストから Snapshot コピーを選択します。
. [Submit （送信） ] をクリックします。
+
再同期ダイアログボックスに戻ります。

. 再同期するソースを複数選択した場合は、既存の Snapshot コピーを指定する次のソースに対して * Default * をクリックします。
. Submit * をクリックして、再同期ジョブを開始します。
+
再同期ジョブが開始されると、保護/ボリューム関係ページに戻り、ページの上部にジョブのリンクが表示されます。

. 各再同期ジョブのステータスを追跡するには、「*保護/ボリューム関係*」ページで「*ジョブを表示」をクリックします。
+
フィルタリングされたジョブのリストが表示されます。

. ブラウザの戻る*矢印をクリックして、「*保護/ボリュームの関係*」ページに戻ります。
+
すべてのタスクが正常に終了すれば再同期処理は終了です。


