---
permalink: online-help/task-viewing-fabricpool-capacity-information.html 
sidebar: sidebar 
keywords:  
summary: クラスタ、アグリゲート、およびボリュームのFabricPool 容量情報は、健全性インベントリおよびそれらのオブジェクトの詳細ページで確認できます。アグリゲートの容量と使用状況レポートにFabricPool 情報を表示することもできます。 
---
= FabricPool の容量情報を表示しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ、アグリゲート、およびボリュームのFabricPool 容量情報は、健全性インベントリおよびそれらのオブジェクトの詳細ページで確認できます。アグリゲートの容量と使用状況レポートにFabricPool 情報を表示することもできます。



== このタスクについて

これらのページには、ローカルの高パフォーマンス階層とクラウド階層の使用可能容量、両方の階層で使用されている容量、クラウド階層に接続されているアグリゲート、 また、特定の情報をクラウド階層に移動することで FabricPool 機能を実装しているボリュームもあります。



== 手順

. 次のいずれかを実行します。
+
|===
| 容量の情報を表示するオブジェクト | 手順 


 a| 
クラスタ
 a| 
.. ケンセンセイ/クラスタインヘントリヘエシテクラスタヲクリックします。
.. [Health/Cluster details]ページで、[* Configuration*]タブをクリックします。
+
このクラスタが接続されているクラウド階層の名前が表示されます。





 a| 
アグリゲート
 a| 
.. Health/Aggregatesインベントリページで' TypeフィールドにFabricPool (SSD)'が表示されているアグリゲートをクリックします
.. 健全性/アグリゲートの詳細ページで、*容量*タブをクリックします。
+
合計容量に加え、クラウド階層の使用済みスペースと空きスペースが表示されます。

.. [ ディスク情報 ] タブをクリックします。
+
クラウド階層の名前と使用可能スペースが表示されます。

.. [* 構成 *] タブをクリックします。
+
クラウド階層の名前とオブジェクトストアに関するその他の詳細情報が表示されます。





 a| 
個のボリューム
 a| 
.. Health/Volumesインベントリページで、「階層化ポリシー」フィールドにポリシー名が表示されているボリュームをクリックします。
.. [稼働状態/ボリュームの詳細]ページで、[*構成*]タブをクリックします。
+
ボリュームに割り当てられている FabricPool 階層化ポリシーの名前が表示されます。



|===




== 完了後

FabricPool アグリゲートの詳細については、 ONTAP 9 ディスクとアグリゲートパワーガイドを参照してください。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ONTAP 9 ディスクとアグリゲートパワーガイド"]
