---
permalink: online-help/task-resuming-scheduled-transfers-on-a-quiesced-relationship.html 
sidebar: sidebar 
keywords:  
summary: 関係を休止してスケジュールされた転送の実行を停止したあと、再開を使用してスケジュールされた転送を再び有効にし、ソースボリュームまたはプライマリボリュームのデータを保護できます。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。 
---
= 休止中の関係のスケジュールされた転送をProtection / Volume Relationshipsページで再開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関係を休止してスケジュールされた転送の実行を停止したあと、* Resume *を使用してスケジュールされた転送を再び有効にし、ソースボリュームまたはプライマリボリュームのデータを保護することができます。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

転送を再開する休止中の関係を 10 個まで選択できます。



== 手順

. [*保護/ボリューム関係*]ページで、関係が休止中のボリュームを1つ以上選択し、ツールバーで[*再開]をクリックします。
. [* Resume * （続行） ] ダイアログボックスで、 [* Continue * （続行） ] をクリックします。
+
保護/ボリューム関係ページに戻ります。

. 関連するジョブタスクを表示してその進捗状況を追跡するには、*保護/ボリューム関係*ページの上部に表示されるジョブのリンクをクリックします。
. 次のいずれかを実行します。
+
** ジョブが1つしか表示されない場合は、Protection / Job Detailsページで* Refresh *をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** 複数のジョブが表示される場合は、
+
... Protection/Jobsページで、詳細を表示するジョブをクリックします。
... 保護/ジョブの詳細ページで、「*更新*」をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。ジョブが完了すると、次回のスケジュールされた転送の実行時にデータ転送が再開されます。





