---
permalink: online-help/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Unified Managerにクラスタを追加して監視することができます。たとえば、クラスタの健常性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性がある問題を特定して解決できるようにすることができます。 
---
= クラスタを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Unified Managerにクラスタを追加して監視することができます。たとえば、クラスタの健常性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性がある問題を特定して解決できるようにすることができます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* クラスタのホスト名またはクラスタ管理 IP アドレス（ IPv4 または IPv6 ）が必要です。
+
ホスト名を使用する場合は、クラスタ管理 LIF のクラスタ管理 IP アドレスに解決される必要があります。ノード管理 LIF を使用すると処理に失敗します。

* クラスタにアクセスするためのユーザ名とパスワードが必要です。
+
このアカウントには、アプリケーションアクセスが _ontapi 、 _ssh_ 、および _http_に 設定された _admin_role が必要です。

* クラスタで設定するプロトコルのタイプ（HTTPまたはHTTPS）とクラスタへの接続に使用するポート番号を確認しておく必要があります。
* Unified Manager サーバに十分なスペースが必要です。スペースの使用率が 90% を超えている場合、サーバにクラスタを追加することはできません。


[NOTE]
====
NAT / ファイアウォールの背後にあるクラスタは、 Unified Manager の NAT IP アドレスを使用して追加できます。接続された Workflow Automation または SnapProtect システムも NAT / ファイアウォールの背後に配置する必要があり、 SnapProtect API 呼び出しでは NAT IP アドレスを使用してクラスタを識別する必要があります。

====


== このタスクについて

* MetroCluster 構成では、各クラスタを個別に追加する必要があります。
* 1 つの Unified Manager インスタンスでサポートできるノードの数には上限があります。ノードの数がサポートされる最大数を超える環境を監視する必要がある場合は、 Unified Manager インスタンスを追加でインストールし、一部のクラスタを監視する必要があります。
* クラスタに 2 つ目のクラスタ管理 LIF を設定し、 Unified Manager の各インスタンスを別々の LIF を介して接続すれば、 1 つのクラスタを Unified Manager の 2 つのインスタンスで監視できます。




== 手順

. 左側のナビゲーションペインで、* Configuration *>* Cluster Data Sources *をクリックします。
. [*設定/クラスタデータソース*]ページで、[*追加]をクリックします。
. [Add Cluster*]ダイアログボックスで、必要に応じて値を指定し、[*Submit*]をクリックします。
. HTTPS を選択した場合は、次の手順を実行します。
+
.. [* Authorize Host * （ホストの認証 * ） ] ダイアログボックスで、 [* View Certificate * （証明書の表示） ] をクリックしてクラスタに関する証明書情報を表示します。
.. 「 * はい * 」をクリックします。
+
Unified Manager では、クラスタが最初に追加されたときにのみ証明書がチェックされます。Unified Manager では、 ONTAP に対する API 呼び出しごとには証明書がチェックされません。

+
証明書の期限が切れている新しいクラスタは追加できません。まずSSL証明書を更新してから、クラスタを追加する必要があります。







== 結果

新しいクラスタのオブジェクトがすべて検出されると（約15分後）、Unified Managerが過去15日間の履歴パフォーマンスデータの収集を開始します。これらの統計は、データの継続性収集機能を使用して収集されます。この機能では、クラスタが追加された直後から 2 週間分のクラスタのパフォーマンス情報を入手できます。データの継続性収集サイクルの完了後、デフォルトではクラスタのリアルタイムのパフォーマンスデータが 5 分ごとに収集されます。

[NOTE]
====
15 日分のパフォーマンスデータを収集すると CPU に負荷がかかるため、新しいクラスタを複数追加する場合は、データの継続性収集のポーリングが同時に多数のクラスタで実行されないように、時間差をつけて追加するようにしてください。また、データの継続性収集期間に Unified Manager を再起動すると、収集が停止し、その間のデータがパフォーマンスチャートに表示されません。

====
[TIP]
====
エラーメッセージが表示されてクラスタを追加できない場合は、次の問題がないかどうかを確認してください。

* 2 つのシステムのクロックが同期されておらず、 Unified Manager の HTTPS 証明書の開始日がクラスタの日付よりもあとの日付になっている。NTP などのサービスを使用してクロックを同期する必要があります。
* クラスタの EMS 通知の送信先が最大数に達しており、 Unified Manager のアドレスを追加できない。デフォルトでは、クラスタで定義できる EMS 通知の送信先は 20 個までです。


====