---
permalink: online-help/task-responding-to-a-system-defined-qos-policy-group-performance-event.html 
sidebar: sidebar 
keywords:  
summary: ワークロードのスループット（IOPS、IOPS/TB、またはMBps）が定義されているONTAP QoSポリシーの設定を超え、ワークロードのレイテンシに影響を及ぼしている場合、Unified ManagerでQoSポリシー警告イベントが生成されます。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。 
---
= QoS ポリシーグループパフォーマンスイベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードのスループット（ IOPS 、 IOPS/TB 、または MBps ）が定義されている ONTAP QoS ポリシーの設定を超え、ワークロードのレイテンシに影響を及ぼしている場合、 Unified Manager で QoS ポリシー警告イベントが生成されます。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 新規、確認済み、または廃止状態のパフォーマンスイベントが存在する必要があります。




== このタスクについて

Unified Manager では、定義されている QoS ポリシーの設定を超えるワークロードが過去 1 時間の各パフォーマンス収集期間で見つかった場合に、 QoS ポリシーの違反とみなして警告イベントを生成します。ワークロードのスループットが各収集期間に短時間だけ QoS のしきい値を超えることがありますが、 Unified Manager のグラフには収集期間中の「平均」のスループットしか表示されません。そのため、 QoS のイベントを受け取った場合でも、グラフではワークロードのスループットがポリシーのしきい値を超えていないように見えることがあります。

System Manager または ONTAP コマンドを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ワークロード用の新しいポリシーグループを作成します
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でワークロードを移動する
* ポリシーグループのスループット制限を変更する
* 別のアグリゲートまたはノードにワークロードを移動する




== 手順

. イベントの詳細ページを表示して、イベントに関する情報を確認します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「 vol1_NFS1 の IOPS 値が 1 、 352 IOPS のため、警告イベントがトリガーされました。ワークロードに潜在的なパフォーマンスの問題があります」というメッセージは、ボリューム vol1_NFS1 で QoS 最大 IOPS イベントが発生したことを示しています。

. イベントが発生した日時とイベントがアクティブになっている期間の詳細については、「イベント情報」セクションを参照してください。
+
また、 QoS ポリシーのスループットを共有しているボリュームまたは LUN については、 IOPS または MBps が高い上位 3 つのワークロードの名前を確認できます。

. システム診断 * セクションで、合計平均 IOPS または MBps （イベントに応じて）とレイテンシの 2 つのグラフを確認します。これらのグラフを見ると、ワークロードが QoS の上限に達したときに、どのクラスタコンポーネントがレイテンシに最も影響しているかを確認できます。
+
共有 QoS ポリシーのイベントの場合、スループットグラフに上位 3 つのワークロードが表示されます。3 つ以上のワークロードが QoS ポリシーを共有している場合、「 other workloads 」カテゴリに追加されたワークロードが表示されます。また、レイテンシグラフには、 QoS ポリシーに含まれるすべてのワークロードの平均レイテンシが表示されます。

+
アダプティブ QoS ポリシーのイベントの場合、 IOPS および MBps のグラフには、ボリュームのサイズに基づいて、 ONTAP が割り当てられた IOPS/TB しきい値ポリシーから変換した IOPS または MBps の値が表示されます。

. 「推奨される対処方法」セクションで、推奨される対処方法を確認し、ワークロードのレイテンシ増加を回避するために実行する必要がある対処方法を決定します。
+
必要に応じて、ヘルプ * ボタンをクリックして、パフォーマンスイベントの解決方法に関する推奨される操作の詳細を確認します。


