---
permalink: online-help/task-moving-workloads-to-another-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: 現在ワークロードが実行されている HA ペアよりも負荷の低い別の HA ペアのノード上のアグリゲートを Unified Manager で特定し、その後、選択したボリュームを新しい HA ペア上のアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。 
---
= 別の HA ペアのもう一方のノードへのワークロードの移動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在ワークロードが実行されている HA ペアよりも負荷の低い別の HA ペアのノード上のアグリゲートを Unified Manager で特定し、その後、選択したボリュームを新しい HA ペア上のアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* クラスタが 2 つ以上の HA ペアで構成されている必要があります。クラスタに HA ペアが 1 つしかない場合は、この改善策を実施できません。
* 現在パフォーマンス問題を備えている HA ペアの 2 つのノードの名前を記録しておく必要があります。
* ノードがパフォーマンスイベントを受け取った日付と時刻を記録しておく必要があります。
* イベントIDを記録しておく必要があります（例："p-sdt-clus1-nod -6982`"）。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。




== このタスクについて

負荷の高いワークロードを別の HA ペアの利用率の低いノードに移動するには、以下に示す手順で次のリソースを特定します。

* 同じクラスタで別の HA ペアを構成する利用率の低いノード
* この別のノードで最も利用率の低いアグリゲート
* 現在のノードで最も負荷の高いボリューム




== 手順

. 同じクラスタ上の別の HA ペアを構成するノードを特定します。
+
.. 左側のナビゲーションペインで、*パフォーマンス*>*クラスタ*をクリックします。
+
ハフオオマンス/クラスタヘエシが表示されます。

.. 現在のクラスタのノード数 * フィールドの数値をクリックします。
+
[Performance/Nodes]ページが表示されます。

.. 現在パフォーマンス問題がある HA ペアとは別の HA ペアのノードの名前を書き留めます。


. この別の HA ペアで最も利用率の低いノードを特定します。
+
.. ノードを利用率が低い順にソートするには、 * Utilization * 列をクリックします。
+
また、最大の * 空き容量 * を持つノードを特定することもできます。これにより、ワークロードの移動先にするノードの候補が一覧表示されます。

.. ワークロードの移動先にするノードの名前を書き留めます。


. この別のノード上の最も利用率の低いアグリゲートを特定します。
+
.. 左側のナビゲーションペインで、*パフォーマンス*>*アグリゲート*をクリックします。
+
パフォーマンス/アグリゲートページが表示されます。

.. [*Filtering*] をクリックし、左側のドロップダウンメニューから [*Node] を選択して、テキストフィールドにノード名を入力し、 [*Apply Filter*] をクリックします。
+
このノードで使用可能なアグリゲートのリストが示されたパフォーマンス/アグリゲートページが再表示されます。

.. 利用率 * 列をクリックして、アグリゲートを利用率が低い順にソートします。
+
空き容量が最も多いアグリゲートを特定することもできます。これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったノードで負荷の高いワークロードを特定します。
+
.. イベントの * Event * 詳細ページに戻ります。
.. 影響を受けるボリューム * フィールドで、最初のノードのボリューム数のリンクをクリックします。
+
パフォーマンス/ボリュームページが開き、そのノード上のボリュームがフィルタリングされて一覧表示されます。

.. 合計容量 * 列をクリックして、ボリュームを最大割り当てスペースでソートします。
+
これにより、移動するボリュームの候補が一覧表示されます。

.. 移動するボリュームの名前と、そのボリュームが現在配置されているアグリゲートの名前を書き留めます。
.. このイベントに関係した 2 つ目のノードに対して手順 4c と 4d を実行して、そのノードから移動するボリュームの候補を特定します。


. 事前に特定した別のノードで最も利用率の低いアグリゲートにボリュームを移動します。
+
移動処理は、OnCommand のSystem Manager、OnCommand Workflow Automation 、ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。





== 完了後

数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
