---
permalink: online-help/task-resuming-scheduled-transfers-on-a-quiesced-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 関係を休止してスケジュールされた転送の実行を停止したあと、健全性/ボリュームの詳細ページで再開を使用してスケジュールされた転送を再び有効にし、ソースボリュームまたはプライマリボリュームのデータを保護します。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。 
---
= 休止中の関係のスケジュールされた転送を健全性/ボリュームの詳細ページで再開しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関係を休止してスケジュールされた転送の実行を停止したあと、健全性/ボリュームの詳細ページで* Resume *を使用してスケジュールされた転送を再び有効にし、ソースボリュームまたはプライマリボリュームのデータを保護することができます。スケジュールされた次回の転送時に、チェックポイントが存在する場合は、チェックポイントから転送が再開されます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== 手順

. [* Health/Volume]*詳細ページの[* Protection]タブで、再開する休止中の関係をトポロジビューで右クリックします。
+
または、 * Actions * > * Relationship * メニューから * Resume * を選択します。

. [* Resume * （続行） ] ダイアログボックスで、 [* Continue * （続行） ] をクリックします。
+
健常性とボリュームの詳細ページに戻ります。

. 関連するジョブタスクを表示してその進捗状況を追跡するには、*健常性/ボリューム*の詳細ページの上部に表示されるジョブのリンクをクリックします。
. [*保護/ジョブ*の詳細]ページで、[*更新]をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
+
ジョブが完了すると、次回のスケジュールされた転送の実行時にデータ転送が再開されます。


