---
permalink: online-help/task-subscribing-to-ontap-ems-events.html 
sidebar: sidebar 
keywords:  
summary: ONTAP ソフトウェアがインストールされているシステムで生成されたイベント管理システム（EMS）イベントを受け取るように登録することができます。一部の EMS イベントは Unified Manager に自動的に報告されますが、それ以外の EMS イベントは登録している場合にのみ報告されます。 
---
= ONTAP EMS イベントに登録する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ソフトウェアがインストールされているシステムで生成された Event Management System （ EMS ；イベント管理システム）イベントを受け取るように登録することができます。一部の EMS イベントは Unified Manager に自動的に報告されますが、それ以外の EMS イベントは登録している場合にのみ報告されます。



== 作業を開始する前に

Unified Manager にすでに自動的に追加されている EMS イベントには登録しないでください。同じ問題のイベントを 2 つ受信すると原因で混乱する可能性があります。



== このタスクについて

EMS イベントはいくつでも登録できます。登録したすべてのイベントが検証され、検証済みのイベントだけが Unified Manager で監視しているクラスタに適用されます。ONTAP 9 EMS イベントカタログ _ は、指定したバージョンの ONTAP 9 ソフトウェアのすべての EMS メッセージに関する詳細情報を提供します。該当するイベントの一覧については、 ONTAP 9 製品ドキュメントページで該当するバージョンの _EMS イベントカタログを参照してください。

https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 製品ライブラリ"]

登録した ONTAP EMS イベントにアラートを設定したり、それらのイベントに対して実行するカスタムスクリプトを作成したりできます。

[NOTE]
====
登録した ONTAP EMS イベントが届かない場合は、クラスタの DNS 設定が含まれている問題で、クラスタから Unified Manager サーバに到達できなくなっていることが考えられます。クラスタ管理者はこの問題を解決するために、クラスタの DNS 設定を修正してから Unified Manager を再起動する必要があります。これにより、保留中の EMS イベントが Unified Manager サーバにフラッシュされます。

====


== 手順

. 左側のナビゲーションペインで、* Configuration *>* Manage Events *をクリックします。
. [*Configuration/Manage Events*]ページで、[*Subscribe to EMS events*]ボタンをクリックします。
. [*Subscribe to EMS events]ダイアログボックスに、登録するONTAP EMSイベントの名前を入力します。
+
登録可能なEMSイベントの名前を確認するには、ONTAP クラスタシェルでを使用します `event route show` コマンド（ONTAP 9より前）または `event catalog show` コマンド（ONTAP 9以降）。個 々 のEMSイベントを特定する詳しい手順については、ナレッジベースの回答 1072320を参照してください。

+
https://kb.netapp.com/app/answers/answer_view/a_id/1072320["KB 1072320 - ONTAP EMSイベントサブスクリプションの設定方法"]

. [ 追加（ Add ） ] をクリックします。
+
EMS イベントはサブスクライブされた EMS イベントのリストに追加されますが、該当する [To Cluster] 列には、追加した EMS イベントのステータスが「 Unknown 」と表示されます。

. Save and Close * をクリックして、 EMS イベントサブスクリプションをクラスタに登録します。
. もう一度 [* EMS イベントをサブスクライブ * ] をクリックします。
+
追加した EMS イベントの [Applicable to Cluster] 列には、ステータス「 Yes 」が表示されます。

+
ステータスが「はい」でない場合は、 ONTAP EMS イベント名のスペルを確認します。入力した名前に間違いがある場合は、そのイベントを削除して追加し直す必要があります。





== 完了後

ONTAP の EMS イベントが発生すると、イベントが Events ページに表示されます。イベントを選択すると、 EMS イベントに関する詳細をイベントの詳細ページで確認できます。イベントの処理を管理したり、イベントのアラートを作成したりすることもできます。
