---
permalink: online-help/task-identifying-trends-of-i-o-response-time-on-cluster-components.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerを使用して、あるボリュームワークロードについて、すべての監視対象クラスタコンポーネントのパフォーマンスの傾向を表示できます。使用率が最も高いコンポーネント、その使用率が読み取り要求と書き込み要求のどちらに起因しているか、およびワークロードの応答時間にどのように影響したかを時系列で確認できます。 
---
= クラスタコンポーネントでのI/O応答時間の傾向を特定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用して、あるボリュームワークロードについて、すべての監視対象クラスタコンポーネントのパフォーマンスの傾向を表示できます。使用率が最も高いコンポーネント、その使用率が読み取り要求と書き込み要求のどちらに起因しているか、およびワークロードの応答時間にどのように影響したかを時系列で確認できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 分析するボリュームまたは関連するLUNの名前を特定しておく必要があります。
* 30日間のパフォーマンス統計を表示するには、Unified Managerで最低30日間のパフォーマンス統計がクラスタから収集されて分析されている必要があります。




== このタスクについて

クラスタコンポーネントのパフォーマンスの傾向を特定することで、管理者はクラスタの使用率が高すぎる/低すぎる状況を判断できます。

イベントの詳細ページを表示している場合は、ボリュームの名前をクリックして、パフォーマンス/ボリュームの詳細ページに直接移動できます。



== 手順

. *検索*バーにボリュームの名前を入力します。
+
ボリュームの名前が検索結果に表示されます。

. ボリュームの名前をクリックします。
+
ボリュームがPerformance / Volume Detailsページに表示されます。

. 履歴データチャートで、過去30日間の履歴データを表示するには、* 30 d *をクリックします。
. [*データを次の単位でブレークダウン（Break down data by *）
. [*Latency*]で、[***クラスタ・コンポーネント***および***読み取り/書き込みレイテンシー***]を選択します。
. [Submit （送信） ] をクリックします。
+
両方のグラフがレイテンシグラフの下に表示されます。

. 「クラスタコンポーネント」の表を確認します。
+
このチャートには応答時間のクラスタコンポーネント別の内訳が表示されます。アグリゲートでの応答時間が最も長くなります。

. クラスタコンポーネント*のグラフと*レイテンシ*のグラフを比較します。
+
レイテンシグラフには、合計応答時間の急増がアグリゲートの応答時間の急増に合わせて表示されます。30日間の最後に数回パフォーマンスしきい値を超えています。

. 読み取り/書き込みレイテンシ*グラフを確認します。
+
このチャートでは、読み取り要求よりも書き込み要求の応答時間が長く、クライアントアプリケーションが書き込み要求の完了を通常よりも長く待機していることがわかります。

. 読み取り/書き込みレイテンシ*のグラフをレイテンシ*のグラフと比較します。
+
クラスタコンポーネントグラフのアグリゲートに対応する合計応答時間の急増は、読み取り/書き込みレイテンシグラフの書き込みにも対応しています。管理者は、ワークロードを使用しているクライアントアプリケーションへの対処が必要かどうか、またはアグリゲートの利用率が高すぎるどうかを判断する必要があります。


