---
permalink: online-help/task-viewing-event-details-in-the-performance-explorer-events-timeline.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスエクスプローラのイベントタイムラインペインで、すべてのイベントとその関連情報を確認できます。指定した期間内にルートオブジェクトで発生したすべての健常性イベントとパフォーマンスイベントをすばやく効率的に表示できるため、パフォーマンスの問題のトラブルシューティングに役立ちます。 
---
= イベントタイムラインでイベントの詳細を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスエクスプローラのイベントタイムラインペインで、すべてのイベントとその関連情報を確認できます。指定した期間内にルートオブジェクトで発生したすべての健常性イベントとパフォーマンスイベントをすばやく効率的に表示できるため、パフォーマンスの問題のトラブルシューティングに役立ちます。



== このタスクについて

イベントタイムラインペインには、選択した期間中にルートオブジェクトで発生したクリティカル、エラー、警告、および情報イベントが表示されます。イベントの重大度ごとに独自のタイムラインがあります。単一または複数のイベントがタイムライン上に点で表されます。イベントを示す点にカーソルを合わせると、イベントの詳細を確認できます。複数のイベントをより詳細に表示するには、期間を縮小します。複数のイベントが複数の単一のイベントとして表示されるため、各イベントを個々に表示して確認することができます。

イベントタイムラインの各パフォーマンスイベントドットは、イベントタイムラインの下に表示されるカウンタグラフのトレンドラインの急増に対応して縦に並んでいます。イベントと全体的なパフォーマンスの間に直接的な相関関係があることを確認できます。健常性イベントもタイムラインに表示されますが、これらのタイプのイベントはいずれかのパフォーマンスグラフのイベントが急増しているポイントと揃うとはかぎりません。



== 手順

. [ * イベントタイムライン * ] ペインで、タイムライン上のイベントドットにカーソルを合わせると、そのイベントポイントでのイベントのサマリーが表示されます。
+
イベントタイプ、イベントが発生した日時、状態、およびイベントの期間に関する情報がポップアップダイアログに表示されます。

. 1 つまたは複数のイベントの詳細を表示します。
+
|===
| 作業 | オプション 


 a| 
1 つのイベントの詳細を表示します
 a| 
* ポップアップダイアログでイベントの詳細を表示 * 。



 a| 
複数のイベントの詳細を表示します
 a| 
* ポップアップダイアログでイベントの詳細を表示 * 。

[NOTE]
====
複数イベントダイアログで 1 つのイベントをクリックすると、該当するイベントの詳細ページが表示されます。

====
|===

