---
permalink: online-help/task-aborting-an-active-data-protection-transfer-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送以外の転送の再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。 
---
= 健常性/ボリュームの詳細ページからアクティブなデータ保護転送を中止します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送以外の転送の再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

中止処理は、次の場合は表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


ベースライン転送の再開チェックポイントは消去できません。



== 手順

. *健常性/ボリューム*の詳細ページの*保護*タブで、中止するデータ転送のトポロジビューで関係を右クリックし、*中止*を選択します。
+
転送の中止ダイアログボックスが表示されます。

. ベースライン転送以外の転送の再開チェックポイントをクリアする場合は、「 * チェックポイントのクリア * 」を選択します。
. [* Continue （続行） ] をクリックします
+
転送の中止ダイアログボックスが閉じ、健常性/ボリュームの詳細ページの上部に中止処理のステータスとジョブの詳細へのリンクが表示されます。

. [*詳細の表示*]リンクをクリックして、[保護/ジョブ*詳細]ページに移動し、詳細を確認したり、ジョブの進捗状況を確認したりします。
. 各ジョブタスクをクリックすると、その詳細が表示されます。
. ブラウザの戻る矢印をクリックして、*正常性/ボリューム*の詳細ページに戻ります。
+
すべてのタスクが正常に完了すれば中止処理は終了です。


