---
permalink: online-help/task-quiescing-a-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースを含む SnapMirror デスティネーションボリュームの Snapshot コピーを作成する場合に、 Snapshot コピーの実行中にデータベースコンテンツの安定を確保する目的で行うことがあります。 
---
= ケンセンセイ/ホリユウムノシヨウサイヘエシテノホコカンケイノキユウシ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースを含む SnapMirror デスティネーションボリュームの Snapshot コピーを作成する場合に、 Snapshot コピーの実行中にデータベースコンテンツの安定を確保する目的で行うことがあります。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

次の場合は休止操作が表示されません。

* RBAC の設定で許可されていない場合：オペレータの権限しかない場合など
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など
* Workflow Automation と Unified Manager を連携させていない場合




== 手順

. *正常性/ボリューム*の詳細ページの*保護*タブで、休止する保護関係のトポロジビューで関係を右クリックします。
. メニューから「 * 休止」を選択します。
. 続行するには、 [ はい ] をクリックします。
+
休止ジョブのステータスは、健常性/ボリュームの詳細ページの上部にジョブの詳細へのリンクとともに表示されます。

. [*詳細の表示*]リンクをクリックして、[保護/ジョブ*詳細]ページに移動し、詳細とジョブの進捗状況を確認します。
. ブラウザの戻る矢印をクリックして、*正常性/ボリューム*の詳細ページに戻ります。
+
すべてのジョブタスクが正常に完了すれば休止ジョブは終了です。


