---
permalink: online-help/task-moving-workloads-to-a-different-aggregate.html 
sidebar: sidebar 
keywords:  
summary: ワークロードが現在配置されているアグリゲートよりも負荷の低いアグリゲートを Unified Manager で特定し、選択したボリュームまたは LUN をそのアグリゲートに移動できます。負荷の高いワークロードを負荷の低いアグリゲートまたはフラッシュストレージが有効なアグリゲートに移動すると、ワークロードの効率が向上します。 
---
= ワークロードを別のアグリゲートに移動しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードが現在配置されているアグリゲートよりも負荷の低いアグリゲートを Unified Manager で特定し、選択したボリュームまたは LUN をそのアグリゲートに移動できます。負荷の高いワークロードを負荷の低いアグリゲートまたはフラッシュストレージが有効なアグリゲートに移動すると、ワークロードの効率が向上します。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 現在パフォーマンス問題があるアグリゲートの名前を記録しておく必要があります。
* アグリゲートがイベントを受け取った日時を記録しておく必要があります。
* イベントIDを記録しておく必要があります（例："p-sdt-clus1-AG-2542`"）。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。




== このタスクについて

負荷の高いワークロードを利用率の低いアグリゲートに移動するには、以下に示す手順で次のリソースを特定します。

* 同じクラスタ上の利用率の低いアグリゲート
* 現在のアグリゲートで最も負荷の高いボリューム




== 手順

. クラスタ内で最も利用率の低いアグリゲートを特定します。
+
.. イベント * の詳細ページで、アグリゲートが配置されているクラスタの名前をクリックします。
+
パフォーマンス / クラスタランディングページにクラスタの詳細が表示されます。

.. [* 概要 *] ページで、 [* 管理対象オブジェクト * ] ペインの [* アグリゲート ] をクリックします。
+
このクラスタ上のアグリゲートのリストが表示されます。

.. 利用率 * 列をクリックして、アグリゲートを利用率が低い順にソートします。
+
空き容量が最も多いアグリゲートを特定することもできます。これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったアグリゲートで負荷の高いボリュームを特定します。
+
.. パフォーマンス問題があるアグリゲートをクリックします。
+
アグリゲートの詳細は、 Performance/AggregateExplorer ヘエシに表示されます。

.. * 時間範囲 * セレクタから「 * 過去 30 日間 * 」を選択し、 * 範囲の適用 * をクリックします。
+
これにより、デフォルトの 72 時間よりも長い期間のパフォーマンス履歴を表示できます。過去 72 時間だけでなく一貫した数のリソースを使用しているボリュームを移動したい。

.. View and Compare * コントロールから、 * このアグリゲートのボリュームを選択します。
+
このアグリゲート上の FlexVol ボリュームおよび FlexGroup コンスティチュエントボリュームのリストが表示されます。

.. ボリュームをMBpsの高い順に並べ替えたあとにIOPSの高い順に並べ替えることで、最も負荷の高いボリュームがわかります。
.. 別のアグリゲートに移動するボリュームの名前を書き留めます。


. 事前に特定した利用率の低いアグリゲートに負荷の高いボリュームを移動します。
+
移動処理は、OnCommand のSystem Manager、OnCommand Workflow Automation 、ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。





== 完了後

数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
