---
permalink: online-help/task-creating-storage-virtual-machine-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: Storage Virtual Machineの関連付けの作成ウィザードでは、パートナーの保護アプリケーションを使用してソースStorage Virtual Machine（SVM）をデスティネーションSVMに関連付け、SnapMirror関係とSnapVault 関係で使用することができます。パートナーアプリケーションでは、デスティネーションボリュームの最初のプロビジョニングの際にこれらの関連付けを使用して、選択するリソースを決定します。 
---
= SVMの関連付けの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create Storage Virtual Machine Associationsウィザードでは、パートナーの保護アプリケーションでソースStorage Virtual Machine（SVM）をデスティネーションSVMに関連付けて、SnapMirror関係とSnapVault 関係で使用することができます。パートナーアプリケーションでは、デスティネーションボリュームの最初のプロビジョニングの際にこれらの関連付けを使用して、選択するリソースを決定します。



== 作業を開始する前に

* 関連付けるSVMがすでに存在している必要があります。
* OnCommand 管理者またはストレージ管理者のロールが必要です。




== このタスクについて

すべてのソースSVMと関係タイプについて、各デスティネーションクラスタでデスティネーションSVMを1つだけ選択できます。

削除機能と作成機能を使用した関連付けの変更は、以降のプロビジョニング処理にのみ反映されます。既存のデスティネーションボリュームは移動されません。



== 手順

. 左側のナビゲーションペインで、* Protection *>* SVM Associations *をクリックします。
. [保護/ Storage Virtual Machineの関連付け*]ページで、[*作成]をクリックします。
+
Storage Virtual Machineの関連付けの作成ウィザードが起動します。

. 次のいずれかのソースを選択します。
+
** * 任意 *
+
任意のプライマリSVMソースと1つ以上のデスティネーションSVMの間で関連付けを作成する場合に、このオプションを選択します。つまり、現時点で保護を必要とする既存のすべてのSVMおよび今後作成されるすべてのSVMが指定したデスティネーションSVMに関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを1箇所にある1つ以上のデスティネーションSVMにバックアップできます。

** * シングル *
+
1つ以上のデスティネーションSVMに関連付ける特定のソースSVMを選択する場合に、このオプションを選択します。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定のSVMソースを、対象のクライアントにのみ割り当てられる特定のSVMデスティネーションに関連付けます。

** * なし（外部） *
+
ソースSVMとデスティネーションSVMの外部のフレキシブルボリュームの間で関連付けを作成する場合に、このオプションを選択します。



. 作成する保護関係タイプとして、次のいずれかまたは両方を選択します。
+
** * SnapMirror *
** * SnapVault *


. 「 * 次へ * 」をクリックします。
. 1つ以上のSVMの保護デスティネーションを選択します。
. [ 完了 ] をクリックします。

