---
permalink: online-help/task-moving-workloads-to-a-different-node.html 
sidebar: sidebar 
keywords:  
summary: ワークロードが現在実行されているノードよりも負荷の低い別のノード上のアグリゲートを Unified Manager で特定し、選択したボリュームをそのアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。 
---
= ワークロードを別のノードに移動する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードが現在実行されているノードよりも負荷の低い別のノード上のアグリゲートを Unified Manager で特定し、選択したボリュームをそのアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 現在パフォーマンス問題があるノードの名前を記録しておく必要があります。
* ノードがパフォーマンスイベントを受け取った日付と時刻を記録しておく必要があります。
* イベントIDを記録しておく必要があります。たとえば、"p-sdt-clus1-nod -6982`"のようにします。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。




== このタスクについて

この手順 を使用して次のリソースを特定すると、負荷の高いワークロードを利用率の低いノードに移動できます。

* 同じクラスタで最も空きパフォーマンス容量が大きいノード
* 別のノードで最も空きパフォーマンス容量が大きいアグリゲート
* 現在のノードで最も負荷の高いボリューム




== 手順

. クラスタで最も空きパフォーマンス容量が大きいノードを特定します。
+
.. [ * Event Details * ] ページで、ノードが配置されているクラスタの名前をクリックします。
+
パフォーマンス / クラスタランディングページにクラスタの詳細が表示されます。

.. [ * 概要 * ] タブの [ * 管理対象オブジェクト * ] ペインで [ * ノード * ] をクリックします。
+
このクラスタ上のノードのリストが表示されます。

.. 使用済みパフォーマンス容量 * 列をクリックして、ノードを使用率が最も低い順にソートします。
+
これにより、ワークロードの移動先にするノードの候補が一覧表示されます。

.. ワークロードの移動先にするノードの名前を書き留めます。


. この別のノード上の最も利用率の低いアグリゲートを特定します。
+
.. 左側のナビゲーションペインで、*パフォーマンス*>*アグリゲート*をクリックします。
+
パフォーマンス/アグリゲートページが表示されます。

.. [*Filtering*] をクリックし、左側のドロップダウンメニューから [*Node] を選択して、テキストフィールドにノード名を入力し、 [*Apply Filter*] をクリックします。
+
このノードで使用可能なアグリゲートのリストが示されたパフォーマンス/アグリゲートページが再表示されます。

.. 使用済みパフォーマンス容量 * 列をクリックして、アグリゲートを使用量が最も少ない順にソートします。
+
これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったノードで負荷の高いワークロードを特定します。
+
.. イベントの * Event Details * ページに戻ります。
.. [ * 影響を受けるボリューム * ] フィールドで、ボリューム数のリンクをクリックします。
+
パフォーマンス/ボリュームページが開き、そのノード上のボリュームがフィルタリングされて一覧表示されます。

.. 合計容量 * 列をクリックして、ボリュームを最大割り当てスペースでソートします。
+
これにより、移動するボリュームの候補が一覧表示されます。

.. 移動するボリュームの名前と、そのボリュームが現在配置されているアグリゲートの名前を書き留めます。


. 事前に特定した別のノードで最も空きパフォーマンス容量が大きいアグリゲートにボリュームを移動します。
+
移動処理は、OnCommand のSystem Manager、OnCommand Workflow Automation 、ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。





== 完了後

数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
