---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 健全性/ボリュームインベントリページでは、同じStorage Virtual Machine（SVM）上の1つ以上のボリュームのSnapVault 関係を作成して、データを保護するためのデータバックアップを有効にすることができます。 
---
= ケンセンセイ/ホリユウムインヘントリヘエシカラノSnapVault ホコカンケイノサクセイ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
健全性/ボリュームインベントリページでは、同じStorage Virtual Machine（SVM）上の1つ以上のボリュームのSnapVault 関係を作成して、データを保護するためのデータバックアップを有効にすることができます。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== このタスクについて

次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など




== 手順

. 左側のナビゲーションペインで、* Health *>* Volumes *をクリックします。
. [*正常性/ボリューム*]インベントリページで、保護するボリュームを右クリックし、[*保護]を選択します。
+
または、同じStorage Virtual Machine（SVM）上に複数の保護関係を作成するには、Health / Volumes（健常性/ボリューム）インベントリページで1つ以上のボリュームを選択し、ツールバーの* Protect（保護）*をクリックします。

. メニューから * SnapVault * を選択します。
+
Configure Protection （保護の設定）ダイアログボックスが開きます。

. SnapVault * をクリックして、 * SnapVault * タブを表示し、セカンダリ・ボリューム情報を設定します。
. [ * 詳細設定 * ] をクリックして、必要に応じて重複排除、圧縮、自動拡張、およびスペースギャランティを設定し、 [ * 適用 * ] をクリックします。
. [* SnapVault * （接続先情報） ] タブの [* 接続先情報 * ] 領域と [* 関係設定 * ] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
健常性/ボリュームのインベントリページに戻ります。

. * Health/Volumes *インベントリページの上部にある保護構成ジョブのリンクをクリックします。
+
保護関係を1つだけ作成する場合は、保護/ジョブの詳細ページが表示されます。ただし、複数の保護関係を作成する場合は、保護処理に関連付けられているすべてのジョブのフィルタされたリストが表示されます。

. 次のいずれかを実行します。
+
** ジョブが 1 つしかない場合は、 ［ * 更新 * ］ をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** ジョブが複数ある場合は、次の手順を実行します。
+
... ジョブリストでジョブをクリックします。
... 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
... フィルタリングされたリストに戻り、別のジョブを表示するには、「 * 戻る」ボタンを使用します。





