---
permalink: online-help/task-customizing-a-report.html 
sidebar: sidebar 
keywords:  
summary: レポートの詳細ページでレポートをカスタマイズして、カスタマイズしたレポートを別の名前で保存することができます。 
---
= レポートのカスタマイズ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
レポートの詳細ページでレポートをカスタマイズして、カスタマイズしたレポートを別の名前で保存することができます。



== このタスクについて

カスタマイズされたレポートを保存した後は、レポートを作成するために適用したフィルタを変更することはできません。これは、レポートが「新しい」と見なされるためです。そのため、レポートを保存する前に、すべての変更が完了していることを確認してください。ただし、レポートに新しいフィルタを適用することはできます。



== 手順

. 左側のナビゲーションペインで、*Reports*をクリックし、カスタマイズするレポートの*Run Report*をクリックします。
+
レポートの詳細ページが表示されます。

. 必要に応じてレポートをカスタマイズし、*アクション*>*カスタマイズされたレポートを名前を付けて保存*をクリックします。
. [カスタマイズされたレポートを名前を付けて保存（Save Customized Report As）]ダイアログボックスで、カスタマイズされたレポートの名前とカスタマイズに関する簡単な概要 を入力して、他のユーザーがレポートの表示内容を理解できるようにします。
+
デフォルトでは、現在のレポート名が表示されます。

. [ 保存（ Save ） ] をクリックします。
+
エラーメッセージ「カスタムレポートを保存できませんでした。必要なファイルが作成されませんでした。しばらく待ってから、もう一度* Save *をクリックしてください。この問題 は、WebブラウザとUnified Managerサーバの間の接続速度が遅い場合に表示されます。





== 結果

カスタマイズしたレポートが保存され、レポートの詳細ページの該当するレポートカテゴリに表示されます。
