---
permalink: online-help/task-adding-alerts-for-performance-events.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザに E メールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する共通のアラートを作成することもできます。 
---
= パフォーマンスイベントのアラートを追加しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザに E メールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する共通のアラートを作成することもできます。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== このタスクについて

次の例は、レイテンシ、 IOPS 、および MBps のすべての重大イベントに対するイベントを作成する方法を示しています。同じ方法で、すべてのパフォーマンスカウンタからイベントを選択したり、すべての警告イベントに対してイベントを選択したりできます。



== 手順

. 左側のナビゲーションペインで、*構成*>*警告*をクリックします。
. [*設定/アラート*]ページで、[*追加]をクリックします。
. [ * アラートの追加 * ] ダイアログボックスで、 [ * 名前 * ] をクリックし、アラートの名前と概要を入力します。
. [* リソース ] ページでは、リソースを選択しないでください。
+
リソースを選択していないため、クラスタ、アグリゲート、ボリュームなど、何に対するイベントを受信したかに関係なく、すべてのリソースにアラートが適用されます。

. [* Events （イベント） ] をクリックして、次の操作を実行します。
+
.. イベントの重大度リストで、 * クリティカル * を選択します。
.. [Event Name Contains]フィールドに、と入力します `latency` 次に、矢印をクリックして、一致するすべてのイベントを選択します。
.. [Event Name Contains]フィールドに、と入力します `iops` 次に、矢印をクリックして、一致するすべてのイベントを選択します。
.. [Event Name Contains]フィールドに、と入力します `mbps` 次に、矢印をクリックして、一致するすべてのイベントを選択します。


. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMP トラップの発行やスクリプトの実行など、このページの他のオプションを設定します。
. [ 保存（ Save ） ] をクリックします。

