---
permalink: online-help/task-creating-snapmirror-relationships-with-version-flexible-replication-with-backup-option.html 
sidebar: sidebar 
keywords:  
summary: バージョンに依存しないレプリケーションとバックアップオプション機能を使用して SnapMirror 関係を作成できます。バックアップオプション機能を使用すると、 SnapMirror 保護を実装できます。また、デスティネーションの場所でバックアップコピーの複数のバージョンを保持することもできます。 
---
= バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 関係の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョンに依存しないレプリケーションとバックアップオプション機能を使用して SnapMirror 関係を作成できます。バックアップオプション機能を使用すると、 SnapMirror 保護を実装できます。また、デスティネーションの場所でバックアップコピーの複数のバージョンを保持することもできます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。
* ソースとデスティネーションの SVM でそれぞれ、 SnapMirror ライセンスが有効になっている必要があります。
* ソースとデスティネーションの SVM でそれぞれ、 SnapVault ライセンスが有効になっている必要があります。
* ソースとデスティネーションのSVMがそれぞれ、バージョンに依存しないレプリケーションをサポートするバージョンのONTAP ソフトウェア（8.3以降）で実行されている必要があります。




== このタスクについて

SnapMirror にバックアップオプション機能を設定すると、ボリュームのフェイルオーバー機能などの SnapMirror ディザスタリカバリ機能を使用してデータを保護できるだけでなく、複数のバックアップコピーによる保護などの SnapVault 機能を利用できます。



== 手順

. 保護するボリュームの * 保護の設定 * ダイアログボックスを表示します。
+
** 正常性/ボリュームの詳細ページの保護タブを表示している場合は、トポロジビューで保護するボリュームの名前を右クリックし、メニューから* Protect *>* SnapMirror *を選択します。
** 健全性/ボリュームインベントリページを表示している場合は、保護するボリュームを特定して右クリックし、メニューから*保護*>* SnapMirror *を選択します。Configure Protection （保護の設定）ダイアログボックスが表示されます。


. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示します。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. 「 * 詳細設定 * 」をクリックして、「 * 詳細設定 * 」ダイアログボックスを表示します。
. バージョンに依存しないレプリケーション * チェックボックスがまだ選択されていない場合は、ここで選択します。
. バックアップオプション機能を有効にするには、 * バックアップオプション * 付きチェックボックスを選択し、 * 適用 * をクリックします。
. [ 適用（ Apply ） ] をクリックします。
+
健常性とボリュームの詳細ページに戻ります。

. 「* Health / Volume * details」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細がProtection / Job Detailsページに表示されます。

. [*保護/ジョブ*の詳細]ページで、[*更新]をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの*戻る*をクリックして*正常性/ボリューム*の詳細ページに戻ります。
+
新しい関係は、健常性/ボリュームの詳細ページのトポロジビューに表示されます。


