---
permalink: online-help/task-reversing-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能ボリュームに変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。 
---
= 保護関係の反転については、保護/ボリューム関係ページを参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能ボリュームに変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。
* SnapVault 関係は使用できません。
* 保護関係がすでに存在している必要があります。
* 保護関係が解除されている必要があります。
* ソースとデスティネーションの両方がオンラインになっている必要があります。
* ソースが別のデータ保護ボリュームのデスティネーションになっていることはできません。




== このタスクについて

* このタスクを実行すると、共通の Snapshot コピーのデータよりも新しいソースのデータは削除されます。
* 逆再同期した関係に対して作成されるポリシーとスケジュールは、元の保護関係と同じになります。
+
ポリシーとスケジュールが存在しない場合は作成されます。





== 手順

. [*保護/ボリューム関係*（* Protection / Volume Relationships *）]ページで、反転する関係を持つ1つ以上のボリュームを選択し、ツールバーで[*逆再同期*（* Reverse Resync *）]をクリックします。
+
逆再同期（ Reverse Resync ）ダイアログボックスが表示されます。

. 逆再同期を実行する関係が * 逆再同期 * （ Reverse Resync * ）ダイアログボックスに表示されていることを確認し、 * 送信 * （ Submit * ）をクリックします。
+
逆再同期処理が開始されると、保護/ボリューム関係ページに戻り、ページの上部にジョブのリンクが表示されます。

. 各逆再同期ジョブのステータスを追跡するには、[*保護/ボリューム関係*]ページで[*ジョブの表示]をクリックします。
+
この処理に関連するジョブがフィルタリングされて表示されます。

. ブラウザの戻る*矢印をクリックして、「*保護/ボリュームの関係*」ページに戻ります。
+
すべてのタスクが正常に完了すれば逆再同期処理は終了です。


