---
permalink: online-help/task-creating-a-snapmirror-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: ケンセンセイ/ホリユウムインヘントリヘエシヲシヨウすると、同じSVM上の複数のボリュームを選択して、複数のSnapMirror保護関係を一度に作成できます。 
---
= ケンセンセイ/ホリユウムインヘントリヘエシカラSnapMirrorホコカンケイヲサクセイ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ケンセンセイ/ホリユウムインヘントリヘエシヲシヨウすると、同じSVM上の複数のボリュームを選択して、複数のSnapMirror保護関係を一度に作成できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など




== 手順

. [*正常性/ボリューム*]インベントリページで、保護するボリュームを右クリックします。
+
または、同じSVM上に複数の保護関係を作成するには、健全性/ボリュームのインベントリページで1つ以上のボリュームを選択し、ツールバーの*保護*>* SnapMirror *をクリックします。

+
Configure Protection （保護の設定）ダイアログボックスが表示されます。

. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示し、デスティネーション情報を設定します。
. 必要に応じて「 * 詳細設定 * 」をクリックしてスペースギャランティを設定し、「 * 適用 * 」をクリックします。
. [* SnapMirror * ] タブの [ * デスティネーション情報 * ] 領域と [ * 関係設定 * ] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
健常性/ボリュームのインベントリページに戻ります。

. * Health/Volumes *インベントリページの上部にある保護構成ジョブのリンクをクリックします。
+
保護関係を1つだけ作成する場合は、保護/ジョブの詳細ページが表示されます。ただし、複数の保護関係を作成する場合は、保護処理に関連付けられているすべてのジョブのリストが表示されます。

. 次のいずれかを実行します。
+
** ジョブが 1 つしかない場合は、 ［ * 更新 * ］ をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** ジョブが複数ある場合は、次の手順を実行します。
+
... ジョブリストでジョブをクリックします。
... 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
... フィルタリングされたリストに戻り、別のジョブを表示するには、「 * 戻る」ボタンを使用します。








== 結果

設定で指定したデスティネーション SVM と詳細設定で有効にしたオプションに応じて、次のいずれかの SnapMirror 関係が作成されます。

* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定した場合、デフォルトではブロックレプリケーションベースの SnapMirror 関係が作成されます。
* ソースボリュームと同じかそれよりも新しいバージョン（8.3以降）のONTAP で実行されているデスティネーションSVMを指定し、詳細設定でバージョンに依存しないレプリケーションを有効にした場合、バージョンに依存しないレプリケーションを使用したSnapMirror関係が作成されます。
* ONTAP 8.3の以前のバージョン、またはソースボリュームよりも新しいバージョンで実行されているデスティネーションSVMを指定した場合、以前のバージョンでバージョンに依存しないレプリケーションがサポートされていれば、バージョンに依存しないレプリケーションを使用したSnapMirror関係が自動で作成されます。

