---
permalink: online-help/task-restoring-data-using-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: ケンシヨウセイ/ホリユウムノシヨウサイヘエシノリストアキノウヲシヨウシテ、上書きまたは削除したファイルやディレクトリ、あるいはボリューム全体をSnapshotコピーからリストアできます。 
---
= 健常性/ボリュームの詳細ページを使用したデータのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ケンシヨウセイ/ホリユウムノシヨウサイヘエシノリストアキノウヲシヨウシテ、上書きまたは削除したファイルやディレクトリ、あるいはボリューム全体をSnapshotコピーからリストアできます。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。



== このタスクについて

NTFS ファイルストリームはリストアできません。

リストアオプションは、次の場合は使用できません。

* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など。
* ボリュームがFlexGroup ボリュームである。
* ボリュームが SnapMirror 同期レプリケーションの対象に設定されている場合。




== 手順

. * Health/Volume *の詳細ページの* Protection *タブで、リストアするボリュームの名前をトポロジビューで右クリックします。
. メニューから * Restore * を選択します。
+
または、 [ アクション * ] メニューから [ リストア * ] を選択して、詳細を表示している現在のボリュームを保護することもできます。

+
[ 復元 ] ダイアログボックスが表示されます。

. デフォルトの設定と異なる場合は、データをリストアするボリュームと Snapshot コピーを選択します。
. リストアする項目を選択します。
+
ボリューム全体をリストアすることも、リストアするフォルダやファイルを指定することもできます。

. 選択したアイテムを復元する場所を選択します。 * 元の場所 * または * 代替の既存の場所 * のいずれかを選択します。
. 別の既存の場所を選択した場合は、次のいずれかを実行します。
+
** [ リストアパス ] テキストフィールドに、データを復元する場所のパスを入力し、 [ * ディレクトリの選択 * ] をクリックします。
** [*Browse*] をクリックして [Browse Directories] ダイアログボックスを起動し、次の手順を実行します。
+
... リストア先のクラスタ、 SVM 、ボリュームを選択します。
... 名前 (Name) テーブルで ' ディレクトリ名を選択します
... [ * ディレクトリの選択 * ] をクリックします。




. [* リストア ] をクリックします。
+
リストアプロセスが開始されます。

+
[NOTE]
====
Cloud Volumes ONTAP HA クラスタ間のリストア処理が NDMP のエラーで失敗する場合は、ソースシステムのクラスタ管理 LIF と通信できるように、デスティネーションクラスタで明示的な AWS ルートを追加しなければならないことがあります。この設定手順は OnCommand Cloud Manager で実行します。

====

