---
permalink: online-help/task-managing-host-system-resource-events.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager には、 Unified Manager がインストールされているホストシステムでのリソースの問題を監視するサービスが用意されています。ディスクスペースが不足している場合やホストシステムでメモリが不足している場合など、管理ステーションイベントがトリガーされて UI 上部にバナーメッセージとして表示されることがあります。 
---
= ホストシステムリソースイベントの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager には、 Unified Manager がインストールされているホストシステムでのリソースの問題を監視するサービスが用意されています。ディスクスペースが不足している場合やホストシステムでメモリが不足している場合など、管理ステーションイベントがトリガーされて UI 上部にバナーメッセージとして表示されることがあります。



== このタスクについて

管理ステーションイベントは、 Unified Manager がインストールされているホストシステムを含む問題を示します。管理ステーションの問題には、たとえば、ホストシステムでのディスクスペースの不足、 Unified Manager での定期的なデータ収集サイクルの失敗、次の収集ポーリングが開始されたことによる統計分析の完了または完了の遅れなどがあります。

Unified Manager の他のイベントメッセージとは異なり、管理ステーション固有の警告イベントと重大イベントはバナーメッセージで表示されます。



== 手順

. 管理ステーションイベント情報を表示するには、次の操作を実行します。
+
|===
| 状況 | 手順 


 a| 
イベントの詳細を表示します
 a| 
イベントバナーをクリックして、問題の推奨ソリューションを含むイベントの詳細ページを表示します。



 a| 
管理ステーションのすべてのイベントを表示します
 a| 
.. 左側のナビゲーションペインで、 * Events * （イベント * ）をクリックします。
.. EventsインベントリページのFiltersペインで、Source TypeリストでManagement Stationのボックスをクリックします。


|===

