---
permalink: online-help/task-creating-a-snapmirror-relationship-with-version-flexible-replication.html 
sidebar: sidebar 
keywords:  
summary: バージョンに依存しないレプリケーションを使用して SnapMirror 関係を作成できます。バージョンに依存しないレプリケーションを使用すると、ソースボリュームとデスティネーションボリュームが異なるバージョンの ONTAP で実行されている場合でも、 SnapMirror 保護を実装できます。 
---
= バージョンに依存しないレプリケーションを使用して SnapMirror 関係を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョンに依存しないレプリケーションを使用して SnapMirror 関係を作成できます。バージョンに依存しないレプリケーションを使用すると、ソースボリュームとデスティネーションボリュームが異なるバージョンの ONTAP で実行されている場合でも、 SnapMirror 保護を実装できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。
* ソースとデスティネーションの SVM でそれぞれ、 SnapMirror ライセンスが有効になっている必要があります。
* ソースとデスティネーションの SVM がそれぞれ、バージョンに依存しないレプリケーションをサポートするバージョンの ONTAP ソフトウェアで実行されている必要があります。




== このタスクについて

バージョンに依存しないレプリケーションを使用する SnapMirror では、すべてのストレージが 1 つのバージョンの ONTAP で実行されていない異機種混在ストレージ環境でも SnapMirror 保護を実装できます。ただし、バージョンに依存しないレプリケーションを使用する SnapMirror で実行されるミラー処理は、従来のブロックレプリケーションによる SnapMirror で実行されるミラー処理ほど高速ではありません。



== 手順

. 保護するボリュームの * 保護の設定 * ダイアログボックスを表示します。
+
** 正常性/ボリュームの詳細ページの保護タブを表示している場合は、保護するボリュームの名前を含むトポロジビューを右クリックし、メニューから*保護*>* SnapMirror *を選択します。
** 健全性/ボリュームインベントリページを表示している場合は、保護するボリュームを特定して右クリックし、メニューから*保護*>* SnapMirror *を選択します。Configure Protection （保護の設定）ダイアログボックスが表示されます。


. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示します。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
+
保護するソースボリュームよりも前のバージョンの ONTAP で実行されるデスティネーション SVM を指定し、その前のバージョンでバージョンに依存しないレプリケーションがサポートされる場合は、 SnapMirror にバージョンに依存しないレプリケーションが自動的に設定されます。

. ソースボリュームと同じバージョンの ONTAP で実行されているデスティネーション SVM を指定し、バージョンに依存しないレプリケーションで SnapMirror を設定する場合は、 * アドバンスト * をクリックしてバージョンに依存しないレプリケーションを有効にし、 * 適用 * をクリックします。
. [ 適用（ Apply ） ] をクリックします。
+
健常性とボリュームの詳細ページに戻ります。

. 「* Health / Volume * details」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細がProtection / Job Detailsページに表示されます。

. [*保護/ジョブ*の詳細]ページで、[*更新]をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの*戻る*をクリックして*正常性/ボリューム*の詳細ページに戻ります。
+
新しい関係は、健常性/ボリュームの詳細ページのトポロジビューに表示されます。


