---
settings:
  name: OnCommand Unified Manager 9.5
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Unified Manager 9.5のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/release-notes.html"
  - title: はじめに
    entries:
    - title: VMware vSphere のクイックスタートインストール
      url: "/qsg-vapp.html"
    - title: Linux のクイックスタートインストール
      url: "/qsg-linux.html"
    - title: Windows のクイックスタートインストール
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: 法的通知
    url: "/legal-notices.html"
