---
permalink: qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Linux プラットフォームでの Unified Manager のクイックスタートガイドです。 
---
= Windows インストールのクイックスタート手順
:allow-uri-read: 




== システム要件

* オペレーティングシステム：Microsoft Windows Server 2012、2012 R2、2016 64-bit Standard EditionおよびDatacenter Edition
* RAM ： 12GB
* CPU ：合計 9572MHz
* 空きディスクスペース：インストールディレクトリ用に 100GB 、 MySQL データディレクトリ用に 50GB のディスクスペースが必要です


システム要件の詳細については、を参照してください link:install/reference-windows-software-and-installation-requirements.html["Windows ソフトウェアとインストールの要件"] および link:http://mysupport.netapp.com/matrix["互換性マトリックス"]。



== OnCommand Unified Managerをインストールしています



=== インストーラをダウンロードします。

. をダウンロードします `OnCommandUnifiedManager-9.5RC1.exes` インストールパッケージ：
. インストールファイルをターゲットシステムのディレクトリにコピーします。




=== Unified Manager をインストールします

Microsoft .NET 4.5.2以降がインストールされている必要があります。Unified Managerのインストール時に、必要なその他のサードパーティパッケージがインストールされます。依存するソフトウェアパッケージの詳細については、を参照してください link:install/concept-installing-upgrading-and-removing-unified-manager-software.html["WindowsでのUnified Managerソフトウェアのインストール、アップグレード、削除"]。

. デフォルトのローカル管理者アカウントで Windows にログインします。
. インストールファイルをダウンロードしたディレクトリで、 Unified Manager の実行ファイル（ .exe ファイル）を右クリックし、管理者として実行します。
. プロンプトが表示されたら、ユーザ名とパスワードを入力して Unified Manager のメンテナンスユーザを作成します。
. データベース接続ウィザードで、 MySQL の root パスワードを入力します。
. 画面の指示に従ってインストールを完了します。
. インストールの完了時に * Finish * をクリックすると、 Unified Manager Web UI が表示されます。

