---
permalink: performance-checker/concept-sources-of-performance-events.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスイベントとは、クラスタでのワークロードパフォーマンスに関連する問題です。応答時間が長いストレージオブジェクト（高レイテンシとも呼ばれます）を特定するのに役立ちます。同時に発生したその他の健全性イベントと一緒に確認することで、応答時間が長くなった原因と考えられる関連する問題を特定することができます。 
---
= パフォーマンスイベントのソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントとは、クラスタでのワークロードパフォーマンスに関連する問題です。応答時間が長いストレージオブジェクト（高レイテンシとも呼ばれます）を特定するのに役立ちます。同時に発生したその他の健全性イベントと一緒に確認することで、応答時間が長くなった原因と考えられる関連する問題を特定することができます。

Unified Manager は、次のソースからパフォーマンスイベントを受け取ります。

* * ユーザ定義のパフォーマンスしきい値ポリシーイベント *
+
独自に設定したしきい値に基づいたパフォーマンスの問題。アグリゲートやボリュームなどのストレージオブジェクトに対してパフォーマンスしきい値ポリシーを設定して、パフォーマンスカウンタのしきい値を超えたときにイベントが生成されるようにします。

+
これらのイベントを受け取るためには、パフォーマンスしきい値ポリシーを定義してストレージオブジェクトに割り当てる必要があります。

* * システム定義のパフォーマンスしきい値ポリシーイベント *
+
システム定義のしきい値に基づいたパフォーマンスの問題。このしきい値ポリシーは Unified Manager にあらかじめ含まれており、一般的なパフォーマンスの問題に対処します。

+
このしきい値はデフォルトで有効化されており、クラスタの追加後すぐにイベントが生成される場合があります。

* * 動的なパフォーマンスしきい値イベント *
+
IT インフラストラクチャの障害やエラー、またはクラスタリソースの使用率が高いワークロードによるパフォーマンスの問題。これらのイベントの原因は、時間がたてば修復する、または修理や設定変更によって解決可能な単純な問題です。動的しきい値イベントは、ONTAP システムで、他のワークロードが共有のクラスタコンポーネントを利用していることが原因でボリュームのワークロードの処理速度が低下した場合に生成されます。

+
このしきい値はデフォルトで有効になっており、新しいクラスタからデータを収集してから 3 日後にイベントが表示されることがあります。


