---
permalink: performance-checker/concept-roles-of-workloads-involved-in-a-performance-incident.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager では、ロールを使用して、パフォーマンスイベントにワークロードがどのように関連しているかを特定します。役割には Victim 、 Bully 、 Shark があります。ユーザ定義のワークロードは同時に Victim 、 Bully 、 Shark となることがあります。 
---
= パフォーマンスイベントに関連したワークロードの役割
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ロールを使用して、パフォーマンスイベントにワークロードがどのように関連しているかを特定します。役割には Victim 、 Bully 、 Shark があります。ユーザ定義のワークロードは同時に Victim 、 Bully 、 Shark となることがあります。

|===
| ロール | 説明 


 a| 
被害者
 a| 
クラスタコンポーネントを過剰に使用している、他のワークロード（ Bully ）によってパフォーマンスが低下したユーザ定義のワークロード。Victim とみなされるのはユーザ定義のワークロードのみです。Unified Managerはレイテンシの偏差に基づいて、イベント中のレイテンシの実測値が想定範囲から大幅に増加しているワークロードをVictimワークロードとして特定します。



 a| 
影響源
 a| 
ユーザ定義またはシステム定義のワークロードで、クラスタコンポーネントが過剰に使用されていると、「 Victim 」と呼ばれる他のワークロードのパフォーマンスが低下した場合。Unified Manager はクラスタコンポーネントの使用量の偏差に基づいて、イベント中の使用量の実測値が想定範囲から大幅に増加しているワークロードを Bully ワークロードとして特定します。



 a| 
シャーク
 a| 
イベントに関連するすべてのワークロードの中でクラスタコンポーネントの使用量が最も多いユーザ定義のワークロード。Unified Manager はイベント中のクラスタコンポーネントの使用量に基づいて Shark ワークロードを特定します。

|===
クラスタのワークロードは、ストレージアグリゲートやCPUなど、複数のクラスタコンポーネントで共有でき、ネットワークやデータの処理に使用されます。ボリュームなどのワークロードがあると、クラスタコンポーネントの使用量が増えて、コンポーネントがワークロードの要求を効率的に満たすことができない状態になると、コンポーネントは競合状態になります。この、クラスタコンポーネントを過剰に消費しているワークロードが「 Bully 」で、これらのコンポーネントを共有しており、 Bully によってパフォーマンスに影響が出ているワークロードが「 Victim 」です。重複排除や Snapshot コピーなど、システム定義のワークロードのアクティビティも、「いじめ」にエスカレーションできます。

Unified Manager はイベントを検出すると、関連するすべてのワークロードとクラスタコンポーネントを特定します。これには、イベントの原因となった Bully ワークロード、競合状態のクラスタコンポーネント、および Bully ワークロードのアクティビティが増加したためにパフォーマンスが低下した Victim ワークロードが含まれます。

[NOTE]
====
Unified Manager が Bully ワークロードを特定できない場合は、 Victim ワークロードと関連するクラスタコンポーネントに関するアラートだけが生成されます。

====
Unified Manager は Bully ワークロードの Victim ワークロードを特定でき、同じワークロードが Bully ワークロードになった場合にも特定できます。ワークロードは自身に対して Bully ワークロードになることがあります。たとえば、負荷の高いワークロードがポリシーグループの制限によって調整される場合、そのワークロードが含まれるポリシーグループ内のすべてのワークロードが調整されます。継続的なパフォーマンスイベントでは、 Bully ワークロードまたは Victim ワークロードは役割が変わったり、あるいはイベントに関連しなくなったりすることがあります。[パフォーマンス/ボリュームの詳細]ページの[イベントリスト]テーブルで、選択したボリュームの役割が変更されると、役割の変更日時が表示されます。
