---
permalink: performance-checker/concept-unified-manager-performance-monitoring-features.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager は、 ONTAP ソフトウェアを実行しているシステムからパフォーマンス統計を収集して分析します。このツールは、動的なパフォーマンスしきい値とユーザ定義のパフォーマンスしきい値を使用して、多数のクラスタコンポーネントにわたるさまざまなパフォーマンスカウンタを監視します。 
---
= Unified Manager のパフォーマンス監視機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、 ONTAP ソフトウェアを実行しているシステムからパフォーマンス統計を収集して分析します。このツールは、動的なパフォーマンスしきい値とユーザ定義のパフォーマンスしきい値を使用して、多数のクラスタコンポーネントにわたるさまざまなパフォーマンスカウンタを監視します。

長い応答時間（レイテンシ）は、ストレージオブジェクト（ボリュームなど）の実行速度が通常よりも遅いことを示しています。また、この問題は、ボリュームを使用しているクライアントアプリケーションのパフォーマンスが低下したことも示します。Unified Manager はパフォーマンス問題が存在するストレージコンポーネントを特定し、そのパフォーマンス問題に対処するための推奨される対処策を提示します。

Unified Manager には次の機能があります。

* ONTAP ソフトウェアを実行しているシステムからワークロードのパフォーマンス統計を監視して分析します。
* クラスタ、ノード、アグリゲート、ポート、SVMのパフォーマンスカウンタを追跡します。ボリューム、LUN、NVMeネームスペース、LIF：
* IOPS （処理数）、 MBps （スループット）、レイテンシ（応答時間）、利用率など、ワークロードのアクティビティを時系列で示す詳細なグラフを表示します。 パフォーマンス容量とキャッシュ比率：
* しきい値を超えた場合にイベントをトリガーして E メールアラートを送信する、ユーザ定義のパフォーマンスしきい値ポリシーを作成できます。
* システム定義のしきい値とワークロードのアクティビティを学習する動的なパフォーマンスしきい値を使用して、パフォーマンスの問題を特定してアラートを送信します。
* 競合状態のクラスタコンポーネントを特定します。
* クラスタコンポーネントを過剰に消費しているワークロードと、アクティビティの増加によってパフォーマンスが影響を受けたワークロードを特定します。

