---
permalink: performance-checker/concept-using-a-threshold-policy-with-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: ノードしきい値ポリシーを作成して、フェイルオーバーが発生する可能性があるとテイクオーバーノードのパフォーマンスが許容できないレベルまで低下する場合に、 Performance/NodeFailover Planning ページで通知されるようにすることができます。 
---
= Node Failover Planning ページでしきい値ポリシーを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードしきい値ポリシーを作成して、フェイルオーバーが発生する可能性があるとテイクオーバーノードのパフォーマンスが許容できないレベルまで低下する場合に、 Performance/NodeFailover Planning ページで通知されるようにすることができます。

「 Node HA pair over-utilized 」という名前のシステム定義のパフォーマンスしきい値ポリシーは、 6 回の収集期間（ 30 分）に連続してしきい値を超えた場合に警告イベントを生成します。HA ペアのノードの使用済みパフォーマンス容量の合計が 200% を超えると、しきい値を超えたと認識されます。

システム定義原因のしきい値ポリシーで生成されたイベントは、フェイルオーバーによってテイクオーバーノードのレイテンシが許容できないレベルまで上昇することを警告します。特定のノードについてこのポリシーで生成されたイベントが表示された場合は、そのノードの Performance/NodeFailover Planning ページに移動して、フェイルオーバーによる予測レイテンシ値を確認できます。

このシステム定義のしきい値ポリシーの使用に加えて、「 Performance Capacity Used - Takeover 」カウンタを使用してしきい値ポリシーを作成し、選択したノードにそのポリシーを適用できます。200% を下回るしきい値を指定すると、システム定義のポリシーのしきい値を超える前にイベントを受け取ることができます。システム定義のポリシーイベントが生成される前に通知を受け取るには、しきい値を超えた最低期間を 30 分未満に指定することもできます。

たとえば、 HA ペアのノードの使用済みパフォーマンス容量の合計が 10 分以上にわたって 175% を超えた場合に警告イベントが生成されるようにしきい値ポリシーを定義できます。HA ペアの Node1 と Node2 にこのポリシーを適用できます。ノード 1 またはノード 2 の警告イベント通知を受け取ったら、そのノードのパフォーマンス / ノードフェイルオーバー計画ページを表示して、テイクオーバーノードへのパフォーマンスの影響を推定できます。フェイルオーバーが発生した場合は、テイクオーバーノードの過負荷を回避するための対処を実行できます。ノードの使用済みパフォーマンス容量の合計が 200% を下回っている間に対処を行うと、この期間にフェイルオーバーが発生してもテイクオーバーノードのレイテンシが許容できないレベルに到達することはありません。
