---
permalink: performance-checker/concept-collecting-data-and-monitoring-workload-performance.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager では、ワークロードアクティビティを 5 分間隔で収集および分析してパフォーマンスイベントを特定するほか、構成の変更を 15 分間隔で検出します。5分ごとのパフォーマンスとイベントの履歴データが最大30日分保持され、そのデータを使用して監視対象のすべてのワークロードの想定範囲が予測されます。 
---
= データを収集してワークロードのパフォーマンスを監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ワークロードアクティビティを 5 分間隔で収集および分析してパフォーマンスイベントを特定するほか、構成の変更を 15 分間隔で検出します。5分ごとのパフォーマンスとイベントの履歴データが最大30日分保持され、そのデータを使用して監視対象のすべてのワークロードの想定範囲が予測されます。

[NOTE]
====
この章では、動的なしきい値の仕組みと、それらを使用してワークロードのパフォーマンスを監視する方法について説明します。この章の内容は、ユーザ定義またはシステム定義のパフォーマンスしきい値の違反による統計やイベントには該当しません。

====
Unified Managerでは、少なくとも3日分のワークロードアクティビティを収集して分析してから、[パフォーマンス/ボリュームの詳細]ページおよび[イベントの詳細]ページに表示するI/O応答時間と処理の想定範囲を決定します。このアクティビティを収集して表示される想定範囲には、ワークロードアクティビティにおける変化がすべて反映されるわけではありません。3日間のアクティビティを収集したあと、Unified Managerでは想定範囲を24時間ごとに午前12時に調整し、ワークロードアクティビティの変化が反映された、より正確なパフォーマンスしきい値を設定します。

Unified Managerでボリュームの監視を開始してから最初の4日間に、前回のデータ収集からの経過時間が24時間を超える期間がある場合、そのボリュームの想定範囲はパフォーマンス/ボリュームの詳細ページのグラフに表示されません。前回の収集よりも前に検出されたイベントは引き続き表示されます。

[NOTE]
====
システム時間が夏時間（DST）に切り替わると、監視しているワークロードのパフォーマンスの統計で使用する想定範囲が変わります。Unified Managerは、想定範囲の修正を即座に開始しますが、完了までに15日間ほどかかります。その間もUnified Managerの使用は継続できますが、Unified Managerは想定範囲を使用してイベントを検出するため、一部のイベントは正確でなくなる可能性があります。時間の変更前に検出されたイベントは影響を受けません。クラスタまたはUnified Managerサーバの時間を以前の時間に手動で変更した場合も、イベントの分析結果に影響します。

====