---
permalink: performance-checker/concept-what-happens-to-performance-threshold-policies-when-an-object-is-moved-opm.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスしきい値ポリシーはストレージオブジェクトに割り当てられているため、オブジェクトを移動した場合、割り当てられているすべてのしきい値ポリシーが移動の完了後もオブジェクトに関連付けられたままになります。たとえば、ボリュームまたは LUN を別のアグリゲートに移動した場合、しきい値ポリシーは新しいアグリゲートのボリュームまたは LUN で引き続きアクティブになります。 
---
= オブジェクトの移動によるパフォーマンスしきい値ポリシーへの影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスしきい値ポリシーはストレージオブジェクトに割り当てられているため、オブジェクトを移動した場合、割り当てられているすべてのしきい値ポリシーが移動の完了後もオブジェクトに関連付けられたままになります。たとえば、ボリュームまたは LUN を別のアグリゲートに移動した場合、しきい値ポリシーは新しいアグリゲートのボリュームまたは LUN で引き続きアクティブになります。

アグリゲートやノードに追加の条件が割り当てられているなど、セカンダリカウンタ条件があるしきい値ポリシー（組み合わせポリシー）の場合、セカンダリカウンタ条件は、ボリュームまたは LUN が移動された新しいアグリゲートやノードに適用されます。

変更されたしきい値ポリシーを使用しているオブジェクトに対して新しいアクティブイベントが存在する場合、それらのイベントは廃止とマークされ、新たに定義されたしきい値ポリシーとしてカウンタの監視が開始されます。

ボリューム移動処理が実行されると、 ONTAP から情報変更イベントが送信されます。パフォーマンスエクスプローラページのイベントタイムラインとパフォーマンス/ボリュームの詳細ページに、変更イベントのアイコンが表示され、移動処理が完了した時間を示します。

[NOTE]
====
オブジェクトを別のクラスタに移動した場合、ユーザ定義のしきい値ポリシーはオブジェクトから削除されます。必要に応じて、移動処理の完了後にしきい値ポリシーをオブジェクトに割り当てる必要があります。ただし、動的なしきい値ポリシーとシステム定義のしきい値ポリシーは、新しいクラスタへの移動後にオブジェクトに自動的に適用されます。

====


== HA のテイクオーバーおよびギブバック時のしきい値ポリシーの機能

ハイアベイラビリティ（ HA ）構成でテイクオーバー処理またはギブバック処理が発生した場合、 1 つのノードから別のノードに移動されたオブジェクトのしきい値ポリシーは手動による移動処理の場合と同じように保持されます。Unified Manager ではクラスタの構成に変更がないかどうかを 15 分間隔でチェックするため、スイッチオーバーによる新しいノードへの影響は、クラスタの構成のポーリングが次に行われるときまで特定されません。

[NOTE]
====
15 分間の構成の変更の収集期間内にテイクオーバー処理とギブバック処理の両方が発生した場合、一方のノードからもう一方のノードへのパフォーマンス統計の移動が表示されないことがあります。

====


== アグリゲートの再配置時のしきい値ポリシーの機能

を使用して、ノード間でアグリゲートを移動する場合 `aggregate relocation start` コマンドでは、単一のしきい値ポリシーと組み合わせしきい値ポリシーの両方がすべてのオブジェクトで保持され、しきい値ポリシーのノードの部分が新しいノードに適用されます。



== MetroCluster スイッチオーバー中のしきい値ポリシー機能

MetroCluster 構成で 1 つのクラスタから別のクラスタにオブジェクトが移動された場合、ユーザ定義のしきい値ポリシーの設定は保持されません。それらのしきい値ポリシーが必要な場合は、パートナークラスタに移動されたボリュームおよび LUN に適用できます。オブジェクトが元のクラスタに戻ると、それらのユーザ定義のしきい値ポリシーが自動的に再適用されます。

xref:concept-volume-behavior-during-switchover-and-switchback.adoc[スイッチオーバーおよびスイッチバックの発生時のボリュームの動作]
