---
permalink: performance-checker/reference-managed-objects-pane.html 
sidebar: sidebar 
keywords:  
summary: Performance Summary タブの Managed Objects ペインには、クラスタのストレージオブジェクトタイプと数の概要が表示されます。このペインでは、各クラスタ内のオブジェクトのステータスを追跡できます。 
---
= [Managed Objects] ペイン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance Summary タブの Managed Objects ペインには、クラスタのストレージオブジェクトタイプと数の概要が表示されます。このペインでは、各クラスタ内のオブジェクトのステータスを追跡できます。

管理対象オブジェクトの数は、前回の収集期間以降のポイントインタイムデータです。新しいオブジェクトは 15 分間隔で検出されます。

いずれかのオブジェクトタイプのリンクされた番号をクリックすると、そのオブジェクトタイプのオブジェクトパフォーマンスインベントリページが表示されます。オブジェクトのインベントリページには、このクラスタ上のオブジェクトだけが表示されます。

管理対象オブジェクトは次のとおりです。

* * ノード * ：
+
クラスタ内の物理システム。

* * アグリゲート *
+
保護およびプロビジョニングの際に 1 つのユニットとして管理可能な、複数の Redundant Array of Independent Disks （ RAID ）グループの集まりです。

* * ポート * ：
+
ネットワーク上の他のデバイスへの接続に使用されるノード上の物理接続ポイント。

* * SVM *
+
一意のネットワークアドレスでネットワークアクセスを提供する仮想マシン。SVM は、固有のネームスペースからデータを提供でき、クラスタの残りのエンティティとは別に管理することができます。

* * ボリューム *
+
サポートされているプロトコルを使用してアクセス可能なユーザデータを格納する論理エンティティ。数にはFlexVol とFlexGroup の両方のボリュームが含まれます。FlexGroup コンスティチュエントとInfinite Volumeは含まれません。

* * LUN*
+
Fibre Channel （ FC ）論理ユニットまたは iSCSI 論理ユニットの識別子。通常、論理ユニットはストレージボリュームに対応し、コンピュータオペレーティングシステム内ではデバイスとして表されます。

* * LIF *
+
ノードへのネットワークアクセスポイントを表す論理ネットワークインターフェイス。数にはすべてのLIFタイプが含まれます。


