---
permalink: performance-checker/reference-performance-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: このページには、選択したFlexVol 、FlexGroup 、またはFlexGroup コンスティチュエントワークロードのすべてのI/Oアクティビティと処理について、詳細なパフォーマンス統計が表示されます。ボリュームの統計やイベントを表示する期間を選択できます。イベントは、パフォーマンスイベントとI/Oパフォーマンスに影響を及ぼしている可能性のある変更を表しています。 
---
= パフォーマンス/ボリュームの詳細ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このページには、選択したFlexVol 、FlexGroup 、またはFlexGroup コンスティチュエントワークロードのすべてのI/Oアクティビティと処理について、詳細なパフォーマンス統計が表示されます。ボリュームの統計やイベントを表示する期間を選択できます。イベントは、パフォーマンスイベントとI/Oパフォーマンスに影響を及ぼしている可能性のある変更を表しています。



== 履歴データチャート

選択したボリュームのパフォーマンス分析の履歴データを表示します。スライダをクリックしてドラッグすることで期間を指定できます。スライダを動かすと期間が増減します。期間外のデータはグレー表示になります。チャートの下部にあるスライダを使用して、履歴データの範囲内で期間を移動できます。表示されているチャートとイベントを含めたページ全体には、期間内の使用可能なデータが反映されます。Unified Managerがこのページに保持できる履歴データは最大30日分です。

[NOTE]
====
履歴データチャートで2日以上の期間を選択すると、画面の解像度によっては、その期間における応答時間とIOPSの最大値が表示されます。

====


== オプション（ Options ）

* *時間セレクタ*
+
ページ全体でボリュームのパフォーマンス統計を表示する期間を指定します。1日（* 1d *）から30日間（* 30d *）をクリックするか、* Custom *をクリックしてカスタム範囲を選択できます。カスタム範囲の場合は、開始日と終了日を選択し、*更新*をクリックしてページ全体を更新できます。

+
[NOTE]
====
パフォーマンス/ボリュームの詳細ページにアクセスし、イベントの詳細ページでボリューム名のリンクをクリックすると、現在の日付の1日前または5日前などの期間が自動的に選択されます。履歴データチャートでスライダを移動すると、期間はカスタム範囲に変わりますが、*カスタム*時間セレクタは選択されません。デフォルトの時間セレクタが選択されたままになります。

====
* ***データをブレークダウン***
+
選択したボリュームのより詳細なパフォーマンス統計を表示するために、パフォーマンス/ボリュームの詳細ページに追加できるグラフのリストが表示されます。


