---
permalink: performance-checker/reference-components-of-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: Performance / Node Failover Planning ページのコンポーネントが、グリッドと Comparing ペインに表示されます。これらのセクションで、ノードのフェイルオーバーによるテイクオーバーノードのパフォーマンスへの影響を評価できます。 
---
= Node Failover Planning ページのコンポーネント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance / Node Failover Planning ページのコンポーネントが、グリッドと Comparing ペインに表示されます。これらのセクションで、ノードのフェイルオーバーによるテイクオーバーノードのパフォーマンスへの影響を評価できます。



== パフォーマンス統計グリッド

Performance/NodeFailover Planning ヘエシには、レイテンシ、 IOPS 、利用率、使用済みパフォーマンス容量の統計を含むグリッドが表示されます。

[NOTE]
====
このページおよびPerformance/NodePerformance Explorerページに表示されるIOPS値は異なる可能性があります。

====
グリッドでは、各ノードに次のいずれかのロールが割り当てられます。

* プライマリ
+
HA パートナーで障害が発生した場合にパートナーをテイクオーバーするノードです。ルートオブジェクトは常にプライマリノードです。

* パートナー
+
フェイルオーバーシナリオで障害が発生したノードです。

* 推定テイクオーバー
+
プライマリノードと同じ。このノードに対して表示されるパフォーマンス統計は、障害が発生したパートナーをテイクオーバーしたあとのテイクオーバーノードのパフォーマンスを示します。



[NOTE]
====
テイクオーバーノードのワークロードはフェイルオーバー後の両方のノードのワークロードの合計に相当しますが、推定テイクオーバーノードの統計はプライマリノードとパートナーノードの統計の合計にはなりません。たとえば、プライマリノードのレイテンシが 2 ミリ秒 / 処理でパートナーノードのレイテンシが 3 ミリ秒 / 処理の場合に、推定テイクオーバーノードのレイテンシが 4 ミリ秒 / 処理になることがありますこの値は Unified Manager で計算されます。

====
パートナーノードをルートオブジェクトにする場合は、そのノードの名前をクリックします。Performance/NodePerformance Explorer ヘエシが表示されたら、 * Failover Planning * タブをクリックして、このノード障害シナリオにおけるパフォーマンスの変化を確認できます。たとえば、 Node1 がプライマリノードで Node2 がパートナーノードの場合、 Node2 をクリックしてプライマリノードに切り替えることができます。これにより、どちらのノードで障害が発生したかに応じて、予想されるパフォーマンスの変化を確認することができます。



== 比較ペイン

デフォルトでは ' 比較ペインに表示される構成部品は次のとおりです

* * イベントチャート *
+
これらの値は、 Performance/NodePerformance Explorer ページと同じ形式で表示されます。プライマリノードのみが対象になります。

* * カウンタチャート *
+
グリッドに表示されるパフォーマンスカウンタの過去の統計が表示されます。各チャートの推定テイクオーバーノードのグラフには、フェイルオーバーが特定の時点で発生した場合の推定パフォーマンスが表示されます。

+
たとえば、利用率のチャートに、推定テイクオーバーノードの 2 月 3 日の午前 11 時の利用率が 73% と表示されているとします2 月 8 日に。その時点でフェイルオーバーが発生した場合は、テイクオーバーノードの利用率は 73% になります。

+
過去の統計は、テイクオーバーノードに過大な負荷をかけずにフェイルオーバーを開始する最適な時刻を特定するのに役立ちます。テイクオーバーノードの予測パフォーマンスを確認して、許容される時間にフェイルオーバーをスケジュールすることができます。



デフォルトでは、ルートオブジェクトとパートナーノードの両方の統計情報が比較ペインに表示されます。Performance/NodePerformance Explorer ページとは異なり、このページには統計比較用のオブジェクトを追加するための *Add* ボタンは表示されません。

[Performance/Node Performance Explorer] ページで行うのと同じ方法で、 [Comparing （比較） ] ペインをカスタマイズできます。グラフをカスタマイズする例を次に示します。

* ノード名をクリックすると、カウンタグラフでそのノードの統計の表示と非表示が切り替わります。
* 特定のカウンタの詳細なグラフを新しいウィンドウに表示するには、 * Zoom View * をクリックします。

