---
permalink: performance-checker/task-determining-whether-a-workload-has-a-performance-issue.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerを使用して、検出されたパフォーマンスイベントの原因が本当にクラスタ上のパフォーマンス問題 であるかどうかを判断できます。イベントの原因はアクティビティの急増である場合があります。たとえばその結果として応答時間が増加したが、現在は通常レベルに戻っている場合などです。 
---
= ワークロードにパフォーマンス問題 があるかどうかを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用して、検出されたパフォーマンスイベントの原因が本当にクラスタ上のパフォーマンス問題 であるかどうかを判断できます。イベントの原因はアクティビティの急増である場合があります。たとえばその結果として応答時間が増加したが、現在は通常レベルに戻っている場合などです。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 分析するボリュームまたは関連するLUNの名前を特定しておく必要があります。
* Unified Managerで最低5日間のパフォーマンス統計がクラスタから収集されて分析されている必要があります。




== このタスクについて

イベントの詳細ページを表示している場合は、ボリュームの名前のリンクをクリックして、パフォーマンス/ボリュームの詳細ページに直接移動できます。



== 手順

. *検索*バーに、ボリューム名の最初の3文字以上を入力します。
+
ボリュームの名前が検索結果に表示されます。

. ボリュームの名前をクリックします。
+
ボリュームがPerformance / Volume Detailsページに表示されます。

. 履歴データ*チャートで、*5d*をクリックして過去5日間の履歴データを表示します。
. 次の質問を回答 に送信する*レイテンシ*チャートを確認します。
+
** 新しいパフォーマンスイベントがあるか。
** 過去にボリュームで問題が発生したことを示す過去のパフォーマンスイベントがあるか。
** 急増が想定範囲内であっても、応答時間に急増はありますか。
** パフォーマンスに影響した可能性のあるクラスタ構成への変更があったか。パフォーマンスイベント、アクティビティの急増、または応答時間に影響した可能性のある最近の構成変更がボリュームの応答時間に表示されない場合は、クラスタが原因のパフォーマンス問題 を除外できます。



