---
permalink: performance-checker/task-configuring-a-connection-between-a-unified-manager-server-and-an-external-data-provider.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager から外部サーバにクラスタのパフォーマンスデータを送信できます。送信する統計データの種類およびデータの送信間隔を指定できます。 
---
= Unified Manager サーバから外部データプロバイダへの接続の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager から外部サーバにクラスタのパフォーマンスデータを送信できます。送信する統計データの種類およびデータの送信間隔を指定できます。



== 作業を開始する前に

* Unified Manager サーバのメンテナンスコンソールへのログインが許可されているユーザ ID が必要です。
* 外部データプロバイダに関する次の情報が必要です。
+
** サーバの名前または IP アドレス（ IPv4 または IPv6 ）
** サーバのデフォルトポート（デフォルトポート 2003 を使用していない場合）


* Unified Manager サーバから統計データを受信できるようにリモートサーバと他社製ソフトウェアを設定しておく必要があります。
* 送信する統計情報のグループを確認しておく必要があります。
+
** performion_indicator ：パフォーマンスモニタの統計情報
** RESOURCE_UTILIZATION ：リソース利用率とパフォーマンスモニタの統計データ
** DRILL_DOWN ：すべての統計データ


* 統計情報を送信する間隔を 5 分、 10 分、または 15 分で指定する必要があります
+
デフォルトでは、 Unified Manager は 5 分間隔で統計データを収集します。送信間隔を 10 分（または 15 分）に設定すると、各送信中に送信されるデータ量は、デフォルトの 5 分間隔を使用する場合の 2 倍（または 3 倍）になります。

+
[NOTE]
====
Unified Manager のパフォーマンス収集間隔を 10 分または 15 分に変更した場合は、送信間隔も Unified Manager の収集間隔以上に変更する必要があります。

====




== このタスクについて

1 台の Unified Manager サーバと 1 台の外部データプロバイダサーバの間に接続を設定できます。



== 手順

. Unified Manager サーバのメンテナンスコンソールにメンテナンスユーザとしてログインします。
+
Unified Manager メンテナンスコンソールのプロンプトが表示されます。

. メンテナンスコンソールで、 * 外部データプロバイダ * メニューオプションの番号を入力します。
+
External Server Connection （外部サーバ接続）メニューが表示されます。

. [ サーバー接続の追加 / 変更 *] メニューオプションの番号を入力します。
+
現在のサーバ接続情報が表示されます。

. プロンプトが表示されたら、と入力します `y` 続行します。
. プロンプトが表示されたら、宛先サーバの IP アドレスまたは名前、およびサーバポート情報を入力します（デフォルトポート 2003 と異なる場合）。
. プロンプトが表示されたら、と入力します `y` 入力した情報が正しいことを確認します。
. 任意のキーを押して、 [External Server Connection] メニューに戻ります。
. [ サーバー構成の変更 *] メニューオプションの番号を入力します。
+
現在のサーバ設定情報が表示されます。

. プロンプトが表示されたら、と入力します `y` 続行します。
. プロンプトが表示されたら、送信する統計のタイプ、統計情報の送信間隔、および統計情報の送信を今すぐ有効にするかどうかを入力します。
+
|===
| 用途 | 入力するコマンド 


 a| 
統計グループ ID
 a| 
`0` - performion_indicator（デフォルト）

`1` - resource_utilizationを指定します

`2` -ドリルダウン



 a| 
ベンダータグ
 a| 
統計情報を外部サーバに保存するフォルダのわかりやすい名前。デフォルト名は「 netapp-performance 」ですが、別の値を入力できます。

点線表記を使用すると、階層フォルダ構造を定義できます。たとえば、と入力します `stats.performance.netapp` 統計は、* stats *>* performance *>* NetApp *に保存されます。



 a| 
送信間隔
 a| 
`5` （デフォルト）、 `10`または `15` 分



 a| 
有効化 / 無効化
 a| 
`0` -無効

`1` -有効（デフォルト）

|===
. プロンプトが表示されたら、と入力します `y` 入力した情報が正しいことを確認します。
. 任意のキーを押して、 [External Server Connection] メニューに戻ります。
. を入力します `x` をクリックしてメンテナンスコンソールを終了します。




== 結果

接続の設定が完了すると、選択したパフォーマンスデータが指定したサーバに指定した送信間隔で送信されます。送信された指標がGraphiteに表示されるまでに数分かかります。新しい指標を表示するには、ブラウザの表示の更新が必要になる場合があります。
