---
permalink: performance-checker/task-responding-to-system-defined-performance-threshold-events.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager を使用して、パフォーマンスカウンタがシステム定義の警告しきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近のイベントがパフォーマンスイベントに関与しているかどうかを判断できます。 
---
= システム定義のパフォーマンスしきい値のイベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を使用して、パフォーマンスカウンタがシステム定義の警告しきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近のイベントがパフォーマンスイベントに関与しているかどうかを判断できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントがある必要があります。




== 手順

. イベントの詳細ページを表示して、イベントに関する情報を確認します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「 Node utilization value of 90 % has triggered a WARNING event based on threshold setting of 85 % 」というメッセージは、クラスタオブジェクトに対してノード使用率警告イベントが発生したことを示しています。

. イベントトリガー時間 * をメモしておき、このイベントの原因となった可能性のある他のイベントが同時に発生したかどうかを調べることができます。
. システム診断 * で、クラスタオブジェクトに対してシステム定義のポリシーで実行されている分析タイプの簡易概要を確認します。
+
一部のイベントについては、診断の横に、その診断で問題が見つかったかどうかを示す緑または赤のアイコンが表示されます。システム定義のその他のタイプのイベントのカウンタグラフには、オブジェクトのパフォーマンスが表示されます。

. [ 推奨される操作 ] で、 [ ヘルプ ] [ この操作を実行する ] リンクをクリックして、自分でパフォーマンスイベントを解決するために実行できる推奨される操作を表示します。

