---
permalink: performance-checker/task-changing-the-performance-statistics-collection-interval.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: パフォーマンス統計のデフォルトの収集間隔は 5 分です。大規模なクラスタからの収集がデフォルトの時間内に完了しない場合は、この間隔を 10 分または 15 分に変更できます。この設定は、この Unified Manager インスタンスで監視しているすべてのクラスタからの統計の収集に適用されます。 
---
= パフォーマンス統計データの収集間隔を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンス統計のデフォルトの収集間隔は 5 分です。大規模なクラスタからの収集がデフォルトの時間内に完了しない場合は、この間隔を 10 分または 15 分に変更できます。この設定は、この Unified Manager インスタンスで監視しているすべてのクラスタからの統計の収集に適用されます。



== 作業を開始する前に

Unified Manager サーバのメンテナンスコンソールへのログインが許可されているユーザ ID とパスワードが必要です。



== このタスクについて

パフォーマンス統計の収集が時間内に完了しなかった問題 は、バナーメッセージで示されます `Unable to consistently collect from cluster <cluster_name>` または `Data collection is taking too long on cluster <cluster_name>`。

収集間隔の変更が必要になるのは、統計の収集が問題のためです。その他の理由でこの設定を変更しないでください。

[NOTE]
====
この値をデフォルト設定の 5 分から変更すると、 Unified Manager でレポートされるパフォーマンスイベントの数や頻度に影響する可能性があります。たとえば、システム定義のパフォーマンスしきい値ポリシーでは、ポリシーを超えた状態が 30 分続くとイベントがトリガーされます。収集間隔が 5 分の場合は、収集間隔が 6 回連続でポリシーの違反となるようにする必要があります。一方、収集間隔が 15 分の場合は、 2 回の収集期間のみでポリシーの違反と判断されます。

====
Cluster Data Sourcesページの下部にあるメッセージは、現在の統計データ収集間隔を示します。



== 手順

. SSH を使用して、 Unified Manager ホストにメンテナンスユーザとしてログインします。
+
Unified Manager メンテナンスコンソールのプロンプトが表示されます。

. 「パフォーマンスポーリング間隔の設定 * 」というラベルの付いたメニューオプションの番号を入力し、 Enter キーを押します。
. プロンプトが表示されたら、メンテナンスユーザのパスワードをもう一度入力します。
. 設定する新しいポーリング間隔の値を入力し、 Enter キーを押します。




== 完了後

外部データプロバイダ（ Graphite など）への接続を現在設定してある場合は、 Unified Manager の収集間隔を 10 分または 15 分に変更したあと、データプロバイダの送信間隔も Unified Manager の収集間隔以上に変更する必要があります。
