---
permalink: performance-checker/task-responding-to-user-defined-performance-threshold-events.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager を使用して、パフォーマンスカウンタがユーザ定義の警告または重大のしきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近の健常性イベントがパフォーマンスイベントに関与しているかどうかを判断できます。 
---
= ユーザ定義のパフォーマンスしきい値イベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を使用して、パフォーマンスカウンタがユーザ定義の警告または重大のしきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近の健常性イベントがパフォーマンスイベントに関与しているかどうかを判断できます。



== 作業を開始する前に

* オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントがある必要があります。




== 手順

. イベントの詳細ページを表示して、イベントに関する情報を確認します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「レイテンシ値 456 ms/op has triggered a WARNING event based on threshold setting of 400 ms/op 」というメッセージは、オブジェクトに対してレイテンシ警告イベントが発生したことを示しています。

. ポリシー名にカーソルを合わせると、イベントをトリガーしたしきい値ポリシーの詳細が表示されます。
+
これには、ポリシー名、評価されるパフォーマンスカウンタ、超過した場合に重大または警告イベントが生成されるカウンタ値、およびカウンタが値を超える必要がある期間が含まれます。

. イベントトリガー時間 * をメモしておき、このイベントの原因となった可能性のある他のイベントが同時に発生したかどうかを調べることができます。
. 次のいずれかのオプションを使用してイベントをさらに詳しく調査し、パフォーマンスの問題を解決するための操作を実行する必要があるかどうかを判断します。
+
|===
| オプション | 調査方法 


 a| 
ソースオブジェクト名をクリックすると ' そのオブジェクトのエクスプローラページが表示されます
 a| 
このページでは、オブジェクトの詳細を表示して他の同様のストレージオブジェクトと比較し、他のストレージオブジェクトに同じタイミングでパフォーマンス問題が設定されているかどうかを確認できます。たとえば、同じアグリゲート上の他のボリュームにもパフォーマンス問題があるかどうかを確認できます。



 a| 
クラスタ名をクリックして、クラスタの概要ページを表示します。
 a| 
このページでは、オブジェクトが配置されているクラスタの詳細を表示して、他のパフォーマンスの問題が同時に発生していないかどうかを確認できます。

|===

