---
permalink: health-checker/concept-common-unified-manager-administrative-workflows-and-tasks.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerに関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性/容量/保護に悪影響を及ぼす状態の診断、保護関係の作成、失われたデータのリストアなどがあります。Infinite Volumeの設定と管理、および診断データのバンドルとテクニカルサポートへの送信（必要な場合）。 
---
= Unified Manager の一般的な健常性関連のワークフローとタスク
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerに関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性/容量/保護に悪影響を及ぼす状態の診断、保護関係の作成、失われたデータのリストアなどがあります。Infinite Volumeの設定と管理、および診断データのバンドルとテクニカルサポートへの送信（必要な場合）

Unified Manager では、ストレージ管理者がダッシュボードを表示して管理対象ストレージクラスタの全体的な容量、可用性、保護の状態の健全性を評価できるほか、発生の可能性がある具体的な問題を突き止めて確認し、診断を行い、解決のための割り当てを行うことができます。

管理対象ストレージオブジェクトのストレージ容量、データ可用性、または保護の信頼性に影響する、クラスタ、Storage Virtual Machine（SVM）、ボリューム、FlexGroup ボリューム、または保護関係に関連した最も重要な問題が、[ダッシュボード/概要]ページのシステムヘルスグラフおよびイベントに表示されます。重要な問題が特定されると、このページに適切なトラブルシューティングワークフローをサポートするためのリンクが表示されます。

Unified Manager は、 OnCommand Workflow Automation （ WFA ）などの関連管理ツールを含むワークフローにも含まれており、ストレージリソースを直接設定できます。

このドキュメントでは、次の管理タスクに関連する一般的なワークフローについて説明します。

* 可用性の問題を診断および管理する
+
ハードウェア障害またはストレージリソース構成で原因 が[ダッシュボード/概要]ページにデータ可用性イベントを表示する場合、ストレージ管理者は組み込みのリンクを使用して、該当するストレージリソースに関する接続情報を表示し、トラブルシューティングのアドバイスを表示し、他の管理者に問題 解決を割り当てることができます。

* パフォーマンスインシデントの設定と監視
+
OnCommand 管理者は、監視対象のストレージシステムリソースのパフォーマンスを監視し、管理することができます。詳細については、Unified Managerワークフローガイド-クラスタパフォーマンス管理を参照してください。

* ボリューム容量の問題を診断および管理する
+
[ダッシュボード/概要]ページにボリュームストレージ容量の問題が表示された場合、ストレージ管理者は、埋め込まれたリンクを使用して、該当するボリュームのストレージ容量に関連する現在と過去の傾向を表示したり、トラブルシューティングのアドバイスを参照したり、他の管理者に問題 の解決を割り当てたりすることができます。

* 保護関係の設定、監視、問題の診断
+
保護関係を作成して設定すると、ストレージ管理者は[ダッシュボード/概要]ページで保護関係に関連する潜在的な問題を確認できます。また、組み込みのリンクを使用して、保護関係の現在の状態、影響を受ける関係に関する現在および過去の保護ジョブの成功情報を確認できます。およびトラブルシューティングのアドバイスを提供し、他の管理者に問題 の解決方法を割り当てる。また、SnapMirror関係とSnapVault 関係を設定および管理することもできます。

* バックアップファイルの作成とバックアップファイルからのデータのリストア
* ストレージオブジェクトへのアノテーションの関連付け
+
ストレージ管理者は、ストレージオブジェクトにアノテーションを関連付けることで、ストレージオブジェクトに関連するイベントをフィルタリングして表示できます。これにより、イベントに関連する問題に優先順位を付けて解決することができます。

* テクニカルサポートへのサポートバンドルの送信
+
ストレージ管理者は、メンテナンスコンソールを使用して、サポートバンドルを取得し、テクニカルサポートに送信できます。問題で AutoSupport メッセージよりも詳しい診断とトラブルシューティングが必要な場合は、サポートバンドルをテクニカルサポートに送信する必要があります。

* インポート用の新しいレポートを作成しています
+
ストレージ管理者は、新規に作成できます `.rptdesign` Eclipse BIRT（Business Intelligence and Reporting Tools）プラグインを使用してファイルを保存する。これらのレポートは、Unified Manager UIにインポートして、Reportsページに表示できます。

+
レポートページに表示されるレポートには、ストレージオブジェクトの現在のステータスが示されます。現在の使用状況に基づいて、ストレージの調達に関する決定など、重要な意思決定を下すことができます。これらのレポートには、ボリューム、ディスクシェルフ、アグリゲートなどのストレージオブジェクトの詳細が表示されます。

+
Unified Manager UIのレポートページでは、生成したレポートに関する詳細情報を確認できます。レポートページでは、特定のレポートの検索、レポートの保存、削除を行うことができます。また、このページからレポートをスケジュール設定、共有、およびインポートすることもできます。

* Infinite Volumeの作成、設定、監視、保護
+
ストレージ管理者は、Workflow Automationツールを使用してInfinite Volumeのストレージクラスの作成、設定、定義を行ったあとに、Unified Managerを使用して、該当のボリュームとそのストレージクラスを対象とした監視、通知しきい値の設定、データポリシーの定義を行うことができます。必要に応じて、WFAとUnified Managerを使用してInfinite Volumeに対するデータ保護をセットアップできます。


