---
permalink: health-checker/concept-types-of-snapmirror-protection.html 
sidebar: sidebar 
keywords:  
summary: 導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。すべての種類の SnapMirror 保護では、フェイルオーバーによるディザスタリカバリ保護が提供されますが、パフォーマンス、バージョン依存性の解消、および複数のバックアップコピーによる保護については、提供される機能が異なります。 
---
= SnapMirror 保護のタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。すべての種類の SnapMirror 保護では、フェイルオーバーによるディザスタリカバリ保護が提供されますが、パフォーマンス、バージョン依存性の解消、および複数のバックアップコピーによる保護については、提供される機能が異なります。



== 従来型の SnapMirror 非同期保護関係

従来型の SnapMirror 非同期保護では、ソースボリュームとデスティネーションボリューム間のブロックレプリケーションによるミラー保護が提供されます。

従来型の SnapMirror 関係では、ブロックレプリケーションに基づいてミラー処理が行われるため、他の SnapMirror 関係よりも高速なミラー処理が可能です。ただし、従来型の SnapMirror 保護では、デスティネーションボリュームで実行されている ONTAP ソフトウェアのマイナーバージョンがソースボリュームと同じかそれよりも新しい必要があります（バージョン 8.x から 8.x 、 9.x から 9.x など）。



== バージョンに依存しないレプリケーションを使用した SnapMirror 非同期保護

バージョンに依存しないレプリケーションを使用したSnapMirror非同期保護では、ソースボリュームとデスティネーションボリューム間に論理レプリケーションによるミラー保護が提供されます。ボリュームで異なるバージョンのONTAP 8.3以降のソフトウェアを実行している場合でも同様です（バージョン8.3から8.3、8.3から9.1、9.0から8.3など）。

バージョンに依存しないレプリケーションを使用した SnapMirror 関係では、ミラー処理が従来型の SnapMirror 関係ほど高速ではありません。

実行速度が遅いため、バージョンに依存しないレプリケーション保護を使用する SnapMirror は、次の状況のどちらにも適していません。

* ソースオブジェクトには、保護対象のファイルが 1 、 000 万を超えています。
* 保護対象データの目標復旧時点が 2 時間以下である。（つまり、ソースのデータからの遅れが 2 時間未満のリカバリ可能なミラーデータが常にデスティネーションに含まれている必要があります）。


これらのいずれかの状況では、デフォルトの SnapMirror 保護をより高速なブロックレプリケーションベースで実行する必要があります。



== バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 非同期保護

バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 非同期保護では、ソースボリュームとデスティネーションボリューム間のミラー保護およびミラーデータの複数のコピーをデスティネーションに格納する機能が提供されます。

ストレージ管理者は、ソースからデスティネーションにミラーリングする Snapshot コピーを指定したり、ソースで削除されたコピーをデスティネーションに保持する期間を指定したりできます。

バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 関係では、ミラー処理が従来型の SnapMirror 関係ほど高速ではありません。



== 厳密な同期を使用した SnapMirror 同期保護

「 stict 」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーになります。セカンダリボリュームへのデータの書き込みでレプリケーションエラーが発生すると、プライマリボリュームに対するクライアント I/O が中断されます。



== 通常の同期を使用した SnapMirror 同期保護

「ル」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーである必要はないため、プライマリボリュームの可用性が確保されます。セカンダリボリュームへのデータの書き込みでレプリケーションエラーが発生すると、プライマリボリュームとセカンダリボリュームが同期されていない状態のまま、プライマリボリュームに対するクライアント I/O が継続されます。

[NOTE]
====
同期保護関係を健全性/ボリュームのインベントリページまたは健全性/ボリュームの詳細ページから監視する場合は、リストアボタンと関係操作ボタンは使用できません。

====