---
permalink: health-checker/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: アノテーションルールとは、ストレージオブジェクト（ボリューム、クラスタ、またはStorage Virtual Machine（SVM））にアノテーションをアノテートする基準を定義したものです。アノテーションルールは、条件グループまたは条件のいずれかを使用して定義できます。 
---
= Unified Manager でのアノテーションルールの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アノテーションルールとは、ストレージオブジェクト（ボリューム、クラスタ、または Storage Virtual Machine （ SVM ））をアノテートする基準を定義したものです。アノテーションルールは、条件グループまたは条件のいずれかを使用して定義できます。

* アノテーションには必ずアノテーションルールを関連付ける必要があります。
* アノテーションルールにはオブジェクトタイプを関連付ける必要があります。関連付けることができるオブジェクトタイプは 1 つだけです。
* Unified Manager でストレージオブジェクトに対してアノテーションが追加または削除されるのは、各監視サイクルの完了後、およびルールの作成、編集、削除、順序変更時です。
* アノテーションルールには 1 つ以上の条件グループを、各条件グループには 1 つ以上の条件を含めることができます。
* ストレージオブジェクトには複数のアノテーションを適用できます。特定のアノテーションに対するアノテーションルールの条件で別のアノテーションを使用して、すでにアノテートされているオブジェクトに別のアノテーションを追加することもできます。




== 条件：

複数の条件グループを作成し、各条件グループに 1 つ以上の条件を含めることができます。アノテーションのアノテーションルールに定義されたすべての条件グループを適用して、ストレージオブジェクトをアノテートすることができます。

条件グループ内の条件は論理 AND を使用して実行されます。条件グループのすべての条件が満たされている必要があります。条件はアノテーションルールを作成または変更すると作成され、条件グループのすべての条件を満たすストレージオブジェクトのみが適用、選択、およびアノテートの対象となります。アノテートするストレージオブジェクトの範囲を限定するには、条件グループで複数の条件を使用します。

次のオペランドと演算子を使用して必要な値を指定することで、ストレージオブジェクトの条件を作成できます。

|===
| ストレージオブジェクトのタイプ | 適用可能なオペランド 


 a| 
ボリューム
 a| 
* オブジェクト名
* 所有クラスタ名
* 所有 SVM 名
* 注釈




 a| 
SVM
 a| 
* オブジェクト名
* 所有クラスタ名
* 注釈




 a| 
クラスタ
 a| 
* オブジェクト名
* 注釈


|===
ストレージ・オブジェクトのオペランドとしてアノテーションを選択すると 'is' 演算子を使用できますそれ以外のオペランドについては ' 演算子として Is または Contains を選択できます「 Is 」演算子を選択した場合は、選択したオペランドの値が指定した値と完全に一致する場合に条件が評価されます。"`contains" 演算子を選択すると、条件は次のいずれかの条件を満たすように評価されます。

* 選択したオペランドの値が指定した値と完全に一致する。
* 選択したオペランドの値に指定した値が含まれる。




== 条件を使用したアノテーションルールの例

ボリュームに対して条件グループが 1 つ設定されたアノテーションルールで、次の 2 つの条件が定義されているとします。

* 名前に「 vol 」を含む
* SVM 名は「 `d ata_svm 」です。


このアノテーションルールでは、名前に「 vol 」を含み、「 `d ata_svm 」という名前の SVMs でホストされているすべてのボリュームが、選択したアノテーションとアノテーションタイプでアノテートされます。



== 条件グループ

条件グループは論理 OR を使用して実行され、ストレージオブジェクトに適用されます。ストレージオブジェクトがアノテートされるためには、いずれかの条件グループの要件を満たす必要があります。すべての条件グループの条件を満たすすべてのストレージオブジェクトがアノテートされます。条件グループを使用して、アノテートするストレージオブジェクトの範囲を広げることができます。



== 条件グループを使用したアノテーションルールの例

ボリュームに対する条件グループが 2 つ設定されたアノテーションルールで、各グループにそれぞれ次の 2 つの条件が定義されているとします。

* 条件グループ 1
+
** 名前に「 vol 」を含む
** SVM 名が「 `d ATA_SVM` 」である場合、この条件グループでは、名前に「 vol 」を含み、「 `d ATA_SVM` 」という名前の SVM でホストされているすべてのボリュームがアノテートされます。


* 条件グループ 2.
+
** 名前に「 vol 」を含む
** data-priority のアノテーション値は「 critical 」ですこの条件グループは ' 名前に「 vol 」を含み ' data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリュームをアノテートします




これらの 2 つの条件グループを含むアノテーションルールをストレージオブジェクトに適用した場合、次のストレージオブジェクトがアノテートされます。

* 名前に「 vol 」を含み、「 'd ata_SVM' 」という名前の SVM でホストされているすべてのボリューム
* 名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリューム

