---
permalink: health-checker/reference-system-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: System Configuration メニューでは、サーバのステータスの表示、仮想マシンのリブートとシャットダウンなど、さまざまなオプションを指定して仮想アプライアンスを管理できます。 
---
= System Configuration （システム設定）メニュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Configuration メニューでは、サーバのステータスの表示、仮想マシンのリブートとシャットダウンなど、さまざまなオプションを指定して仮想アプライアンスを管理できます。

[NOTE]
====
Unified ManagerがRed Hat Enterprise Linux、CentOS、またはMicrosoft Windowsにインストールされている場合は、System Configurationメニューを使用できません。

====
次のメニュー項目を選択できます。

* * サーバーステータスを表示 *
+
現在のサーバステータスを表示します。ステータスには「 Running 」と「 Not Running 」があります。

+
サーバが実行されていない場合は、テクニカルサポートに連絡する必要があります。

* * 仮想マシンの再起動 *
+
すべてのサービスを停止して仮想マシンをリブートします。リブート後、仮想マシンとサービスが再起動します。

* * 仮想マシンのシャットダウン *
+
すべてのサービスを停止して、仮想マシンをシャットダウンします。

+
このオプションは、仮想マシンコンソールからのみ選択できます。

* * < ログインユーザー > ユーザーパスワード * を変更します
+
現在ログインしているユーザのパスワードを変更します。変更できるのはメンテナンスユーザだけです。

* * データディスクのサイズを増やします。 *
+
仮想マシンのデータディスク（ディスク 3 ）のサイズを拡張します。

* * スワップ・ディスク・サイズの増加 *
+
仮想マシンのスワップディスク（ディスク 2 ）のサイズを拡張します。

* * タイムゾーンの変更 *
+
タイムゾーンを自分の場所に変更します。

* * NTP サーバーを変更 *
+
IP アドレスや Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）などの NTP サーバ設定を変更します。

* * OCUMバックアップ*からリストアします
+
以前にバックアップしたバージョンから Unified Manager データベースと設定をリストアします。

* * サーバー証明書をリセット *
+
サーバセキュリティ証明書をリセットします。

* * ホスト名を変更 *
+
仮想アプライアンスがインストールされているホストの名前を変更します。

* * 戻る *
+
System Configuration （システム設定）メニューを終了し、 Main Menu （メインメニュー）に戻ります。

* * 終了 *
+
メンテナンスコンソールメニューを終了します。


