---
permalink: health-checker/reference-network-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: Network Configuration メニューでは、ネットワーク設定を管理できます。このメニューは、 Unified Manager ユーザインターフェイスを使用できない場合に使用してください。 
---
= Network Configuration （ネットワーク設定）メニュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Network Configuration メニューでは、ネットワーク設定を管理できます。このメニューは、 Unified Manager ユーザインターフェイスを使用できない場合に使用してください。

[NOTE]
====
Unified Manager が Red Hat Enterprise Linux 、 CentOS 、または Microsoft Windows にインストールされている場合は、このメニューを使用できません。

====
次のメニュー項目を選択できます。

* * IP アドレス設定 * を表示します
+
仮想アプライアンスの現在のネットワーク設定について、 IP アドレス、ネットワーク、ブロードキャストアドレス、ネットマスク、ゲートウェイ、 および DNS サーバです。

* * IP アドレス設定の変更 *
+
IP アドレス、ネットマスク、ゲートウェイ、 DNS サーバなど、仮想アプライアンスのネットワーク設定を変更できます。メンテナンスコンソールでネットワーク設定を DHCP から静的ネットワークに切り替えた場合は、ホスト名を編集できません。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * ドメイン名検索設定を表示 *
+
ホスト名の解決に使用されるドメイン名検索リストが表示されます。

* * ドメイン名検索設定の変更 *
+
ホスト名を解決する際に検索するドメイン名を変更できます。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * スタティックルートを表示 *
+
現在の静的ネットワークルートが表示されます。

* * スタティックルートの変更 *
+
静的ネットワークルートを追加または削除できます。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

+
** * ルートを追加 *
+
静的ルートを追加できます。

** * ルートの削除 *
+
静的ルートを削除できます。

** * 戻る *
+
メインメニュー * に戻ります。

** * 終了 *
+
メンテナンスコンソールを終了します。



* * ネットワークインターフェイスを無効にします。 *
+
使用可能なネットワークインターフェイスを無効にします。使用可能なネットワークインターフェイスが 1 つしかない場合は、それを無効にすることはできません。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * ネットワーク・インターフェイスを有効にする *
+
使用可能なネットワークインターフェイスを有効にします変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * 変更を確定 *
+
仮想アプライアンスのネットワーク設定に加えた変更を適用します。変更を有効にするには、このオプションを選択する必要があります。そうしないと、変更は行われません。

* * ホストに Ping を実行します *
+
IP アドレスの変更や DNS 設定を確認するために、ターゲットホストに ping を実行します。

* * デフォルト設定に復元 *
+
すべての設定を工場出荷時のデフォルトにリセットします。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * 戻る *
+
メインメニュー * に戻ります。

* * 終了 *
+
メンテナンスコンソールを終了します。


