---
permalink: health-checker/task-creating-custom-rules.html 
sidebar: sidebar 
keywords:  
summary: データセンターの要件に基づいて、カスタムルールを作成してデータポリシーに追加することで、Infinite Volumeを備えたSVMに書き込まれるデータの配置を決めることができます。既存のテンプレートを使用せずに、［ルールの作成］ダイアログボックスからカスタムルールを作成できます。 
---
= カスタムルールを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンターの要件に基づいて、カスタムルールを作成してデータポリシーに追加することで、Infinite Volumeを備えたSVMに書き込まれるデータの配置を決めることができます。既存のテンプレートを使用せずに、［ルールの作成］ダイアログボックスからカスタムルールを作成できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* ストレージクラスを含むInfinite Volumeを備えたSVMが含まれるクラスタをUnified Managerデータベースに追加しておく必要があります。




== このタスクについて

データポリシータブは、Infinite Volumeを備えたSVMの場合にのみ表示されます。



== 手順

. 左側のナビゲーションペインで、* Health *>* SVM*をクリックします。
. *ケンセンセイ/ Storage Virtual Machines *インヘントリヘエシで、適切なSVMを選択します。
. [*データポリシー*]をクリックします。
. [ 作成（ Create ） ] をクリックします。
. [ルールの作成*]ダイアログボックスの[テンプレート*]リストから[*カスタムルール*]を選択します。
. [*Matching Criteria*]領域で、必要に応じて条件を追加します。
+
条件を使用すると、ファイルタイプ、ディレクトリパス、または所有者に基づいてルールを作成できます。これらの条件の組み合わせが条件セットです。たとえば' Place all .mp3 owned by John in bronze storage class.

. 一致するコンテンツをストレージクラスに配置する*ドロップダウン・リストから適切なストレージ・クラスを選択します
. [ 作成（ Create ） ] をクリックします。
+
新しく作成したルールが[データポリシー]タブに表示されます。

. データポリシーに対して行ったその他の変更をプレビューします。
. Activate *をクリックして、SVMのルールのプロパティの変更をアクティブ化します。

