---
permalink: health-checker/task-adding-additional-network-interfaces.html 
sidebar: sidebar 
keywords:  
summary: ネットワークトラフィックを分離する必要がある場合は、新しいネットワークインターフェイスを追加できます。 
---
= ネットワークインターフェイスの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークトラフィックを分離する必要がある場合は、新しいネットワークインターフェイスを追加できます。



== 作業を開始する前に

vSphere を使用して仮想アプライアンスにネットワークインターフェイスを追加しておく必要があります。

仮想アプライアンスの電源をオンにする必要があります。



== このタスクについて

[NOTE]
====
Unified Manager が Red Hat Enterprise Linux または Microsoft Windows にインストールされている場合は、この処理を実行できません。

====


== 手順

. vSphereコンソール*のメインメニュー*で、* System Configuration *>* Reboot Operating System *を選択します。
+
リブート後、新たに追加したネットワークインターフェイスはメンテナンスコンソールで検出できます。

. メンテナンスコンソールにアクセスします
. ネットワーク構成 *>*Enable Network Interface* を選択します。
. 新しいネットワークインターフェイスを選択し、 * Enter * キーを押します。
+
* eth1 * を選択し、 * Enter * を押します。

. 「 * y * 」と入力してネットワーク・インターフェイスを有効にします。
. ネットワーク設定を入力します。
+
静的インターフェイスを使用している場合、または DHCP が検出されない場合は、ネットワーク設定を入力するように求められます。

+
ネットワーク設定を入力すると、自動的に *Network Configuration* メニューに戻ります。

. [ 変更のコミット *] を選択します。
+
ネットワークインターフェイスを追加するには、変更をコミットする必要があります。


