---
permalink: health-checker/task-resolving-a-protection-job-failure.html 
sidebar: sidebar 
keywords:  
summary: このワークフローでは、 Unified Manager のダッシュボードで保護ジョブの失敗を特定して解決する方法の例を示します。 
---
= 保護ジョブの失敗を解決する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、 Unified Manager のダッシュボードで保護ジョブの失敗を特定して解決する方法の例を示します。



== 作業を開始する前に

このワークフローの一部のタスクはOnCommand 管理者ロールでログインする必要があるため、の説明に従って、さまざまな機能を使用するために必要なロールを把握しておく必要があります xref:reference-unified-manager-roles-and-capabilities.adoc[Unified Manager のユーザロールと機能]。



== このタスクについて

このシナリオでは、[ダッシュボード/概要]ページにアクセスして、保護ジョブに問題がないかどうかを確認します。保護インシデント領域には、ボリュームで保護ジョブの失敗エラーが表示され、ジョブ終了インシデントがあることがわかりました。このエラーを調査して、原因と潜在的な解決策を特定します。



== 手順

. [ダッシュボード*未解決のインシデントとリスク*]領域の[保護インシデント*]パネルで、[保護ジョブ失敗*]イベントをクリックします。
+
[TIP]
====
イベントのリンクされたテキストがフォームに書き込まれます `object_name:/object_name - Error Name`など `cluster2_src_svm:/cluster2_src_vol2 - Protection Job Failed`。

====
+
失敗した保護ジョブのイベントの詳細ページが表示されます。

. 「概要」エリアの「原因」フィールドのエラーメッセージを確認して、問題を特定し、考えられる対処方法を評価します。
+
を参照してください xref:task-identifying-the-problem-and-performing-corrective-actions-for-a-failed-protection-job.adoc[保護ジョブが失敗した場合の問題の特定と対処策の実施]。


