---
permalink: health-checker/task-resolving-volume-offline-issues.html 
sidebar: sidebar 
keywords:  
summary: 'このワークフローでは、Unified Managerのダッシュボード/概要ページの可用性領域に表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者がUnified Managerを使用して、[ダッシュボード/概要]ページに表示される1つ以上のボリュームオフラインイベントのトラブルシューティングを行います。' 
---
= ボリュームのオフライン状態の問題を解決する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、Unified Managerのダッシュボード/概要ページの可用性領域に表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者がUnified Managerを使用して、[ダッシュボード/概要]ページに表示される1つ以上のボリュームオフラインイベントのトラブルシューティングを行います。



== 作業を開始する前に

オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。



== このタスクについて

ボリュームがオフライン状態と報告された場合は、いくつかの理由が考えられ

* SVM 管理者が意図的にボリュームをオフラインにした。
* ボリュームをホストしているクラスタノードが停止し、その HA ペアパートナーへのストレージフェイルオーバーも失敗した。
* ボリュームをホストしている SVM のルートボリュームをホストしているノードが停止したために、 SVM が停止した。
* 2 つの RAID ディスクで同時に障害が発生したために、ボリュームをホストしているアグリゲートが停止した。


ダッシュボード/概要ページおよび健全性/クラスタ、健全性/ SVM、健全性/ボリュームの詳細ページを使用して、これらの可能性を確認したり、それらを除外したりできます。



== 手順

. [未解決のインシデントとリスク*（Unresolved Incidents and Risks *）]セクションの[*可用性*（* Availability *）]パネルで、ボリュームオフラインイベントに表示されるハイパーテキストリンクをクリックします。
+
可用性インシデントのイベント詳細ページが表示されます。

. このページで、 SVM 管理者が対象のボリュームをオフラインにしたことを示すメモがないか確認します。
. イベント * の詳細ページで、次のタスクの 1 つ以上に関する情報を確認できます。
+
** 原因（診断）フィールドに表示された情報を確認して、考えられる診断ガイダンスを確認します。
+
この例では、原因フィールドの情報から、ボリュームがオフラインであることのみがわかります。

** Notes and Updates 領域で、 SVM 管理者が該当のボリュームを意図的にオフラインにしたかどうかを確認します。
** イベントのソースをクリックすると、オフラインとして報告されるボリュームをクリックすると、そのボリュームに関する詳細情報が表示されます。 xref:task-performing-diagnotstic-actions-for-volume-offline-conditions.adoc[ボリュームがオフライン状態になった場合の対処策の実施]
** イベントを管理者に割り当てます。 xref:task-assigning-events-to-specific-users.adoc[イベントを割り当てます]
** イベントに応答するか、必要に応じて解決済みとしてマークします。 xref:task-acknowledging-and-resolving-events.adoc[イベントを確認して解決します]



