---
permalink: health-checker/task-restoring-a-mysql-database-backup-on-windows.html 
sidebar: sidebar 
keywords:  
summary: データ損失やデータ破損が発生した場合、リストア機能を使用して Unified Manager を以前の安定した状態にリストアすることで損失を最小限に抑えることができます。Unified Managerデータベースは、リストアコマンドを使用してローカルとリモートのどちらのWindowsシステムにもリストアできます。 
---
= Windowsでのデータベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失やデータ破損が発生した場合、リストア機能を使用して Unified Manager を以前の安定した状態にリストアすることで損失を最小限に抑えることができます。Unified Managerデータベースは、リストアコマンドを使用してローカルとリモートのどちらのWindowsシステムにもリストアできます。



== 作業を開始する前に

* Unified Managerがサーバにインストールされている必要があります。
* Windows の管理者権限が必要です。
* リストア処理を実行するシステムに Unified Manager のバックアップファイルとデータベースリポジトリディレクトリの内容をコピーしておく必要があります。
+
バックアップファイルはデフォルトのディレクトリにコピーすることを推奨します `\ProgramData\NetApp\OnCommandAppData\ocum\backup`。データベースリポジトリのファイルは、にコピーする必要があります `\database_dumps_repo` のサブディレクトリ `\backup` ディレクトリ。

* バックアップファイルはにする必要があります `.7z` を入力します。




== このタスクについて

リストア機能は、プラットフォームおよびバージョンに固有の機能です。Unified Managerのバックアップは、同じバージョンのUnified Managerにのみリストアできます。また、Windowsのバックアップは、Windowsプラットフォームにのみリストアできます。

[TIP]
====
フォルダ名にスペースが含まれている場合は、バックアップファイルの絶対パスまたは相対パスを二重引用符で囲む必要があります。

====


== 手順

. 新しいサーバへのリストアを実行する場合は、 Unified Manager のインストールの完了後に、 UI を起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。この情報は、リストアプロセスでバックアップファイルに取り込まれます。
. Unified Managerコンソールに管理者としてログインします。 `um cli login -u maint_username`
. コマンドプロンプトで、バックアップをリストアします。 `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.4.N151118.2300_backup_windows_02-20-2018-02-51.7z`





== 完了後

リストア処理が完了したら、 Unified Manager にログインできます。
