---
permalink: health-checker/task-generating-and-uploading-a-support-bundle.html 
sidebar: sidebar 
keywords:  
summary: トラブルシューティングのサポートを受ける際に、十分な診断情報を含むサポートバンドルを生成し、テクニカルサポートに送信することができます。一部のタイプのデータは、クラスタリソースを大量に使用したり、完了までに時間がかかったりする可能性があるため、サポートバンドルに含めるデータタイプと除外するデータタイプを指定できます。 
---
= サポートバンドルの生成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラブルシューティングのサポートを受ける際に、十分な診断情報を含むサポートバンドルを生成し、テクニカルサポートに送信することができます。一部のタイプのデータは、クラスタリソースを大量に使用したり、完了までに時間がかかったりする可能性があるため、サポートバンドルに含めるデータタイプと除外するデータタイプを指定できます。



== 作業を開始する前に

メンテナンスコンソールにメンテナンスユーザとしてアクセスできる必要があります。



== このタスクについて

Unified Manager では、生成されたサポートバンドルのうち最新の 2 つだけが保持されます。それよりも古いサポートバンドルはシステムから削除されます。

[NOTE]
====
Windowsシステムの場合は、コマンド `supportbundle.bat` サポートバンドルの生成でのサポートの廃止

====


== 手順

. メンテナンスコンソール * メインメニュー * で、 * サポート / 診断 * を選択します。
. 「サポートバンドルの生成」を選択します。
. サポートバンドルに含めるデータタイプと除外するデータタイプを選択または選択解除します。
+
** * データベースダンプ *
+
MySQL Server データベースのダンプ。

** * ヒープダンプ *
+
メインの Unified Manager サーバプロセスの状態の Snapshot 。このオプションはデフォルトでは無効になっており、カスタマーサポートから要求された場合にのみ選択します。

** * 取得記録 *
+
Unified Manager と監視対象クラスタの間のすべての通信の記録。



+
[NOTE]
====
すべてのデータタイプを選択解除しても、それ以外の Unified Manager データでサポートバンドルが生成されます。

====
. を入力します `g`をクリックし、Enterキーを押してサポートバンドルを生成します。
+
サポートバンドルの生成ではメモリが大量に消費されるため、この時点でサポートバンドルを生成するかどうかを確認するメッセージが表示されます。

. を入力します `y`をクリックし、Enterキーを押してサポートバンドルを生成します。
+
この時点でサポートバンドルを生成しない場合は、と入力します `n`をクリックし、Enterキーを押します。

. サポートバンドルにデータベースダンプファイルを含めるように指定した場合は、パフォーマンス統計の対象期間を指定するように求められます。パフォーマンス統計の追加には多くの時間とスペースが必要になることがあるため、パフォーマンス統計を含めずにデータベースをダンプすることもできます。
+
.. 開始日を「 YYYYMMDD 」の形式で入力します。
+
たとえば、と入力します `20170101` 2017年1月1日入力するコマンド `n` パフォーマンス統計を含めない場合は、

.. 対象とする統計の日数を、午前 12 時から入力します指定した開始日の日付にある。
+
1 ～ 10 の数値を入力できます。



+
パフォーマンス統計を含める場合は、収集期間が表示されます。

. 「サポートバンドルの生成」を選択します。
+
生成されたサポートバンドルは、にあります `/support` ディレクトリ。





== 完了後

サポートバンドルが生成されたら、SFTPクライアントを使用するか、UNIXまたはLinuxのCLIコマンドを使用して、サポートバンドルを取得することができます。Windows 環境では、 Remote Desktop （ RDP ）を使用してサポートバンドルを取得することができます。

生成されたサポートバンドルは、にあります `/support` VMwareシステムのディレクトリ `/opt/netapp/data/support/` Linuxシステムの場合は、および `ProgramData\NetApp\OnCommandAppData\ocum\support` Windowsシステム：
