---
permalink: health-checker/task-creating-rules-using-templates.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerで定義されているルールテンプレートを使用して新しいルールを追加することで、Infinite Volumeを備えたSVMに書き込まれるデータの配置を決めることができます。ファイルタイプ、ディレクトリパス、または所有者に基づいてルールを作成できます。 
---
= テンプレートを使用したルールの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerで定義されているルールテンプレートを使用して新しいルールを追加することで、Infinite Volumeを備えたSVMに書き込まれるデータの配置を決めることができます。ファイルタイプ、ディレクトリパス、または所有者に基づいてルールを作成できます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* ストレージクラスを含むInfinite Volumeを備えたSVMが含まれるクラスタをUnified Managerデータベースに追加しておく必要があります。




== このタスクについて

データポリシータブは、Infinite Volumeを備えたSVMの場合にのみ表示されます。



== 手順

. 左側のナビゲーションペインで、* Health *>* SVM*をクリックします。
. *ケンセンセイ/ Storage Virtual Machines *インヘントリヘエシで、適切なSVMを選択します。
. [*データポリシー*]タブをクリックします。
+
選択したInfinite Volumeを備えたSVMのデータポリシーに含まれるルールのリストが表示されます。

. [ 作成（ Create ） ] をクリックします。
. [ルールの作成*]ダイアログボックスで、ドロップダウンリストから適切なルールテンプレートを選択します。
+
テンプレートは、ファイルタイプ、所有者、ディレクトリパスの3つのカテゴリに基づいています。

. 選択したテンプレートに基づいて、必要な条件を[*Matching Criteria*]領域に追加します。
. 一致するコンテンツをストレージクラスに配置する*ドロップダウン・リストから適切なストレージ・クラスを選択します
. [ 作成（ Create ） ] をクリックします。
+
作成した新しいルールが[データポリシー]タブに表示されます。

. データポリシーに対して行ったその他の変更をプレビューします。
. Activate *をクリックして、SVMのルールのプロパティの変更をアクティブ化します。

