---
permalink: health-checker/task-performing-corrective-action-for-a-flashcard-offline.html 
sidebar: sidebar 
keywords:  
summary: フラッシュカードのオフラインイベントの詳細ページの原因 フィールドで概要 を確認したら、状況を解決するのに役立つ追加情報 を検索できます。 
---
= フラッシュカードがオフラインになった場合の対処策の実施
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
フラッシュカードのオフラインイベントの詳細ページの原因 フィールドで概要 を確認したら、状況を解決するのに役立つ追加情報 を検索できます。



== 作業を開始する前に

オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。



== このタスクについて

この例では、イベントの詳細ページに表示されるイベントの概要に、オフラインのフラッシュカード状態に関する次の情報が表示されます。

[listing]
----
Severity: Critical
State: New
Impact Level: Incident
Impact Area: Availability
Source: alpha-node
Source Type: Node
Acknowledged By:
Resolved By:
Assigned To:
Cause: Flash cards at slot numbers 3 are offline.
Alert Settings:
----
イベント情報は'クラスタ・ノード"alpha-node"のスロット3に取り付けられたフラッシュ・カードがオフラインであることを示します

この情報から、フラッシュカードのオフライン状態が特定のクラスタノードの特定のスロットで発生していることはわかりますが、フラッシュカードがオフラインになった理由までは特定できません。



== 手順

. フラッシュカードのオフライン状態を診断するための詳細情報を得るには、イベントのソースの名前をクリックします。
+
この例では、イベントのソースは「アルファノード」クラスタノードです。そのノード名をクリックすると、該当するクラスタの健常性/クラスタの詳細ページのNodesタブにHAの詳細が表示されます。表示されたHAの詳細には、そのノードが属しているHAペアに関する情報が表示されます。

+
この例では、HA DetailsのEvents Summaryテーブルに関連情報が表示されます。この表には、フラッシュカードオフラインイベント、イベントが生成された時刻、およびこのイベントの生成元であるクラスタノードが示されます。

. ONTAP CLIまたはOnCommand のSystem Managerを使用して、該当するクラスタのEvent Manager System（EMS；イベントマネージャシステム）ログにアクセスします。
+
この例では、イベント名、イベント時間、およびイベントソースを使用して、このイベントのEMSレポートを検索します。イベントのEMSレポートには、イベントの詳細な概要 が記載されており、多くの場合、イベントが示す状態を修復するための情報も記載されています。





== 完了後

問題を診断したら、管理者またはオペレータに連絡して、フラッシュカードをオンラインに戻すために必要な手順を手動で実行します。
