---
permalink: health-checker/task-performing-suggested-remedial-actions-for-a-full-volume.html 
sidebar: sidebar 
keywords:  
summary: 「ボリュームスペースがフル」エラーイベントを受け取ったら、イベントの詳細ページで推奨される修正策を確認し、推奨されるいずれかの操作を実行します。 
---
= ボリュームがフルになった場合の推奨修正策の実施
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリューム容量がいっぱいです」エラーイベントを受け取った後、イベントの詳細ページで推奨される修正策を確認し、推奨されるアクションのいずれかを実行することにします。



== 作業を開始する前に

OnCommand 管理者またはストレージ管理者のロールが必要です。

Unified Manager を使用するこのワークフロー内のタスクは、どのロールのユーザでも実行できます。



== このタスクについて

この例では、Unified Managerのダッシュボード/概要ページでボリューム容量がフルエラーイベントが表示され、そのイベントの名前をクリックしています。

ボリュームがフルになった場合に実施できる修正策には、次のものがあります。

* ボリュームに対して自動拡張、重複排除、または圧縮を有効にする
* ボリュームをサイズ変更するか、移動しています
* ボリュームからデータを削除または移動する


これらのすべての操作はOnCommand System ManagerまたはONTAP CLIから実行する必要がありますが、実行する操作を決定するために必要な情報はUnified Managerで確認できます。



== 手順

. イベント * の詳細ページで、ソースフィールドのボリューム名をクリックすると、該当するボリュームの詳細が表示されます。
. *正常性/ボリューム*の詳細ページで*設定*をクリックすると、ボリュームで重複排除機能と圧縮機能がすでに有効になっていることがわかります。
+
ボリュームのサイズを変更することにします。

. Related Devices * ペインで、ホスティングアグリゲートの名前をクリックすると、アグリゲートがボリュームの拡張に対応できるかどうかがわかります。
. * Health / Aggregate * detailsページで、フルボリュームをホストしているアグリゲートにコミットされていない容量が十分にあることを確認できます。ボリュームのサイズを変更して容量を拡大するには、OnCommand System Managerを使用します。

