---
permalink: health-checker/task-creating-a-snapmirror-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: データレプリケーションを有効にしてデータを保護するために、健常性/ボリュームの詳細ページを使用してSnapMirror関係を作成することができます。SnapMirror レプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。 
---
= ケンセンセイ/ホリユウムノシヨウサイヘエシテSnapMirrorホコカンケイヲサクセイ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データレプリケーションを有効にしてデータを保護するために、健常性/ボリュームの詳細ページを使用してSnapMirror関係を作成することができます。SnapMirror レプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。



== 作業を開始する前に

* OnCommand 管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。




== このタスクについて

次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリュームがFlexGroup ボリュームの場合
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


保護ジョブは、パフォーマンスに影響を及ぼすことなく最大 10 件まで同時に実行できます。11~30 件のジョブを同時に実行すると、パフォーマンスが低下することがあります。30 を超えるジョブを同時に実行することは推奨されません。



== 手順

. *正常性/ボリューム*の詳細ページの*保護*タブで、保護するボリュームの名前をトポロジビューで右クリックします。
. メニューから * Protect * > * SnapMirror * を選択します。
+
Configure Protection （保護の設定）ダイアログボックスが表示されます。

. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示し、デスティネーション情報を設定します。
. 必要に応じて「 * 詳細設定 * 」をクリックしてスペースギャランティを設定し、「 * 適用 * 」をクリックします。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
健常性とボリュームの詳細ページに戻ります。

. 「* Health / Volume * details」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細が保護/ジョブの詳細ページに表示されます。

. [*保護/ジョブ*の詳細]ページで、[*更新]をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの*戻る*をクリックして*正常性/ボリューム*の詳細ページに戻ります。
+
新しい関係は、健常性/ボリュームの詳細ページのトポロジビューに表示されます。





== 結果

設定で指定したデスティネーション SVM と詳細設定で有効にしたオプションに応じて、次のいずれかの SnapMirror 関係が作成されます。

* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定した場合、デフォルトではブロックレプリケーションベースの SnapMirror 関係が作成されます。
* ソースボリュームと同じかそれよりも新しいバージョン（バージョン8.3以降）のONTAP で実行されているデスティネーションSVMを指定し、詳細設定でバージョンに依存しないレプリケーションを有効にした場合、バージョンに依存しないレプリケーションを使用したSnapMirror関係が作成されます。
* ONTAP 8.3の以前のバージョン、またはソースボリュームよりも新しいバージョンで実行されているデスティネーションSVMを指定した場合、以前のバージョンでバージョンに依存しないレプリケーションがサポートされていれば、バージョンに依存しないレプリケーションを使用したSnapMirror関係が自動で作成されます。

