---
permalink: health-checker/task-resolving-a-flashcard-offline-condition.html 
sidebar: sidebar 
keywords:  
summary: このワークフローでは、フラッシュカードのオフライン状態を解決する方法の例を示します。このシナリオでは、管理者またはオペレータが、ダッシュボードを監視して可用性に問題がないかを確認します。フラッシュカードがオフライン状態であることを確認し、問題の原因 と解決策を特定します。 
---
= フラッシュカードのオフライン状態を解決する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、フラッシュカードのオフライン状態を解決する方法の例を示します。このシナリオでは、管理者またはオペレータが、ダッシュボードを監視して可用性に問題がないかを確認します。フラッシュカードがオフライン状態であることを確認し、問題の原因 と解決策を特定します。



== 作業を開始する前に

オペレータ、OnCommand 管理者、またはストレージ管理者のロールが必要です。



== このタスクについて

Unified Managerのダッシュボード/概要ページの可用性領域に表示されるイベント情報とリンクでは、監視対象クラスタでのデータストレージリソースの全体的な可用性を監視して、その可用性に影響する可能性のある特定のイベントを診断できます。

このシナリオでは、[ダッシュボード/概要]ページの[可用性インシデント]セクションに、[オフライン]のイベントFlashカードが表示されます。フラッシュカードがオフラインの場合は、カードが取り付けられているクラスタノードのパフォーマンスに問題があるため、格納されているデータの可用性が損なわれます。潜在的な問題を突き止めるには、次の手順を実行します。



== 手順

. [未解決のインシデントとリスク*（Unresolved Incidents and Risks *）]セクションの[*可用性*（* Availability *）]パネルで、[オフライン（Offline）]に表示されるハイパーテキストリンクをクリックします。
+
可用性インシデントのイベント詳細ページが表示されます。

. [*Event* details]ページでは、原因 フィールドに表示される情報を確認し、次のタスクを1つ以上実行できます。
+
** イベントを管理者に割り当てます。 xref:task-assigning-events-to-specific-users.adoc[イベントを割り当てます]
** イベントのソースをクリックします。この場合は、オフラインのフラッシュカードが配置されているクラスタノードをクリックすると、そのノードに関する詳細を確認できます。 xref:task-performing-corrective-action-for-a-flashcard-offline.adoc[フラッシュカードがオフラインになった場合の対処策の実施]
** イベントに応答します。 xref:task-acknowledging-and-resolving-events.adoc[イベントを確認して解決します]



