---
permalink: config/task-adding-alerts.html 
sidebar: sidebar 
keywords:  
summary: 特定のイベントが生成されたときに通知するようにアラートを設定できます。アラートは、単一のリソース、リソースのグループ、または特定の重大度タイプのイベントについて設定することができます。通知を受け取る頻度を指定したり、アラートにスクリプトを関連付けたりできます。 
---
= アラートの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のイベントが生成されたときに通知するようにアラートを設定できます。アラートは、単一のリソース、リソースのグループ、または特定の重大度タイプのイベントについて設定することができます。通知を受け取る頻度を指定したり、アラートにスクリプトを関連付けたりできます。



== 作業を開始する前に

* イベントが生成されたときにUnified Managerサーバからユーザに通知を送信できるように、通知に使用するユーザのEメールアドレス、SMTPサーバ、SNMPトラップホストなどを設定しておく必要があります。
* アラートをトリガーするリソースとイベント、および通知するユーザのユーザ名または E メールアドレスを確認しておく必要があります。
* イベントに基づいてスクリプトを実行する場合は、Management/Scriptsページを使用してUnified Managerにスクリプトを追加しておく必要があります。
* OnCommand 管理者またはストレージ管理者のロールが必要です。




== このタスクについて

イベントを受け取った後は、イベントの詳細ページから直接アラートを作成できます。また、ここで説明する構成/アラートページからアラートを作成することもできます。



== 手順

. 左側のナビゲーションペインで、*構成*>*警告*をクリックします。
. [*設定/アラート*]ページで、[*追加]をクリックします。
. [ * アラートの追加 * ] ダイアログボックスで、 [ * 名前 * ] をクリックし、アラートの名前と概要を入力します。
. [* リソース ] をクリックし、アラートに含めるリソースまたはアラートから除外するリソースを選択します。
+
[ * 次を含む名前（ * Name Contains ） ] フィールドでテキスト文字列を指定してフィルタを設定し、リソースのグループを選択できます。指定したテキスト文字列に基づいて、フィルタルールに一致するリソースのみが使用可能なリソースのリストに表示されます。指定するテキスト文字列では、大文字と小文字が区別されます。

+
あるリソースが対象に含めるルールと除外するルールの両方に該当する場合は、除外するルールが優先され、除外されたリソースに関連するイベントについてはアラートが生成されません。

. [*Events] をクリックし、アラートをトリガーするイベント名またはイベントの重大度タイプに基づいてイベントを選択します。
+
[TIP]
====
複数のイベントを選択するには、 Ctrl キーを押しながら選択します。

====
. [*Actions] をクリックし、通知するユーザを選択し、通知頻度を選択し、 SNMP トラップをトラップレシーバに送信するかどうかを選択し、アラートが生成されたときに実行するスクリプトを割り当てます。
+
[NOTE]
====
ユーザに対して指定されている E メールアドレスを変更し、アラートを再び開いて編集しようとすると、変更した E メールアドレスが以前に選択したユーザにマッピングされていないため、名前フィールドは空白になります。また、[Management/Users]ページで選択したユーザのEメールアドレスを変更しても、変更後のEメールアドレスは更新されません。

====
+
SNMP トラップを使用してユーザに通知することもできます。

. [ 保存（ Save ） ] をクリックします。




== アラートの追加例

この例は、次の要件を満たすアラートを作成する方法を示しています。

* アラート名： HealthTest
* リソース：名前に「 abc 」が含まれるすべてのボリュームを対象に含め、名前に「 xyz 」が含まれるすべてのボリュームを対象から除外する
* イベント：健全性に関するすべての重大なイベントを含みます
* アクション:「sample@domain.com」、「Test」スクリプトを含み、15分ごとにユーザーに通知する必要があります


[Add Alert] ダイアログボックスで、次の手順を実行します。

. [*名前*]をクリックし、と入力します `HealthTest` [*アラート名*]フィールドに入力します。
. [* リソース ] をクリックし、 [ 含める ] タブで、ドロップダウン・リストから [* ボリューム ] を選択します。
+
.. 入力するコマンド `abc` 「* Name contains *」フィールドには、名前に「abc」が含まれるボリュームが表示されます。
.. [使用可能なリソース（Available Resources）]領域から[*\<リソース（*\<<All Volumes whose name contains 'abc'> >*）]を選択し、[選択したリソース（Selected Resources）]領域に移動する。
.. [*除外する*]をクリックし、と入力します `xyz` [名前に*が含まれています]フィールドで、[*追加]をクリックします。


. [* イベント *] をクリックし、 [ イベントの重要度 ] フィールドから [* クリティカル *] を選択します。
. [Matching Events] 領域から [*All Critical Events] を選択し、 [Selected Events] 領域に移動します。
. [*アクション*]をクリックし、と入力します `sample@domain.com` [これらのユーザーにアラートを送信]フィールドに入力します。
. 15 分ごとにユーザに通知するには、「 * 15 分ごとに通知する」を選択します。
+
指定した期間、受信者に繰り返し通知を送信するようにアラートを設定できます。アラートに対してイベント通知をアクティブにする時間を決める必要があります。

. 実行するスクリプトの選択メニューで、*テスト*スクリプトを選択します。
. [ 保存（ Save ） ] をクリックします。

