---
permalink: install/concept-virtual-infrastructure-or-hardware-system-requirements.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerを仮想インフラまたは物理システムのどちらにインストールするかに応じて、それぞれのメモリ、CPU、およびディスクスペースの最小要件を満たす必要があります。 
---
= 仮想インフラおよびハードウェアシステムの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを仮想インフラまたは物理システムのどちらにインストールするかに応じて、それぞれのメモリ、CPU、およびディスクスペースの最小要件を満たす必要があります。

次の表に、メモリ、 CPU 、およびディスクスペースの各リソースについて、推奨される値を示します。これらは、 Unified Manager が許容されるパフォーマンスレベルを達成することが確認されている値です。

|===
| ハードウェア構成 | 推奨設定 


 a| 
RAM
 a| 
12GB （最小要件は 8GB ）



 a| 
プロセッサ
 a| 
CPU × 4



 a| 
CPU サイクル容量
 a| 
合計 9572MHz （最小要件は 9572MHz ）



 a| 
空きディスク容量
 a| 
VMware ：

* 5GB （シンプロビジョニング）
* 152GB （シックプロビジョニング）




 a| 
Red HatまたはCentOS：150GB。割り当ては次のとおりです。

* 50GB をルートパーティションに割り当て
* に100GBの空きディスクスペースが割り当てられている `/opt/netapp/data` ディレクトリ。LVMドライブまたはターゲットシステムに接続された別のローカルディスクにマウントされます


[NOTE]
====
。 `/tmp` ディレクトリに10GB以上の空きスペースとが必要です `/var/log` ディレクトリには16GB以上の空きスペースが必要です。

==== a| 
Windows：150GB。割り当ては次のとおりです。

* 100GB - インストールディレクトリ用
* 50GB の MySQL データディレクトリ用ディスクスペースが必要です


|===
Unified Manager はメモリの少ないシステムにもインストールできますが、推奨される 12GB の RAM があれば最適なパフォーマンスが保証されるだけでなく、拡張時にクラスタやストレージオブジェクトの追加にも対応できます。Unified Managerを導入するVMにはメモリの上限などを設定しないでください。また、ソフトウェアがシステムで割り当てられているメモリを利用できなくなる機能（バルーニングなど）は有効にしないでください。

また、1つのUnified Managerインスタンスで監視できるノードの数には上限があり、この上限を超える場合は2つ目のUnified Managerインスタンスをインストールする必要があります。詳細については、_ベストプラクティスガイド_を参照してください。

https://www.netapp.com/pdf.html?item=/media/13504-tr4621pdf.pdf["テクニカルレポート 4621 ：『 Unified Manager Best Practices Guide 』"^]

メモリページのスワッピングは、システムや管理アプリケーションのパフォーマンスに悪影響を及ぼします。CPU リソースがホスト全体で競合して使用できなくなると、パフォーマンスが低下する可能性があります。



== 専用使用の要件

Unified Managerをインストールする物理システムまたは仮想システムは、他のアプリケーションとは共有せず、Unified Manager専用にする必要があります。他のアプリケーションにシステムリソースが消費されることで、 Unified Manager のパフォーマンスが大幅に低下する可能性があります。



== バックアップ用のスペース要件

Unified Managerのバックアップとリストア機能を使用する場合は、「data」ディレクトリまたはディスクに150GBのスペースがあるように、追加の容量を割り当てる必要があります。バックアップはローカルにもリモートにも保存できますが、Unified Manager ホストシステムとは別の、 150GB 以上のスペースがあるリモートの場所に保存することを推奨します。



== ホスト接続の要件

Unified Managerをインストールする物理システムまたは仮想システムは、問題なく設定できるようにする必要があります `ping` ホスト自体のホスト名です。IPv6構成の場合は、確認する必要があります `ping6` これでUnified Managerを正しくインストールできるようになります。

製品の Web UI には、ホスト名（またはホストの IP アドレス）を使用してアクセスできます。導入時に静的 IP アドレスを使用してネットワークを設定した場合は、指定したネットワークホストの名前を使用します。DHCP を使用してネットワークを設定した場合は、 DNS からホスト名を取得します。

完全修飾ドメイン名（ FQDN ）または IP アドレスの代わりに短縮名を使用した Unified Manager へのアクセスをユーザに許可する場合は、短縮名が有効な FQDN に解決されるようにネットワークを設定する必要があります。



== マウント済み `/opt/netapp` または `/opt/netapp/data` 要件

マウントできます `/opt/netapp` または `/opt/netapp/data` NASデバイスまたはSANデバイス。リモートマウントポイントを使用すると、原因 の拡張で問題が発生する可能性があります。リモートマウントポイントを使用する場合は、SANまたはNASのネットワークにUnified ManagerのI/Oのニーズを満たす十分な容量があることを確認してください。この容量は一定ではなく、監視するクラスタおよびストレージオブジェクトの数に応じて増えることがあります。

をマウント済みの場合 `/opt/netapp` または `/opt/netapp/data` SELinuxを有効にしている環境で、ルートファイルシステム以外の場所から、マウントされたディレクトリに正しいコンテキストを設定する必要があります。

を参照してください xref:task-selinux-requirements-for-mounting-opt-netapp-or-opt-netapp-data-on-an-nfs-or-cifs-share.adoc[SELinux で NFS 共有または CIFS 共有に /opt/netapp または /opt/netapp/data をマウントする場合の要件] 正しいSELinuxコンテキストの設定については、を参照してください。
