---
permalink: install/concept-requirements-and-limitations-for-unified-manager-in-mscs.html 
sidebar: sidebar 
keywords:  
summary: フェイルオーバークラスタリング環境でUnified Managerをインストールする場合は、クラスタノードがUnified Managerをサポートするように適切に設定されていることを事前に確認する必要があります。 
---
= フェイルオーバークラスタリング環境でのUnified Managerの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
フェイルオーバークラスタリング環境でUnified Managerをインストールする場合は、クラスタノードがUnified Managerをサポートするように適切に設定されていることを事前に確認する必要があります。

フェイルオーバークラスタの構成が次の要件を満たしていることを確認する必要があります。

* 両方のクラスタノードで同じバージョンのMicrosoft Windows Serverが実行されている必要があります。
* 両方のクラスタノードで同じバージョンのUnified Managerが同じパスにインストールされている必要があります。
* 両方のノードにフェイルオーバークラスタリングがインストールされて有効になっている必要があります。
+
手順については、Microsoftのドキュメントを参照してください。

* Fibre ChannelスイッチファブリックまたはiSCSIベースのストレージを使用して、共有データディスクをストレージバックエンドとして作成しておく必要があります
* オプション：SnapDrive for Windowsを使用して、ハイアベイラビリティ構成の両方のノードからアクセスできる共有の場所を作成する必要があります。
+
共有の場所のインストールと作成については、SnapDrive for Windowsインストールガイドを参照してください。

+
ストレージシステムのコマンドラインインターフェイスを使用してLUNを管理することもできます。詳細については、SnapDrive for Windowsの互換性マトリックスを参照してください。

* Perlをにインストールしておく必要があります `XML::LibXML` および `File::chdir` スクリプトが機能するためのモジュール。
* クラスタセットアップのノードは2つだけにする必要があります。
* フェイルオーバー・クラスタリングには'ノードとディスク・マジョリティクォーラム・タイプを使用する必要があります
* Unified Managerへのアクセスにクラスタで使用するグローバルIPアドレスとして、共有IPアドレスと対応するFQDNを設定しておく必要があります。
* Unified Managerのメンテナンスユーザのパスワードを両方のノードで同じにする必要があります。
* IPv4 IPアドレスのみを使用する必要があります。

