---
permalink: install/reference-completing-the-worksheet-um.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager をインストールして設定する前に、環境に関する特定の情報を確認しておく必要があります。この情報はワークシートに記録できます。 
---
= ワークシートへの記入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager をインストールして設定する前に、環境に関する特定の情報を確認しておく必要があります。この情報はワークシートに記録できます。



== Unified Manager のインストール情報

Unified Manager をインストールする際に必要な情報を記入します。

|===
| ソフトウェアが導入されているシステム | あなたの価値 


 a| 
ESXiサーバのIPアドレス（VMwareのみ）
 a| 



 a| 
ホストの完全修飾ドメイン名
 a| 



 a| 
ホストの IP アドレス
 a| 



 a| 
ネットワークマスク
 a| 



 a| 
ゲートウェイの IP アドレス
 a| 



 a| 
プライマリ DNS アドレス
 a| 



 a| 
セカンダリ DNS アドレス
 a| 



 a| 
検索ドメイン
 a| 



 a| 
メンテナンスユーザのユーザ名
 a| 



 a| 
メンテナンスユーザのパスワード
 a| 

|===


== Unified Manager の設定情報

インストール後に Unified Manager を設定するための情報を記入します。設定によっては省略可能な値もあります。

|===
| 設定 | あなたの価値 


 a| 
メンテナンスユーザの E メールアドレス
 a| 



 a| 
NTPサーバ（VMwareのみ）
 a| 



 a| 
SMTP サーバのホスト名または IP アドレス
 a| 



 a| 
SMTP ユーザ名
 a| 



 a| 
SMTP パスワード
 a| 



 a| 
SMTP ポート
 a| 
25 （デフォルト値）



 a| 
アラート通知の送信元 E メールアドレス
 a| 



 a| 
認証サーバのホスト名または IP アドレス
 a| 



 a| 
Active Directory の管理者名または LDAP のバインド識別名
 a| 



 a| 
Active Directory のパスワードまたは LDAP のバインドパスワード
 a| 



 a| 
認証サーバのベース識別名
 a| 



 a| 
アイデンティティプロバイダ（ IdP ）の URL
 a| 



 a| 
アイデンティティプロバイダ（ IdP ）のメタデータ
 a| 



 a| 
SNMPトラップの送信先ホストのIPアドレス
 a| 



 a| 
SNMP ポート
 a| 

|===


== クラスタ情報

Unified Managerを使用して管理するストレージシステムの情報を記入します。

|===
| クラスタ 1 / N | あなたの価値 


 a| 
ホスト名またはクラスタ管理 IP アドレス
 a| 



 a| 
ONTAP 管理者のユーザ名

[NOTE]
====
管理者には「 admin 」ロールが割り当てられている必要があります。

==== a| 



 a| 
ONTAP 管理者のパスワード
 a| 



 a| 
プロトコル（ HTTP または HTTPS ）
 a| 

|===