---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: 新しいカスタムのJBossパスワードを作成して、インストール時に設定されたデフォルトのパスワードを上書きできます。このタスクはオプションですが、サイトによってはセキュリティ上の理由からUnified Managerのデフォルトのインストール設定とは異なる設定が必要になることがあります。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。 
---
= JBoss パスワードを変更しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいカスタムのJBossパスワードを作成して、インストール時に設定されたデフォルトのパスワードを上書きできます。このタスクはオプションですが、サイトによってはセキュリティ上の理由からUnified Managerのデフォルトのインストール設定とは異なる設定が必要になることがあります。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。



== 作業を開始する前に

* Unified Manager がインストールされている Red Hat Enterprise Linux または CentOS のシステムへの root ユーザアクセスが必要です。
* ネットアップが提供するサービスにアクセスできる必要があります `password.sh` ディレクトリ内のスクリプト `/opt/netapp/essentials/bin`。




== 手順

. システムに root ユーザとしてログインします。
. 次のコマンドを記載された順序で入力して、 Unified Manager サービスを停止します。 `service ocieau stop``service ocie stop`
+
関連付けられている MySQL ソフトウェアは停止しないでください。

. 次のコマンドを入力して、パスワードの変更プロセスを開始します。 `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. プロンプトが表示されたら、古いJBossパスワードを入力します。
+
デフォルトのパスワードはです `D11h1aMu@79%`。

. プロンプトが表示されたら、新しい JBoss パスワードを入力し、確認のためにもう一度入力します。
. スクリプトが完了したら、次のコマンドを記載された順序で入力して、 Unified Manager サービスを開始します。 `service ocie start``service ocieau start`
. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

