---
permalink: install/task-deploying-the-unified-manager-virtual-appliance-vapp.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager仮想アプライアンスは、NetApp Support Site から.ovaファイルをダウンロードしたあとに導入できます。ESXiサーバに仮想アプライアンスを導入するには、vSphere Web Client \（vSphereバージョン6.5 \）またはvSphere Client \（vSphereバージョン5.5または6.0）を使用する必要があります。仮想アプライアンスを導入すると、仮想マシンが作成されます。 
---
= Unified Manager 仮想アプライアンスの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
をダウンロードしたら、Unified Manager仮想アプライアンスを導入できます `.ova` NetApp Support Site からのファイルです。ESXiサーバへの仮想アプライアンスの導入には、vSphere Web Client（vSphereバージョン6.5）またはvSphere Client（vSphereバージョン5.5または6.0）を使用する必要があります。仮想アプライアンスを導入すると、仮想マシンが作成されます。



== 作業を開始する前に

システム要件を確認しておく必要があります。システム要件を満たすために変更が必要な場合は、Unified Manager仮想アプライアンスを導入する前に変更しておく必要があります。

xref:concept-requirements-for-installing-unified-manager.adoc[仮想インフラの要件]

xref:reference-vmware-software-and-installation-requirements.adoc[VMware ソフトウェアとインストールの要件]

DHCPを使用する場合は、DHCPサーバが使用可能で、DHCPと仮想マシン（VM）のネットワークアダプタが正しく設定されていることを確認する必要があります。DHCP はデフォルトで設定されています。

静的なネットワーク設定を使用する場合は、IPアドレスが同じサブネット内で重複していないこと、および適切なDNSサーバエントリが設定されていることを確認する必要があります。

仮想アプライアンスを導入する前に、次の情報を用意しておく必要があります。

* VMware vCenter ServerとvSphere Web Client（vSphereバージョン6.5）またはvSphere Client（vSphereバージョン5.5または6.0）にアクセスするためのクレデンシャル
* Unified Manager 仮想アプライアンスを導入する ESXi サーバの IP アドレス
* ストレージスペースの可用性など、データセンターに関する詳細
* DHCPを使用しない場合は、接続するネットワークデバイスのIPv4またはIPv6アドレス：
+
** ホストの完全修飾ドメイン名（ FQDN ）
** ホストの IP アドレス
** ネットワークマスク
** デフォルトゲートウェイの IP アドレス
** プライマリおよびセカンダリ DNS アドレス
** 検索ドメイン


* VMware ToolsのCD-ROMまたはISOイメージ




== このタスクについて

VMware Toolsはには含まれていません `.ova` ファイル。VMware Toolsは別途インストールする必要があります。

仮想アプライアンスを導入すると、 HTTPS アクセス用に一意の自己署名証明書が生成されます。Unified Manager Web UI にアクセスする際に、信頼された証明書でないことを示す警告がブラウザに表示されることがあります。

Unified Manager 仮想アプライアンスでは、 VMware High Availability がサポートされます。



== 手順

. vSphere Client で、 * File * > * Deploy OVF Template * をクリックします。
. Deploy OVF Template *ウィザードを実行して、Unified Manager仮想アプライアンスを導入します。
+
Networking Configuration ページで、次の手順を実行します。

+
** DHCP と IPv4 アドレスを使用する場合は、すべてのフィールドを空白のままにします。
** DHCP と IPv6 アドレスを使用する場合は '[Enable Auto IPv6 addressing] チェックボックスをオンにし ' その他のフィールドはすべて空白のままにします
** 静的なネットワーク設定を使用する場合は、このページのフィールドに値を入力します。これらの設定は導入時に適用されます。導入先のホストで一意で、使用されておらず、有効なDNSエントリが割り当てられたIPアドレスを指定する必要があります。


. Unified Manager 仮想アプライアンスを ESXi サーバに導入したら、 VM を右クリックして電源をオンにし、 * 電源オン * を選択します。
+
リソースが十分でないために電源投入に失敗した場合は、リソースを追加してからインストールを再試行する必要があります。

. [* コンソール * ] タブをクリックします。
+
初回ブートプロセスが完了するまでに数分かかります。

. プロンプトに従って、VMにVMware Toolsをインストールします。
+
vSphere 6.5でvSphere Web Clientを使用している場合は、VMware ToolsのISOイメージを手動でマウントする必要があります。VMから、*設定の編集*>*仮想ハードウェア*>* CD/DVDドライブx *>*データストアISOファイル*を選択し、*参照*をクリックしてファイルを選択する必要があります `linux.iso` をマウントイメージとして使用します。

. タイムゾーンを設定するには、VM * Console *ウィンドウに表示される指示に従って、地理的な地域と都市または地域を入力します。
+
表示されるすべての日付情報には、管理対象デバイスのタイムゾーンの設定に関係なく、 Unified Manager 用に設定されているタイムゾーンが使用されます。タイムスタンプを比較するときは、この点に注意してください。ストレージシステムと管理サーバで同じ NTP サーバが設定されている場合、違う時間が表示された場合でも、それぞれが表しているのは同じ時刻です。たとえば、管理サーバとは異なるタイムゾーンが設定されたデバイスを使用してSnapshotコピーを作成した場合、タイムスタンプは管理サーバの時間になります。

. 使用可能な DHCP サービスがない場合や静的なネットワーク設定でエラーが発生した場合は、次のいずれかのオプションを選択します。
+
|===
| を使用する場合 | 操作 


 a| 
DHCP
 a| 
[DHCP の再試行 *] を選択します。DHCP を使用する場合は、正しく設定されていることを確認してください。

DHCP 対応のネットワークを使用すると、 FQDN と DNS サーバのエントリが仮想アプライアンスに自動的に割り当てられます。DHCPにDNSが正しく設定されていない場合'ホスト名OnCommand が自動的に割り当てられ'セキュリティ証明書に関連付けられますDHCP対応のネットワークをセットアップしていない場合は、ネットワーク設定情報を手動で入力する必要があります。



 a| 
静的なネットワーク設定
 a| 
.. 「 * Enter the details for static network configuration * 」を選択します。
+
設定プロセスが完了するまでに数分かかります。

.. 入力した値を確認し、 * Y * を選択します。


|===
. プロンプトでメンテナンスユーザの名前を入力し、* Enter *をクリックします。
+
メンテナンスユーザの名前は、a~zのアルファベットのあとに、a~zまたは0~9の任意の組み合わせを使用してください。

. プロンプトでパスワードを入力し、* Enter *をクリックします。
+
VM コンソールに Unified Manager Web UI の URL が表示されます。





== 完了後

Web UIにアクセスしてUnified Managerの初期セットアップを実行できます。手順については、OnCommand Unified Managerシステム構成ガイドを参照してください。
