---
permalink: install/task-removing-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Red Hat Enterprise LinuxホストまたはCentOSホストからUnified Managerを削除する必要がある場合は、1つのコマンドでUnified Managerを停止してアンインストールできます。 
---
= Red Hat Enterprise LinuxホストまたはCentOSホストからのUnified Managerの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Red Hat Enterprise LinuxホストまたはCentOSホストからUnified Managerを削除する必要がある場合は、1つのコマンドでUnified Managerを停止してアンインストールできます。



== 作業を開始する前に

* Unified Manager を削除するサーバへの root ユーザアクセスが必要です。
* Red Hat マシンで Security-Enhanced Linux （ SELinux ）を無効にしておく必要があります。を使用して、SELinuxランタイムモードを「permissive」に変更します `setenforce 0` コマンドを実行します
* ソフトウェアを削除する前に、 Unified Manager サーバからすべてのクラスタ（データソース）を削除しておく必要があります。
* Unified ManagerサーバからGraphiteなどの外部データプロバイダへのアクティブな接続を確立できません。
+
接続されている場合は、Unified Managerメンテナンスコンソールを使用して接続を削除する必要があります。





== このタスクについて

以下の手順には、Veritas Operation Managerを使用してハイアベイラビリティ用に構成されているシステム向けの手順も含まれています。システムがハイアベイラビリティ用に構成されていない場合は、ここで説明する追加の手順は無視してください。



== 手順

. Unified Managerを削除するクラスタリソースを所有するクラスタノードにrootユーザとしてログインします。
. VCS Operations ManagerまたはVCSコマンドを使用して、Unified Managerのすべてのサービスを停止します。
. Unified Manager を停止してサーバから削除します。 `rpm -e netapp-ocum ocie-au ocie-server netapp-platform-base netapp-application-server ocie-serverbase`
+
これにより、関連付けられているネットアップの RPM パッケージがすべて削除されます。Java 、 MySQL 、 p7zip など、前提条件のソフトウェアモジュールは削除されません。

. VCS Operations Managerを使用して、もう一方のノードに切り替えます。
. クラスタの2つ目のノードにログインします。
. すべてのサービスを停止し、2つ目のノードからUnified Managerを削除します。 `rpm -e netapp-ocum ocie-au ocie-server netapp-platform-base netapp-application-server ocie-serverbase`
. サービスグループによるVCS Operations ManagerまたはVCSコマンドの使用を中止します。
. 必要に応じて、Java、MySQL、p7zipなどのサポートソフトウェアモジュールを削除します。 `rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y`




== 結果

この処理が完了するとソフトウェアが削除されますが、MySQLのデータは削除されません。からのすべてのデータ `/opt/netapp/data` ディレクトリがに移動されます `/opt/netapp/data/BACKUP` アンインストール後のフォルダ。
